function yamlRuntimeHelper() {
  return [
    "const YAML_JSON_NUMBER_RE = /^-?(?:0|[1-9]\\\\d*)(?:\\\\.\\\\d+)?(?:[eE][+-]?\\\\d+)?$/;",
    "function yamlScalarSource(node) {",
    "  if (!node) return \"\";",
    "  if (typeof node.source === \"string\") return node.source;",
    "  return String(node.value ?? \"\");",
    "}",
    "function yamlClassifyScalar(node) {",
    "  const isPlain = node?.type === \"PLAIN\";",
    "  if (typeof node?.value === \"number\") return { type: \"num\", value: node.value };",
    "  if (typeof node?.value === \"boolean\") return { type: \"bool\", value: node.value };",
    "  if (node?.value === null) return { type: \"hollow\", value: null };",
    "  const raw = String(yamlScalarSource(node) ?? \"\").trim();",
    "  if (!isPlain) return { type: \"text\", value: String(node?.value ?? \"\") };",
    "  if (raw === \"\" || raw === \"~\" || /^null$/i.test(raw)) return { type: \"hollow\", value: null };",
    "  if (/^(true|false)$/i.test(raw)) return { type: \"bool\", value: /^true$/i.test(raw) };",
    "  if (YAML_JSON_NUMBER_RE.test(raw)) return { type: \"num\", value: Number(raw) };",
    "  return { type: \"text\", value: raw };",
    "}",
    "function yamlKeyText(node) {",
    "  if (!YAML.isScalar(node)) throw new Error(\"yaml key defective\");",
    "  const isPlain = node?.type === \"PLAIN\";",
    "  const raw = String(yamlScalarSource(node) ?? \"\").trim();",
    "  let key;",
    "  if (!isPlain) key = String(node?.value ?? \"\");",
    "  else if (raw === \"\" || raw === \"~\" || /^null$/i.test(raw)) key = \"null\";",
    "  else if (/^(true|false)$/i.test(raw)) key = /^true$/i.test(raw) ? \"true\" : \"false\";",
    "  else if (YAML_JSON_NUMBER_RE.test(raw)) key = raw;",
    "  else key = raw;",
    "  if (!String(key ?? \"\").trim()) throw new Error(\"yaml key defective\");",
    "  return key;",
    "}",
    "function yamlClone(value) {",
    "  if (Array.isArray(value)) return value.map((item) => yamlClone(item));",
    "  if (value && typeof value === \"object\") {",
    "    const out = {};",
    "    for (const [key, val] of Object.entries(value)) out[key] = yamlClone(val);",
    "    return out;",
    "  }",
    "  return value;",
    "}",
    "function yamlCollectAnchors(node, anchors) {",
    "  if (!node || typeof node !== \"object\") return;",
    "  if (node.anchor) anchors.set(node.anchor, node);",
    "  if (YAML.isMap(node)) {",
    "    for (const pair of node.items) {",
    "      yamlCollectAnchors(pair.key, anchors);",
    "      yamlCollectAnchors(pair.value, anchors);",
    "    }",
    "    return;",
    "  }",
    "  if (YAML.isSeq(node)) {",
    "    for (const item of node.items) yamlCollectAnchors(item, anchors);",
    "  }",
    "}",
    "function yamlResolveAlias(node, ctx) {",
    "  const aliasName = String(node?.source ?? \"\").trim();",
    "  if (!aliasName) throw new Error(\"yaml referential defective\");",
    "  const target = ctx.anchors.get(aliasName);",
    "  if (!target) throw new Error(\"yaml referential defective\");",
    "  if (ctx.resolving.has(aliasName)) throw new Error(\"yaml referential defective\");",
    "  ctx.resolving.add(aliasName);",
    "  const value = yamlNodeToJson(target, ctx);",
    "  ctx.resolving.delete(aliasName);",
    "  return yamlClone(value);",
    "}",
    "function yamlMergeInto(target, source) {",
    "  if (!source || typeof source !== \"object\" || Array.isArray(source)) {",
    "    throw new Error(\"yaml defective\");",
    "  }",
    "  for (const [key, value] of Object.entries(source)) {",
    "    if (!(key in target)) target[key] = value;",
    "  }",
    "}",
    "function yamlMapToJson(node, ctx) {",
    "  const out = {};",
    "  for (const pair of node.items) {",
    "    const keyText = yamlKeyText(pair.key);",
    "    if (keyText === \"<<\") {",
    "      const mergeValue = yamlNodeToJson(pair.value, ctx);",
    "      if (Array.isArray(mergeValue)) {",
    "        for (const entry of mergeValue) yamlMergeInto(out, entry);",
    "      } else {",
    "        yamlMergeInto(out, mergeValue);",
    "      }",
    "      continue;",
    "    }",
    "    const value = yamlNodeToJson(pair.value, ctx);",
    "    out[keyText] = value;",
    "  }",
    "  return out;",
    "}",
    "function yamlSeqToJson(node, ctx) {",
    "  const out = [];",
    "  for (const item of node.items) out.push(yamlNodeToJson(item, ctx));",
    "  return out;",
    "}",
    "function yamlNodeToJson(node, ctx) {",
    "  if (!node) return null;",
    "  if (node?.tag) throw new Error(\"yaml defective\");",
    "  if (node?.constructor?.name === \"Alias\") return yamlResolveAlias(node, ctx);",
    "  if (YAML.isMap(node)) return yamlMapToJson(node, ctx);",
    "  if (YAML.isSeq(node)) return yamlSeqToJson(node, ctx);",
    "  if (YAML.isScalar(node)) {",
    "    const classified = yamlClassifyScalar(node);",
    "    if (classified.type === \"hollow\") return null;",
    "    if (classified.type === \"bool\") return Boolean(classified.value);",
    "    if (classified.type === \"num\") return Number(classified.value);",
    "    return String(classified.value ?? \"\");",
    "  }",
    "  throw new Error(\"yaml defective\");",
    "}",
    "function yamlToJsonValue(text) {",
    "  const docs = YAML.parseAllDocuments(String(text ?? \"\"), { keepNodeTypes: true });",
    "  if (!docs || docs.length === 0 || docs.length !== 1) throw new Error(\"yaml defective\");",
    "  const doc = docs[0];",
    "  if (doc?.errors?.length) throw new Error(\"yaml defective\");",
    "  const root = doc.contents;",
    "  if (!YAML.isMap(root)) throw new Error(\"yaml root defective\");",
    "  const anchors = new Map();",
    "  yamlCollectAnchors(root, anchors);",
    "  const ctx = { anchors, resolving: new Set() };",
    "  const value = yamlNodeToJson(root, ctx);",
    "  if (!value || typeof value !== \"object\" || Array.isArray(value)) throw new Error(\"yaml root defective\");",
    "  return canonicalizeJsonValue(value);",
    "}",
    "function yamlToPyashTextRuntime(text, rootName) {",
    "  const json = yamlToJsonValue(text);",
    "  return jsonToPyashTextRuntime(json, rootName);",
    "}"
  ].join("\n");
}

export { yamlRuntimeHelper };
