function yamlStringifyHelper() {
  return [
    "function yamlCompareUtf8(a, b) {",
    "  if (a === b) return 0;",
    "  const encoder = typeof TextEncoder !== \"undefined\" ? new TextEncoder() : null;",
    "  const bufA = encoder ? encoder.encode(a) : Array.from(a, ch => ch.charCodeAt(0));",
    "  const bufB = encoder ? encoder.encode(b) : Array.from(b, ch => ch.charCodeAt(0));",
    "  const len = Math.min(bufA.length, bufB.length);",
    "  for (let i = 0; i < len; i += 1) {",
    "    if (bufA[i] !== bufB[i]) return bufA[i] < bufB[i] ? -1 : 1;",
    "  }",
    "  return bufA.length < bufB.length ? -1 : 1;",
    "}",
    "function yamlCanonicalize(value) {",
    "  if (Array.isArray(value)) return value.map((item) => yamlCanonicalize(item));",
    "  if (value && typeof value === \"object\") {",
    "    const out = {};",
    "    const keys = Object.keys(value).sort(yamlCompareUtf8);",
    "    for (const key of keys) out[key] = yamlCanonicalize(value[key]);",
    "    return out;",
    "  }",
    "  return value;",
    "}",
    "function yamlEmit(value, indent, out) {",
    "  if (value === null) { out.push(\"null\"); return; }",
    "  if (typeof value === \"boolean\") { out.push(value ? \"true\" : \"false\"); return; }",
    "  if (typeof value === \"number\") { out.push(String(value)); return; }",
    "  if (typeof value === \"string\") { out.push(JSON.stringify(value)); return; }",
    "  if (Array.isArray(value)) {",
    "    if (indent > 0) out.push(\"\\n\");",
    "    for (const item of value) {",
    "      out.push(\" \".repeat(indent));",
    "      out.push(\"- \");",
    "      yamlEmit(item, indent + 2, out);",
    "      out.push(\"\\n\");",
    "    }",
    "    return;",
    "  }",
    "  if (value && typeof value === \"object\") {",
    "    if (indent > 0) out.push(\"\\n\");",
    "    for (const key of Object.keys(value)) {",
    "      out.push(\" \".repeat(indent));",
    "      out.push(JSON.stringify(String(key ?? \"\")));",
    "      out.push(\": \");",
    "      yamlEmit(value[key], indent + 2, out);",
    "      out.push(\"\\n\");",
    "    }",
    "    return;",
    "  }",
    "  out.push(\"null\");",
    "}",
    "function yamlStringifyRuntime(value) {",
    "  const json = yamlCanonicalize(value ?? {});",
    "  const out = [];",
    "  yamlEmit(json, 0, out);",
    "  return out.join(\"\");",
    "}"
  ].join("\n");
}

export { yamlStringifyHelper };
