version: "3.8"
services:
  pyash:
    container_name: pyash
    build:
      context: ..
      dockerfile: container/Dockerfile
    image: pyash-dev
    working_dir: /workplace
    volumes:
      - ..:/workplace
      - ../minds:/minds
    stdin_open: true
    tty: true
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-http://host.docker.internal:11434}
    extra_hosts:
      - host.docker.internal:host-gateway
