import fs from "node:fs/promises";
import path from "node:path";

const rootDir = path.resolve(new URL("..", import.meta.url).pathname);
const configPath = path.join(rootDir, "configure", "workplace.pya");
const overridePath = path.join(rootDir, "container", "compose.override.yaml");

function parseWorkplace(text) {
  const out = new Map();
  const lines = text.split("\n");
  for (const line of lines) {
    const textMatch = line.match(/^\s*su name ([^ ]+) ob text "([^"]*)" ya\s*$/);
    if (textMatch) {
      out.set(textMatch[1], textMatch[2]);
      continue;
    }
    const boolMatch = line.match(/^\s*su name ([^ ]+) ob bool (truth|lie) ya\s*$/);
    if (boolMatch) {
      out.set(boolMatch[1], boolMatch[2]);
      continue;
    }
  }
  return out;
}

async function loadWorkplace() {
  try {
    const text = await fs.readFile(configPath, "utf8");
    return parseWorkplace(text);
  } catch {
    return new Map();
  }
}

function yamlList(items, indent = "    ") {
  if (!items.length) return [];
  return items.map(item => `${indent}- ${item}`);
}

function yamlKeyValue(key, value, indent = "    ") {
  return `${indent}${key}: ${value}`;
}

function quote(value) {
  if (typeof value !== "string") return value;
  if (/^[A-Za-z0-9_./:$-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

const workplace = await loadWorkplace();
const gpuEnabled = (workplace.get("gpu enabled") ?? "lie") === "truth";
const audioEnabled = (workplace.get("audio enabled") ?? "lie") === "truth";
const vncEnabled = (workplace.get("vnc enabled") ?? "lie") === "truth";

const lines = [
  "# Generated by container/update_compose.mjs",
  "services:",
  "  pyash:",
  yamlKeyValue("user", quote("${PYASH_UID}:${PYASH_GID}"), "    "),
  "    environment:",
  `      - HOME=${quote("/workplace")}`
];

const pulseDir = process.env.PYASH_PULSE_DIR;
const pulseCookie = process.env.PYASH_PULSE_COOKIE;
const codexDir = process.env.PYASH_CODEX_DIR;
const gitConfig = process.env.PYASH_GITCONFIG;
const gitConfigXdg = process.env.PYASH_GITCONFIG_XDG;
const hostTz = process.env.PYASH_TZ;

const volumes = [];
const devices = [];
const ports = [];

if (audioEnabled && pulseDir && pulseCookie) {
  try {
    await fs.stat(pulseDir);
    await fs.stat(pulseCookie);
    lines.push("      - XDG_CONFIG_HOME=/workplace/.config");
    lines.push(`      - PULSE_SERVER=unix:${"${PYASH_PULSE_DIR}"}/pulse/native`);
    volumes.push(`${"${PYASH_PULSE_DIR}"}:${"${PYASH_PULSE_DIR}"}`);
    volumes.push(`${"${PYASH_PULSE_COOKIE}"}:/workplace/.config/pulse/cookie`);
    devices.push("/dev/snd:/dev/snd");
  } catch {}
}

if (codexDir) {
  try {
    await fs.stat(codexDir);
    volumes.push(`${"${PYASH_CODEX_DIR}"}:/workplace/.codex`);
    lines.push("      - CODEX_HOME=/workplace/.codex");
  } catch {}
}

if (gitConfig) {
  try {
    await fs.stat(gitConfig);
    volumes.push(`${"${PYASH_GITCONFIG}"}:/workplace/.gitconfig:ro`);
  } catch {}
}

if (gitConfigXdg) {
  try {
    await fs.stat(gitConfigXdg);
    volumes.push(`${"${PYASH_GITCONFIG_XDG}"}:/workplace/.config/git/config:ro`);
  } catch {}
}

if (hostTz) {
  lines.push(`      - TZ=${quote(hostTz)}`);
}

if (vncEnabled) {
  ports.push("\"5900:5900\"");
  ports.push("\"6080:6080\"");
  lines.push("    command: [\"/workplace/container/run_vnc_novnc.sh\"]");
}

if (gpuEnabled) {
  lines.push("    device_requests:");
  lines.push("      - driver: nvidia");
  lines.push("        count: all");
  lines.push("        capabilities: [gpu]");
}

if (ports.length) {
  lines.push("    ports:");
  lines.push(...yamlList(ports, "      "));
}

if (devices.length) {
  lines.push("    devices:");
  lines.push(...yamlList(devices, "      "));
}

if (volumes.length) {
  lines.push("    volumes:");
  lines.push(...yamlList(volumes.map(quote), "      "));
}

await fs.writeFile(overridePath, `${lines.join("\n")}\n`, "utf8");
