#!/usr/bin/env bash

# Convenience wrapper:
# - If called with positional args (<input> <output> [target]),
#   build a compile sentence: from filename "<input>" from state pyash
#   to filename "<output>" to state <target> be compile do
# - Otherwise, pass through to run_pya_program (preserve flags like --full)

if [[ "$#" -ge 1 && "$1" != -* ]]; then
  INPUT="$1"
  OUTPUT="$2"
  TARGET="$3"
  if [[ -z "$OUTPUT" ]]; then
    echo "usage: ./compile <input.pya> <output.{js|c|txt}> [target-state]" >&2
    exit 1
  fi
  if [[ -z "$TARGET" ]]; then
    TARGET="javascript"
  fi
  SENTENCE="from filename \"${INPUT}\" from state pyash to filename \"${OUTPUT}\" to state ${TARGET} be compile do"
  node program/command/run_pya_program.mjs --gross "${SENTENCE}"
else
  node program/command/run_pya_program.mjs --gross "$@"
fi
