export function buildRefineryCPreludeLines() {
  const lines = [];
  lines.push("static void pya_sleep_ms(int ms) {");
  lines.push("  if (ms <= 0) return;");
  lines.push("  struct timespec req;");
  lines.push("  req.tv_sec = ms / 1000;");
  lines.push("  req.tv_nsec = (long)(ms % 1000) * 1000000L;");
  lines.push("  nanosleep(&req, NULL);");
  lines.push("}");
  lines.push("static uint32_t pya_fnv1a_update(uint32_t hash, const unsigned char *data, size_t len) {");
  lines.push("  for (size_t i = 0; i < len; i++) {");
  lines.push("    hash ^= data[i];");
  lines.push("    hash *= 16777619u;");
  lines.push("  }");
  lines.push("  return hash;");
  lines.push("}");
  lines.push("static void pya_fnv1a_hex(const char *text, char *out) {");
  lines.push("  uint32_t hash = 2166136261u;");
  lines.push("  const unsigned char *data = (const unsigned char *)(text ? text : \"\");");
  lines.push("  hash = pya_fnv1a_update(hash, data, strlen((const char *)data));");
  lines.push("  snprintf(out, 16, \"%08x\", hash);");
  lines.push("}");
  lines.push("static void pya_checkpoint_hash(const char *action, const char **depNames, const char **depResults, int depCount, char *out) {");
  lines.push("  uint32_t hash = 2166136261u;");
  lines.push("  const char *prefix = \"action:\";");
  lines.push("  hash = pya_fnv1a_update(hash, (const unsigned char *)prefix, strlen(prefix));");
  lines.push("  hash = pya_fnv1a_update(hash, (const unsigned char *)(action ? action : \"\"), strlen(action ? action : \"\"));");
  lines.push("  for (int i = 0; i < depCount; i++) {");
  lines.push("    const char *dep = depNames[i];");
  lines.push("    const char *res = depResults[i] ? depResults[i] : \"\";");
  lines.push("    const char *sep = \"\\n\";");
  lines.push("    const char *depPrefix = \"dep:\";");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)sep, 1);");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)depPrefix, strlen(depPrefix));");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)(dep ? dep : \"\"), strlen(dep ? dep : \"\"));");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)\":\", 1);");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)res, strlen(res));");
  lines.push("  }");
  lines.push("  snprintf(out, 16, \"%08x\", hash);");
  lines.push("}");
  lines.push("typedef struct {");
  lines.push("  char refinery[128];");
  lines.push("  char platform[128];");
  lines.push("  char hash[16];");
  lines.push("  char result[PYA_TEXT_CAP];");
  lines.push("} pya_checkpoint_entry;");
  lines.push("static pya_checkpoint_entry pya_checkpoints[256];");
  lines.push("static int pya_checkpoint_count = 0;");
  lines.push("static int pya_checkpoint_loaded = 0;");
  lines.push("static void pya_checkpoint_unescape(const char *src, char *out, size_t cap) {");
  lines.push("  if (!out || cap == 0) return;");
  lines.push("  size_t len = 0;");
  lines.push("  for (const char *p = src ? src : \"\"; *p && len + 1 < cap; p++) {");
  lines.push("    if (*p == '\\\\') {");
  lines.push("      p++;");
  lines.push("      if (!*p) break;");
  lines.push("      if (*p == 't') out[len++] = '\\t';");
  lines.push("      else if (*p == 'n') out[len++] = '\\n';");
  lines.push("      else if (*p == 'r') out[len++] = '\\r';");
  lines.push("      else out[len++] = *p;");
  lines.push("    } else {");
  lines.push("      out[len++] = *p;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  out[len] = '\\0';");
  lines.push("}");
  lines.push("static void pya_load_checkpoints(void) {");
  lines.push("  if (pya_checkpoint_loaded) return;");
  lines.push("  pya_checkpoint_loaded = 1;");
  lines.push("  const char *env = getenv(\"PYA_CHECKPOINTS\");");
  lines.push("  if (!env || !*env) return;");
  lines.push("  const char *p = env;");
  lines.push("  while (*p && pya_checkpoint_count < 256) {");
  lines.push("    char line[PYA_TEXT_CAP];");
  lines.push("    size_t len = 0;");
  lines.push("    while (*p && *p != '\\n' && len + 1 < sizeof(line)) {");
  lines.push("      line[len++] = *p++;");
  lines.push("    }");
  lines.push("    if (*p == '\\n') p++;");
  lines.push("    line[len] = '\\0';");
  lines.push("    if (len == 0) continue;");
  lines.push("    char *fields[4] = { line, NULL, NULL, NULL };");
  lines.push("    int fieldCount = 1;");
  lines.push("    for (size_t i = 0; line[i] && fieldCount < 4; i++) {");
  lines.push("      if (line[i] == '\\t') {");
  lines.push("        line[i] = '\\0';");
  lines.push("        fields[fieldCount++] = line + i + 1;");
  lines.push("      }");
  lines.push("    }");
  lines.push("    if (fieldCount < 4) continue;");
  lines.push("    pya_checkpoint_entry *entry = &pya_checkpoints[pya_checkpoint_count++];");
  lines.push("    pya_checkpoint_unescape(fields[0], entry->refinery, sizeof(entry->refinery));");
  lines.push("    pya_checkpoint_unescape(fields[1], entry->platform, sizeof(entry->platform));");
  lines.push("    pya_checkpoint_unescape(fields[2], entry->hash, sizeof(entry->hash));");
  lines.push("    pya_checkpoint_unescape(fields[3], entry->result, sizeof(entry->result));");
  lines.push("  }");
  lines.push("}");
  lines.push("static const char *pya_find_checkpoint(const char *refinery, const char *platform, const char *hash) {");
  lines.push("  for (int i = 0; i < pya_checkpoint_count; i++) {");
  lines.push("    if (strcmp(pya_checkpoints[i].refinery, refinery) == 0 && strcmp(pya_checkpoints[i].platform, platform) == 0 && strcmp(pya_checkpoints[i].hash, hash) == 0) {");
  lines.push("      return pya_checkpoints[i].result;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return NULL;");
  lines.push("}");
  lines.push("static int pya_looks_like_remote_locator(const char *value) {");
  lines.push("  if (!value || !*value) return 0;");
  lines.push("  for (const char *p = value; *p; p++) {");
  lines.push("    unsigned char ch = (unsigned char)*p;");
  lines.push("    if (*p == ':') return (p[1] == '/' && p[2] == '/');");
  lines.push("    if (!(isalnum(ch) || *p == '+' || *p == '-' || *p == '.')) return 0;");
  lines.push("  }");
  lines.push("  return 0;");
  lines.push("}");
  lines.push("static int pya_read_filename_token(const char *src, char *out, size_t cap) {");
  lines.push("  if (!src || !out || cap == 0) return 0;");
  lines.push("  while (*src == ' ' || *src == '\\t') src++;");
  lines.push("  if (!*src) return 0;");
  lines.push("  size_t len = 0;");
  lines.push("  if (*src == '\"') {");
  lines.push("    src++;");
  lines.push("    while (*src && len + 1 < cap) {");
  lines.push("      if (*src == '\\\\' && src[1]) {");
  lines.push("        src++;");
  lines.push("        if (*src == 'n') out[len++] = '\\n';");
  lines.push("        else if (*src == 'r') out[len++] = '\\r';");
  lines.push("        else if (*src == 't') out[len++] = '\\t';");
  lines.push("        else out[len++] = *src;");
  lines.push("        src++;");
  lines.push("        continue;");
  lines.push("      }");
  lines.push("      if (*src == '\"') {");
  lines.push("        src++;");
  lines.push("        break;");
  lines.push("      }");
  lines.push("      out[len++] = *src++;");
  lines.push("    }");
  lines.push("  } else {");
  lines.push("    while (*src && !isspace((unsigned char)*src) && len + 1 < cap) {");
  lines.push("      out[len++] = *src++;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  out[len] = '\\0';");
  lines.push("  return len > 0;");
  lines.push("}");
  lines.push("static int pya_checkpoint_result_files_exist(const char *resultLine) {");
  lines.push("  if (!resultLine || !*resultLine) return 1;");
  lines.push("  const char *cases[] = { \"ob filename\", \"to filename\", \"from filename\" };");
  lines.push("  for (int ci = 0; ci < 3; ci++) {");
  lines.push("    const char *needle = cases[ci];");
  lines.push("    const size_t needle_len = strlen(needle);");
  lines.push("    const char *cursor = resultLine;");
  lines.push("    while ((cursor = strstr(cursor, needle)) != NULL) {");
  lines.push("      const char *valueStart = cursor + needle_len;");
  lines.push("      char locator[PYA_TEXT_CAP];");
  lines.push("      if (pya_read_filename_token(valueStart, locator, sizeof(locator))) {");
  lines.push("        if (!pya_looks_like_remote_locator(locator)) {");
  lines.push("          struct stat st;");
  lines.push("          if (stat(locator, &st) != 0) return 0;");
  lines.push("        }");
  lines.push("      }");
  lines.push("      cursor = valueStart;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return 1;");
  lines.push("}");
  lines.push("typedef struct {");
  lines.push("  int artificial_kind;");
  lines.push("  int artificial_value;");
  lines.push("  int seed_kind;");
  lines.push("  double seed;");
  lines.push("  int start_tick_kind;");
  lines.push("  double start_tick;");
  lines.push("  int parallel_capacity_kind;");
  lines.push("  double parallel_capacity;");
  lines.push("  int waiting_capacity_kind;");
  lines.push("  double waiting_capacity;");
  lines.push("  int schedule_newspaper_kind;");
  lines.push("  int schedule_newspaper_value;");
  lines.push("} pya_sim_conduct;");
  lines.push("static int pya_sim_uint32(double value, int positive) {");
  lines.push("  if (value != value || value < (positive ? 1.0 : 0.0) || value > 4294967295.0) return 0;");
  lines.push("  return value == (double)(uint32_t)value;");
  lines.push("}");
  lines.push("static int pya_sim_normalize(const pya_sim_conduct *raw, uint32_t *seed, uint32_t *startTick, uint32_t *parallelCapacity, uint32_t *waitingCapacity, int *scheduleNewspaper) {");
  lines.push("  if (!raw) return 0;");
  lines.push("  if (raw->artificial_kind != 1) return -1;");
  lines.push("  if (!raw->artificial_value) return 0;");
  lines.push("  if (raw->seed_kind != 1 || !pya_sim_uint32(raw->seed, 0)) return -1;");
  lines.push("  if (raw->start_tick_kind != 1 || !pya_sim_uint32(raw->start_tick, 0)) return -1;");
  lines.push("  if (raw->parallel_capacity_kind != 1 || !pya_sim_uint32(raw->parallel_capacity, 1)) return -1;");
  lines.push("  if (raw->waiting_capacity_kind != 1 || !pya_sim_uint32(raw->waiting_capacity, 0)) return -1;");
  lines.push("  if (raw->schedule_newspaper_kind == 2) return -1;");
  lines.push("  *seed = (uint32_t)raw->seed;");
  lines.push("  *startTick = (uint32_t)raw->start_tick;");
  lines.push("  *parallelCapacity = (uint32_t)raw->parallel_capacity;");
  lines.push("  *waitingCapacity = (uint32_t)raw->waiting_capacity;");
  lines.push("  *scheduleNewspaper = raw->schedule_newspaper_kind == 1 ? raw->schedule_newspaper_value : 0;");
  lines.push("  return 1;");
  lines.push("}");
  lines.push("static void pya_sim_defect(void) {");
  lines.push("  pya_emit_exchange(\"su name artificial conduct defective ob text \\\"artificial conduct defective\\\" from name refinery be error ya\");");
  lines.push("}");
  lines.push("static uint32_t pya_sim_rank(const char *name, uint32_t seed) {");
  lines.push("  uint32_t hash = 2166136261u;");
  lines.push("  const unsigned char *data = (const unsigned char *)(name ? name : \"\");");
  lines.push("  for (size_t i = 0; data[i]; i++) hash = (uint32_t)((hash ^ data[i]) * 16777619u);");
  lines.push("  uint32_t value = hash ^ seed;");
  lines.push("  value = (uint32_t)(value ^ (value << 13));");
  lines.push("  value = (uint32_t)(value ^ (value >> 17));");
  lines.push("  value = (uint32_t)(value ^ (value << 5));");
  lines.push("  return value;");
  lines.push("}");
  lines.push("static int pya_sim_compare_index(int left, int right, const char **names, const uint32_t *ranks, int rankFirst) {");
  lines.push("  if (rankFirst && ranks[left] != ranks[right]) return ranks[left] < ranks[right] ? -1 : 1;");
  lines.push("  int nameOrder = strcmp(names[left], names[right]);");
  lines.push("  if (nameOrder != 0) return nameOrder < 0 ? -1 : 1;");
  lines.push("  return 0;");
  lines.push("}");
  lines.push("static void pya_sim_sort(int *values, int length, const char **names, const uint32_t *ranks, int rankFirst) {");
  lines.push("  for (int i = 1; i < length; i++) {");
  lines.push("    int value = values[i];");
  lines.push("    int j = i;");
  lines.push("    while (j > 0 && pya_sim_compare_index(value, values[j - 1], names, ranks, rankFirst) < 0) { values[j] = values[j - 1]; j--; }");
  lines.push("    values[j] = value;");
  lines.push("  }");
  lines.push("}");
  lines.push("static void pya_sim_schedule_record(const char *refinery, const char *platform, uint64_t tick, uint64_t *ordinal, const char *be, int enabled) {");
  lines.push("  *ordinal += 1;");
  lines.push("  if (!enabled) return;");
  lines.push("  char line[PYA_TEXT_CAP];");
  lines.push("  snprintf(line, sizeof(line), \"su name %s from name %s during num %llu by num %llu be %s ya\", platform, refinery, (unsigned long long)tick, (unsigned long long)*ordinal, be);");
  lines.push("  pya_emit_exchange(line);");
  lines.push("}");
  lines.push("static void pya_sim_fault_record(const char *refinery, const char *platform, uint64_t tick, uint64_t *ordinal, const char *text) {");
  lines.push("  *ordinal += 1;");
  lines.push("  char line[PYA_TEXT_CAP];");
  lines.push("  snprintf(line, sizeof(line), \"su name %s ob text \\\"%s\\\" from name %s during num %llu by num %llu be error ya\", platform, text, refinery, (unsigned long long)tick, (unsigned long long)*ordinal);");
  lines.push("  pya_emit_exchange(line);");
  lines.push("}");
  lines.push("static int pya_simulation_run(const char *refineryName, const char **names, const char ***deps, const int *depCounts, const double *durations, const int *durationKinds, const double *timeboxes, const int *timeboxKinds, int count, const pya_sim_conduct *raw) {");
  lines.push("  uint32_t seed = 0; uint32_t startTick = 0; uint32_t parallelCapacity = 0; uint32_t waitingCapacity = 0; int scheduleNewspaper = 0;");
  lines.push("  int normalized = pya_sim_normalize(raw, &seed, &startTick, &parallelCapacity, &waitingCapacity, &scheduleNewspaper);");
  lines.push("  if (normalized == 0) return 0;");
  lines.push("  if (normalized < 0 || count <= 0) { pya_sim_defect(); return -1; }");
  lines.push("  uint32_t ranks[count]; uint64_t durationsInt[count]; uint64_t timeboxesInt[count]; int hasTimebox[count]; int status[count]; int denied[count]; uint64_t finishTicks[count]; uint64_t deadlineTicks[count];");
  lines.push("  for (int i = 0; i < count; i++) {");
  lines.push("    if (durationKinds[i] != 1 || !pya_sim_uint32(durations[i], 1) || (timeboxKinds[i] == 2) || (timeboxKinds[i] == 1 && !pya_sim_uint32(timeboxes[i], 1))) { pya_sim_defect(); return -1; }");
  lines.push("    ranks[i] = pya_sim_rank(names[i], seed); durationsInt[i] = (uint64_t)durations[i]; hasTimebox[i] = timeboxKinds[i] == 1; timeboxesInt[i] = hasTimebox[i] ? (uint64_t)timeboxes[i] : 0; status[i] = 0; denied[i] = 0; finishTicks[i] = 0; deadlineTicks[i] = 0;");
  lines.push("    for (int d = 0; d < depCounts[i]; d++) { int found = 0; for (int j = 0; j < count; j++) if (strcmp(deps[i][d], names[j]) == 0) { found = 1; break; } if (!found) { pya_sim_defect(); return -1; } }");
  lines.push("  }");
  lines.push("  uint64_t tick = startTick; uint64_t ordinal = 0;");
  lines.push("  for (;;) {");
  lines.push("    int activeCount = 0; int waitingCount = 0; int pendingCount = 0;");
  lines.push("    for (int i = 0; i < count; i++) { if (status[i] == 0) pendingCount++; else if (status[i] == 1) waitingCount++; else if (status[i] == 2 || status[i] == 3) activeCount++; }");
  lines.push("    if (pendingCount == 0 && waitingCount == 0 && activeCount == 0) break;");
  lines.push("    int candidates[count > 0 ? count : 1]; int candidateCount = 0;");
  lines.push("    for (int i = 0; i < count; i++) if (status[i] == 3 && finishTicks[i] == tick) candidates[candidateCount++] = i;");
  lines.push("    pya_sim_sort(candidates, candidateCount, names, ranks, 1);");
  lines.push("    for (int k = 0; k < candidateCount; k++) { int i = candidates[k]; status[i] = 4; activeCount--; pya_sim_schedule_record(refineryName, names[i], tick, &ordinal, \"schedule finish\", scheduleNewspaper); }");
  lines.push("    candidateCount = 0; for (int i = 0; i < count; i++) if (status[i] == 3 && hasTimebox[i] && deadlineTicks[i] <= tick) candidates[candidateCount++] = i;");
  lines.push("    pya_sim_sort(candidates, candidateCount, names, ranks, 1);");
  lines.push("    for (int k = 0; k < candidateCount; k++) { int i = candidates[k]; status[i] = 5; activeCount--; pya_sim_fault_record(refineryName, names[i], tick, &ordinal, \"platform timebox\"); }");
  lines.push("    int cancel[count > 0 ? count : 1]; for (int i = 0; i < count; i++) cancel[i] = 0;");
  lines.push("    int changed = 1; while (changed) { changed = 0; for (int i = 0; i < count; i++) if ((status[i] == 0 || status[i] == 1) && !cancel[i]) { for (int d = 0; d < depCounts[i]; d++) { int dependency = -1; for (int j = 0; j < count; j++) if (strcmp(deps[i][d], names[j]) == 0) { dependency = j; break; } if (dependency >= 0 && (status[dependency] == 5 || status[dependency] == 6 || cancel[dependency])) { cancel[i] = 1; changed = 1; break; } } } }");
  lines.push("    candidateCount = 0; for (int i = 0; i < count; i++) if (cancel[i]) candidates[candidateCount++] = i; pya_sim_sort(candidates, candidateCount, names, ranks, 0);");
  lines.push("    for (int k = 0; k < candidateCount; k++) { int i = candidates[k]; status[i] = 6; pya_sim_fault_record(refineryName, names[i], tick, &ordinal, \"platform cancel\"); }");
  lines.push("    candidateCount = 0; for (int i = 0; i < count; i++) if (status[i] == 1) candidates[candidateCount++] = i; pya_sim_sort(candidates, candidateCount, names, ranks, 1);");
  lines.push("    for (int k = 0; k < candidateCount && activeCount < (int)parallelCapacity; k++) { int i = candidates[k]; status[i] = 2; activeCount++; waitingCount--; }");
  lines.push("    candidateCount = 0; for (int i = 0; i < count; i++) { if (status[i] != 0) continue; int ready = 1; for (int d = 0; d < depCounts[i]; d++) { int dependency = -1; for (int j = 0; j < count; j++) if (strcmp(deps[i][d], names[j]) == 0) { dependency = j; break; } if (dependency < 0 || status[dependency] != 4) { ready = 0; break; } } if (ready) candidates[candidateCount++] = i; }");
  lines.push("    pya_sim_sort(candidates, candidateCount, names, ranks, 1);");
  lines.push("    for (int k = 0; k < candidateCount; k++) { int i = candidates[k]; if (activeCount < (int)parallelCapacity) { status[i] = 2; activeCount++; pya_sim_schedule_record(refineryName, names[i], tick, &ordinal, \"schedule admission\", scheduleNewspaper); } else if (waitingCount < (int)waitingCapacity) { status[i] = 1; waitingCount++; pya_sim_schedule_record(refineryName, names[i], tick, &ordinal, \"schedule admission\", scheduleNewspaper); } else if (!denied[i]) { denied[i] = 1; ordinal++; if (scheduleNewspaper) { char line[PYA_TEXT_CAP]; snprintf(line, sizeof(line), \"su name %s ob text \\\"schedule crowded\\\" from name %s during num %llu by num %llu be schedule crowded ya\", names[i], refineryName, (unsigned long long)tick, (unsigned long long)ordinal); pya_emit_exchange(line); } } }");
  lines.push("    candidateCount = 0; for (int i = 0; i < count; i++) if (status[i] == 2) candidates[candidateCount++] = i; pya_sim_sort(candidates, candidateCount, names, ranks, 1);");
  lines.push("    for (int k = 0; k < candidateCount; k++) { int i = candidates[k]; status[i] = 3; finishTicks[i] = tick + durationsInt[i]; deadlineTicks[i] = hasTimebox[i] ? tick + timeboxesInt[i] : 0; pya_sim_schedule_record(refineryName, names[i], tick, &ordinal, \"schedule start\", scheduleNewspaper); }");
  lines.push("    pendingCount = 0; waitingCount = 0; activeCount = 0; for (int i = 0; i < count; i++) { if (status[i] == 0) pendingCount++; else if (status[i] == 1) waitingCount++; else if (status[i] == 2 || status[i] == 3) activeCount++; } if (pendingCount == 0 && waitingCount == 0 && activeCount == 0) break;");
  lines.push("    int haveNext = 0; uint64_t nextTick = 0; for (int i = 0; i < count; i++) if (status[i] == 3) { if (finishTicks[i] > tick && (!haveNext || finishTicks[i] < nextTick)) { nextTick = finishTicks[i]; haveNext = 1; } if (hasTimebox[i] && deadlineTicks[i] > tick && (!haveNext || deadlineTicks[i] < nextTick)) { nextTick = deadlineTicks[i]; haveNext = 1; } } if (!haveNext || nextTick <= tick) { pya_sim_defect(); return -1; } tick = nextTick;");
  lines.push("  }");
  lines.push("  return 1;");
  lines.push("}");
  return lines;
}
