export function buildRefineryCPreludeLines() {
  const lines = [];
  lines.push("static void pya_sleep_ms(int ms) {");
  lines.push("  if (ms <= 0) return;");
  lines.push("  struct timespec req;");
  lines.push("  req.tv_sec = ms / 1000;");
  lines.push("  req.tv_nsec = (long)(ms % 1000) * 1000000L;");
  lines.push("  nanosleep(&req, NULL);");
  lines.push("}");
  lines.push("static uint32_t pya_fnv1a_update(uint32_t hash, const unsigned char *data, size_t len) {");
  lines.push("  for (size_t i = 0; i < len; i++) {");
  lines.push("    hash ^= data[i];");
  lines.push("    hash *= 16777619u;");
  lines.push("  }");
  lines.push("  return hash;");
  lines.push("}");
  lines.push("static void pya_fnv1a_hex(const char *text, char *out) {");
  lines.push("  uint32_t hash = 2166136261u;");
  lines.push("  const unsigned char *data = (const unsigned char *)(text ? text : \"\");");
  lines.push("  hash = pya_fnv1a_update(hash, data, strlen((const char *)data));");
  lines.push("  snprintf(out, 16, \"%08x\", hash);");
  lines.push("}");
  lines.push("static void pya_checkpoint_hash(const char *action, const char **depNames, const char **depResults, int depCount, char *out) {");
  lines.push("  uint32_t hash = 2166136261u;");
  lines.push("  const char *prefix = \"action:\";");
  lines.push("  hash = pya_fnv1a_update(hash, (const unsigned char *)prefix, strlen(prefix));");
  lines.push("  hash = pya_fnv1a_update(hash, (const unsigned char *)(action ? action : \"\"), strlen(action ? action : \"\"));");
  lines.push("  for (int i = 0; i < depCount; i++) {");
  lines.push("    const char *dep = depNames[i];");
  lines.push("    const char *res = depResults[i] ? depResults[i] : \"\";");
  lines.push("    const char *sep = \"\\n\";");
  lines.push("    const char *depPrefix = \"dep:\";");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)sep, 1);");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)depPrefix, strlen(depPrefix));");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)(dep ? dep : \"\"), strlen(dep ? dep : \"\"));");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)\":\", 1);");
  lines.push("    hash = pya_fnv1a_update(hash, (const unsigned char *)res, strlen(res));");
  lines.push("  }");
  lines.push("  snprintf(out, 16, \"%08x\", hash);");
  lines.push("}");
  lines.push("typedef struct {");
  lines.push("  char refinery[128];");
  lines.push("  char platform[128];");
  lines.push("  char hash[16];");
  lines.push("  char result[PYA_TEXT_CAP];");
  lines.push("} pya_checkpoint_entry;");
  lines.push("static pya_checkpoint_entry pya_checkpoints[256];");
  lines.push("static int pya_checkpoint_count = 0;");
  lines.push("static int pya_checkpoint_loaded = 0;");
  lines.push("static void pya_checkpoint_unescape(const char *src, char *out, size_t cap) {");
  lines.push("  if (!out || cap == 0) return;");
  lines.push("  size_t len = 0;");
  lines.push("  for (const char *p = src ? src : \"\"; *p && len + 1 < cap; p++) {");
  lines.push("    if (*p == '\\\\') {");
  lines.push("      p++;");
  lines.push("      if (!*p) break;");
  lines.push("      if (*p == 't') out[len++] = '\\t';");
  lines.push("      else if (*p == 'n') out[len++] = '\\n';");
  lines.push("      else if (*p == 'r') out[len++] = '\\r';");
  lines.push("      else out[len++] = *p;");
  lines.push("    } else {");
  lines.push("      out[len++] = *p;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  out[len] = '\\0';");
  lines.push("}");
  lines.push("static void pya_load_checkpoints(void) {");
  lines.push("  if (pya_checkpoint_loaded) return;");
  lines.push("  pya_checkpoint_loaded = 1;");
  lines.push("  const char *env = getenv(\"PYA_CHECKPOINTS\");");
  lines.push("  if (!env || !*env) return;");
  lines.push("  const char *p = env;");
  lines.push("  while (*p && pya_checkpoint_count < 256) {");
  lines.push("    char line[PYA_TEXT_CAP];");
  lines.push("    size_t len = 0;");
  lines.push("    while (*p && *p != '\\n' && len + 1 < sizeof(line)) {");
  lines.push("      line[len++] = *p++;");
  lines.push("    }");
  lines.push("    if (*p == '\\n') p++;");
  lines.push("    line[len] = '\\0';");
  lines.push("    if (len == 0) continue;");
  lines.push("    char *fields[4] = { line, NULL, NULL, NULL };");
  lines.push("    int fieldCount = 1;");
  lines.push("    for (size_t i = 0; line[i] && fieldCount < 4; i++) {");
  lines.push("      if (line[i] == '\\t') {");
  lines.push("        line[i] = '\\0';");
  lines.push("        fields[fieldCount++] = line + i + 1;");
  lines.push("      }");
  lines.push("    }");
  lines.push("    if (fieldCount < 4) continue;");
  lines.push("    pya_checkpoint_entry *entry = &pya_checkpoints[pya_checkpoint_count++];");
  lines.push("    pya_checkpoint_unescape(fields[0], entry->refinery, sizeof(entry->refinery));");
  lines.push("    pya_checkpoint_unescape(fields[1], entry->platform, sizeof(entry->platform));");
  lines.push("    pya_checkpoint_unescape(fields[2], entry->hash, sizeof(entry->hash));");
  lines.push("    pya_checkpoint_unescape(fields[3], entry->result, sizeof(entry->result));");
  lines.push("  }");
  lines.push("}");
  lines.push("static const char *pya_find_checkpoint(const char *refinery, const char *platform, const char *hash) {");
  lines.push("  for (int i = 0; i < pya_checkpoint_count; i++) {");
  lines.push("    if (strcmp(pya_checkpoints[i].refinery, refinery) == 0 && strcmp(pya_checkpoints[i].platform, platform) == 0 && strcmp(pya_checkpoints[i].hash, hash) == 0) {");
  lines.push("      return pya_checkpoints[i].result;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return NULL;");
  lines.push("}");
  return lines;
}
