export function buildRefineryJsPreludeLines(effectiveRetryConfig) {
  const lines = [];
  lines.push("const __pyaRefineries = {};");
  lines.push("const __pyaCompareUtf8 = (() => {");
  lines.push("  const encoder = typeof TextEncoder !== \"undefined\" ? new TextEncoder() : null;");
  lines.push("  return (a, b) => {");
  lines.push("    if (a === b) return 0;");
  lines.push("    const bufA = encoder ? encoder.encode(a) : Array.from(a, ch => ch.charCodeAt(0));");
  lines.push("    const bufB = encoder ? encoder.encode(b) : Array.from(b, ch => ch.charCodeAt(0));");
  lines.push("    const len = Math.min(bufA.length, bufB.length);");
  lines.push("    for (let i = 0; i < len; i += 1) {");
  lines.push("      if (bufA[i] !== bufB[i]) return bufA[i] < bufB[i] ? -1 : 1;");
  lines.push("    }");
  lines.push("    return bufA.length < bufB.length ? -1 : 1;");
  lines.push("  };");
  lines.push("})();");
  lines.push("const __pyaNewspaper = (typeof process !== \"undefined\" ? process.env?.PYA_NEWSPAPER : undefined) === \"1\";");
  lines.push("let __pyaLastErrorLine = null;");
  lines.push("const __pyaEmitNewspaper = (line) => {");
  lines.push("  if (!__pyaNewspaper || !line) return;");
  lines.push("  const text = String(line);");
  lines.push("  if (text.includes(\" be error ya\")) __pyaLastErrorLine = text;");
  lines.push("  if (text.includes(\"\\n\")) {");
  lines.push("    console.log(\"PYA_NEWSPAPER:BEGIN\");");
  lines.push("    console.log(text);");
  lines.push("    console.log(\"PYA_NEWSPAPER:END\");");
  lines.push("  } else {");
  lines.push("    console.log(\"PYA_NEWSPAPER:\" + text);");
  lines.push("  }");
  lines.push("};");
  lines.push("if (typeof pyaEmitNewspaper === \"function\") {");
  lines.push("  const __pyaOrig = pyaEmitNewspaper;");
  lines.push("  pyaEmitNewspaper = (line) => {");
  lines.push("    if (line && String(line).includes(\" be error ya\")) __pyaLastErrorLine = String(line);");
  lines.push("    return __pyaOrig(line);");
  lines.push("  };");
  lines.push("}");
  lines.push("const __pyaRetry = " + JSON.stringify(effectiveRetryConfig) + ";");
  lines.push("const __pyaCheckpointEnabled = !(typeof process !== \"undefined\" && process?.env?.PYA_NO_CHECKPOINT === \"1\");");
  lines.push("const __pyaCheckpoints = new Map();");
  lines.push("const __pyaCheckpointUnescape = (value) => String(value || \"\")");
  lines.push("  .replace(/\\\\t/g, \"\\t\")");
  lines.push("  .replace(/\\\\r/g, \"\\r\")");
  lines.push("  .replace(/\\\\n/g, \"\\n\")");
  lines.push("  .replace(/\\\\\\\\/g, \"\\\\\\\\\");");
  lines.push("const __pyaCheckpointLoad = () => {");
  lines.push("  if (!__pyaCheckpointEnabled) return;");
  lines.push("  const raw = (typeof process !== \"undefined\" ? process?.env?.PYA_CHECKPOINTS : undefined) || \"\";");
  lines.push("  if (!raw) return;");
  lines.push("  for (const line of raw.split(/\\r?\\n/)) {");
  lines.push("    if (!line) continue;");
  lines.push("    const parts = line.split(\"\\t\");");
  lines.push("    if (parts.length < 4) continue;");
  lines.push("    const refinery = __pyaCheckpointUnescape(parts[0]);");
  lines.push("    const platform = __pyaCheckpointUnescape(parts[1]);");
  lines.push("    const hash = __pyaCheckpointUnescape(parts[2]);");
  lines.push("    const result = __pyaCheckpointUnescape(parts.slice(3).join(\"\\t\"));");
  lines.push("    __pyaCheckpoints.set(`${refinery}::${platform}::${hash}`, result);");
  lines.push("  }");
  lines.push("};");
  lines.push("const __pyaFnv1aHex = (text) => {");
  lines.push("  const encoder = typeof TextEncoder !== \"undefined\" ? new TextEncoder() : null;");
  lines.push("  const bytes = encoder ? encoder.encode(String(text ?? \"\")) : Array.from(String(text ?? \"\"), ch => ch.charCodeAt(0));");
  lines.push("  let hash = 0x811c9dc5;");
  lines.push("  for (const byte of bytes) {");
  lines.push("    hash ^= byte;");
  lines.push("    hash = (hash * 0x01000193) >>> 0;");
  lines.push("  }");
  lines.push("  return hash.toString(16).padStart(8, \"0\");");
  lines.push("};");
  lines.push("const __pyaCheckpointHash = (actionLine, depNames, depResults) => {");
  lines.push("  const parts = [`action:${actionLine}`];");
  lines.push("  for (let i = 0; i < depNames.length; i += 1) {");
  lines.push("    parts.push(`dep:${depNames[i]}:${depResults[i] ?? \"\"}`);");
  lines.push("  }");
  lines.push("  return __pyaFnv1aHex(parts.join(\"\\n\"));");
  lines.push("};");
  lines.push("const __pyaCheckpointDecodeToken = (token) => {");
  lines.push("  const text = String(token ?? \"\").trim();");
  lines.push("  if (!text) return \"\";");
  lines.push("  if (text.startsWith(\"\\\"\") && text.endsWith(\"\\\"\") && text.length >= 2) {");
  lines.push("    const body = text.slice(1, -1);");
  lines.push("    return body");
  lines.push("      .replace(/\\\\t/g, \"\\t\")");
  lines.push("      .replace(/\\\\r/g, \"\\r\")");
  lines.push("      .replace(/\\\\n/g, \"\\n\")");
  lines.push("      .replace(/\\\\\\\"/g, \"\\\"\")");
  lines.push("      .replace(/\\\\\\\\/g, \"\\\\\");");
  lines.push("  }");
  lines.push("  return text;");
  lines.push("};");
  lines.push("const __pyaCheckpointCollectFilenameLocators = (resultLine) => {");
  lines.push("  const text = String(resultLine ?? \"\");");
  lines.push("  const out = [];");
  lines.push("  const cases = [\"ob\", \"to\", \"from\"];");
  lines.push("  for (const caseName of cases) {");
  lines.push("    const pattern = new RegExp(`\\\\b${caseName}\\\\s+filename\\\\s+(\\\"(?:\\\\\\\\.|[^\\\"\\\\\\\\])*\\\"|\\\\S+)`, \"g\");");
  lines.push("    let match;");
  lines.push("    while ((match = pattern.exec(text))) {");
  lines.push("      const locator = __pyaCheckpointDecodeToken(match[1]);");
  lines.push("      if (locator) out.push(locator);");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return out;");
  lines.push("};");
  lines.push("const __pyaLooksLikeRemoteLocator = (value) => /^[a-z]+:\\/\\//i.test(String(value ?? \"\").trim());");
  lines.push("const __pyaCheckpointResultFilesExist = (resultLine) => {");
  lines.push("  const locators = __pyaCheckpointCollectFilenameLocators(resultLine);");
  lines.push("  if (!locators.length) return true;");
  lines.push("  for (const locator of locators) {");
  lines.push("    if (__pyaLooksLikeRemoteLocator(locator)) continue;");
  lines.push("    if (!fs.existsSync(locator)) return false;");
  lines.push("  }");
  lines.push("  return true;");
  lines.push("};");
  lines.push("const __pyaSleepMs = (ms) => {");
  lines.push("  const delay = Math.max(0, Number(ms) || 0);");
  lines.push("  if (!delay) return;");
  lines.push("  if (typeof Atomics === \"object\" && typeof SharedArrayBuffer === \"function\") {");
  lines.push("    const buf = new SharedArrayBuffer(4);");
  lines.push("    const view = new Int32Array(buf);");
  lines.push("    Atomics.wait(view, 0, 0, delay);");
  lines.push("    return;");
  lines.push("  }");
  lines.push("  const start = Date.now();");
  lines.push("  while (Date.now() - start < delay) {}");
  lines.push("};");
  lines.push("function __pyaRunRefinery(name) {");
  lines.push("  const refinery = __pyaRefineries[name];");
  lines.push("  if (!refinery) return null;");
  lines.push("  __pyaCheckpointLoad();");
  lines.push("  const completed = new Set();");
  lines.push("  const results = new Map();");
  lines.push("  const pending = new Set(Object.keys(refinery.platforms));");
  lines.push("  while (pending.size > 0) {");
  lines.push("    const ready = [];");
  lines.push("    for (const platformName of pending) {");
  lines.push("      const platform = refinery.platforms[platformName];");
  lines.push("      const deps = platform?.deps || [];");
  lines.push("      if (deps.every((dep) => completed.has(dep))) ready.push(platformName);");
  lines.push("    }");
  lines.push("    if (ready.length === 0) return null;");
  lines.push("    ready.sort(__pyaCompareUtf8);");
  lines.push("    const next = ready[0];");
  lines.push("    const platform = refinery.platforms[next];");
  lines.push("    const deps = platform?.deps || [];");
  lines.push("    const depNames = [...deps].sort(__pyaCompareUtf8);");
  lines.push("    const depResults = depNames.map(dep => results.get(dep) ?? \"\");");
  lines.push("    const checkpointHash = __pyaCheckpointHash(platform.result, depNames, depResults);");
  lines.push("    const checkpointKey = `${name}::${next}::${checkpointHash}`;");
  lines.push("    const checkpointResult = __pyaCheckpointEnabled ? __pyaCheckpoints.get(checkpointKey) : null;");
  lines.push("    if (__pyaCheckpointEnabled && checkpointResult && __pyaCheckpointResultFilesExist(checkpointResult)) {");
  lines.push("      __pyaEmitNewspaper(`su name ${next} ob text \"${checkpointHash}\" from name ${name} to la ${checkpointResult} ko be checkpoint ya`);");
  lines.push("      __pyaEmitNewspaper(checkpointResult);");
  lines.push("      results.set(next, checkpointResult);");
  lines.push("      completed.add(next);");
  lines.push("      pending.delete(next);");
  lines.push("      continue;");
  lines.push("    }");
  lines.push("    let attempt = 0;");
  lines.push("    let delayMs = __pyaRetry.initialDelayMs || 0;");
  lines.push("    for (;;) {");
  lines.push("      attempt += 1;");
  lines.push("      __pyaLastErrorLine = null;");
  lines.push("      __pyaEmitNewspaper(platform.evoke);");
  lines.push("      let res;");
  lines.push("      try { res = platform.run(); } catch (err) {");
  lines.push("        const msg = err?.message ? String(err.message) : \"refinery failed\";");
  lines.push("        __pyaEmitNewspaper(`su name refinery failure ob text ${msg.replace(/\\\\/g, \"\\\\\\\\\").replace(/\"/g, \"\\\\\\\"\")} from name runtime be error ya`);");
  lines.push("        res = { be: \"error\", mood: \"ya\" };");
  lines.push("      }");
  lines.push("      const sawError = (res && res.be === \"error\" && res.mood) || __pyaLastErrorLine;");
  lines.push("      if (sawError) {");
  lines.push("        if (attempt < (__pyaRetry.maxAttempts || 1)) {");
  lines.push("          const errText = __pyaLastErrorLine || (res?.ob?.text ?? \"reiterate\");");
  lines.push("          const errQuoted = JSON.stringify(String(errText));");
  lines.push("          __pyaEmitNewspaper(`su name ${next} by num ${attempt + 1} ob text ${errQuoted} from name ${name} be reiterate ya`);");
  lines.push("          __pyaSleepMs(delayMs);");
  lines.push("          delayMs = Math.min(Math.trunc(delayMs * (__pyaRetry.backoff || 1)), __pyaRetry.maxDelayMs || delayMs);");
  lines.push("          continue;");
  lines.push("        }");
  lines.push("        return res || { be: \"error\" };");
  lines.push("      }");
  lines.push("      __pyaEmitNewspaper(platform.result);");
  lines.push("      results.set(next, platform.result);");
  lines.push("      if (__pyaCheckpointEnabled) {");
  lines.push("        __pyaEmitNewspaper(`su name ${next} ob text \"${checkpointHash}\" from name ${name} to la ${platform.result} ko be checkpoint ya`);");
  lines.push("      }");
  lines.push("      completed.add(next);");
  lines.push("      pending.delete(next);");
  lines.push("      break;");
  lines.push("    }");
  lines.push("  }");
  lines.push("  return null;");
  lines.push("}");
  return lines;
}
