import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";

import { parse } from "../program/understand/parse_tokens.mjs";
import { interpret } from "../program/bridge/index.mjs";
import { forget } from "../program/remember/index.mjs";

async function run(text) {
  const sentence = parse(text);
  return interpret(sentence);
}

async function importCompileAuto() {
  const modulePath = path.resolve("module/compile_auto.pya");
  await run(`from filename "${modulePath}" ob name compile auto to name compile auto be import do`);
}

const pandocAvailable = (() => {
  const res = spawnSync("pandoc", ["-v"], { stdio: "ignore" });
  return !res.error;
})();

const pandocPdfAvailable = (() => {
  if (!pandocAvailable) return false;
  const probePath = path.resolve("quiz/sandpit/pandoc-probe.pdf");
  const res = spawnSync("pandoc", ["--from=markdown", "-o", probePath], {
    input: "# probe\n",
    stdio: ["pipe", "ignore", "ignore"]
  });
  return res.status === 0;
})();

test("compile auto routes json to pyash map file", async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });

  await importCompileAuto();

  const jsonIn = path.resolve("quiz/sandpit/compile-auto.json");
  const pyashOut = path.resolve("quiz/sandpit/compile-auto.pya");

  await fs.writeFile(jsonIn, JSON.stringify({ title: "Auto", count: 2 }), "utf8");
  await run(`from filename "${jsonIn}" to filename "${pyashOut}" be compile auto do`);
  const pyashText = await fs.readFile(pyashOut, "utf8");
  assert.match(pyashText, /be json map def/);
  assert.match(pyashText, /su name title ob text "Auto" ya/);
});

test("compile auto routes pya to javascript", async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  await fs.writeFile(path.resolve("quiz/sandpit/compile-auto-input.pya"), 'ob text hello be write do\n', "utf8");
  const jsOut = path.resolve("quiz/sandpit/compile-auto.js");
  await run(`from filename "quiz/sandpit/compile-auto-input.pya" to filename "${jsOut}" be compile auto do`);
  const jsText = await fs.readFile(jsOut, "utf8");
  assert.match(jsText, /console\.log\("hello"\)/);
});

test("compile auto routes txt to c", async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  const txtIn = path.resolve("quiz/sandpit/compile-auto-input.txt");
  const cOut = path.resolve("quiz/sandpit/compile-auto.c");
  await fs.writeFile(txtIn, 'ob text hello be write do\n', "utf8");
  await run(`from filename "${txtIn}" to filename "${cOut}" be compile auto do`);
  const cText = await fs.readFile(cOut, "utf8");
  assert.match(cText, /Generated by Pyash compile/);
  assert.match(cText, /int main/);
});

test("compile auto routes pya to c", async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  const pyaIn = path.resolve("quiz/sandpit/compile-auto-c-input.pya");
  const cOut = path.resolve("quiz/sandpit/compile-auto-from-pya.c");
  await fs.writeFile(pyaIn, 'ob text hello be write do\n', "utf8");
  await run(`from filename "${pyaIn}" to filename "${cOut}" be compile auto do`);
  const cText = await fs.readFile(cOut, "utf8");
  assert.match(cText, /Generated by Pyash compile/);
  assert.match(cText, /int main/);
});

test("compile auto routes txt to javascript", async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  const txtIn = path.resolve("quiz/sandpit/compile-auto-js-input.txt");
  const jsOut = path.resolve("quiz/sandpit/compile-auto-from-txt.js");
  await fs.writeFile(txtIn, 'ob text hello be write do\n', "utf8");
  await run(`from filename "${txtIn}" to filename "${jsOut}" be compile auto do`);
  const jsText = await fs.readFile(jsOut, "utf8");
  assert.match(jsText, /console\.log\("hello"\)/);
});

test("compile auto routes markdown to html", { skip: !pandocAvailable }, async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  const mdIn = path.resolve("quiz/sandpit/compile-auto.md");
  const htmlOut = path.resolve("quiz/sandpit/compile-auto.html");
  await fs.writeFile(mdIn, "Hello [Example](https://example.com).", "utf8");
  await run(`from filename "${mdIn}" to filename "${htmlOut}" be compile auto do`);
  const htmlText = await fs.readFile(htmlOut, "utf8");
  assert.match(htmlText, /https:\/\/example\.com/);
});

test("compile auto routes markdown to pdf", { skip: !pandocPdfAvailable }, async () => {
  forget();
  await fs.mkdir("quiz/sandpit", { recursive: true });
  await importCompileAuto();

  const mdIn = path.resolve("quiz/sandpit/compile-auto-pdf.md");
  const pdfOut = path.resolve("quiz/sandpit/compile-auto.pdf");
  await fs.writeFile(mdIn, "# Auto PDF\n\nhello\n", "utf8");
  await run(`from filename "${mdIn}" to filename "${pdfOut}" be compile auto do`);
  const stat = await fs.stat(pdfOut);
  assert.ok(stat.size > 0);
});
