export const MIND_RUNTIME_HELPER_PART_02 = [
"  pya_mind_counters[pya_mind_counter_len].count = 1;",
"  pya_mind_counter_len += 1;",
"  return 1;",
"}",
"",
"typedef struct {",
"  char *name;",
"  int count;",
"} pya_mind_debug;",
"",
"static pya_mind_debug *pya_mind_debugs = NULL;",
"static size_t pya_mind_debug_len = 0;",
"static size_t pya_mind_debug_cap = 0;",
"",
"static int pya_mind_next_debug(const char *name) {",
"  const char *key = name ? name : \"mind\";",
"  for (size_t i = 0; i < pya_mind_debug_len; i++) {",
"    if (pya_mind_debugs[i].name && strcmp(pya_mind_debugs[i].name, key) == 0) {",
"      pya_mind_debugs[i].count += 1;",
"      return pya_mind_debugs[i].count;",
"    }",
"  }",
"  if (pya_mind_debug_len + 1 > pya_mind_debug_cap) {",
"    size_t next = pya_mind_debug_cap == 0 ? 4 : pya_mind_debug_cap * 2;",
"    pya_mind_debug *resized = (pya_mind_debug *)realloc(pya_mind_debugs, sizeof(pya_mind_debug) * next);",
"    if (!resized) return 1;",
"    pya_mind_debugs = resized;",
"    pya_mind_debug_cap = next;",
"  }",
"  pya_mind_debugs[pya_mind_debug_len].name = pya_strdup(key);",
"  pya_mind_debugs[pya_mind_debug_len].count = 1;",
"  pya_mind_debug_len += 1;",
"  return 1;",
"}",
"",
"static void pya_record_mind_json(const char *target, const char *label, const char *payload) {",
"  if (!payload) return;",
"  int count = pya_mind_next_debug(target);",
"  char mapName[PYA_TEXT_CAP];",
"  snprintf(mapName, sizeof(mapName), \"%s %s %d\", target ? target : \"mind\", label ? label : \"request\", count);",
"  char pyash[PYA_TEXT_CAP];",
"  pya_json_error err; memset(&err, 0, sizeof(err));",
"  if (!pya_json_to_pyash(payload, mapName, pyash, &err)) {",
"    return;",
"  }",
"  const char *start = pyash;",
"  const char *cursor = pyash;",
"  for (; *cursor; cursor++) {",
"    if (*cursor == '\\n') {",
"      size_t len = (size_t)(cursor - start);",
"      if (len > 0) {",
"        char *line = (char *)malloc(len + 1);",
"        if (!line) return;",
"        memcpy(line, start, len);",
"        line[len] = '\\0';",
"        pya_emit_exchange(line);",
"        free(line);",
"      }",
"      start = cursor + 1;",
"    }",
"  }",
"  if (start && *start) {",
"    pya_emit_exchange(start);",
"  }",
"}",
"",
"static size_t pya_curl_write(void *ptr, size_t size, size_t nmemb, void *userdata) {",
"  size_t total = size * nmemb;",
"  pya_buf *buf = (pya_buf *)userdata;",
"  pya_buf_reserve(buf, total);",
"  if (!buf->data) return 0;",
"  memcpy(buf->data + buf->len, ptr, total);",
"  buf->len += total;",
"  buf->data[buf->len] = '\\0';",
"  return total;",
"}",
"",
"static char *pya_mind_http_post(const char *url, const char *body) {",
"  CURL *curl = curl_easy_init();",
"  if (!curl) return NULL;",
"  struct curl_slist *headers = NULL;",
"  headers = curl_slist_append(headers, \"Content-Type: application/json\");",
"  pya_buf response;",
"  pya_buf_init(&response);",
"  curl_easy_setopt(curl, CURLOPT_URL, url);",
"  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);",
"  curl_easy_setopt(curl, CURLOPT_POST, 1L);",
"  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body ? body : \"{}\");",
"  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, pya_curl_write);",
"  curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);",
"  CURLcode res = curl_easy_perform(curl);",
"  curl_slist_free_all(headers);",
"  curl_easy_cleanup(curl);",
"  if (res != CURLE_OK) {",
"    if (response.data) free(response.data);",
"    return NULL;",
"  }",
"  return pya_buf_take(&response);",
"}",
"",
"typedef char *(*pya_tool_dispatch_fn)(const char *tool_name, const char *args_json);",
"",
"static char *pya_tool_block_from_map(pya_map *map) {",
"  if (!map || map->length == 0) return NULL;",
"  pya_map_entry **sorted = (pya_map_entry **)malloc(sizeof(pya_map_entry *) * map->length);",
"  if (!sorted) return NULL;",
"  for (int i = 0; i < map->length; i++) sorted[i] = &map->entries[i];",
"  qsort(sorted, map->length, sizeof(pya_map_entry *), map_entry_compare);",
"  pya_buf buf; pya_buf_init(&buf);",
"  pya_buf_append(&buf, \"TOOLS:\\n\");",
"  int added = 0;",
"  for (int i = 0; i < map->length; i++) {",
"    const pya_map_entry *entry = sorted[i];",
"    if (!entry || entry->kind != PYA_MAP_SENTENCE) continue;",
"    if (!entry->text || entry->text[0] == '\\0') continue;",
"    pya_buf_append(&buf, entry->text);",
"    pya_buf_append(&buf, \"\\n\");",
"    added = 1;",
"  }",
"  free(sorted);",
"  if (!added) {",
"    if (buf.data) free(buf.data);",
"    return NULL;",
"  }",
"  return pya_buf_take(&buf);",
"}",
"",
"static char *pya_mind_invoke(const char *mind, const char *dialogue, const char *user_text, const char *tool_block, const char *tool_json, pya_tool_dispatch_fn tool_dispatch, const char *model_override, int window_override, int *out_count) {",
"  const char *mock = getenv(\"PYA_MIND_RESPONSE\");",
"  if (mock) {",
"    int count = pya_mind_next_count(dialogue);",
"    if (out_count) *out_count = count;",
"    pya_mind_record(dialogue, \"user\", user_text ? user_text : \"\", window_override > 0 ? window_override : 8);",
"    pya_mind_record(dialogue, \"assistant\", mock, window_override > 0 ? window_override : 8);",
"    return pya_strdup(mock);",
"  }",
"  pya_mind_config *cfg = pya_mind_get_config(mind);",
"  const char *host = cfg && cfg->space ? cfg->space : getenv(\"OLLAMA_HOST\");",
"  if (!host) host = \"http://localhost:11434\";",
"  const char *model = model_override ? model_override : (cfg && cfg->model ? cfg->model : \"qwen3-vl:8b-instruct\");",
"  int window = window_override > 0 ? window_override : (cfg && cfg->window > 0 ? cfg->window : 8);",
"  const char *prompt = cfg && cfg->prompt ? cfg->prompt : NULL;",
"  cJSON *messages = cJSON_CreateArray();",
"  if (prompt) {",
"    cJSON *msg = cJSON_CreateObject();",
"    cJSON_AddStringToObject(msg, \"role\", \"system\");",
"    cJSON_AddStringToObject(msg, \"content\", prompt);",
"    cJSON_AddItemToArray(messages, msg);",
"  }",
"  if (tool_block) {",
"    cJSON *msg = cJSON_CreateObject();",
"    cJSON_AddStringToObject(msg, \"role\", \"system\");",
"    cJSON_AddStringToObject(msg, \"content\", tool_block);",
"    cJSON_AddItemToArray(messages, msg);",
"  }",
"  pya_mind_history *hist = pya_mind_get_history(dialogue);",
"  if (hist) {",
"    for (size_t i = 0; i < hist->len; i++) {",
"      cJSON *msg = cJSON_CreateObject();",
"      cJSON_AddStringToObject(msg, \"role\", hist->items[i].role ? hist->items[i].role : \"user\");",
"      cJSON_AddStringToObject(msg, \"content\", hist->items[i].content ? hist->items[i].content : \"\");",
"      cJSON_AddItemToArray(messages, msg);",
"    }",
"  }",
"  cJSON *user = cJSON_CreateObject();",
"  cJSON_AddStringToObject(user, \"role\", \"user\");",
"  cJSON_AddStringToObject(user, \"content\", user_text ? user_text : \"\");",
"  cJSON_AddItemToArray(messages, user);",
"  int turns = 0;",
"  char *out = NULL;",
"  while (turns < 6) {",
"    turns += 1;",
"    cJSON *root = cJSON_CreateObject();",
"    cJSON_AddStringToObject(root, \"model\", model);",
"    cJSON_AddItemToObject(root, \"messages\", cJSON_Duplicate(messages, 1));",
"    if (tool_json) {",
"      cJSON *tools = cJSON_Parse(tool_json);",
"      if (tools && cJSON_IsArray(tools)) {",
"        cJSON_AddItemToObject(root, \"tools\", tools);",
"      } else if (tools) {"
];
