export const MIND_RUNTIME_HELPER_PART_03 = [
"        cJSON_Delete(tools);",
"      }",
"    }",
"    cJSON_AddBoolToObject(root, \"stream\", 0);",
"    char *payload = cJSON_PrintUnformatted(root);",
"    char *pretty = cJSON_Print(root);",
"    cJSON_Delete(root);",
"    if (!payload) { if (pretty) free(pretty); break; }",
"    pya_record_mind_json(mind, \"request\", pretty ? pretty : payload);",
"    if (pretty) free(pretty);",
"    pya_buf url; pya_buf_init(&url);",
"    pya_buf_append(&url, host);",
"    if (url.len > 0 && url.data[url.len - 1] == '/') url.data[url.len - 1] = '\\0';",
"    pya_buf_append(&url, \"/api/chat\");",
"    char *resp = pya_mind_http_post(url.data, payload);",
"    free(payload);",
"    if (url.data) free(url.data);",
"    if (!resp) {",
"      char err[PYA_TEXT_CAP];",
"      snprintf(err, sizeof(err), \"su name mind defective ob text \\\"mind defective: request failed\\\" from name mind be error ya\");",
"      pya_emit_exchange(err);",
"      fprintf(stderr, \"%s\\n\", \"mind defective: request failed\");",
"      exit(1);",
"    }",
"    cJSON *respJson = cJSON_Parse(resp);",
"    if (respJson) {",
"      cJSON_DeleteItemFromObjectCaseSensitive(respJson, \"context\");",
"      char *respPretty = cJSON_Print(respJson);",
"      if (respPretty) {",
"        pya_record_mind_json(mind, \"response\", respPretty);",
"        free(respPretty);",
"      } else {",
"        pya_record_mind_json(mind, \"response\", resp);",
"      }",
"    } else {",
"      pya_record_mind_json(mind, \"response\", resp);",
"    }",
"    cJSON *message = respJson ? cJSON_GetObjectItemCaseSensitive(respJson, \"message\") : NULL;",
"    cJSON *toolCalls = message ? cJSON_GetObjectItemCaseSensitive(message, \"tool_calls\") : NULL;",
"    if (toolCalls && cJSON_IsArray(toolCalls) && cJSON_GetArraySize(toolCalls) > 0) {",
"      if (!tool_dispatch) {",
"        char err[PYA_TEXT_CAP];",
"        snprintf(err, sizeof(err), \"su name tool defective ob text \\\"tool defective: missing dispatcher\\\" from name mind be error ya\");",
"        pya_emit_exchange(err);",
"        fprintf(stderr, \"%s\\n\", \"tool defective: missing dispatcher\");",
"        exit(1);",
"      }",
"      cJSON *assistant = cJSON_CreateObject();",
"      cJSON_AddStringToObject(assistant, \"role\", \"assistant\");",
"      cJSON *content = message ? cJSON_GetObjectItemCaseSensitive(message, \"content\") : NULL;",
"      cJSON_AddStringToObject(assistant, \"content\", (content && cJSON_IsString(content)) ? content->valuestring : \"\");",
"      cJSON_AddItemToObject(assistant, \"tool_calls\", cJSON_Duplicate(toolCalls, 1));",
"      cJSON_AddItemToArray(messages, assistant);",
"      int tcCount = cJSON_GetArraySize(toolCalls);",
"      for (int i = 0; i < tcCount; i++) {",
"        cJSON *call = cJSON_GetArrayItem(toolCalls, i);",
"        cJSON *fn = call ? cJSON_GetObjectItemCaseSensitive(call, \"function\") : NULL;",
"        cJSON *name = fn ? cJSON_GetObjectItemCaseSensitive(fn, \"name\") : NULL;",
"        if (!name) name = call ? cJSON_GetObjectItemCaseSensitive(call, \"name\") : NULL;",
"        const char *toolName = (name && cJSON_IsString(name)) ? name->valuestring : NULL;",
"        cJSON *callId = cJSON_GetObjectItemCaseSensitive(call, \"id\");",
"        const char *toolCallId = (callId && cJSON_IsString(callId)) ? callId->valuestring : NULL;",
"        cJSON *argsNode = fn ? cJSON_GetObjectItemCaseSensitive(fn, \"arguments\") : NULL;",
"        if (!argsNode) argsNode = call ? cJSON_GetObjectItemCaseSensitive(call, \"arguments\") : NULL;",
"        char *argsText = NULL;",
"        if (argsNode && cJSON_IsString(argsNode)) argsText = pya_strdup(argsNode->valuestring);",
"        else if (argsNode) argsText = cJSON_PrintUnformatted(argsNode);",
"        char *toolResult = toolName ? tool_dispatch(toolName, argsText ? argsText : \"\") : NULL;",
"        if (argsText) free(argsText);",
"        if (!toolResult) {",
"          if (respJson) cJSON_Delete(respJson);",
"          free(resp);",
"          char err[PYA_TEXT_CAP];",
"          snprintf(err, sizeof(err), \"su name tool defective ob text \\\"tool defective: unknown tool\\\" from name mind be error ya\");",
"          pya_emit_exchange(err);",
"          fprintf(stderr, \"%s\\n\", \"tool defective: unknown tool\");",
"          exit(1);",
"        }",
"        cJSON *toolMsg = cJSON_CreateObject();",
"        cJSON_AddStringToObject(toolMsg, \"role\", \"tool\");",
"        if (toolCallId && toolCallId[0]) {",
"          cJSON_AddStringToObject(toolMsg, \"tool_call_id\", toolCallId);",
"        }",
"        cJSON_AddStringToObject(toolMsg, \"tool_name\", toolName ? toolName : \"\");",
"        cJSON_AddStringToObject(toolMsg, \"content\", toolResult);",
"        cJSON_AddItemToArray(messages, toolMsg);",
"        free(toolResult);",
"      }",
"      if (respJson) cJSON_Delete(respJson);",
"      free(resp);",
"      continue;",
"    }",
"    if (message) {",
"      cJSON *content = cJSON_GetObjectItemCaseSensitive(message, \"content\");",
"      if (content && cJSON_IsString(content)) out = pya_strdup(content->valuestring);",
"    }",
"    if (!out && respJson) {",
"      cJSON *content = cJSON_GetObjectItemCaseSensitive(respJson, \"response\");",
"      if (!content) content = cJSON_GetObjectItemCaseSensitive(respJson, \"output\");",
"      if (content && cJSON_IsString(content)) out = pya_strdup(content->valuestring);",
"    }",
"    if (respJson) cJSON_Delete(respJson);",
"    free(resp);",
"    break;",
"  }",
"  if (!out) out = pya_strdup(\"\");",
"  cJSON_Delete(messages);",
"  int count = pya_mind_next_count(dialogue);",
"  if (out_count) *out_count = count;",
"  pya_mind_record(dialogue, \"user\", user_text ? user_text : \"\", window);",
"  pya_mind_record(dialogue, \"assistant\", out, window);",
"  return out;",
"}"
];
