export const MIND_RUNTIME_HELPER_PART_01 = [
"#define PYA_MIND_RUNTIME 1",
"",
"typedef struct {",
"  char *data;",
"  size_t len;",
"  size_t cap;",
"} pya_buf;",
"",
"static void pya_buf_init(pya_buf *buf) {",
"  if (!buf) return;",
"  buf->data = NULL;",
"  buf->len = 0;",
"  buf->cap = 0;",
"}",
"",
"static void pya_buf_reserve(pya_buf *buf, size_t extra) {",
"  if (!buf) return;",
"  size_t need = buf->len + extra + 1;",
"  if (need <= buf->cap) return;",
"  size_t next = buf->cap == 0 ? 256 : buf->cap;",
"  while (next < need) next *= 2;",
"  char *data = (char *)realloc(buf->data, next);",
"  if (!data) return;",
"  buf->data = data;",
"  buf->cap = next;",
"}",
"",
"static void pya_buf_append(pya_buf *buf, const char *text) {",
"  if (!buf || !text) return;",
"  size_t len = strlen(text);",
"  pya_buf_reserve(buf, len);",
"  if (!buf->data) return;",
"  memcpy(buf->data + buf->len, text, len);",
"  buf->len += len;",
"  buf->data[buf->len] = '\\0';",
"}",
"",
"static char *pya_buf_take(pya_buf *buf) {",
"  if (!buf) return NULL;",
"  char *out = buf->data;",
"  buf->data = NULL;",
"  buf->len = 0;",
"  buf->cap = 0;",
"  return out;",
"}",
"",
"typedef struct {",
"  char *name;",
"  char *space;",
"  char *model;",
"  char *prompt;",
"  int window;",
"} pya_mind_config;",
"",
"static pya_mind_config *pya_mind_configs = NULL;",
"static size_t pya_mind_config_len = 0;",
"static size_t pya_mind_config_cap = 0;",
"",
"static pya_mind_config *pya_mind_get_config(const char *name) {",
"  if (!name) return NULL;",
"  for (size_t i = 0; i < pya_mind_config_len; i++) {",
"    if (pya_mind_configs[i].name && strcmp(pya_mind_configs[i].name, name) == 0) {",
"      return &pya_mind_configs[i];",
"    }",
"  }",
"  return NULL;",
"}",
"",
"static void pya_mind_set_config(const char *name, const char *space, const char *model, const char *prompt, int window) {",
"  if (!name) return;",
"  pya_mind_config *cfg = pya_mind_get_config(name);",
"  if (!cfg) {",
"    if (pya_mind_config_len + 1 > pya_mind_config_cap) {",
"      size_t next = pya_mind_config_cap == 0 ? 4 : pya_mind_config_cap * 2;",
"      pya_mind_config *resized = (pya_mind_config *)realloc(pya_mind_configs, sizeof(pya_mind_config) * next);",
"      if (!resized) return;",
"      pya_mind_configs = resized;",
"      pya_mind_config_cap = next;",
"    }",
"    cfg = &pya_mind_configs[pya_mind_config_len++];",
"    memset(cfg, 0, sizeof(*cfg));",
"    cfg->name = pya_strdup(name);",
"  }",
"  if (space) { free(cfg->space); cfg->space = pya_strdup(space); }",
"  if (model) { free(cfg->model); cfg->model = pya_strdup(model); }",
"  if (prompt) { free(cfg->prompt); cfg->prompt = pya_strdup(prompt); }",
"  if (window > 0) cfg->window = window;",
"}",
"",
"typedef struct {",
"  char *role;",
"  char *content;",
"} pya_mind_msg;",
"",
"typedef struct {",
"  char *dialogue;",
"  pya_mind_msg *items;",
"  size_t len;",
"  size_t cap;",
"} pya_mind_history;",
"",
"static pya_mind_history *pya_mind_histories = NULL;",
"static size_t pya_mind_history_len = 0;",
"static size_t pya_mind_history_cap = 0;",
"",
"static pya_mind_history *pya_mind_get_history(const char *dialogue) {",
"  if (!dialogue) return NULL;",
"  for (size_t i = 0; i < pya_mind_history_len; i++) {",
"    if (pya_mind_histories[i].dialogue && strcmp(pya_mind_histories[i].dialogue, dialogue) == 0) {",
"      return &pya_mind_histories[i];",
"    }",
"  }",
"  if (pya_mind_history_len + 1 > pya_mind_history_cap) {",
"    size_t next = pya_mind_history_cap == 0 ? 4 : pya_mind_history_cap * 2;",
"    pya_mind_history *resized = (pya_mind_history *)realloc(pya_mind_histories, sizeof(pya_mind_history) * next);",
"    if (!resized) return NULL;",
"    pya_mind_histories = resized;",
"    pya_mind_history_cap = next;",
"  }",
"  pya_mind_history *hist = &pya_mind_histories[pya_mind_history_len++];",
"  memset(hist, 0, sizeof(*hist));",
"  hist->dialogue = pya_strdup(dialogue);",
"  return hist;",
"}",
"",
"static void pya_mind_trim_history(pya_mind_history *hist, int window) {",
"  if (!hist || window <= 0) return;",
"  size_t max = (size_t)window * 2;",
"  if (hist->len <= max) return;",
"  size_t drop = hist->len - max;",
"  for (size_t i = 0; i < drop; i++) {",
"    free(hist->items[i].role);",
"    free(hist->items[i].content);",
"  }",
"  memmove(hist->items, hist->items + drop, sizeof(pya_mind_msg) * max);",
"  hist->len = max;",
"}",
"",
"static void pya_mind_record(const char *dialogue, const char *role, const char *content, int window) {",
"  if (!dialogue || !role || !content) return;",
"  pya_mind_history *hist = pya_mind_get_history(dialogue);",
"  if (!hist) return;",
"  if (hist->len + 1 > hist->cap) {",
"    size_t next = hist->cap == 0 ? 8 : hist->cap * 2;",
"    pya_mind_msg *resized = (pya_mind_msg *)realloc(hist->items, sizeof(pya_mind_msg) * next);",
"    if (!resized) return;",
"    hist->items = resized;",
"    hist->cap = next;",
"  }",
"  hist->items[hist->len].role = pya_strdup(role);",
"  hist->items[hist->len].content = pya_strdup(content);",
"  hist->len += 1;",
"  pya_mind_trim_history(hist, window);",
"}",
"",
"typedef struct {",
"  char *dialogue;",
"  int count;",
"} pya_mind_counter;",
"",
"static pya_mind_counter *pya_mind_counters = NULL;",
"static size_t pya_mind_counter_len = 0;",
"static size_t pya_mind_counter_cap = 0;",
"",
"static int pya_mind_next_count(const char *dialogue) {",
"  if (!dialogue) return 1;",
"  for (size_t i = 0; i < pya_mind_counter_len; i++) {",
"    if (pya_mind_counters[i].dialogue && strcmp(pya_mind_counters[i].dialogue, dialogue) == 0) {",
"      pya_mind_counters[i].count += 1;",
"      return pya_mind_counters[i].count;",
"    }",
"  }",
"  if (pya_mind_counter_len + 1 > pya_mind_counter_cap) {",
"    size_t next = pya_mind_counter_cap == 0 ? 4 : pya_mind_counter_cap * 2;",
"    pya_mind_counter *resized = (pya_mind_counter *)realloc(pya_mind_counters, sizeof(pya_mind_counter) * next);",
"    if (!resized) return 1;",
"    pya_mind_counters = resized;",
"    pya_mind_counter_cap = next;",
"  }",
"  pya_mind_counters[pya_mind_counter_len].dialogue = pya_strdup(dialogue);"
];
