import {
  COMMAND_POLICY_CONTRACT,
  commandPolicyRuntimeData
} from "../../../../../library/command_policy.mjs";

export function commandHelperSource({ policy, includeCommand = true, includePolicy = false } = {}) {
  const contract = JSON.stringify(COMMAND_POLICY_CONTRACT);
  const policyData = JSON.stringify(commandPolicyRuntimeData(policy));
  const lines = [];
  if (includeCommand) lines.push(
    "function pyaCommand(cmd, input) {",
    "  if (typeof process !== \"undefined\" && process.env?.PYA_COMMAND_RESPONSE !== undefined) {",
    "    return String(process.env.PYA_COMMAND_RESPONSE ?? \"\");",
    "  }",
    "  const res = child_process.spawnSync(String(cmd ?? \"\"), {",
    "    shell: true,",
    "    input: input ?? undefined,",
    "    encoding: \"utf8\",",
    "    maxBuffer: 1024 * 1024",
    "  });",
    "  if (res.error || res.status) {",
    "    throw new Error(\"command defective\");",
    "  }",
    "  return String(res.stdout ?? \"\");",
    "}",
  );
  if (includePolicy) lines.push(
    `const PYA_COMMAND_POLICY_CONTRACT = ${contract};`,
    `const PYA_COMMAND_POLICY = ${policyData};`,
    "function pyaCommandHasWord(text, word) {",
    "  const escaped = String(word ?? \"\").replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\");",
    "  return new RegExp(\"(^|[^A-Za-z0-9_])\" + escaped + \"(?=$|[^A-Za-z0-9_])\", \"iu\").test(text);",
    "}",
    "function pyaCommandHasRule(text, rule) {",
    "  if (rule.kind === \"word\") return pyaCommandHasWord(text, rule.value);",
    "  if (rule.kind === \"sequence\") {",
    "    const sequence = rule.values.map(value => String(value).replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\")).join(\"\\\\s+\");",
    "    return new RegExp(\"(^|[^A-Za-z0-9_])\" + sequence + \"(?=$|[^A-Za-z0-9_])\", \"iu\").test(text);",
    "  }",
    "  if (rule.kind === \"fork_bomb\") return /\\b:\(\)\\s*\\{\\s*:\|:\\s*&\\s*\\};:/u.test(text);",
    "  if (rule.kind === \"url\") return /\\bhttps?:\\/\\//iu.test(text);",
    "  if (rule.kind === \"redirect\") return />>?/.test(text);",
    "  if (rule.kind === \"word_before_redirect\") return pyaCommandHasWord(text, rule.value) && />>?/.test(text);",
    "  if (rule.kind === \"text\") return String(text).toLowerCase().includes(String(rule.value).toLowerCase());",
    "  return false;",
    "}",
    "function pyaClassifyCommand(text) {",
    "  const cmd = String(text ?? \"\").trim();",
    "  if (!cmd) return \"unknown\";",
    "  if (/^node\\s+(?:\\.\\/)?command\\/see_vl_runner\\b/iu.test(cmd)) return \"read_only\";",
    "  for (const entry of PYA_COMMAND_POLICY_CONTRACT) {",
    "    if (entry.rules.some(rule => pyaCommandHasRule(cmd, rule))) return entry.name;",
    "  }",
    "  return \"unknown\";",
    "}",
    "function pyaCommandPolicySnapshot() {",
    "  const scopes = PYA_COMMAND_POLICY.scopes ?? {};",
    "  const legacy = PYA_COMMAND_POLICY.legacy ?? {};",
    "  const sessionMode = scopes.session?.mode ?? legacy.sessionMode ?? null;",
    "  const agentMode = scopes.agent?.mode ?? legacy.agentMode ?? null;",
    "  const commandMode = scopes.command?.mode ?? legacy.commandMode ?? null;",
    "  const mode = sessionMode ?? agentMode ?? commandMode ?? \"ask\";",
    "  const source = sessionMode !== null ? \"session command configure\" : agentMode !== null ? \"agent command configure\" : \"command configure\";",
    "  const classifierEnabled = scopes.session?.classifierEnabled ?? scopes.agent?.classifierEnabled ?? scopes.command?.classifierEnabled ?? legacy.classifierEnabled ?? PYA_COMMAND_POLICY.classifierEnabled;",
    "  return { mode, classifierEnabled, source };",
    "}",
    "function pyaCommandPolicyApplyMap(scope, mode, classifierEnabled) {",
    "  PYA_COMMAND_POLICY.scopes ??= {};",
    "  PYA_COMMAND_POLICY.scopes[scope] = { mode: mode ?? null, classifierEnabled: classifierEnabled ?? null };",
    "}",
    "function pyaCommandPolicyApplyLegacyMode(scope, mode) {",
    "  PYA_COMMAND_POLICY.legacy ??= {};",
    "  PYA_COMMAND_POLICY.legacy[`${scope}Mode`] = mode ?? \"ask\";",
    "}",
    "function pyaCommandPolicyApplyLegacyClassifier(classifierEnabled) {",
    "  PYA_COMMAND_POLICY.legacy ??= {};",
    "  PYA_COMMAND_POLICY.legacy.classifierEnabled = Boolean(classifierEnabled);",
    "}",
    "function pyaCommandPolicyFor(mood, commandClass) {",
    "  const current = pyaCommandPolicySnapshot();",
    "  let mode = current.mode;",
    "  if (mood === \"propose\") mode = \"ask\";",
    "  if (mood === \"can\" && mode !== \"deny\") mode = \"allow\";",
    "  return { mode, classifierEnabled: current.classifierEnabled, source: current.source, class: current.classifierEnabled ? commandClass : \"unknown\" };",
    "}",
    "function pyaCommandAuditOrdinal(requestName) {",
    "  return String(requestName ?? \"\").match(/(\\d{6})$/u)?.[1] ?? \"000000\";",
    "}",
    "function pyaEmitCommandAudit({ requestName, stage, commandClass, policy, decision, evoked, result } = {}) {",
    "  const effectiveClass = policy?.classifierEnabled === false ? \"unknown\" : String(commandClass ?? \"unknown\");",
    "  const timestamp = new Date().toISOString();",
    "  let line = `exists su name command audit ${pyaCommandAuditOrdinal(requestName)} ob text ${JSON.stringify(String(evoked ?? \"\"))} from name ${policy?.source ?? \"command configure\"} to name ${requestName} as name ${stage ?? \"policy\"} accordingto name ${decision ?? policy?.mode ?? \"allow\"}`;",
    "  if (effectiveClass && effectiveClass !== \"unknown\") line += ` by name ${effectiveClass}`;",
    "  if (result) line += ` totext text ${JSON.stringify(String(result))}`;",
    "  line += ` fromtext text ${JSON.stringify(timestamp)} be command audit ya`;",
    "  pyaEmitNewspaper(line);",
    "}",
    "function pyaCommandPolicyGate({ requestName, evoked, commandText, mood } = {}) {",
    "  const commandClass = pyaClassifyCommand(commandText);",
    "  const policy = pyaCommandPolicyFor(mood, commandClass);",
    "  if (policy.mode === \"deny\" && (mood === \"propose\" || commandClass === \"destructive\")) {",
    "    pyaEmitCommandAudit({ requestName, stage: \"policy\", commandClass: policy.class, policy, decision: \"deny\", evoked });",
    "    throw new Error(`command policy defective: denied class=${commandClass}`);",
    "  }",
    "  if (policy.mode === \"ask\" && (mood === \"propose\" || commandClass === \"destructive\")) {",
    "    const resumeToken = JSON.stringify({ kind: \"command\", issuedAt: new Date().toISOString(), class: commandClass, text: String(commandText ?? \"\"), requestIdentity: requestName, sentence: { mood: mood ?? \"do\", be: \"command\", ob: { text: String(commandText ?? \"\") } } });",
    "    const ratify = `su name command approval ob text ${JSON.stringify(`approve command (${policy.class}): ${String(commandText ?? \"\")}`)} from name command to name ${requestName} accordingto name resume token fromtext text ${JSON.stringify(resumeToken)} be ratify do`;",
    "    pyaEmitCommandAudit({ requestName, stage: \"policy\", commandClass: policy.class, policy, decision: \"ask\", evoked, result: ratify });",
    "    pyaEmitNewspaper(ratify);",
    "    throw new Error(\"command policy defective: approval required\");",
    "  }",
    "  pyaEmitCommandAudit({ requestName, stage: \"policy\", commandClass: policy.class, policy, decision: \"allow\", evoked });",
    "  return { commandClass, policy };",
    "}",
    "function pyaCommandResultAudit({ requestName, commandText, evoked, decision, result, policy: priorPolicy } = {}) {",
    "  const commandClass = pyaClassifyCommand(commandText);",
    "  const policy = priorPolicy ?? pyaCommandPolicyFor(\"do\", commandClass);",
    "  pyaEmitCommandAudit({ requestName, stage: \"result\", commandClass: policy.class, policy, decision, evoked, result });",
    "}"
  );
  return lines.join("\n");
}

export function commandPolicyHelperSource({ policy } = {}) {
  return commandHelperSource({ policy, includeCommand: false, includePolicy: true });
}
