export const CEREMONY_VALUE_HELPER = [
  "typedef enum {",
  "  PYA_VAL_NONE = 0,",
  "  PYA_VAL_NUM = 1,",
  "  PYA_VAL_TEXT = 2",
  "} pya_value_kind;",
  "typedef struct {",
  "  pya_value_kind kind;",
  "  double num;",
  "  const char *text;",
  "} pya_value;",
  "static inline pya_value pya_value_none(void) {",
  "  return (pya_value){ PYA_VAL_NONE, 0, 0 };",
  "}",
  "static inline pya_value pya_value_num(double v) {",
  "  return (pya_value){ PYA_VAL_NUM, v, 0 };",
  "}",
  "static inline pya_value pya_value_text(const char *v) {",
  "  return (pya_value){ PYA_VAL_TEXT, 0, v };",
  "}",
  "static inline pya_value pya_value_from_this(void) {",
  "  if (pya_ob_text) return pya_value_text(pya_ob_text);",
  "  return pya_value_num(pya_ob_num);",
  "}"
].join("\n");
