import {
  COMMAND_POLICY_CONTRACT,
  commandPolicyRuntimeData
} from "../../../../../library/command_policy.mjs";

export const COMMAND_HELPER = [
  "static char *pya_command_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static char *pya_command(const char *cmd) {",
  "  const char *mock = getenv(\"PYA_COMMAND_RESPONSE\");",
  "  if (mock) return pya_command_strdup(mock);",
  "  if (!cmd) return pya_command_strdup(\"\");",
  "  FILE *pipe = popen(cmd, \"r\");",
  "  if (!pipe) return NULL;",
  "  char out[PYA_TEXT_CAP];",
  "  out[0] = '\\0';",
  "  char buf[256];",
  "  while (fgets(buf, sizeof(buf), pipe)) {",
  "    pya_concat_buf(out, buf);",
  "  }",
  "  int status = pclose(pipe);",
  "  if (status != 0) return NULL;",
  "  return pya_command_strdup(out);",
  "}"
].join("\n");

export function commandPolicyCSource({ policy } = {}) {
  const runtimePolicy = commandPolicyRuntimeData(policy);
  const lines = [
    `static const char *pya_command_policy_mode = ${JSON.stringify(runtimePolicy.mode)};`,
    `static const char *pya_command_policy_source = ${JSON.stringify(runtimePolicy.source)};`,
    `static const int pya_command_classifier_enabled = ${runtimePolicy.classifierEnabled ? 1 : 0};`,
    "",
    "static int pya_command_word_char(char ch) {",
    "  return (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_';",
    "}",
    "",
    "static char pya_command_fold(char ch) {",
    "  return ch >= 'A' && ch <= 'Z' ? (char)(ch - 'A' + 'a') : ch;",
    "}",
    "",
    "static int pya_command_space(char ch) {",
    "  return ch == ' ' || ch == '\\t' || ch == '\\n' || ch == '\\r' || ch == '\\f' || ch == '\\v';",
    "}",
    "",
    "static int pya_command_starts_with(const char *text, const char *value) {",
    "  if (!text || !value) return 0;",
    "  while (*value) {",
    "    if (!*text || pya_command_fold(*text) != pya_command_fold(*value)) return 0;",
    "    text++; value++;",
    "  }",
    "  return 1;",
    "}",
    "",
    "static int pya_command_contains(const char *text, const char *value) {",
    "  if (!text || !value || !value[0]) return 0;",
    "  for (const char *cursor = text; *cursor; cursor++) {",
    "    if (pya_command_starts_with(cursor, value)) return 1;",
    "  }",
    "  return 0;",
    "}",
    "",
    "static int pya_command_contains_url(const char *text, const char *value) {",
    "  if (!text || !value || !value[0]) return 0;",
    "  for (const char *cursor = text; *cursor; cursor++) {",
    "    const char before = cursor == text ? '\\0' : cursor[-1];",
    "    if (!pya_command_word_char(before) && pya_command_starts_with(cursor, value)) return 1;",
    "  }",
    "  return 0;",
    "}",
    "",
    "static int pya_command_has_word(const char *text, const char *word) {",
    "  if (!text || !word || !word[0]) return 0;",
    "  const char *cursor = text;",
    "  size_t wordLen = strlen(word);",
    "  while (*cursor) {",
    "    if (!pya_command_starts_with(cursor, word)) { cursor++; continue; }",
    "    const char before = cursor == text ? '\\0' : cursor[-1];",
    "    const char after = cursor[wordLen];",
    "    if (!pya_command_word_char(before) && !pya_command_word_char(after)) return 1;",
    "    cursor++;",
    "  }",
    "  return 0;",
    "}",
    "",
    "static int pya_command_has_sequence(const char *text, const char *first, const char *second) {",
    "  if (!text || !first || !second) return 0;",
    "  const char *cursor = text;",
    "  size_t firstLen = strlen(first);",
    "  size_t secondLen = strlen(second);",
    "  while (*cursor) {",
    "    if (!pya_command_starts_with(cursor, first)) { cursor++; continue; }",
    "    const char before = cursor == text ? '\\0' : cursor[-1];",
    "    const char afterFirst = cursor[firstLen];",
    "    if (!pya_command_word_char(before) && !pya_command_word_char(afterFirst)) {",
    "      const char *next = cursor + firstLen;",
    "      while (pya_command_space(*next)) next++;",
    "      if (pya_command_starts_with(next, second) && !pya_command_word_char(next[secondLen])) return 1;",
    "    }",
    "    cursor++;",
    "  }",
    "  return 0;",
    "}",
    "",
    "static int pya_command_has_fork_bomb(const char *text) {",
    "  if (!text) return 0;",
    "  for (const char *cursor = text; *cursor; cursor++) {",
    "    if (*cursor != ':' || cursor == text || !pya_command_word_char(cursor[-1])) continue;",
    "    const char *next = cursor + 1;",
    "    if (*next != '(') continue;",
    "    next++;",
    "    if (*next != ')') continue;",
    "    next++;",
    "    while (pya_command_space(*next)) next++;",
    "    if (*next != '{') continue;",
    "    next++;",
    "    while (pya_command_space(*next)) next++;",
    "    if (*next != ':') continue;",
    "    next++;",
    "    if (*next != '|') continue;",
    "    next++;",
    "    if (*next != ':') continue;",
    "    next++;",
    "    while (pya_command_space(*next)) next++;",
    "    if (*next != '&') continue;",
    "    next++;",
    "    while (pya_command_space(*next)) next++;",
    "    if (*next != '}') continue;",
    "    next++;",
    "    if (*next != ';') continue;",
    "    next++;",
    "    if (*next == ':') return 1;",
    "  }",
    "  return 0;",
    "}",
    "",
    "static int pya_command_is_see_runner(const char *text) {",
    "  const char *runner = \"command/see_vl_runner.mjs\";",
    "  if (!text || !pya_command_starts_with(text, \"node\")) return 0;",
    "  const char *next = text + 4;",
    "  if (!pya_command_space(*next)) return 0;",
    "  while (pya_command_space(*next)) next++;",
    "  if (pya_command_starts_with(next, \"./\")) next += 2;",
    "  return pya_command_starts_with(next, runner) && !pya_command_word_char(next[strlen(runner)]);",
    "}",
    "",
    "static int pya_command_matches_rule(const char *text, const char *kind, const char *value) {",
    "  if (strcmp(kind, \"word\") == 0) return pya_command_has_word(text, value);",
    "  if (strcmp(kind, \"fork_bomb\") == 0) return pya_command_has_fork_bomb(text);",
    "  if (strcmp(kind, \"text\") == 0) return pya_command_contains(text, value);",
    "  if (strcmp(kind, \"url\") == 0) return pya_command_contains_url(text, \"http://\") || pya_command_contains_url(text, \"https://\");",
    "  if (strcmp(kind, \"redirect\") == 0) return text && strstr(text, \">\") != NULL;",
    "  if (strcmp(kind, \"word_before_redirect\") == 0) return pya_command_has_word(text, value) && text && strstr(text, \">\") != NULL;",
    "  return 0;",
    "}",
    "",
    "static const char *pya_command_classify(const char *text) {",
    "  if (!text || !text[0]) return \"unknown\";",
    "  if (pya_command_is_see_runner(text)) return \"read_only\";"
  ];

  for (const entry of COMMAND_POLICY_CONTRACT) {
    for (const rule of entry.rules) {
      if (rule.kind === "sequence") {
        lines.push(`  if (pya_command_has_sequence(text, ${JSON.stringify(rule.values[0])}, ${JSON.stringify(rule.values[1])})) return ${JSON.stringify(entry.name)};`);
      } else {
        lines.push(`  if (pya_command_matches_rule(text, ${JSON.stringify(rule.kind)}, ${JSON.stringify(rule.value ?? "")})) return ${JSON.stringify(entry.name)};`);
      }
    }
  }

  lines.push(
    "  return \"unknown\";",
    "}",
    "",
    "static const char *pya_command_audit_class(const char *commandClass) {",
    "  return pya_command_classifier_enabled ? (commandClass && commandClass[0] ? commandClass : \"unknown\") : \"unknown\";",
    "}",
    "",
    "static const char *pya_command_audit_ordinal(const char *request) {",
    "  size_t length = request ? strlen(request) : 0;",
    "  return length >= 6 ? request + length - 6 : \"000000\";",
    "}",
    "",
    "static void pya_command_emit_audit(const char *request, const char *stage, const char *commandClass, const char *decision, const char *evoked, const char *result) {",
    "  char escapedEvoked[PYA_TEXT_CAP];",
    "  char escapedResult[PYA_TEXT_CAP];",
    "  char line[PYA_TEXT_CAP];",
    "  pya_escape_text(evoked ? evoked : \"\", escapedEvoked, sizeof(escapedEvoked));",
    "  pya_escape_text(result ? result : \"\", escapedResult, sizeof(escapedResult));",
    "  snprintf(line, sizeof(line), \"exists su name command audit %s ob text \\\"%s\\\" from name %s to name %s as name %s accordingto name %s\", pya_command_audit_ordinal(request), escapedEvoked, pya_command_policy_source, request ? request : \"\", stage ? stage : \"policy\", decision ? decision : \"allow\");",
    "  const char *auditedClass = pya_command_audit_class(commandClass);",
    "  if (strcmp(auditedClass, \"unknown\") != 0) { pya_concat_buf(line, \" by name \" ); pya_concat_buf(line, auditedClass); }",
    "  if (result && result[0]) { pya_concat_buf(line, \" totext text \\\"\" ); pya_concat_buf(line, escapedResult); pya_concat_buf(line, \"\\\"\" ); }",
    "  pya_concat_buf(line, \" be command audit ya\");",
    "  pya_emit_exchange(line);",
    "}",
    "",
    "static void pya_command_policy_gate(const char *request, const char *evoked, const char *commandText, const char *mood) {",
    "  const char *commandClass = pya_command_classify(commandText);",
    "  const int proposed = mood && strcmp(mood, \"propose\") == 0;",
    "  const int canRun = mood && strcmp(mood, \"can\") == 0;",
    "  const char *mode = pya_command_policy_mode;",
    "  if (proposed) mode = \"ask\";",
    "  if (canRun && strcmp(mode, \"deny\") != 0) mode = \"allow\";",
    "  if (strcmp(mode, \"deny\") == 0 && (proposed || strcmp(commandClass, \"destructive\") == 0)) {",
    "    pya_command_emit_audit(request, \"policy\", commandClass, \"deny\", evoked, NULL);",
    "    fprintf(stderr, \"command policy defective: denied class=%s\\n\", commandClass);",
    "    exit(1);",
    "  }",
    "  if (strcmp(mode, \"ask\") == 0 && (proposed || strcmp(commandClass, \"destructive\") == 0)) {",
    "    char escapedCommand[PYA_TEXT_CAP];",
    "    char prompt[PYA_TEXT_CAP];",
    "    char escapedPrompt[PYA_TEXT_CAP];",
    "    char token[PYA_TEXT_CAP];",
    "    char ratify[PYA_TEXT_CAP];",
    "    pya_escape_text(commandText ? commandText : \"\", escapedCommand, sizeof(escapedCommand));",
    "    snprintf(token, sizeof(token), \"{\\\"kind\\\":\\\"command\\\",\\\"class\\\":\\\"%s\\\",\\\"text\\\":\\\"%s\\\",\\\"requestIdentity\\\":\\\"%s\\\"}\", commandClass, escapedCommand, request ? request : \"\");",
    "    snprintf(prompt, sizeof(prompt), \"approve command (%s): %s\", pya_command_audit_class(commandClass), commandText ? commandText : \"\");",
    "    pya_escape_text(prompt, escapedPrompt, sizeof(escapedPrompt));",
    "    snprintf(ratify, sizeof(ratify), \"su name command approval ob text \\\"%s\\\" from name command to name %s accordingto name resume token fromtext text \\\"%s\\\" be ratify do\", escapedPrompt, request ? request : \"\", token);",
    "    pya_command_emit_audit(request, \"policy\", commandClass, \"ask\", evoked, ratify);",
    "    pya_emit_exchange(ratify);",
    "    fprintf(stderr, \"command policy defective: approval required\\n\");",
    "    exit(1);",
    "  }",
    "  pya_command_emit_audit(request, \"policy\", commandClass, \"allow\", evoked, NULL);",
    "}"
  );
  return lines.join("\n");
}
