export const COMMAND_HELPER = [
  "static char *pya_command_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static char *pya_command(const char *cmd) {",
  "  const char *mock = getenv(\"PYA_COMMAND_RESPONSE\");",
  "  if (mock) return pya_command_strdup(mock);",
  "  if (!cmd) return pya_command_strdup(\"\");",
  "  FILE *pipe = popen(cmd, \"r\");",
  "  if (!pipe) return NULL;",
  "  char out[PYA_TEXT_CAP];",
  "  out[0] = '\\0';",
  "  char buf[256];",
  "  while (fgets(buf, sizeof(buf), pipe)) {",
  "    pya_concat_buf(out, buf);",
  "  }",
  "  int status = pclose(pipe);",
  "  if (status != 0) return NULL;",
  "  return pya_command_strdup(out);",
  "}"
].join("\n");
