export const CSV_RUNTIME_HELPER = [
  "#define PYA_CSV_RUNTIME 1",
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_csv_error;",
  "typedef struct {",
  "  char **cells;",
  "  size_t count;",
  "} pya_csv_row;",
  "typedef struct {",
  "  pya_csv_row *rows;",
  "  size_t length;",
  "  size_t cap;",
  "} pya_csv_rows;",
  "typedef struct {",
  "  char **header_raw;",
  "  char **header;",
  "  size_t width;",
  "  size_t rows;",
  "  char ***columns;",
  "} pya_csv_map;",
  "typedef struct {",
  "  char *name;",
  "  pya_csv_map map;",
  "} pya_csv_named;",
  "static pya_csv_named *pya_csv_maps = NULL;",
  "static size_t pya_csv_map_count = 0;",
  "static size_t pya_csv_map_cap = 0;",
  "static char *pya_csv_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "static void pya_csv_set_error(pya_csv_error *err, const char *message, int line, int column) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", message ? message : \"csv defective\");",
  "  err->line = line;",
  "  err->column = column;",
  "}",
  "static int pya_csv_is_blank(const char *s) {",
  "  if (!s) return 1;",
  "  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
  "    if (!isspace(*p)) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void pya_csv_lower_trim(const char *s, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  out[0] = '\\0';",
  "  if (!s) return;",
  "  size_t len = strlen(s);",
  "  char buf[PYA_TEXT_CAP];",
  "  size_t idx = 0;",
  "  int lastSpace = 1;",
  "  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
  "    unsigned char ch = (unsigned char)s[i];",
  "    if (isspace(ch)) {",
  "      if (!lastSpace) { buf[idx++] = ' '; lastSpace = 1; }",
  "    } else {",
  "      buf[idx++] = (char)tolower(ch);",
  "      lastSpace = 0;",
  "    }",
  "  }",
  "  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
  "  buf[idx] = '\\0';",
  "  snprintf(out, cap, \"%s\", buf);",
  "}",
  "static int pya_csv_eq_lower(const char *s, const char *target) {",
  "  char buf[PYA_TEXT_CAP];",
  "  pya_csv_lower_trim(s, buf, sizeof(buf));",
  "  return strcmp(buf, target) == 0;",
  "}",
  "static int pya_csv_has_alpha(const char *s) {",
  "  if (!s) return 0;",
  "  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
  "    if (isalpha(*p)) return 1;",
  "  }",
  "  return 0;",
  "}",
  "static int pya_csv_is_numeric(const char *s) {",
  "  if (!s) return 0;",
  "  while (isspace((unsigned char)*s)) s++;",
  "  if (!*s) return 0;",
  "  char *end = NULL;",
  "  strtod(s, &end);",
  "  if (!end) return 0;",
  "  while (*end && isspace((unsigned char)*end)) end++;",
  "  return *end == '\\0';",
  "}",
  "static void pya_csv_rows_push(pya_csv_rows *rows, pya_csv_row row) {",
  "  if (!rows) return;",
  "  if (rows->length >= rows->cap) {",
  "    size_t next = rows->cap == 0 ? 16 : rows->cap * 2;",
  "    pya_csv_row *nextRows = (pya_csv_row *)realloc(rows->rows, sizeof(pya_csv_row) * next);",
  "    if (!nextRows) return;",
  "    rows->rows = nextRows;",
  "    rows->cap = next;",
  "  }",
  "  rows->rows[rows->length++] = row;",
  "}",
  "struct pya_csv_parse_ctx { zsv_parser parser; pya_csv_rows rows; };",
  "static void pya_csv_row_handler(void *ctx) {",
  "  struct pya_csv_parse_ctx *data = ctx;",
  "  size_t count = zsv_cell_count(data->parser);",
  "  char **cells = count ? (char **)calloc(count, sizeof(char *)) : NULL;",
  "  for (size_t i = 0; i < count; i++) {",
  "    struct zsv_cell cell = zsv_get_cell(data->parser, i);",
  "    char *value = (char *)malloc(cell.len + 1);",
  "    if (!value) continue;",
  "    memcpy(value, cell.str, cell.len);",
  "    value[cell.len] = '\\0';",
  "    cells[i] = value;",
  "  }",
  "  pya_csv_row row = { cells, count };",
  "  pya_csv_rows_push(&data->rows, row);",
  "}",
  "static void pya_csv_free_row(pya_csv_row *row) {",
  "  if (!row) return;",
  "  for (size_t i = 0; i < row->count; i++) free(row->cells[i]);",
  "  free(row->cells);",
  "  row->cells = NULL;",
  "  row->count = 0;",
  "}",
  "static void pya_csv_map_free(pya_csv_map *map) {",
  "  if (!map) return;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    free(map->header_raw[i]);",
  "    free(map->header[i]);",
  "    for (size_t r = 0; r < map->rows; r++) free(map->columns[i][r]);",
  "    free(map->columns[i]);",
  "  }",
  "  free(map->header_raw);",
  "  free(map->header);",
  "  free(map->columns);",
  "  map->header_raw = NULL;",
  "  map->header = NULL;",
  "  map->columns = NULL;",
  "  map->width = 0;",
  "  map->rows = 0;",
  "}",
  "static pya_csv_map *pya_csv_find(const char *name) {",
  "  if (!name) return NULL;",
  "  for (size_t i = 0; i < pya_csv_map_count; i++) {",
  "    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) return &pya_csv_maps[i].map;",
  "  }",
  "  return NULL;",
  "}",
  "static void pya_csv_store(const char *name, pya_csv_map *map) {",
  "  if (!name || !map) return;",
  "  for (size_t i = 0; i < pya_csv_map_count; i++) {",
  "    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) {",
  "      pya_csv_map_free(&pya_csv_maps[i].map);",
  "      pya_csv_maps[i].map = *map;",
  "      return;",
  "    }",
  "  }",
  "  if (pya_csv_map_count >= pya_csv_map_cap) {",
  "    size_t next = pya_csv_map_cap == 0 ? 8 : pya_csv_map_cap * 2;",
  "    pya_csv_named *nextMaps = (pya_csv_named *)realloc(pya_csv_maps, sizeof(pya_csv_named) * next);",
  "    if (!nextMaps) return;",
  "    pya_csv_maps = nextMaps;",
  "    pya_csv_map_cap = next;",
  "  }",
  "  pya_csv_maps[pya_csv_map_count].name = pya_csv_strdup(name);",
  "  pya_csv_maps[pya_csv_map_count].map = *map;",
  "  pya_csv_map_count += 1;",
  "}",
  "static int pya_csv_build_map(pya_csv_rows *rows, pya_csv_map *out, pya_csv_error *err) {",
  "  if (!rows || rows->length == 0) {",
  "    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
  "    return 0;",
  "  }",
  "  size_t nonEmpty = rows->length;",
  "  for (size_t i = 0; i < rows->length; i++) {",
  "    int has = 0;",
  "    for (size_t c = 0; c < rows->rows[i].count; c++) {",
  "      if (!pya_csv_is_blank(rows->rows[i].cells[c])) { has = 1; break; }",
  "    }",
  "    if (has) { nonEmpty = i; break; }",
  "  }",
  "  if (nonEmpty >= rows->length) {",
  "    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
  "    return 0;",
  "  }",
  "  int isTemplate = 0;",
  "  if (rows->length > 0 && rows->rows[0].count > 0 && pya_csv_eq_lower(rows->rows[0].cells[0], \"data import template\")) {",
  "    isTemplate = 1;",
  "  }",
  "  size_t headerRowIndex = rows->length;",
  "  if (isTemplate) {",
  "    for (size_t i = 0; i < rows->length; i++) {",
  "      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"column name:\")) {",
  "        headerRowIndex = i; break;",
  "      }",
  "    }",
  "    if (headerRowIndex >= rows->length) {",
  "      pya_csv_set_error(err, \"csv header defective\", 1, 1);",
  "      return 0;",
  "    }",
  "  } else {",
  "    size_t lastWidths[20] = {0};",
  "    size_t lastCount = 0;",
  "    for (size_t i = 0; i < rows->length; i++) {",
  "      int has = 0;",
  "      for (size_t c = 0; c < rows->rows[i].count; c++) {",
  "        if (!pya_csv_is_blank(rows->rows[i].cells[c])) { has = 1; break; }",
  "      }",
  "      if (!has) continue;",
  "      size_t width = rows->rows[i].count;",
  "      if (lastCount < 20) {",
  "        lastWidths[lastCount++] = width;",
  "      } else {",
  "        for (size_t j = 1; j < 20; j++) lastWidths[j - 1] = lastWidths[j];",
  "        lastWidths[19] = width;",
  "      }",
  "    }",
  "    size_t widthMode = 0;",
  "    size_t bestCount = 0;",
  "    for (size_t i = 0; i < lastCount; i++) {",
  "      size_t width = lastWidths[i];",
  "      size_t count = 0;",
  "      for (size_t j = 0; j < lastCount; j++) if (lastWidths[j] == width) count++;",
  "      if (count > bestCount || (count == bestCount && width > widthMode)) {",
  "        widthMode = width;",
  "        bestCount = count;",
  "      }",
  "    }",
  "    for (size_t i = 0; i < rows->length; i++) {",
  "      pya_csv_row row = rows->rows[i];",
  "      if (row.count != widthMode || widthMode == 0) continue;",
  "      int ok = 1;",
  "      int hasAlpha = 0;",
  "      for (size_t c = 0; c < row.count; c++) {",
  "        const char *cell = row.cells[c];",
  "        if (pya_csv_is_blank(cell)) { ok = 0; break; }",
  "        if (pya_csv_has_alpha(cell)) hasAlpha = 1;",
  "        if (pya_csv_is_numeric(cell)) { ok = 0; break; }",
  "      }",
  "      if (ok && hasAlpha) { headerRowIndex = i; break; }",
  "    }",
  "    if (headerRowIndex >= rows->length && widthMode > 0) {",
  "      for (size_t i = 0; i < rows->length; i++) {",
  "        if (rows->rows[i].count == widthMode) { headerRowIndex = i; break; }",
  "      }",
  "    }",
  "  }",
  "  if (headerRowIndex >= rows->length) headerRowIndex = nonEmpty;",
  "  pya_csv_row headerRow = rows->rows[headerRowIndex];",
  "  size_t headerCount = headerRow.count > 0 ? headerRow.count - (isTemplate ? 1 : 0) : 0;",
  "  if (headerCount == 0) {",
  "    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
  "    return 0;",
  "  }",
  "  char *drop = (char *)calloc(headerCount, 1);",
  "  if (isTemplate) {",
  "    for (size_t i = 0; i < headerCount; i++) {",
  "      const char *cell = headerRow.cells[i + 1];",
  "      char norm[PYA_TEXT_CAP];",
  "      pya_csv_lower_trim(cell, norm, sizeof(norm));",
  "      if (pya_csv_is_blank(cell) || strcmp(norm, \"~\") == 0) drop[i] = 1;",
  "    }",
  "  }",
  "  size_t filteredCount = 0;",
  "  for (size_t i = 0; i < headerCount; i++) if (!drop[i]) filteredCount++;",
  "  if (filteredCount == 0) {",
  "    free(drop);",
  "    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
  "    return 0;",
  "  }",
  "  char **header_raw = (char **)calloc(filteredCount, sizeof(char *));",
  "  char **header = (char **)calloc(filteredCount, sizeof(char *));",
  "  size_t headerIdx = 0;",
  "  for (size_t i = 0; i < headerCount; i++) {",
  "    if (drop[i]) continue;",
  "    const char *cell = headerRow.cells[i + (isTemplate ? 1 : 0)];",
  "    header_raw[headerIdx] = pya_csv_strdup(cell ? cell : \"\");",
  "    if (isTemplate) {",
  "      header[headerIdx] = pya_csv_strdup(cell ? cell : \"\");",
  "    } else {",
  "      char norm[PYA_TEXT_CAP];",
  "      pya_csv_lower_trim(cell, norm, sizeof(norm));",
  "      header[headerIdx] = pya_csv_strdup(norm);",
  "    }",
  "    headerIdx++;",
  "  }",
  "  if (isTemplate) {",
  "    char **bases = (char **)calloc(filteredCount, sizeof(char *));",
  "    for (size_t i = 0; i < filteredCount; i++) {",
  "      bases[i] = pya_csv_strdup(header[i]);",
  "    }",
  "    for (size_t i = 0; i < filteredCount; i++) {",
  "      if (!bases[i] || !*bases[i]) continue;",
  "      int count = 0;",
  "      for (size_t j = 0; j < i; j++) if (bases[j] && strcmp(bases[j], bases[i]) == 0) count++;",
  "      if (count > 0) {",
  "        char buf[PYA_TEXT_CAP];",
  "        snprintf(buf, sizeof(buf), \"%s %d\", bases[i], count + 1);",
  "        free(header[i]);",
  "        header[i] = pya_csv_strdup(buf);",
  "      }",
  "    }",
  "    for (size_t i = 0; i < filteredCount; i++) free(bases[i]);",
  "    free(bases);",
  "  }",
  "  const char *metaLabels[] = {\"column name:\",\"mandatory:\",\"type:\",\"info:\",\"doctype:\",\"column labels:\",\"start entering data below this line\"};",
  "  size_t dataStart = headerRowIndex + 1;",
  "  if (isTemplate) {",
  "    for (size_t i = headerRowIndex + 1; i < rows->length; i++) {",
  "      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"start entering data below this line\")) {",
  "        dataStart = i + 1; break;",
  "      }",
  "    }",
  "  }",
  "  size_t dataCount = 0;",
  "  for (size_t r = dataStart; r < rows->length; r++) {",
  "    pya_csv_row row = rows->rows[r];",
  "    if (isTemplate) {",
  "      int isMeta = 0;",
  "      if (row.count > 0) {",
  "        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
  "          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
  "        }",
  "      }",
  "      if (isMeta) continue;",
  "      int allBlank = 1;",
  "      for (size_t c = 0; c < row.count; c++) {",
  "        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
  "      }",
  "      if (allBlank) continue;",
  "    }",
  "    dataCount++;",
  "  }",
  "  char ***columns = (char ***)calloc(filteredCount, sizeof(char **));",
  "  for (size_t i = 0; i < filteredCount; i++) columns[i] = (char **)calloc(dataCount, sizeof(char *));",
  "  size_t rowIndex = 0;",
  "  for (size_t r = dataStart; r < rows->length; r++) {",
  "    pya_csv_row row = rows->rows[r];",
  "    if (isTemplate) {",
  "      int isMeta = 0;",
  "      if (row.count > 0) {",
  "        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
  "          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
  "        }",
  "      }",
  "      if (isMeta) continue;",
  "      int allBlank = 1;",
  "      for (size_t c = 0; c < row.count; c++) {",
  "        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
  "      }",
  "      if (allBlank) continue;",
  "    }",
  "    size_t dataLen = row.count > 0 ? row.count - (isTemplate ? 1 : 0) : 0;",
  "    if (dataLen > headerCount) {",
  "      free(drop);",
  "      pya_csv_set_error(err, \"csv row defective\", (int)r + 1, (int)dataLen + (isTemplate ? 1 : 0));",
  "      return 0;",
  "    }",
  "    size_t colIndex = 0;",
  "    for (size_t c = 0; c < headerCount; c++) {",
  "      if (drop[c]) continue;",
  "      const char *cell = (c + (isTemplate ? 1 : 0) < row.count) ? row.cells[c + (isTemplate ? 1 : 0)] : \"\";",
  "      columns[colIndex][rowIndex] = pya_csv_strdup(cell ? cell : \"\");",
  "      colIndex++;",
  "    }",
  "    rowIndex++;",
  "  }",
  "  free(drop);",
  "  out->header_raw = header_raw;",
  "  out->header = header;",
  "  out->width = filteredCount;",
  "  out->rows = dataCount;",
  "  out->columns = columns;",
  "  return 1;",
  "}",
  "static int pya_csv_read_file(const char *filename, const char *name, pya_csv_error *err) {",
  "  if (!filename || !name) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
  "  FILE *f = fopen(filename, \"rb\");",
  "  if (!f) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
  "  struct zsv_opts opts = {0};",
  "  struct pya_csv_parse_ctx ctx = {0};",
  "  opts.row_handler = pya_csv_row_handler;",
  "  opts.ctx = &ctx;",
  "  opts.stream = f;",
  "  ctx.parser = zsv_new(&opts);",
  "  enum zsv_status stat;",
  "  while ((stat = zsv_parse_more(ctx.parser)) == zsv_status_ok) { }",
  "  zsv_finish(ctx.parser);",
  "  zsv_delete(ctx.parser);",
  "  fclose(f);",
  "  if (stat != zsv_status_no_more_input) {",
  "    pya_csv_set_error(err, \"csv defective\", 0, 0);",
  "    return 0;",
  "  }",
  "  pya_csv_map map = {0};",
  "  if (!pya_csv_build_map(&ctx.rows, &map, err)) {",
  "    for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
  "    free(ctx.rows.rows);",
  "    return 0;",
  "  }",
  "  for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
  "  free(ctx.rows.rows);",
  "  pya_csv_store(name, &map);",
  "  return 1;",
  "}",
  "static int pya_csv_header_raw_unique(pya_csv_map *map) {",
  "  if (!map || !map->header_raw) return 0;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    char normA[PYA_TEXT_CAP];",
  "    pya_csv_lower_trim(map->header_raw[i], normA, sizeof(normA));",
  "    if (!*normA) return 0;",
  "    for (size_t j = i + 1; j < map->width; j++) {",
  "      char normB[PYA_TEXT_CAP];",
  "      pya_csv_lower_trim(map->header_raw[j], normB, sizeof(normB));",
  "      if (strcmp(normA, normB) == 0) return 0;",
  "    }",
  "  }",
  "  return 1;",
  "}",
  "static void pya_csv_escape(FILE *out, const char *value) {",
  "  const char *str = value ? value : \"\";",
  "  int needs = 0;",
  "  for (const char *p = str; *p; p++) {",
  "    if (*p == '\"' || *p == '\\n' || *p == '\\r' || *p == ',') { needs = 1; break; }",
  "  }",
  "  if (!needs) { fputs(str, out); return; }",
  "  fputc('\"', out);",
  "  for (const char *p = str; *p; p++) {",
  "    if (*p == '\"') fputc('\"', out);",
  "    fputc(*p, out);",
  "  }",
  "  fputc('\"', out);",
  "}",
  "static int pya_csv_write_file(const char *name, const char *filename) {",
  "  pya_csv_map *map = pya_csv_find(name);",
  "  if (!map || !filename) return 0;",
  "  FILE *out = fopen(filename, \"w\");",
  "  if (!out) return 0;",
  "  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    if (i) fputc(',', out);",
  "    pya_csv_escape(out, headers[i]);",
  "  }",
  "  fputc('\\n', out);",
  "  for (size_t r = 0; r < map->rows; r++) {",
  "    for (size_t c = 0; c < map->width; c++) {",
  "      if (c) fputc(',', out);",
  "      pya_csv_escape(out, map->columns[c][r]);",
  "    }",
  "    fputc('\\n', out);",
  "  }",
  "  fclose(out);",
  "  return 1;",
  "}",
  "static int pya_csv_write_stdout(const char *name) {",
  "  pya_csv_map *map = pya_csv_find(name);",
  "  if (!map) return 0;",
  "  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    if (i) fputc(',', stdout);",
  "    pya_csv_escape(stdout, headers[i]);",
  "  }",
  "  fputc('\\n', stdout);",
  "  for (size_t r = 0; r < map->rows; r++) {",
  "    for (size_t c = 0; c < map->width; c++) {",
  "      if (c) fputc(',', stdout);",
  "      pya_csv_escape(stdout, map->columns[c][r]);",
  "    }",
  "    fputc('\\n', stdout);",
  "  }",
  "  return 1;",
  "}",
  "static int pya_pyash_is_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
  "    if (!(isalnum(*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void pya_pyash_print_escaped(FILE *out, const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      fputc('\\\\', out);",
  "      fputc(*p, out);",
  "    } else if (*p == '\\n') {",
  "      fputs(\"\\\\n\", out);",
  "    } else {",
  "      fputc(*p, out);",
  "    }",
  "  }",
  "}",
  "static void pya_pyash_print_token(FILE *out, const char *s) {",
  "  if (!s) return;",
  "  if (pya_pyash_is_token(s)) {",
  "    fputs(s, out);",
  "  } else {",
  "    fputc('\"', out);",
  "    pya_pyash_print_escaped(out, s);",
  "    fputc('\"', out);",
  "  }",
  "}",
  "static void pya_pyash_print_text_vector(FILE *out, char **values, size_t count) {",
  "  fputs(\"ve text\", out);",
  "  for (size_t i = 0; i < count; i++) {",
  "    fputc(' ', out);",
  "    pya_pyash_print_token(out, values[i] ? values[i] : \"\");",
  "  }",
  "}",
  "static int pya_csv_write_pyash(FILE *out, const char *name) {",
  "  pya_csv_map *map = pya_csv_find(name);",
  "  if (!map || !out) return 0;",
  "  fputs(\"su name \", out);",
  "  pya_pyash_print_token(out, name ? name : \"\");",
  "  fputs(\" be csv map def\\n\", out);",
  "  fputs(\"su name header raw ob \", out);",
  "  pya_pyash_print_text_vector(out, map->header_raw ? map->header_raw : map->header, map->width);",
  "  fputs(\" ya\\n\", out);",
  "  fputs(\"su name header ob \", out);",
  "  pya_pyash_print_text_vector(out, map->header, map->width);",
  "  fputs(\" ya\\n\", out);",
  "  for (size_t c = 0; c < map->width; c++) {",
  "    fputs(\"su name \", out);",
  "    pya_pyash_print_token(out, map->header[c] ? map->header[c] : \"\");",
  "    fputs(\" ob \", out);",
  "    pya_pyash_print_text_vector(out, map->columns[c], map->rows);",
  "    fputs(\" ya\\n\", out);",
  "  }",
  "  fputs(\"prah\\n\", out);",
  "  return 1;",
  "}",
  "static int pya_csv_write_pyash_file(const char *name, const char *filename) {",
  "  FILE *out = fopen(filename, \"w\");",
  "  if (!out) return 0;",
  "  int ok = pya_csv_write_pyash(out, name);",
  "  fclose(out);",
  "  return ok;",
  "}",
  "static int pya_csv_write_pyash_stdout(const char *name) {",
  "  return pya_csv_write_pyash(stdout, name);",
  "}"
].join("\n");
