export const DATE_MATH_HELPER = [
  "#ifndef _WIN32",
  "time_t timegm(struct tm *tm);",
  "#endif",
  "",
  "static time_t pya_timegm(struct tm *tm) {",
  "#if defined(_WIN32)",
  "  return _mkgmtime(tm);",
  "#else",
  "  return timegm(tm);",
  "#endif",
  "}",
  "",
  "static int pya_parse_iso_date(const char *value, struct tm *out, int *use_local) {",
  "  if (!value || !out || !use_local) return 0;",
  "  if (strcmp(value, \"now\") == 0) {",
  "    time_t now = time(NULL);",
  "    struct tm *tmv = localtime(&now);",
  "    if (!tmv) return 0;",
  "    *out = *tmv;",
  "    *use_local = 1;",
  "    return 1;",
  "  }",
  "  if (strcmp(value, \"today\") == 0) {",
  "    time_t now = time(NULL);",
  "    struct tm *tmv = localtime(&now);",
  "    if (!tmv) return 0;",
  "    *out = *tmv;",
  "    out->tm_hour = 0;",
  "    out->tm_min = 0;",
  "    out->tm_sec = 0;",
  "    *use_local = 1;",
  "    return 1;",
  "  }",
  "  int year = 0, mon = 0, day = 0, hour = 0, min = 0, sec = 0;",
  "  if (sscanf(value, \"%4d-%2d-%2dT%2d:%2d:%2dZ\", &year, &mon, &day, &hour, &min, &sec) == 6) {",
  "    memset(out, 0, sizeof(struct tm));",
  "    out->tm_year = year - 1900;",
  "    out->tm_mon = mon - 1;",
  "    out->tm_mday = day;",
  "    out->tm_hour = hour;",
  "    out->tm_min = min;",
  "    out->tm_sec = sec;",
  "    *use_local = 0;",
  "    return 1;",
  "  }",
  "  if (sscanf(value, \"%4d-%2d-%2d\", &year, &mon, &day) == 3) {",
  "    memset(out, 0, sizeof(struct tm));",
  "    out->tm_year = year - 1900;",
  "    out->tm_mon = mon - 1;",
  "    out->tm_mday = day;",
  "    out->tm_hour = 0;",
  "    out->tm_min = 0;",
  "    out->tm_sec = 0;",
  "    *use_local = 0;",
  "    return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static int pya_date_add(const char *value, const char *unit, double amount, int direction, char *out, size_t cap) {",
  "  struct tm tmv;",
  "  int use_local = 0;",
  "  if (!pya_parse_iso_date(value, &tmv, &use_local)) return 0;",
  "  time_t base = use_local ? mktime(&tmv) : pya_timegm(&tmv);",
  "  if (base == (time_t)-1) return 0;",
  "  double seconds = amount;",
  "  if (strcmp(unit, \"minute\") == 0) seconds *= 60;",
  "  else if (strcmp(unit, \"hour\") == 0) seconds *= 3600;",
  "  else if (strcmp(unit, \"day\") == 0) seconds *= 86400;",
  "  else if (strcmp(unit, \"week\") == 0) seconds *= 604800;",
  "  else if (strcmp(unit, \"second\") != 0) return 0;",
  "  time_t result = base + (time_t)(seconds * (double)direction);",
  "  struct tm *out_tm = gmtime(&result);",
  "  if (!out_tm) return 0;",
  "  if (strftime(out, cap, \"%Y-%m-%dT%H:%M:%S.000Z\", out_tm) == 0) return 0;",
  "  return 1;",
  "}"
].join("\n");
