export const FILESYSTEM_HELPER = [
  "typedef struct { char **items; int length; int cap; } pya_str_list;",
  "",
  "static char *pya_fs_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static void pya_list_init(pya_str_list *list) {",
  "  if (!list) return;",
  "  list->items = NULL;",
  "  list->length = 0;",
  "  list->cap = 0;",
  "}",
  "",
  "static int pya_list_push(pya_str_list *list, const char *value) {",
  "  if (!list || !value) return 0;",
  "  if (list->length + 1 > list->cap) {",
  "    int next = list->cap ? list->cap * 2 : 8;",
  "    char **nextItems = (char **)realloc(list->items, sizeof(char *) * next);",
  "    if (!nextItems) return 0;",
  "    list->items = nextItems;",
  "    list->cap = next;",
  "  }",
  "  list->items[list->length++] = pya_fs_strdup(value);",
  "  return 1;",
  "}",
  "",
  "static int pya_list_cmp(const void *a, const void *b) {",
  "  const char *lhs = *(const char * const *)a;",
  "  const char *rhs = *(const char * const *)b;",
  "  if (!lhs && !rhs) return 0;",
  "  if (!lhs) return -1;",
  "  if (!rhs) return 1;",
  "  return strcmp(lhs, rhs);",
  "}",
  "",
  "static void pya_list_sort(pya_str_list *list) {",
  "  if (!list || list->length <= 1) return;",
  "  qsort(list->items, list->length, sizeof(char *), pya_list_cmp);",
  "}",
  "",
  "static int pya_list_walk(const char *root, const char *relBase, int recursive, int includeFiles, int includeDirs, int includeHidden, pya_str_list *out) {",
  "  DIR *dir = opendir(root);",
  "  if (!dir) return 0;",
  "  struct dirent *entry;",
  "  while ((entry = readdir(dir)) != NULL) {",
  "    const char *name = entry->d_name;",
  "    if (!name || strcmp(name, \".\") == 0 || strcmp(name, \"..\") == 0) continue;",
  "    if (!includeHidden && name[0] == '.') continue;",
  "    char fullPath[PYA_TEXT_CAP];",
  "    char relPath[PYA_TEXT_CAP];",
  "    if (relBase && relBase[0]) {",
  "      snprintf(fullPath, sizeof(fullPath), \"%s/%s\", root, name);",
  "      snprintf(relPath, sizeof(relPath), \"%s/%s\", relBase, name);",
  "    } else {",
  "      snprintf(fullPath, sizeof(fullPath), \"%s/%s\", root, name);",
  "      snprintf(relPath, sizeof(relPath), \"%s\", name);",
  "    }",
  "    struct stat st;",
  "    if (stat(fullPath, &st) != 0) continue;",
  "    const char *outputPath = recursive ? relPath : name;",
  "    if (S_ISDIR(st.st_mode)) {",
  "      if (includeDirs) {",
  "        if (!pya_list_push(out, outputPath)) { closedir(dir); return 0; }",
  "      }",
  "      if (recursive) {",
  "        if (!pya_list_walk(fullPath, relPath, recursive, includeFiles, includeDirs, includeHidden, out)) {",
  "          closedir(dir);",
  "          return 0;",
  "        }",
  "      }",
  "    } else {",
  "      if (includeFiles) {",
  "        if (!pya_list_push(out, outputPath)) { closedir(dir); return 0; }",
  "      }",
  "    }",
  "  }",
  "  closedir(dir);",
  "  return 1;",
  "}",
  "",
  "static int pya_fs_mkdir_recursive(const char *path) {",
  "  if (!path || !*path) return 0;",
  "  char tmp[PYA_TEXT_CAP];",
  "  size_t len = strlen(path);",
  "  if (len >= sizeof(tmp)) return 0;",
  "  snprintf(tmp, sizeof(tmp), \"%s\", path);",
  "  for (size_t i = 1; i < len; i++) {",
  "    if (tmp[i] == '/') {",
  "      tmp[i] = '\\0';",
  "      if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
  "      tmp[i] = '/';",
  "    }",
  "  }",
  "  if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
  "  return 1;",
  "}",
  "",
  "static int pya_fs_copy_file(const char *src, const char *dst) {",
  "  if (!src || !dst) return 0;",
  "  FILE *in = fopen(src, \"rb\");",
  "  if (!in) return 0;",
  "  FILE *out = fopen(dst, \"wb\");",
  "  if (!out) { fclose(in); return 0; }",
  "  char buf[8192];",
  "  size_t n;",
  "  while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {",
  "    if (fwrite(buf, 1, n, out) != n) { fclose(in); fclose(out); return 0; }",
  "  }",
  "  fclose(in);",
  "  fclose(out);",
  "  return 1;",
  "}",
  "",
  "static int pya_fs_copy_dir(const char *src, const char *dst) {",
  "  struct stat st;",
  "  if (stat(src, &st) != 0) return 0;",
  "  if (!S_ISDIR(st.st_mode)) return 0;",
  "  if (!pya_fs_mkdir_recursive(dst)) return 0;",
  "  DIR *dir = opendir(src);",
  "  if (!dir) return 0;",
  "  struct dirent *entry;",
  "  while ((entry = readdir(dir)) != NULL) {",
  "    const char *name = entry->d_name;",
  "    if (!name || strcmp(name, \".\") == 0 || strcmp(name, \"..\") == 0) continue;",
  "    char srcPath[PYA_TEXT_CAP];",
  "    char dstPath[PYA_TEXT_CAP];",
  "    snprintf(srcPath, sizeof(srcPath), \"%s/%s\", src, name);",
  "    snprintf(dstPath, sizeof(dstPath), \"%s/%s\", dst, name);",
  "    if (stat(srcPath, &st) != 0) { closedir(dir); return 0; }",
  "    if (S_ISDIR(st.st_mode)) {",
  "      if (!pya_fs_copy_dir(srcPath, dstPath)) { closedir(dir); return 0; }",
  "    } else {",
  "      if (!pya_fs_copy_file(srcPath, dstPath)) { closedir(dir); return 0; }",
  "    }",
  "  }",
  "  closedir(dir);",
  "  return 1;",
  "}",
  "",
  "static int pya_fs_delete_recursive(const char *path) {",
  "  if (!path || !*path) return 0;",
  "  struct stat st;",
  "  if (stat(path, &st) != 0) return 0;",
  "  if (S_ISDIR(st.st_mode)) {",
  "    DIR *dir = opendir(path);",
  "    if (!dir) return 0;",
  "    struct dirent *entry;",
  "    while ((entry = readdir(dir)) != NULL) {",
  "      const char *name = entry->d_name;",
  "      if (!name || strcmp(name, \".\") == 0 || strcmp(name, \"..\") == 0) continue;",
  "      char child[PYA_TEXT_CAP];",
  "      snprintf(child, sizeof(child), \"%s/%s\", path, name);",
  "      if (!pya_fs_delete_recursive(child)) {",
  "        closedir(dir);",
  "        return 0;",
  "      }",
  "    }",
  "    closedir(dir);",
  "    return (rmdir(path) == 0);",
  "  }",
  "  return (unlink(path) == 0);",
  "}"
].join("\n");
