export const MIND_RUNTIME_HELPER = [
  "#define PYA_MIND_RUNTIME 1",
  "",
  "typedef struct {",
  "  char *data;",
  "  size_t len;",
  "  size_t cap;",
  "} pya_buf;",
  "",
  "static void pya_buf_init(pya_buf *buf) {",
  "  if (!buf) return;",
  "  buf->data = NULL;",
  "  buf->len = 0;",
  "  buf->cap = 0;",
  "}",
  "",
  "static void pya_buf_reserve(pya_buf *buf, size_t extra) {",
  "  if (!buf) return;",
  "  size_t need = buf->len + extra + 1;",
  "  if (need <= buf->cap) return;",
  "  size_t next = buf->cap == 0 ? 256 : buf->cap;",
  "  while (next < need) next *= 2;",
  "  char *data = (char *)realloc(buf->data, next);",
  "  if (!data) return;",
  "  buf->data = data;",
  "  buf->cap = next;",
  "}",
  "",
  "static void pya_buf_append(pya_buf *buf, const char *text) {",
  "  if (!buf || !text) return;",
  "  size_t len = strlen(text);",
  "  pya_buf_reserve(buf, len);",
  "  if (!buf->data) return;",
  "  memcpy(buf->data + buf->len, text, len);",
  "  buf->len += len;",
  "  buf->data[buf->len] = '\\0';",
  "}",
  "",
  "static char *pya_buf_take(pya_buf *buf) {",
  "  if (!buf) return NULL;",
  "  char *out = buf->data;",
  "  buf->data = NULL;",
  "  buf->len = 0;",
  "  buf->cap = 0;",
  "  return out;",
  "}",
  "",
  "typedef struct {",
  "  char *name;",
  "  char *space;",
  "  char *model;",
  "  char *prompt;",
  "  int window;",
  "} pya_mind_config;",
  "",
  "static pya_mind_config *pya_mind_configs = NULL;",
  "static size_t pya_mind_config_len = 0;",
  "static size_t pya_mind_config_cap = 0;",
  "",
  "static pya_mind_config *pya_mind_get_config(const char *name) {",
  "  if (!name) return NULL;",
  "  for (size_t i = 0; i < pya_mind_config_len; i++) {",
  "    if (pya_mind_configs[i].name && strcmp(pya_mind_configs[i].name, name) == 0) {",
  "      return &pya_mind_configs[i];",
  "    }",
  "  }",
  "  return NULL;",
  "}",
  "",
  "static void pya_mind_set_config(const char *name, const char *space, const char *model, const char *prompt, int window) {",
  "  if (!name) return;",
  "  pya_mind_config *cfg = pya_mind_get_config(name);",
  "  if (!cfg) {",
  "    if (pya_mind_config_len + 1 > pya_mind_config_cap) {",
  "      size_t next = pya_mind_config_cap == 0 ? 4 : pya_mind_config_cap * 2;",
  "      pya_mind_config *resized = (pya_mind_config *)realloc(pya_mind_configs, sizeof(pya_mind_config) * next);",
  "      if (!resized) return;",
  "      pya_mind_configs = resized;",
  "      pya_mind_config_cap = next;",
  "    }",
  "    cfg = &pya_mind_configs[pya_mind_config_len++];",
  "    memset(cfg, 0, sizeof(*cfg));",
  "    cfg->name = pya_strdup(name);",
  "  }",
  "  if (space) { free(cfg->space); cfg->space = pya_strdup(space); }",
  "  if (model) { free(cfg->model); cfg->model = pya_strdup(model); }",
  "  if (prompt) { free(cfg->prompt); cfg->prompt = pya_strdup(prompt); }",
  "  if (window > 0) cfg->window = window;",
  "}",
  "",
  "typedef struct {",
  "  char *role;",
  "  char *content;",
  "} pya_mind_msg;",
  "",
  "typedef struct {",
  "  char *dialogue;",
  "  pya_mind_msg *items;",
  "  size_t len;",
  "  size_t cap;",
  "} pya_mind_history;",
  "",
  "static pya_mind_history *pya_mind_histories = NULL;",
  "static size_t pya_mind_history_len = 0;",
  "static size_t pya_mind_history_cap = 0;",
  "",
  "static pya_mind_history *pya_mind_get_history(const char *dialogue) {",
  "  if (!dialogue) return NULL;",
  "  for (size_t i = 0; i < pya_mind_history_len; i++) {",
  "    if (pya_mind_histories[i].dialogue && strcmp(pya_mind_histories[i].dialogue, dialogue) == 0) {",
  "      return &pya_mind_histories[i];",
  "    }",
  "  }",
  "  if (pya_mind_history_len + 1 > pya_mind_history_cap) {",
  "    size_t next = pya_mind_history_cap == 0 ? 4 : pya_mind_history_cap * 2;",
  "    pya_mind_history *resized = (pya_mind_history *)realloc(pya_mind_histories, sizeof(pya_mind_history) * next);",
  "    if (!resized) return NULL;",
  "    pya_mind_histories = resized;",
  "    pya_mind_history_cap = next;",
  "  }",
  "  pya_mind_history *hist = &pya_mind_histories[pya_mind_history_len++];",
  "  memset(hist, 0, sizeof(*hist));",
  "  hist->dialogue = pya_strdup(dialogue);",
  "  return hist;",
  "}",
  "",
  "static void pya_mind_trim_history(pya_mind_history *hist, int window) {",
  "  if (!hist || window <= 0) return;",
  "  size_t max = (size_t)window * 2;",
  "  if (hist->len <= max) return;",
  "  size_t drop = hist->len - max;",
  "  for (size_t i = 0; i < drop; i++) {",
  "    free(hist->items[i].role);",
  "    free(hist->items[i].content);",
  "  }",
  "  memmove(hist->items, hist->items + drop, sizeof(pya_mind_msg) * max);",
  "  hist->len = max;",
  "}",
  "",
  "static void pya_mind_record(const char *dialogue, const char *role, const char *content, int window) {",
  "  if (!dialogue || !role || !content) return;",
  "  pya_mind_history *hist = pya_mind_get_history(dialogue);",
  "  if (!hist) return;",
  "  if (hist->len + 1 > hist->cap) {",
  "    size_t next = hist->cap == 0 ? 8 : hist->cap * 2;",
  "    pya_mind_msg *resized = (pya_mind_msg *)realloc(hist->items, sizeof(pya_mind_msg) * next);",
  "    if (!resized) return;",
  "    hist->items = resized;",
  "    hist->cap = next;",
  "  }",
  "  hist->items[hist->len].role = pya_strdup(role);",
  "  hist->items[hist->len].content = pya_strdup(content);",
  "  hist->len += 1;",
  "  pya_mind_trim_history(hist, window);",
  "}",
  "",
  "typedef struct {",
  "  char *dialogue;",
  "  int count;",
  "} pya_mind_counter;",
  "",
  "static pya_mind_counter *pya_mind_counters = NULL;",
  "static size_t pya_mind_counter_len = 0;",
  "static size_t pya_mind_counter_cap = 0;",
  "",
  "static int pya_mind_next_count(const char *dialogue) {",
  "  if (!dialogue) return 1;",
  "  for (size_t i = 0; i < pya_mind_counter_len; i++) {",
  "    if (pya_mind_counters[i].dialogue && strcmp(pya_mind_counters[i].dialogue, dialogue) == 0) {",
  "      pya_mind_counters[i].count += 1;",
  "      return pya_mind_counters[i].count;",
  "    }",
  "  }",
  "  if (pya_mind_counter_len + 1 > pya_mind_counter_cap) {",
  "    size_t next = pya_mind_counter_cap == 0 ? 4 : pya_mind_counter_cap * 2;",
  "    pya_mind_counter *resized = (pya_mind_counter *)realloc(pya_mind_counters, sizeof(pya_mind_counter) * next);",
  "    if (!resized) return 1;",
  "    pya_mind_counters = resized;",
  "    pya_mind_counter_cap = next;",
  "  }",
  "  pya_mind_counters[pya_mind_counter_len].dialogue = pya_strdup(dialogue);",
  "  pya_mind_counters[pya_mind_counter_len].count = 1;",
  "  pya_mind_counter_len += 1;",
  "  return 1;",
  "}",
  "",
  "typedef struct {",
  "  char *name;",
  "  int count;",
  "} pya_mind_debug;",
  "",
  "static pya_mind_debug *pya_mind_debugs = NULL;",
  "static size_t pya_mind_debug_len = 0;",
  "static size_t pya_mind_debug_cap = 0;",
  "",
  "static int pya_mind_next_debug(const char *name) {",
  "  const char *key = name ? name : \"mind\";",
  "  for (size_t i = 0; i < pya_mind_debug_len; i++) {",
  "    if (pya_mind_debugs[i].name && strcmp(pya_mind_debugs[i].name, key) == 0) {",
  "      pya_mind_debugs[i].count += 1;",
  "      return pya_mind_debugs[i].count;",
  "    }",
  "  }",
  "  if (pya_mind_debug_len + 1 > pya_mind_debug_cap) {",
  "    size_t next = pya_mind_debug_cap == 0 ? 4 : pya_mind_debug_cap * 2;",
  "    pya_mind_debug *resized = (pya_mind_debug *)realloc(pya_mind_debugs, sizeof(pya_mind_debug) * next);",
  "    if (!resized) return 1;",
  "    pya_mind_debugs = resized;",
  "    pya_mind_debug_cap = next;",
  "  }",
  "  pya_mind_debugs[pya_mind_debug_len].name = pya_strdup(key);",
  "  pya_mind_debugs[pya_mind_debug_len].count = 1;",
  "  pya_mind_debug_len += 1;",
  "  return 1;",
  "}",
  "",
  "static void pya_record_mind_json(const char *target, const char *label, const char *payload) {",
  "  if (!payload) return;",
  "  int count = pya_mind_next_debug(target);",
  "  pya_buf buf; pya_buf_init(&buf);",
  "  pya_buf_append(&buf, \"su name \");",
  "  pya_buf_append(&buf, target ? target : \"mind\");",
  "  pya_buf_append(&buf, \" \");",
  "  pya_buf_append(&buf, label ? label : \"request\");",
  "  char num[32];",
  "  snprintf(num, sizeof(num), \" %d\", count);",
  "  pya_buf_append(&buf, num);",
  "  pya_buf_append(&buf, \" ob text quoted.json.\\n\");",
  "  pya_buf_append(&buf, payload);",
  "  pya_buf_append(&buf, \"\\n.json.quoted from name mind be write ya\");",
  "  char *line = pya_buf_take(&buf);",
  "  if (line) {",
  "    pya_emit_exchange(line);",
  "    free(line);",
  "  }",
  "}",
  "",
  "static size_t pya_curl_write(void *ptr, size_t size, size_t nmemb, void *userdata) {",
  "  size_t total = size * nmemb;",
  "  pya_buf *buf = (pya_buf *)userdata;",
  "  pya_buf_reserve(buf, total);",
  "  if (!buf->data) return 0;",
  "  memcpy(buf->data + buf->len, ptr, total);",
  "  buf->len += total;",
  "  buf->data[buf->len] = '\\0';",
  "  return total;",
  "}",
  "",
  "static char *pya_mind_http_post(const char *url, const char *body) {",
  "  CURL *curl = curl_easy_init();",
  "  if (!curl) return NULL;",
  "  struct curl_slist *headers = NULL;",
  "  headers = curl_slist_append(headers, \"Content-Type: application/json\");",
  "  pya_buf response;",
  "  pya_buf_init(&response);",
  "  curl_easy_setopt(curl, CURLOPT_URL, url);",
  "  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);",
  "  curl_easy_setopt(curl, CURLOPT_POST, 1L);",
  "  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body ? body : \"{}\");",
  "  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, pya_curl_write);",
  "  curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);",
  "  CURLcode res = curl_easy_perform(curl);",
  "  curl_slist_free_all(headers);",
  "  curl_easy_cleanup(curl);",
  "  if (res != CURLE_OK) {",
  "    if (response.data) free(response.data);",
  "    return NULL;",
  "  }",
  "  return pya_buf_take(&response);",
  "}",
  "",
  "typedef char *(*pya_tool_dispatch_fn)(const char *tool_name, const char *args_json);",
  "",
  "static char *pya_tool_block_from_map(pya_map *map) {",
  "  if (!map || map->length == 0) return NULL;",
  "  pya_map_entry **sorted = (pya_map_entry **)malloc(sizeof(pya_map_entry *) * map->length);",
  "  if (!sorted) return NULL;",
  "  for (int i = 0; i < map->length; i++) sorted[i] = &map->entries[i];",
  "  qsort(sorted, map->length, sizeof(pya_map_entry *), map_entry_compare);",
  "  pya_buf buf; pya_buf_init(&buf);",
  "  pya_buf_append(&buf, \"TOOLS:\\n\");",
  "  int added = 0;",
  "  for (int i = 0; i < map->length; i++) {",
  "    const pya_map_entry *entry = sorted[i];",
  "    if (!entry || entry->kind != PYA_MAP_SENTENCE) continue;",
  "    if (!entry->text || entry->text[0] == '\\0') continue;",
  "    pya_buf_append(&buf, entry->text);",
  "    pya_buf_append(&buf, \"\\n\");",
  "    added = 1;",
  "  }",
  "  free(sorted);",
  "  if (!added) {",
  "    if (buf.data) free(buf.data);",
  "    return NULL;",
  "  }",
  "  return pya_buf_take(&buf);",
  "}",
  "",
  "static char *pya_mind_invoke(const char *mind, const char *dialogue, const char *user_text, const char *tool_block, const char *tool_json, pya_tool_dispatch_fn tool_dispatch, const char *model_override, int window_override, int *out_count) {",
  "  const char *mock = getenv(\"PYA_MIND_RESPONSE\");",
  "  if (mock) {",
    "    int count = pya_mind_next_count(dialogue);",
    "    if (out_count) *out_count = count;",
    "    pya_mind_record(dialogue, \"user\", user_text ? user_text : \"\", window_override > 0 ? window_override : 8);",
    "    pya_mind_record(dialogue, \"assistant\", mock, window_override > 0 ? window_override : 8);",
    "    return pya_strdup(mock);",
  "  }",
  "  pya_mind_config *cfg = pya_mind_get_config(mind);",
  "  const char *host = cfg && cfg->space ? cfg->space : getenv(\"OLLAMA_HOST\");",
  "  if (!host) host = \"http://localhost:11434\";",
  "  const char *model = model_override ? model_override : (cfg && cfg->model ? cfg->model : \"qwen3-vl:8b-instruct\");",
  "  int window = window_override > 0 ? window_override : (cfg && cfg->window > 0 ? cfg->window : 8);",
  "  const char *prompt = cfg && cfg->prompt ? cfg->prompt : NULL;",
  "  cJSON *messages = cJSON_CreateArray();",
  "  if (prompt) {",
    "    cJSON *msg = cJSON_CreateObject();",
    "    cJSON_AddStringToObject(msg, \"role\", \"system\");",
    "    cJSON_AddStringToObject(msg, \"content\", prompt);",
    "    cJSON_AddItemToArray(messages, msg);",
  "  }",
  "  if (tool_block) {",
    "    cJSON *msg = cJSON_CreateObject();",
  "    cJSON_AddStringToObject(msg, \"role\", \"system\");",
  "    cJSON_AddStringToObject(msg, \"content\", tool_block);",
  "    cJSON_AddItemToArray(messages, msg);",
  "  }",
  "  pya_mind_history *hist = pya_mind_get_history(dialogue);",
  "  if (hist) {",
  "    for (size_t i = 0; i < hist->len; i++) {",
  "      cJSON *msg = cJSON_CreateObject();",
  "      cJSON_AddStringToObject(msg, \"role\", hist->items[i].role ? hist->items[i].role : \"user\");",
  "      cJSON_AddStringToObject(msg, \"content\", hist->items[i].content ? hist->items[i].content : \"\");",
  "      cJSON_AddItemToArray(messages, msg);",
  "    }",
  "  }",
  "  cJSON *user = cJSON_CreateObject();",
  "  cJSON_AddStringToObject(user, \"role\", \"user\");",
  "  cJSON_AddStringToObject(user, \"content\", user_text ? user_text : \"\");",
  "  cJSON_AddItemToArray(messages, user);",
  "  int turns = 0;",
  "  char *out = NULL;",
  "  while (turns < 6) {",
  "    turns += 1;",
  "    cJSON *root = cJSON_CreateObject();",
  "    cJSON_AddStringToObject(root, \"model\", model);",
  "    cJSON_AddItemToObject(root, \"messages\", cJSON_Duplicate(messages, 1));",
  "    if (tool_json) {",
  "      cJSON *tools = cJSON_Parse(tool_json);",
  "      if (tools && cJSON_IsArray(tools)) {",
  "        cJSON_AddItemToObject(root, \"tools\", tools);",
  "      } else if (tools) {",
  "        cJSON_Delete(tools);",
  "      }",
  "    }",
  "    cJSON_AddBoolToObject(root, \"stream\", 0);",
  "    char *payload = cJSON_PrintUnformatted(root);",
  "    char *pretty = cJSON_Print(root);",
  "    cJSON_Delete(root);",
  "    if (!payload) { if (pretty) free(pretty); break; }",
  "    pya_record_mind_json(mind, \"request\", pretty ? pretty : payload);",
  "    if (pretty) free(pretty);",
  "    pya_buf url; pya_buf_init(&url);",
  "    pya_buf_append(&url, host);",
  "    if (url.len > 0 && url.data[url.len - 1] == '/') url.data[url.len - 1] = '\\0';",
  "    pya_buf_append(&url, \"/api/chat\");",
  "    char *resp = pya_mind_http_post(url.data, payload);",
  "    free(payload);",
  "    if (url.data) free(url.data);",
  "    if (!resp) {",
  "      char err[PYA_TEXT_CAP];",
  "      snprintf(err, sizeof(err), \"su name mind defective ob text \\\"mind defective: request failed\\\" from name mind be error ya\");",
  "      pya_emit_exchange(err);",
  "      fprintf(stderr, \"%s\\n\", \"mind defective: request failed\");",
  "      exit(1);",
  "    }",
  "    cJSON *respJson = cJSON_Parse(resp);",
  "    if (respJson) {",
    "      cJSON_DeleteItemFromObjectCaseSensitive(respJson, \"context\");",
    "      char *respPretty = cJSON_Print(respJson);",
    "      if (respPretty) {",
      "        pya_record_mind_json(mind, \"response\", respPretty);",
      "        free(respPretty);",
    "      } else {",
      "        pya_record_mind_json(mind, \"response\", resp);",
    "      }",
  "    } else {",
  "      pya_record_mind_json(mind, \"response\", resp);",
  "    }",
  "    cJSON *message = respJson ? cJSON_GetObjectItemCaseSensitive(respJson, \"message\") : NULL;",
  "    cJSON *toolCalls = message ? cJSON_GetObjectItemCaseSensitive(message, \"tool_calls\") : NULL;",
  "    if (toolCalls && cJSON_IsArray(toolCalls) && cJSON_GetArraySize(toolCalls) > 0) {",
  "      if (!tool_dispatch) {",
  "        char err[PYA_TEXT_CAP];",
  "        snprintf(err, sizeof(err), \"su name tool defective ob text \\\"tool defective: missing dispatcher\\\" from name mind be error ya\");",
  "        pya_emit_exchange(err);",
  "        fprintf(stderr, \"%s\\n\", \"tool defective: missing dispatcher\");",
  "        exit(1);",
  "      }",
  "      cJSON *assistant = cJSON_CreateObject();",
  "      cJSON_AddStringToObject(assistant, \"role\", \"assistant\");",
  "      cJSON *content = message ? cJSON_GetObjectItemCaseSensitive(message, \"content\") : NULL;",
  "      cJSON_AddStringToObject(assistant, \"content\", (content && cJSON_IsString(content)) ? content->valuestring : \"\");",
  "      cJSON_AddItemToObject(assistant, \"tool_calls\", cJSON_Duplicate(toolCalls, 1));",
  "      cJSON_AddItemToArray(messages, assistant);",
  "      int tcCount = cJSON_GetArraySize(toolCalls);",
  "      for (int i = 0; i < tcCount; i++) {",
  "        cJSON *call = cJSON_GetArrayItem(toolCalls, i);",
  "        cJSON *fn = call ? cJSON_GetObjectItemCaseSensitive(call, \"function\") : NULL;",
  "        cJSON *name = fn ? cJSON_GetObjectItemCaseSensitive(fn, \"name\") : NULL;",
  "        if (!name) name = call ? cJSON_GetObjectItemCaseSensitive(call, \"name\") : NULL;",
  "        const char *toolName = (name && cJSON_IsString(name)) ? name->valuestring : NULL;",
  "        cJSON *callId = cJSON_GetObjectItemCaseSensitive(call, \"id\");",
  "        const char *toolCallId = (callId && cJSON_IsString(callId)) ? callId->valuestring : NULL;",
  "        cJSON *argsNode = fn ? cJSON_GetObjectItemCaseSensitive(fn, \"arguments\") : NULL;",
  "        if (!argsNode) argsNode = call ? cJSON_GetObjectItemCaseSensitive(call, \"arguments\") : NULL;",
  "        char *argsText = NULL;",
  "        if (argsNode && cJSON_IsString(argsNode)) argsText = pya_strdup(argsNode->valuestring);",
  "        else if (argsNode) argsText = cJSON_PrintUnformatted(argsNode);",
  "        char *toolResult = toolName ? tool_dispatch(toolName, argsText ? argsText : \"\") : NULL;",
  "        if (argsText) free(argsText);",
  "        if (!toolResult) {",
  "          if (respJson) cJSON_Delete(respJson);",
  "          free(resp);",
  "          char err[PYA_TEXT_CAP];",
  "          snprintf(err, sizeof(err), \"su name tool defective ob text \\\"tool defective: unknown tool\\\" from name mind be error ya\");",
  "          pya_emit_exchange(err);",
  "          fprintf(stderr, \"%s\\n\", \"tool defective: unknown tool\");",
  "          exit(1);",
  "        }",
  "        cJSON *toolMsg = cJSON_CreateObject();",
  "        cJSON_AddStringToObject(toolMsg, \"role\", \"tool\");",
  "        if (toolCallId && toolCallId[0]) {",
  "          cJSON_AddStringToObject(toolMsg, \"tool_call_id\", toolCallId);",
  "        }",
  "        cJSON_AddStringToObject(toolMsg, \"tool_name\", toolName ? toolName : \"\");",
  "        cJSON_AddStringToObject(toolMsg, \"content\", toolResult);",
  "        cJSON_AddItemToArray(messages, toolMsg);",
  "        free(toolResult);",
  "      }",
  "      if (respJson) cJSON_Delete(respJson);",
  "      free(resp);",
  "      continue;",
  "    }",
  "    if (message) {",
  "      cJSON *content = cJSON_GetObjectItemCaseSensitive(message, \"content\");",
  "      if (content && cJSON_IsString(content)) out = pya_strdup(content->valuestring);",
  "    }",
  "    if (!out && respJson) {",
  "      cJSON *content = cJSON_GetObjectItemCaseSensitive(respJson, \"response\");",
  "      if (!content) content = cJSON_GetObjectItemCaseSensitive(respJson, \"output\");",
  "      if (content && cJSON_IsString(content)) out = pya_strdup(content->valuestring);",
  "    }",
  "    if (respJson) cJSON_Delete(respJson);",
  "    free(resp);",
  "    break;",
  "  }",
  "  if (!out) out = pya_strdup(\"\");",
  "  cJSON_Delete(messages);",
  "  int count = pya_mind_next_count(dialogue);",
  "  if (out_count) *out_count = count;",
  "  pya_mind_record(dialogue, \"user\", user_text ? user_text : \"\", window);",
  "  pya_mind_record(dialogue, \"assistant\", out, window);",
  "  return out;",
  "}"
].join("\n");
