export const VECTOR_TYPE_DECL = "typedef struct { const char *type; int length; double *num_values; const char **text_values; } pya_vec;";

export const VECTOR_PRINT_HELPER = [
  "static int is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void print_vec_inline(const pya_vec *vec) {",
  "  if (!vec) { printf(\"ve num\"); return; }",
  "  const char *type = vec->type ? vec->type : \"num\";",
  "  printf(\"ve %s\", type);",
  "  if (strcmp(type, \"bool\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      printf(\" %s\", vec->num_values[i] != 0 ? \"truth\" : \"lie\");",
  "    }",
  "    return;",
  "  }",
  "  if (strcmp(type, \"text\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      const char *val = vec->text_values[i];",
  "      if (is_safe_token(val)) {",
  "        printf(\" %s\", val);",
  "      } else {",
  "        printf(\" \\\"\");",
  "        print_escaped(val);",
  "        printf(\"\\\"\");",
  "      }",
  "    }",
  "    return;",
  "  }",
  "  for (int i = 0; i < vec->length; i++) { printf(\" %g\", vec->num_values[i]); }",
  "}",
  "static void print_vec(const pya_vec *vec) {",
  "  print_vec_inline(vec);",
  "  printf(\"\\n\");",
  "}",
  "static void print_vec_sentence(const char *name, const pya_vec *vec) {",
  "  printf(\"su name %s ob \", name ? name : \"\");",
  "  print_vec_inline(vec);",
  "  printf(\" be vector ya\\n\");",
  "}"
].join("\n");
