function mindHelperSource() {
  return `async function callMind({ host, model, messages = [], tools, numCtx = 8192 }) {\n  if (typeof process !== \"undefined\" && process.env?.PYA_MIND_RESPONSE) {\n    const raw = process.env.PYA_MIND_RESPONSE;\n    try {\n      return JSON.parse(raw);\n    } catch {\n      return { message: { content: String(raw ?? \"\") } };\n    }\n  }\n  const transport = globalThis?.ollamaChat;\n  if (typeof transport === \"function\") {\n    const res = await Promise.resolve(transport({ host, model, messages, tools, numCtx }));\n    if (res && typeof res === \"object\") {\n      return res;\n    }\n    return { message: { content: String(res ?? \"\") } };\n  }\n  if (typeof fetch !== \"function\") {\n    throw new Error(\"mind: provide globalThis.ollamaChat or fetch\");\n  }\n  const resp = await fetch(String(host).replace(/\\/$/, \"\") + \"/api/chat\", {\n    method: \"POST\",\n    headers: { \"Content-Type\": \"application/json\" },\n    body: JSON.stringify({ model, messages, tools, options: { num_ctx: numCtx }, stream: false })\n  });\n  const data = await (typeof resp.json === \"function\" ? resp.json() : Promise.resolve({ message: { content: String(resp) } }));\n  return data && typeof data === \"object\" ? data : { message: { content: String(data ?? \"\") } };\n}`;
}

function mindHistorySource() {
  return `const mindHistory = new Map();\nfunction buildMindHistory(dialogue, windowSize = 8) {\n  const arr = mindHistory.get(dialogue) || [];\n  if (windowSize <= 0) return [];\n  const max = windowSize * 2;\n  return arr.slice(-max);\n}\nfunction recordMindTurn(dialogue, userMsg, assistantMsg, windowSize = 8) {\n  const arr = mindHistory.get(dialogue) || [];\n  if (userMsg) arr.push(userMsg);\n  if (assistantMsg) arr.push(assistantMsg);\n  if (windowSize <= 0) {\n    mindHistory.set(dialogue, []);\n    return;\n  }\n  const max = windowSize * 2;\n  const trimmed = arr.slice(-max);\n  mindHistory.set(dialogue, trimmed);\n}`;
}

export { mindHelperSource, mindHistorySource };
