import fs from "node:fs/promises";
import path from "node:path";

const rootDir = path.resolve(new URL("../..", import.meta.url).pathname);
const configPath = path.join(rootDir, "configure", "workplace.pya");
const overridePath = path.join(rootDir, "container", "building", "compose.override.yaml");

function parseWorkplace(text) {
  const out = new Map();
  const lines = text.split("\n");
  for (const line of lines) {
    const textMatch = line.match(/^\s*su name ([^ ]+) ob text "([^"]*)" ya\s*$/);
    if (textMatch) {
      out.set(textMatch[1], textMatch[2]);
      continue;
    }
    const boolMatch = line.match(/^\s*su name ([^ ]+) ob bool (truth|lie) ya\s*$/);
    if (boolMatch) {
      out.set(boolMatch[1], boolMatch[2]);
      continue;
    }
  }
  return out;
}

async function loadWorkplace() {
  try {
    const text = await fs.readFile(configPath, "utf8");
    return parseWorkplace(text);
  } catch {
    return new Map();
  }
}

function yamlList(items, indent = "    ") {
  if (!items.length) return [];
  return items.map(item => `${indent}- ${item}`);
}

function yamlKeyValue(key, value, indent = "    ") {
  return `${indent}${key}: ${value}`;
}

function quote(value) {
  if (typeof value !== "string") return value;
  if (/^[A-Za-z0-9_./:$-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

const workplace = await loadWorkplace();
const gpuEnabled = (workplace.get("gpu enabled") ?? "lie") === "truth";
const audioEnabled = (workplace.get("audio enabled") ?? "lie") === "truth";
const envVncEnabled = process.env.PYASH_VNC_ENABLED;
const vncEnabled = ((envVncEnabled ?? workplace.get("vnc enabled") ?? "lie") === "truth");

const pulseDir = process.env.PYASH_PULSE_DIR;
const pulseCookie = process.env.PYASH_PULSE_COOKIE;
const sshDir = process.env.PYASH_SSH_DIR;
const sshKnownHosts = process.env.PYASH_SSH_KNOWN_HOSTS;
const containerHome = process.env.PYASH_CONTAINER_HOME || "/workplace";
const containerHomeDir = process.env.PYASH_CONTAINER_HOME_DIR;

const lines = [
  "# Generated by container/update_compose.mjs",
  "services:",
  "  pyash:",
  yamlKeyValue("user", quote("${PYASH_UID}:${PYASH_GID}"), "    "),
  "    environment:",
  `      - HOME=${quote(containerHome)}`,
  `      - NPM_CONFIG_PREFIX=${quote(`${containerHome}/.npm-global`)}`,
  `      - PATH=${quote(`${containerHome}/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`)}`
];
const codexDir = process.env.PYASH_CODEX_DIR;
const gitConfig = process.env.PYASH_GITCONFIG;
const gitConfigXdg = process.env.PYASH_GITCONFIG_XDG;
const hostTz = process.env.PYASH_TZ;

const volumes = [];
const devices = [];
const ports = [];

if (containerHomeDir) {
  try {
    await fs.mkdir(containerHomeDir, { recursive: true });
    volumes.push(`${"${PYASH_CONTAINER_HOME_DIR}"}:${quote(containerHome)}`);
  } catch {}
}

if (audioEnabled && pulseDir && pulseCookie) {
  try {
    await fs.stat(pulseDir);
    await fs.stat(pulseCookie);
    lines.push(`      - XDG_CONFIG_HOME=${quote(`${containerHome}/.config`)}`);
    lines.push(`      - PULSE_SERVER=unix:${"${PYASH_PULSE_DIR}"}/pulse/native`);
    volumes.push(`${"${PYASH_PULSE_DIR}"}:${"${PYASH_PULSE_DIR}"}`);
    volumes.push(`${"${PYASH_PULSE_COOKIE}"}:${quote(`${containerHome}/.config/pulse/cookie`)}`);
    devices.push("/dev/snd:/dev/snd");
  } catch {}
}

if (sshDir) {
  try {
    await fs.stat(sshDir);
    volumes.push(`${"${PYASH_SSH_DIR}"}:${quote(`${containerHome}/.ssh`)}:ro`);
  } catch {}
}

if (sshKnownHosts) {
  try {
    await fs.stat(sshKnownHosts);
    volumes.push(
      `${"${PYASH_SSH_KNOWN_HOSTS}"}:${quote(`${containerHome}/.ssh/known_hosts`)}`
    );
  } catch {}
}

if (codexDir) {
  try {
    await fs.stat(codexDir);
    volumes.push(`${"${PYASH_CODEX_DIR}"}:${quote(`${containerHome}/.codex`)}`);
    lines.push(`      - CODEX_HOME=${quote(`${containerHome}/.codex`)}`);
  } catch {}
}

if (gitConfig) {
  try {
    await fs.stat(gitConfig);
    volumes.push(`${"${PYASH_GITCONFIG}"}:${quote(`${containerHome}/.gitconfig`)}:ro`);
  } catch {}
}

if (gitConfigXdg) {
  try {
    await fs.stat(gitConfigXdg);
    volumes.push(`${"${PYASH_GITCONFIG_XDG}"}:${quote(`${containerHome}/.config/git/config`)}:ro`);
  } catch {}
}

if (hostTz) {
  lines.push(`      - TZ=${quote(hostTz)}`);
  try {
    await fs.stat("/etc/localtime");
    volumes.push("/etc/localtime:/etc/localtime:ro");
  } catch {}
  try {
    await fs.stat("/etc/timezone");
    volumes.push("/etc/timezone:/etc/timezone:ro");
  } catch {}
}

try {
  await fs.stat("/etc/passwd");
  volumes.push("/etc/passwd:/etc/passwd:ro");
} catch {}

try {
  await fs.stat("/etc/group");
  volumes.push("/etc/group:/etc/group:ro");
} catch {}

lines.push(`      - GIT_SSH_COMMAND=ssh -i ${containerHome}/.ssh/id_ed25519 -o IdentitiesOnly=yes -o UserKnownHostsFile=${containerHome}/.ssh/known_hosts -o StrictHostKeyChecking=yes`);

if (vncEnabled) {
  ports.push("\"5900:5900\"");
  ports.push("\"6080:6080\"");
  lines.push("    command: [\"/workplace/container/command/run_vnc_novnc.sh\"]");
}

if (gpuEnabled) {
  lines.push("    device_requests:");
  lines.push("      - driver: nvidia");
  lines.push("        count: all");
  lines.push("        capabilities: [gpu]");
}

if (ports.length) {
  lines.push("    ports:");
  lines.push(...yamlList(ports, "      "));
}

if (devices.length) {
  lines.push("    devices:");
  lines.push(...yamlList(devices, "      "));
}

if (volumes.length) {
  lines.push("    volumes:");
  lines.push(...yamlList(volumes.map(quote), "      "));
}

try {
  await fs.mkdir(path.dirname(overridePath), { recursive: true });
  await fs.writeFile(overridePath, `${lines.join("\n")}\n`, "utf8");
} catch (err) {
  console.error("compose override write failed: run ./introductory to bootstrap, or create container/building/");
  throw err;
}
