function exchangeRuntimeHelper() {
  return [
    "const PYA_NEWSPAPER_PREFIX = \"PYA_NEWSPAPER:\";",
    "function pyaNewspaperEnabled() {",
    "  return typeof process !== \"undefined\" && process?.env?.PYA_NEWSPAPER === \"1\";",
    "}",
    "function pyaEmitNewspaper(line) {",
    "  if (!pyaNewspaperEnabled() || !line) return;",
    "  const text = String(line);",
    "  const payload = text.includes(\"\\n\")",
    "    ? `${PYA_NEWSPAPER_PREFIX}BEGIN\\n${text}\\n${PYA_NEWSPAPER_PREFIX}END\\n`",
    "    : `${PYA_NEWSPAPER_PREFIX}${text}\\n`;",
    "  if (typeof process !== \"undefined\" && process.stdout && typeof process.stdout.write === \"function\") {",
    "    process.stdout.write(payload);",
    "  } else {",
    "    console.log(payload.trimEnd());",
    "  }",
    "}",
    "let pyaToolCounter = 0;",
    "function pyaNextToolEventId() {",
    "  pyaToolCounter += 1;",
    "  return String(pyaToolCounter).padStart(6, \"0\");",
    "}",
    "let pyaArtifactCounter = 0;",
    "const pyaArtifacts = new Map();",
    "const pyaArtifactHashes = new Map();",
    "function pyaExchangeEnabled() {",
    "  return pyaNewspaperEnabled();",
    "}",
    "function pyaNormalizeNewlines(text) {",
    "  return String(text ?? \"\").replace(/\\r\\n/g, \"\\n\").replace(/\\r/g, \"\\n\");",
    "}",
    "function pyaNormalizeLocator(locator) {",
    "  const text = String(locator ?? \"\");",
    "  if (/^[A-Za-z][A-Za-z0-9+.-]*:\\/\\//.test(text)) return text;",
    "  const runRoot = process.cwd();",
    "  const resolved = path.resolve(runRoot, text);",
    "  const relative = path.relative(runRoot, resolved);",
    "  if (relative.startsWith(\"..\") || path.isAbsolute(relative)) {",
    "    throw new Error(\"exchange defective\");",
    "  }",
    "  return relative.replace(/\\\\/g, \"/\");",
    "}",
    "function pyaEmitExchange(line) {",
    "  pyaEmitNewspaper(line);",
    "}",
    "function pyaArtifactExt(locator) {",
    "  try {",
    "    const url = new URL(locator);",
    "    return path.extname(url.pathname || \"\");",
    "  } catch {",
    "    return path.extname(locator);",
    "  }",
    "}",
    "function pyaContentAddressPath(hash, locator) {",
    "  const ext = pyaArtifactExt(locator);",
    "  const rel = path.join(\"artifacts\", \"sha256\", hash.slice(0, 2), hash.slice(2, 4), `${hash}${ext}`);",
    "  return rel.replace(/\\\\/g, \"/\");",
    "}",
    "function pyaWriteArtifactBytes(relPath, bytes) {",
    "  if (!relPath) return null;",
    "  const abs = path.resolve(process.cwd(), relPath);",
    "  fs.mkdirSync(path.dirname(abs), { recursive: true });",
    "  fs.writeFileSync(abs, bytes);",
    "  return abs;",
    "}",
    "function pyaLinkRunAlias(name, target) {",
    "  const runId = typeof process !== \"undefined\" ? process?.env?.PYA_RUN_ID : null;",
    "  if (!runId || !name || !target) return null;",
    "  const rel = path.join(\"artifacts\", runId, name).replace(/\\\\/g, \"/\");",
    "  const abs = path.resolve(process.cwd(), rel);",
    "  fs.mkdirSync(path.dirname(abs), { recursive: true });",
    "  if (!fs.existsSync(abs)) {",
    "    try {",
    "      fs.linkSync(target, abs);",
    "    } catch {",
    "      try {",
    "        fs.symlinkSync(target, abs);",
    "      } catch {}",
    "    }",
    "  }",
    "  return rel;",
    "}",
    "function pyaRecordArtifact(locator, bytes, op, sentenceId) {",
    "  if (!pyaExchangeEnabled()) return null;",
    "  const normalized = pyaNormalizeLocator(locator);",
    "  const existing = pyaArtifacts.get(normalized);",
    "  const hash = crypto.createHash(\"sha256\").update(bytes).digest(\"hex\");",
    "  const caRel = pyaContentAddressPath(hash, normalized);",
    "  const caAbs = pyaWriteArtifactBytes(caRel, bytes);",
    "  if (existing) {",
    "    const priorHash = pyaArtifactHashes.get(existing);",
    "    if (priorHash && priorHash !== hash) {",
    "      pyaEmitExchange(`exists su name hash inconsistency ob text \"hash inconsistency\" from name exchange be error ya`);",
    "      throw new Error(\"hash inconsistency\");",
    "    }",
    "    if (!priorHash) pyaArtifactHashes.set(existing, hash);",
    "    pyaLinkRunAlias(existing, caAbs);",
    "    if (op) pyaEmitExchange(`exists su name ${existing} as name ${op} from name exchange be exchange ya`);",
    "    return existing;",
    "  }",
    "  const name = `artifact-${pyaArtifactCounter++}`;",
    "  pyaArtifacts.set(normalized, name);",
    "  pyaArtifactHashes.set(name, hash);",
    "  const size = bytes?.length ?? 0;",
    "  const locatorText = JSON.stringify(normalized);",
    "  const obText = sentenceId ? `ob name ${sentenceId}` : `ob text ${locatorText}`;",
    "  pyaEmitExchange(`exists su name ${name} ${obText} to filename ${locatorText} accordingto name sha256 fromtext text \"${hash}\" by num ${size} from name exchange be artifact ya`);",
    "  pyaLinkRunAlias(name, caAbs);",
    "  if (op) {",
    "    pyaEmitExchange(`exists su name ${name} as name ${op} from name exchange be exchange ya`);",
    "  }",
    "  return name;",
    "}",
    "function pyaReadTextFile(filename, op, sentenceId) {",
    "  const buf = fs.readFileSync(filename);",
    "  pyaRecordArtifact(filename, buf, op, sentenceId);",
    "  return buf.toString(\"utf8\");",
    "}",
    "function pyaWriteTextFile(filename, text, op, sentenceId) {",
    "  const normalized = pyaNormalizeNewlines(text);",
    "  fs.writeFileSync(filename, normalized);",
    "  const buf = Buffer.from(String(normalized ?? \"\"), \"utf8\");",
    "  pyaRecordArtifact(filename, buf, op, sentenceId);",
    "}"
  ].join("\n");
}

export { exchangeRuntimeHelper };
