function jsonRuntimeHelper() {
  return [
    "function sanitizeNamePart(value) {",
    "  const raw = String(value ?? \"\").trim();",
    "  if (!raw) return \"item\";",
    "  const cleaned = raw.replace(/[^A-Za-z0-9_.-]+/g, \" \").replace(/\\s+/g, \" \").trim();",
    "  return cleaned || \"item\";",
    "}",
    "function uniqueName(base, used) {",
    "  if (!used.has(base)) { used.add(base); return base; }",
    "  let i = 2;",
    "  while (used.has(`${base} ${i}`)) i += 1;",
    "  const name = `${base} ${i}`;",
    "  used.add(name);",
    "  return name;",
    "}",
    "function vectorForScalarArray(values, type) {",
    "  if (type === \"bool\") return { ve: { type: \"bool\", values: values.map(v => (v ? \"truth\" : \"lie\")) } };",
    "  return { ve: { type, values } };",
    "}",
    "function jsonArrayToObj(values, { parentName, key, used, emitMap }) {",
    "  if (values.length === 0) return { ve: { type: \"hollow\", values: [] } };",
    "  const typeSet = new Set();",
    "  for (const value of values) {",
    "    if (value === null) typeSet.add(\"hollow\");",
    "    else if (Array.isArray(value)) typeSet.add(\"array\");",
    "    else if (typeof value === \"object\") typeSet.add(\"object\");",
    "    else if (typeof value === \"boolean\") typeSet.add(\"bool\");",
    "    else if (typeof value === \"number\") typeSet.add(\"num\");",
    "    else typeSet.add(\"text\");",
    "  }",
    "  if (typeSet.has(\"array\")) throw new Error(\"json map contents defective: nested arrays are unsupported\");",
    "  if (typeSet.has(\"hollow\")) throw new Error(\"json map contents defective: null elements are unsupported in arrays\");",
    "  if (typeSet.size > 1 && !(typeSet.size === 1 && typeSet.has(\"object\"))) {",
    "    throw new Error(\"json map contents defective: mixed array types are unsupported\");",
    "  }",
    "  if (typeSet.has(\"object\")) {",
    "    const names = values.map((value, idx) => {",
    "      const baseKey = sanitizeNamePart(key);",
    "      const base = `${parentName} ${baseKey} ${idx + 1}`;",
    "      const childName = uniqueName(base, used);",
    "      emitMap(value, childName);",
    "      return childName;",
    "    });",
    "    return { ve: { type: \"name\", values: names } };",
    "  }",
    "  if (typeSet.has(\"bool\")) return vectorForScalarArray(values, \"bool\");",
    "  if (typeSet.has(\"num\")) return vectorForScalarArray(values, \"num\");",
    "  return vectorForScalarArray(values, \"text\");",
    "}",
    "function jsonValueToObj(value, { parentName, key, used, emitMap }) {",
    "  if (value === null) return { hollow: true };",
    "  if (Array.isArray(value)) return jsonArrayToObj(value, { parentName, key, used, emitMap });",
    "  if (typeof value === \"string\") return { text: value };",
    "  if (typeof value === \"number\") return { num: value };",
    "  if (typeof value === \"boolean\") return { boolean: value };",
    "  if (typeof value === \"object\") {",
    "    const baseKey = sanitizeNamePart(key);",
    "    const base = `${parentName} ${baseKey}`;",
    "    const childName = uniqueName(base, used);",
    "    emitMap(value, childName);",
    "    return { name: childName };",
    "  }",
    "  return undefined;",
    "}",
    "function jsonToMapSentencesRuntime(value, rootName) {",
    "  const used = new Set();",
    "  const sentences = [];",
    "  const emitMap = (ob, name) => {",
    "    if (!ob || typeof ob !== \"object\" || Array.isArray(ob)) {",
    "      throw new Error(\"json map contents defective: object expected\");",
    "    }",
    "    const map = {};",
    "    const orderedKeys = Object.keys(ob).sort(compareUtf8);",
    "    for (const key of orderedKeys) {",
    "      const val = ob[key];",
    "      const objValue = jsonValueToObj(val, { parentName: name, key, used, emitMap });",
    "      if (objValue === undefined) continue;",
    "      map[key] = objValue;",
    "    }",
    "    sentences.push({ mood: \"ya\", su: { name }, be: \"json map\", ob: { map } });",
    "  };",
    "  const root = uniqueName(sanitizeNamePart(rootName), used);",
    "  emitMap(value, root);",
    "  return { rootName: root, sentences };",
    "}",
    "function jsonToPyashTextRuntime(value, rootName) {",
    "  const { sentences } = jsonToMapSentencesRuntime(value, rootName);",
    "  const blocks = sentences.map((sentence) => formatMapSentence(sentence.su?.name ?? \"map\", sentence));",
    "  return blocks.join(\"\\n\\n\") + \"\\n\";",
    "}",
    "function tokenizePyashLine(line) {",
    "  const tokens = [];",
    "  let i = 0;",
    "  while (i < line.length) {",
    "    while (i < line.length && /\\s/.test(line[i])) i += 1;",
    "    if (i >= line.length) break;",
    "    if (line[i] === '\"') {",
    "      i += 1;",
    "      let buf = \"\";",
    "      while (i < line.length && line[i] !== '\"') {",
    "        if (line[i] === '\\\\' && i + 1 < line.length) i += 1;",
    "        buf += line[i];",
    "        i += 1;",
    "      }",
    "      if (i < line.length && line[i] === '\"') i += 1;",
    "      tokens.push(buf);",
    "      continue;",
    "    }",
    "    let buf = \"\";",
    "    while (i < line.length && !/\\s/.test(line[i])) {",
    "      buf += line[i];",
    "      i += 1;",
    "    }",
    "    if (buf) tokens.push(buf);",
    "  }",
    "  return tokens;",
    "}",
    "function splitNameVectorTokens(tokens, knownNames) {",
    "  const names = [];",
    "  const maxWords = knownNames.maxWords || 1;",
    "  let i = 0;",
    "  while (i < tokens.length) {",
    "    let matched = null;",
    "    let matchedLen = 0;",
    "    for (let len = Math.min(maxWords, tokens.length - i); len >= 1; len -= 1) {",
    "      const candidate = tokens.slice(i, i + len).join(\" \");",
    "      if (knownNames.set.has(candidate)) {",
    "        matched = candidate;",
    "        matchedLen = len;",
    "        break;",
    "      }",
    "    }",
    "    if (matched) {",
    "      names.push(matched);",
    "      i += matchedLen;",
    "    } else {",
    "      names.push(tokens[i]);",
    "      i += 1;",
    "    }",
    "  }",
    "  return names;",
    "}",
    "function parsePyashValue(tokens, knownNames) {",
    "  if (!tokens.length) return undefined;",
    "  const [head, ...rest] = tokens;",
    "  if (head === \"num\") return { num: Number(rest[0] ?? 0) };",
    "  if (head === \"text\") return { text: rest[0] ?? \"\" };",
    "  if (head === \"bool\") return { boolean: rest[0] === \"truth\" };",
    "  if (head === \"hollow\") return { hollow: true };",
    "  if (head === \"unspecified\") return { unspecified: true };",
    "  if (head === \"name\") return { name: rest[0] ?? \"\" };",
    "  if (head === \"ve\" || head === \"vec\") {",
    "    let idx = 0;",
    "    let type = \"num\";",
    "    if ([\"num\", \"text\", \"bool\", \"name\", \"hollow\"].includes(rest[idx])) { type = rest[idx]; idx += 1; }",
    "    if (type === \"hollow\") return { ve: { type: \"hollow\", values: [] } };",
    "    const valueTokens = rest.slice(idx);",
    "    const values = (type === \"name\" && knownNames)",
    "      ? splitNameVectorTokens(valueTokens, knownNames)",
    "      : valueTokens.map((val) => {",
    "        if (type === \"num\") return Number(val ?? 0);",
    "        if (type === \"text\") return val ?? \"\";",
    "        if (type === \"bool\") return val === \"truth\";",
    "        if (type === \"name\") return val ?? \"\";",
    "        return val;",
    "      });",
    "    return { ve: { type, values } };",
    "  }",
    "  return undefined;",
    "}",
    "function parsePyashMapDefs(text) {",
    "  const maps = new Map();",
    "  const nameSet = new Set();",
    "  let maxWords = 1;",
    "  const lines = String(text ?? \"\").split(/\\n/);",
    "  for (const rawLine of lines) {",
    "    const line = rawLine.trim();",
    "    if (!line) continue;",
    "    const tokens = tokenizePyashLine(line);",
    "    if (!tokens.length) continue;",
    "    const mood = tokens[tokens.length - 1];",
    "    if (mood === \"def\" && tokens[0] === \"su\" && tokens[1] === \"name\") {",
    "      const beIdx = tokens.indexOf(\"be\");",
    "      if (beIdx > 2) {",
    "        const name = tokens.slice(2, beIdx).join(\" \");",
    "      nameSet.add(name);",
    "      const wordCount = name.split(\" \").length;",
    "      if (wordCount > maxWords) maxWords = wordCount;",
    "      }",
    "    }",
    "  }",
    "  const knownNames = { set: nameSet, maxWords };",
    "  let current = null;",
    "  for (const rawLine of lines) {",
    "    const line = rawLine.trim();",
    "    if (!line) continue;",
    "    const tokens = tokenizePyashLine(line);",
    "    if (!tokens.length) continue;",
    "    const mood = tokens[tokens.length - 1];",
    "    if (mood === \"def\" && tokens[0] === \"su\" && tokens[1] === \"name\") {",
    "      const beIdx = tokens.indexOf(\"be\");",
    "      const name = beIdx > 2 ? tokens.slice(2, beIdx).join(\" \") : tokens[2];",
    "      current = maps.get(name) ?? { name, entries: new Map() };",
    "      maps.set(name, current);",
    "      continue;",
    "    }",
    "    if (mood === \"prah\") {",
    "      current = null;",
    "      continue;",
    "    }",
    "    if (mood === \"ya\" && current && tokens[0] === \"su\" && tokens[1] === \"name\" && tokens[3] === \"ob\") {",
    "      const key = tokens[2];",
    "      const value = parsePyashValue(tokens.slice(4, -1), knownNames);",
    "      current.entries.set(key, value);",
    "    }",
    "  }",
    "  return maps;",
    "}",
    "function canonicalizeJsonValue(value) {",
    "  const encoder = typeof TextEncoder !== \"undefined\" ? new TextEncoder() : null;",
    "  const compareUtf8 = (a, b) => {",
    "    if (a === b) return 0;",
    "    const bufA = encoder ? encoder.encode(a) : Array.from(a, ch => ch.charCodeAt(0));",
    "    const bufB = encoder ? encoder.encode(b) : Array.from(b, ch => ch.charCodeAt(0));",
    "    const len = Math.min(bufA.length, bufB.length);",
    "    for (let i = 0; i < len; i += 1) {",
    "      if (bufA[i] !== bufB[i]) return bufA[i] < bufB[i] ? -1 : 1;",
    "    }",
    "    return bufA.length < bufB.length ? -1 : 1;",
    "  };",
    "  if (Array.isArray(value)) return value.map((item) => canonicalizeJsonValue(item));",
    "  if (value && typeof value === \"object\") {",
    "    const out = {};",
    "    const keys = Object.keys(value).sort(compareUtf8);",
    "    for (const key of keys) out[key] = canonicalizeJsonValue(value[key]);",
    "    return out;",
    "  }",
    "  return value;",
    "}",
    "function jsonFromPyashMap(name, maps, seen) {",
    "  if (seen.has(name)) throw new Error(\"json map export self referential\");",
    "  const map = maps.get(name);",
    "  if (!map) throw new Error(`json map referential defective: ${name}`);",
    "  seen.add(name);",
    "  const out = {};",
    "  for (const [key, value] of map.entries.entries()) {",
    "    if (!value || value.unspecified) continue;",
    "    let jsonValue;",
    "    if (value.hollow) jsonValue = null;",
    "    else if (value.text !== undefined) jsonValue = value.text;",
    "    else if (value.num !== undefined) jsonValue = value.num;",
    "    else if (value.boolean !== undefined) jsonValue = value.boolean;",
    "    else if (value.name) jsonValue = jsonFromPyashMap(value.name, maps, seen);",
    "    else if (value.ve) {",
    "      const type = value.ve.type || \"num\";",
    "      if (type === \"hollow\") jsonValue = [];",
    "      else if (type === \"name\") jsonValue = value.ve.values.map((child) => jsonFromPyashMap(child, maps, seen));",
    "      else if (type === \"bool\") jsonValue = value.ve.values.map((v) => v === \"truth\" || v === true || v === 1);",
    "      else jsonValue = value.ve.values;",
    "    } else if (value && Object.keys(value).length > 0) {",
    "      throw new Error(\"json map contents defective: unsupported contents\");",
    "    }",
    "    if (jsonValue !== undefined) out[key] = jsonValue;",
    "  }",
    "  seen.delete(name);",
    "  return out;",
    "}",
    "function pyashToJsonTextRuntime(text, rootName, mode = \"canonical\") {",
    "  const maps = parsePyashMapDefs(text);",
    "  const root = rootName || (maps.keys().next().value ?? \"data\");",
    "  const json = jsonFromPyashMap(root, maps, new Set());",
    "  if (mode === \"pretty\") return JSON.stringify(json, null, 2);",
    "  return JSON.stringify(canonicalizeJsonValue(json));",
    "}"
  ].join("\n");
}

export { jsonRuntimeHelper };
