export const EXCHANGE_HELPER_PART_03 = [
"      pya_exchange_fail(\"hash inconsistency\", \"hash inconsistency\");",
"    }",
"    if (!pya_artifacts[existing].has_hash) {",
"      strncpy(pya_artifacts[existing].hash, hash, sizeof(pya_artifacts[existing].hash) - 1);",
"      pya_artifacts[existing].hash[sizeof(pya_artifacts[existing].hash) - 1] = '\\0';",
"      pya_artifacts[existing].has_hash = 1;",
"    }",
"    pya_link_run_alias(pya_artifacts[existing].name, ca_abs);",
"    if (op) {",
"      char line2[PYA_TEXT_CAP];",
"      line2[0] = '\\0';",
"      pya_concat_buf(line2, \"exists su name \");",
"      pya_concat_buf(line2, pya_artifacts[existing].name);",
"      pya_concat_buf(line2, \" as name \");",
"      pya_concat_buf(line2, op);",
"      pya_concat_buf(line2, \" from name exchange be exchange ya\");",
"      pya_emit_exchange(line2);",
"    }",
"    return;",
"  }",
"  char name[64];",
"  snprintf(name, sizeof(name), \"artifact-%d\", pya_artifact_counter++);",
"  if (pya_artifact_count < 256) {",
"    strncpy(pya_artifacts[pya_artifact_count].locator, norm, sizeof(pya_artifacts[pya_artifact_count].locator) - 1);",
"    pya_artifacts[pya_artifact_count].locator[sizeof(pya_artifacts[pya_artifact_count].locator) - 1] = '\\0';",
"    strncpy(pya_artifacts[pya_artifact_count].name, name, sizeof(pya_artifacts[pya_artifact_count].name) - 1);",
"    pya_artifacts[pya_artifact_count].name[sizeof(pya_artifacts[pya_artifact_count].name) - 1] = '\\0';",
"    strncpy(pya_artifacts[pya_artifact_count].hash, hash, sizeof(pya_artifacts[pya_artifact_count].hash) - 1);",
"    pya_artifacts[pya_artifact_count].hash[sizeof(pya_artifacts[pya_artifact_count].hash) - 1] = '\\0';",
"    pya_artifacts[pya_artifact_count].has_hash = 1;",
"    pya_artifact_count += 1;",
"  }",
"  char line[PYA_TEXT_CAP];",
"  line[0] = '\\0';",
"  pya_concat_buf(line, \"exists su name \");",
"  pya_concat_buf(line, name);",
"  if (sentence_id && sentence_id[0]) {",
"    pya_concat_buf(line, \" ob name \");",
"    pya_concat_buf(line, sentence_id);",
"  } else {",
"    pya_concat_buf(line, \" ob text \\\"\");",
"    pya_concat_buf(line, escaped);",
"    pya_concat_buf(line, \"\\\"\");",
"  }",
"  pya_concat_buf(line, \" to filename \\\"\");",
"  pya_concat_buf(line, escaped);",
"  pya_concat_buf(line, \"\\\" accordingto name sha256 fromtext text \\\"\");",
"  pya_concat_buf(line, hash);",
"  pya_concat_buf(line, \"\\\" by num \");",
"  pya_concat_num_buf(line, (double)len);",
"  pya_concat_buf(line, \" from name exchange be artifact ya\");",
"  pya_emit_exchange(line);",
"  pya_link_run_alias(name, ca_abs);",
"  if (op) {",
"    char line2[PYA_TEXT_CAP];",
"    line2[0] = '\\0';",
"    pya_concat_buf(line2, \"exists su name \");",
"    pya_concat_buf(line2, name);",
"    pya_concat_buf(line2, \" as name \");",
"    pya_concat_buf(line2, op);",
"    pya_concat_buf(line2, \" from name exchange be exchange ya\");",
"    pya_emit_exchange(line2);",
"  }",
"}",
"",
"static void pya_exchange_record_file(const char *filename, const char *op, const char *sentence_id) {",
"  if (!filename) return;",
"  FILE *f = fopen(filename, \"rb\");",
"  if (!f) return;",
"  fseek(f, 0, SEEK_END);",
"  long size = ftell(f);",
"  if (size < 0) { fclose(f); return; }",
"  rewind(f);",
"  unsigned char *buf = (unsigned char *)malloc((size_t)size);",
"  if (!buf) { fclose(f); return; }",
"  size_t read = fread(buf, 1, (size_t)size, f);",
"  fclose(f);",
"  pya_exchange_record_bytes(filename, buf, read, op, sentence_id);",
"  free(buf);",
"}"
];
