export const EXCHANGE_HELPER_PART_01 = [
"static int pya_exchange_enabled() {",
"  const char *flag = getenv(\"PYA_NEWSPAPER\");",
"  return flag && strcmp(flag, \"1\") == 0;",
"}",
"",
"static int pya_tool_event_id = 0;",
"static int pya_next_tool_event_id() {",
"  pya_tool_event_id += 1;",
"  return pya_tool_event_id;",
"}",
"",
"static int pya_artifact_counter = 0;",
"",
"static void pya_escape_text(const char *text, char *out, size_t cap) {",
"  if (!out || cap == 0) return;",
"  size_t len = 0;",
"  for (const char *p = text ? text : \"\"; *p && len + 2 < cap; p++) {",
"    char ch = *p;",
"    if (ch == '\\\\' || ch == '\"') {",
"      out[len++] = '\\\\';",
"      out[len++] = ch;",
"    } else if (ch == '\\n') {",
"      out[len++] = '\\\\';",
"      out[len++] = 'n';",
"    } else {",
"      out[len++] = ch;",
"    }",
"  }",
"  out[len] = '\\0';",
"}",
"",
"static int pya_exchange_last_error = 0;",
"static char pya_exchange_last_error_line[PYA_TEXT_CAP];",
"static void pya_emit_exchange(const char *line) {",
"  if (!pya_exchange_enabled() || !line) return;",
"  if (strstr(line, \" be error ya\")) {",
"    pya_exchange_last_error = 1;",
"    snprintf(pya_exchange_last_error_line, sizeof(pya_exchange_last_error_line), \"%s\", line);",
"  }",
"  if (strchr(line, '\\n')) {",
"    printf(\"PYA_NEWSPAPER:BEGIN\\n\");",
"    printf(\"%s\\n\", line);",
"    printf(\"PYA_NEWSPAPER:END\\n\");",
"    return;",
"  }",
"  printf(\"PYA_NEWSPAPER:%s\\n\", line);",
"}",
"",
"static void pya_exchange_reset_error(void) {",
"  pya_exchange_last_error = 0;",
"  pya_exchange_last_error_line[0] = '\\0';",
"}",
"",
"static int pya_exchange_has_error(void) {",
"  return pya_exchange_last_error;",
"}",
"",
"static const char *pya_exchange_error_text(void) {",
"  return pya_exchange_last_error_line;",
"}",
"",
"typedef struct {",
"  char locator[PYA_TEXT_CAP];",
"  char name[64];",
"  char hash[65];",
"  int has_hash;",
"} pya_artifact_entry;",
"static pya_artifact_entry pya_artifacts[256];",
"static int pya_artifact_count = 0;",
"",
"static int pya_find_artifact(const char *locator) {",
"  for (int i = 0; i < pya_artifact_count; i++) {",
"    if (strcmp(pya_artifacts[i].locator, locator) == 0) return i;",
"  }",
"  return -1;",
"}",
"",
"static void pya_exchange_fail(const char *name, const char *message) {",
"  char line[PYA_TEXT_CAP];",
"  line[0] = '\\0';",
"  pya_concat_buf(line, \"exists su name \");",
"  pya_concat_buf(line, name);",
"  pya_concat_buf(line, \" ob text \\\"\");",
"  pya_concat_buf(line, message);",
"  pya_concat_buf(line, \"\\\" from name exchange be error ya\");",
"  pya_emit_exchange(line);",
"  fprintf(stderr, \"%s\\n\", message);",
"  exit(1);",
"}",
"",
"static int pya_normalize_relative(const char *input, char *out, size_t cap) {",
"  size_t len = 0;",
"  int depth = 0;",
"  size_t starts[256];",
"  size_t i = 0;",
"  if (!out || cap == 0) return 0;",
"  out[0] = '\\0';",
"  while (input && input[i]) {",
"    while (input[i] == '/' ) i++;",
"    size_t segStart = i;",
"    while (input[i] && input[i] != '/') i++;",
"    size_t segLen = i - segStart;",
"    if (segLen == 0) break;",
"    if (segLen == 1 && input[segStart] == '.') continue;",
"    if (segLen == 2 && input[segStart] == '.' && input[segStart + 1] == '.') {",
"      if (depth == 0) return 0;",
"      depth -= 1;",
"      len = starts[depth];",
"      if (len > 0 && out[len - 1] == '/') len -= 1;",
"      out[len] = '\\0';",
"      continue;",
"    }",
"    if (len > 0) {",
"      if (len + 1 >= cap) return 0;",
"      out[len++] = '/';",
"    }",
"    if (len + segLen >= cap) return 0;",
"    starts[depth++] = len;",
"    memcpy(out + len, input + segStart, segLen);",
"    len += segLen;",
"    out[len] = '\\0';",
"  }",
"  return 1;",
"}",
"",
"static int pya_normalize_locator(const char *locator, char *out, size_t cap) {",
"  if (!locator) return 0;",
"  if (strstr(locator, \"://\")) {",
"    snprintf(out, cap, \"%s\", locator);",
"    return 1;",
"  }",
"  char runRoot[PYA_TEXT_CAP];",
"  if (!getcwd(runRoot, sizeof(runRoot))) return 0;",
"  for (char *p = runRoot; *p; p++) { if (*p == '\\\\') *p = '/'; }",
"  char loc[PYA_TEXT_CAP];",
"  snprintf(loc, sizeof(loc), \"%s\", locator);",
"  for (char *p = loc; *p; p++) { if (*p == '\\\\') *p = '/'; }",
"  if (loc[0] == '/') {",
"    size_t rootLen = strlen(runRoot);",
"    if (strncmp(loc, runRoot, rootLen) != 0) return 0;",
"    const char *rel = loc + rootLen;",
"    if (*rel == '/') rel += 1;",
"    return pya_normalize_relative(rel, out, cap);",
"  }",
"  return pya_normalize_relative(loc, out, cap);",
"}",
"",
"static int pya_mkdir_recursive(const char *path) {",
"  char tmp[PYA_TEXT_CAP];",
"  size_t len = strlen(path);",
"  if (len >= sizeof(tmp)) return 0;",
"  snprintf(tmp, sizeof(tmp), \"%s\", path);",
"  for (size_t i = 1; i < len; i++) {",
"    if (tmp[i] == '/') {",
"      tmp[i] = '\\0';",
"      if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
"      tmp[i] = '/';",
"    }",
"  }",
"  if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
"  return 1;",
"}",
"",
"static void pya_artifact_ext(const char *locator, char *out, size_t cap) {",
"  if (!out || cap == 0) return;",
"  out[0] = '\\0';",
"  if (!locator) return;",
"  const char *lastSlash = strrchr(locator, '/');",
"  const char *lastDot = strrchr(locator, '.');",
"  if (!lastDot) return;",
"  if (lastSlash && lastDot < lastSlash) return;",
"  snprintf(out, cap, \"%s\", lastDot);",
"}",
"",
"static void pya_content_address_path(const char *hash, const char *locator, char *out, size_t cap) {",
"  if (!hash || strlen(hash) < 4) { if (out && cap) out[0] = '\\0'; return; }",
"  char ext[32];",
"  pya_artifact_ext(locator, ext, sizeof(ext));",
"  snprintf(out, cap, \"artifacts/sha256/%c%c/%c%c/%s%s\", hash[0], hash[1], hash[2], hash[3], hash, ext);",
"}"
];
