import { sentenceToPyash } from "../../../beautiful.mjs";
import { throwErrorSentence } from "../../../error.mjs";
import { deriveSignatureFromDefinition, joinSignatureWords } from "../../../bridge/signature.mjs";
import { handleCeremonyDefinition } from "./emit_ceremony_def.mjs";
import { handleMapDefinition } from "./emit_map_def.mjs";
import { jsonFromMapSentence, csvTextFromMapSentence, normalizeJsonMapError } from "./map_helpers.mjs";
import { canonicalJsonStringify, canonicalizeJsonValue } from "./parse_helpers.mjs";
import { markDeclared, sanitizeName } from "./util.mjs";
import { transpileSentence } from "./transpile_sentence.mjs";
import { handleRefineryDefinition } from "./transpile_program/refinery_defs.mjs";
import { emitRefineryC } from "./transpile_program/refinery_emit_c.mjs";
import { emitRefineryJs } from "./transpile_program/refinery_emit_js.mjs";
import { applyJsPrelude } from "./transpile_program/js_prelude.mjs";
import { applyCPrelude } from "./transpile_program/c_prelude.mjs";

export function transpileProgram(sentences, { lang, sourceLineNumbers, sourceFilename, collectSourceMap, retryConfig } = {}) {
  const header =
    lang === "c"
      ? "/* Generated by Pyash compile */"
      : "// Generated by Pyash compile";
  let lines = [header];
  const sourceLines = Array.isArray(sourceLineNumbers) ? sourceLineNumbers : [];
  const sourceLineFor = (idx) => sourceLines[idx] ?? null;
  const mainLines = [];
  let usesRememberShim = false;
  let usesMapShim = false;
  const rememberFlag = { used: false };
  const cHelpers = { usesPrintf: false, usesVectorType: false, usesVectorPrinter: false, usesString: false, usesCtype: false, usesStdlib: false, usesTextHelper: false, usesMap: false, usesMapPrinter: false, usesMapGlobals: false, usesJsonRuntime: false, usesYamlRuntime: false, usesYamlStringify: false, usesCsvRuntime: false, usesExchange: false, usesMindRuntime: false, usesCommand: false, usesCeremonyValue: false, usesDateMath: false };
  const loopShim = { used: false };
  const mindShim = { used: false };
  const jsHelpers = { usesVectorFormat: false, usesJsonMap: false, usesCsvMap: false, usesJsonRuntime: false, usesCsvRuntime: false, usesYamlRuntime: false, usesYamlStringify: false, usesFs: false, usesExchange: false, usesCommand: false, usesDateMath: false, usesInterpret: false, usesOs: false, usesPath: false, readCounter: 0 };
  const cState = { vectorCounter: 0, csvCounter: 0, fileCounter: 0, ceremonyCounter: 0, jsonMapStrings: new Map(), jsonMapPrettyStrings: new Map(), yamlMapStrings: new Map(), csvMapStrings: new Map(), preMain: [] };
  const mapDefs = new Map();
  const refineryDefs = new Map();
  const declared = new Set();
  const declaredTypes = new Map();
  const ceremonyFns = new Map();
  const ceremonyReturnTypes = new Map();
  const declaredVectorTypes = new Map();
  for (let i = 0; i < sentences.length; i++) {
    const sentence = sentences[i];
    const name = sentence?.su?.name;

    const refineryDef = handleRefineryDefinition({
      sentence,
      sentences,
      index: i,
      refineryDefs,
      throwErrorSentence
    });
    if (refineryDef) {
      i = refineryDef.endIndex;
      continue;
    }

    const ceremonyDef = handleCeremonyDefinition({
      sentence,
      sentences,
      index: i,
      lang,
      declared,
      declaredTypes,
      declaredVectorTypes,
      ceremonyFns,
      ceremonyReturnTypes,
      cHelpers,
      jsHelpers,
      cState
    }, {
      deriveSignatureFromDefinition,
      joinSignatureWords,
      sanitizeName,
      transpileSentence,
      throwErrorSentence
    });
    if (ceremonyDef) {
      if (ceremonyDef.usesRememberShim) {
        usesRememberShim = true;
      }
      if (ceremonyDef.usesMapShim) {
        usesMapShim = true;
        usesRememberShim = true;
      }
      if (collectSourceMap && sourceLineFor(i)) {
        lines.push(`// @pyash-line ${sourceLineFor(i)}`);
      }
      if (lang === "c" && sourceLineFor(i) && sourceFilename) {
        lines.push(`#line ${sourceLineFor(i)} "${sourceFilename}"`);
      }
      lines.push(ceremonyDef.fn);
      i = ceremonyDef.endIndex;
      continue;
    }

    const mapDef = handleMapDefinition({
      sentence,
      sentences,
      index: i,
      name,
      lang,
      collectSourceMap,
      sourceFilename,
      sourceLineFor,
      lines,
      mainLines,
      cHelpers,
      cState,
      mapDefs,
      declared,
      declaredTypes
    }, {
      throwErrorSentence,
      jsonFromMapSentence,
      canonicalJsonStringify,
      canonicalizeJsonValue,
      normalizeJsonMapError,
      csvTextFromMapSentence,
      sanitizeName,
      sentenceToPyash,
      markDeclared
    });
    if (mapDef) {
      i = mapDef.endIndex;
      continue;
    }

    if (sentence.mood === "ya" && name && !sentence.exists && !declared.has(name) && sentence.be !== "export") {
      const pyash = sentenceToPyash(sentence);
      throwErrorSentence({
        name: "variable as not exists",
        message: `su quoted.pyash.${pyash}.pyash.quoted be error ob name variable as not exists ya`,
        from: { name: "compile" },
        pyash,
        raw: sentence
      });
    }

    const line = transpileSentence(sentence, { lang, ceremonyFns, ceremonyReturnTypes, declared, declaredTypes, declaredVectorTypes, loopShim, mindShim, cHelpers, rememberFlag, jsHelpers, cState, mapDefs });
    if (typeof line === "string" && line.includes("remember(")) {
      usesRememberShim = true;
    }
    if (rememberFlag.used) {
      usesRememberShim = true;
      rememberFlag.used = false;
    }
    if (typeof line === "string" && line.includes("runAtAll(")) {
      usesMapShim = true;
      usesRememberShim = true;
    }
    const todoPrefix = lang === "c" ? "/* TODO" : "// TODO";
    const todoSuffix = lang === "c" ? " */" : "";
    const target = (() => {
      if (lang === "c" && sentence.mood === "ya") {
        if (typeof line === "string" && (line.startsWith("double ") || line.startsWith("const char") || line.startsWith("char *") || line.startsWith("char ") || line.startsWith("pya_vec "))) {
          return lines; // keep declarations global
        }
      }
      return lang === "c" ? mainLines : lines;
    })();
    const sourceLine = sourceLineFor(i);
    if (collectSourceMap && sourceLine) {
      target.push(`// @pyash-line ${sourceLine}`);
    }
    if (lang === "c" && sourceLine && sourceFilename) {
      target.push(`#line ${sourceLine} "${sourceFilename}"`);
    }
    target.push(line ?? `${todoPrefix}: ${JSON.stringify(sentence)}${todoSuffix}`);
    if (name && sentence.mood === "ya") {
      markDeclared(declared, name);
      if (sentence.be === "text" || sentence.ob?.text !== undefined) {
        declaredTypes.set(name, "text");
      } else if (sentence.be === "date" || sentence.ob?.date !== undefined) {
        declaredTypes.set(name, "date");
      } else if (sentence.be === "number" || sentence.ob?.num !== undefined) {
        declaredTypes.set(name, "number");
      } else if (sentence.ob?.la) {
        declaredTypes.set(name, "sentence");
      } else if (sentence.be === "vector" || sentence.ob?.ve) {
        declaredTypes.set(name, "vector");
        if (sentence.ob?.ve?.type) {
          declaredVectorTypes.set(name, sentence.ob.ve.type);
        }
      }
    }
  }

  const effectiveRetryConfig = {
    initialDelayMs: 250,
    backoff: 2,
    maxAttempts: 5,
    maxDelayMs: 8000,
    ...(retryConfig || {})
  };

  if (refineryDefs.size > 0) {
    if (lang === "c") {
      const refineryResult = emitRefineryC({
        refineryDefs,
        lang,
        ceremonyFns,
        declared,
        declaredTypes,
        declaredVectorTypes,
        loopShim,
        mindShim,
        cHelpers,
        rememberFlag,
        jsHelpers,
        cState,
        mapDefs,
        effectiveRetryConfig,
        transpileSentence,
        usesRememberShim,
        usesMapShim
      });
      lines.push(...refineryResult.lines);
      mainLines.push(...refineryResult.mainLines);
      usesRememberShim = refineryResult.usesRememberShim;
      usesMapShim = refineryResult.usesMapShim;
    } else {
      const refineryResult = emitRefineryJs({
        refineryDefs,
        lang,
        ceremonyFns,
        declared,
        declaredTypes,
        declaredVectorTypes,
        loopShim,
        mindShim,
        cHelpers,
        rememberFlag,
        jsHelpers,
        cState,
        mapDefs,
        effectiveRetryConfig,
        transpileSentence,
        usesRememberShim,
        usesMapShim
      });
      lines.push(...refineryResult.lines);
      usesRememberShim = refineryResult.usesRememberShim;
      usesMapShim = refineryResult.usesMapShim;
    }
  }

  if (lang !== "c") {
    lines = applyJsPrelude(lines, { jsHelpers, usesRememberShim, usesMapShim, mindShim, loopShim });
  }

  if (lang === "c") {
    lines = applyCPrelude(lines, { cHelpers, mainLines, cState });
  }

  return lines.join("\n") + "\n";
}
