export const JSON_PYASH_PART_01 = [
"typedef struct {",
"  char message[PYA_TEXT_CAP];",
"  int line;",
"  int column;",
"} pya_json_error;",
"",
"typedef struct {",
"  char **items;",
"  int length;",
"  int cap;",
"} pya_used_names;",
"",
"static char *pya_strdup(const char *s) {",
"  if (!s) return NULL;",
"  size_t len = strlen(s);",
"  char *out = (char *)malloc(len + 1);",
"  if (!out) return NULL;",
"  memcpy(out, s, len);",
"  out[len] = '\\0';",
"  return out;",
"}",
"",
"static void pya_used_init(pya_used_names *used) {",
"  if (!used) return;",
"  used->items = NULL;",
"  used->length = 0;",
"  used->cap = 0;",
"}",
"",
"static void pya_used_free(pya_used_names *used) {",
"  if (!used) return;",
"  for (int i = 0; i < used->length; i++) free(used->items[i]);",
"  free(used->items);",
"  used->items = NULL;",
"  used->length = 0;",
"  used->cap = 0;",
"}",
"",
"static int pya_used_has(const pya_used_names *used, const char *name) {",
"  if (!used || !name) return 0;",
"  for (int i = 0; i < used->length; i++) {",
"    if (used->items[i] && strcmp(used->items[i], name) == 0) return 1;",
"  }",
"  return 0;",
"}",
"",
"static void pya_used_add(pya_used_names *used, const char *name) {",
"  if (!used || !name) return;",
"  if (pya_used_has(used, name)) return;",
"  if (used->length >= used->cap) {",
"    int next = used->cap == 0 ? 8 : used->cap * 2;",
"    char **nextItems = (char **)realloc(used->items, sizeof(char *) * next);",
"    if (!nextItems) return;",
"    used->items = nextItems;",
"    used->cap = next;",
"  }",
"  used->items[used->length++] = pya_strdup(name);",
"}",
"",
"static void pya_used_remove(pya_used_names *used, const char *name) {",
"  if (!used || !name) return;",
"  for (int i = 0; i < used->length; i++) {",
"    if (used->items[i] && strcmp(used->items[i], name) == 0) {",
"      free(used->items[i]);",
"      for (int j = i + 1; j < used->length; j++) {",
"        used->items[j - 1] = used->items[j];",
"      }",
"      used->length -= 1;",
"      return;",
"    }",
"  }",
"}",
"",
"static void pya_sanitize_name_part(const char *raw, char *out, size_t cap) {",
"  if (!out || cap == 0) return;",
"  out[0] = '\\0';",
"  if (!raw) { snprintf(out, cap, \"item\"); return; }",
"  size_t len = strlen(raw);",
"  char buf[PYA_TEXT_CAP];",
"  size_t idx = 0;",
"  int lastSpace = 1;",
"  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
"    char ch = raw[i];",
"    int ok = (isalnum((unsigned char)ch) || ch == '_' || ch == '.' || ch == '-');",
"    if (ok) {",
"      buf[idx++] = ch;",
"      lastSpace = 0;",
"    } else if (!lastSpace) {",
"      buf[idx++] = ' ';",
"      lastSpace = 1;",
"    }",
"  }",
"  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
"  buf[idx] = '\\0';",
"  if (idx == 0) { snprintf(out, cap, \"item\"); return; }",
"  snprintf(out, cap, \"%s\", buf);",
"}",
"",
"static char *pya_unique_name(const char *base, pya_used_names *used) {",
"  if (!base || !used) return NULL;",
"  if (!pya_used_has(used, base)) {",
"    pya_used_add(used, base);",
"    return pya_strdup(base);",
"  }",
"  int i = 2;",
"  char candidate[PYA_TEXT_CAP];",
"  while (1) {",
"    snprintf(candidate, sizeof(candidate), \"%s %d\", base, i);",
"    if (!pya_used_has(used, candidate)) {",
"      pya_used_add(used, candidate);",
"      return pya_strdup(candidate);",
"    }",
"    i += 1;",
"  }",
"}",
"",
"static void pya_json_error_loc(const char *json, const char *pos, int *line, int *column) {",
"  int l = 1;",
"  int c = 1;",
"  if (!json || !pos || pos < json) {",
"    if (line) *line = l;",
"    if (column) *column = c;",
"    return;",
"  }",
"  for (const char *p = json; p < pos && *p; p++) {",
"    if (*p == '\\n') {",
"      l += 1;",
"      c = 1;",
"    } else {",
"      c += 1;",
"    }",
"  }",
"  if (line) *line = l;",
"  if (column) *column = c;",
"}",
"",
"static void pya_set_json_error(pya_json_error *err, const char *message, const char *json, const char *pos) {",
"  if (!err) return;",
"  snprintf(err->message, PYA_TEXT_CAP, \"%s\", message ? message : \"json map defective\");",
"  pya_json_error_loc(json, pos, &err->line, &err->column);",
"}",
"",
"static void pya_append_json_string(char *out, const char *text) {",
"  pya_concat_buf(out, \"\\\"\");",
"  if (text) {",
"    for (const char *p = text; *p; p++) {",
"      char ch = *p;",
"      if (ch == '\\\\' || ch == '\"') {",
"        char tmp[3] = { '\\\\', ch, '\\0' };",
"        pya_concat_buf(out, tmp);",
"      } else if (ch == '\\n') {",
"        pya_concat_buf(out, \"\\\\n\");",
"      } else {",
"        char tmp[2] = { ch, '\\0' };",
"        pya_concat_buf(out, tmp);",
"      }",
"    }",
"  }",
"  pya_concat_buf(out, \"\\\"\");",
"}",
"",
"static int pya_is_safe_token(const char *s) {",
"  if (!s || !*s) return 0;",
"  for (const char *p = s; *p; p++) {",
"    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
"  }",
"  return 1;",
"}",
"",
"static void pya_append_token(char *out, const char *token) {",
"  if (pya_is_safe_token(token)) {",
"    pya_concat_buf(out, token);",
"  } else {",
"    pya_append_json_string(out, token);",
"  }",
"}",
"",
"static int pya_read_file_text(const char *path, char *out) {",
"  if (!out || !path) return 0;",
"  FILE *f = fopen(path, \"r\");"
];
