export const JSON_PYASH_PART_04 = [
"  if (!storage || !items) { free(storage); free(items); return 0; }",
"  size_t count = 0;",
"  size_t pos = 0;",
"  size_t write = 0;",
"  while (pos < len) {",
"    while (pos < len && isspace((unsigned char)line[pos])) pos++;",
"    if (pos >= len) break;",
"    items[count++] = &storage[write];",
"    if (line[pos] == '\"') {",
"      pos++;",
"      while (pos < len && line[pos] != '\"') {",
"        if (line[pos] == '\\\\' && pos + 1 < len) pos++;",
"        storage[write++] = line[pos++];",
"      }",
"      if (pos < len && line[pos] == '\"') pos++;",
"    } else {",
"      while (pos < len && !isspace((unsigned char)line[pos])) {",
"        storage[write++] = line[pos++];",
"      }",
"    }",
"    storage[write++] = '\\0';",
"  }",
"  *tokensOut = items;",
"  *countOut = (int)count;",
"  return (int)write;",
"}",
"",
"static void pya_pyash_tokens_free(char **tokens, int count) {",
"  if (!tokens) return;",
"  if (count > 0) free(tokens[0]);",
"  free(tokens);",
"}",
"",
"static int pya_pyash_is_keyword(const char *token) {",
"  if (!token) return 0;",
"  return strcmp(token, \"su\") == 0",
"    || strcmp(token, \"ob\") == 0",
"    || strcmp(token, \"to\") == 0",
"    || strcmp(token, \"from\") == 0",
"    || strcmp(token, \"by\") == 0",
"    || strcmp(token, \"fromindex\") == 0",
"    || strcmp(token, \"toindex\") == 0",
"    || strcmp(token, \"atindex\") == 0",
"    || strcmp(token, \"be\") == 0",
"    || strcmp(token, \"then\") == 0",
"    || strcmp(token, \"ya\") == 0",
"    || strcmp(token, \"def\") == 0",
"    || strcmp(token, \"prah\") == 0",
"    || strcmp(token, \"do\") == 0;",
"}",
"",
"static int pya_pyash_parse_value(char **tokens, int count, int *idx, pya_pyash_value *out, const pya_name_list *known) {",
"  if (!tokens || !idx || !out || *idx >= count) return 0;",
"  const char *tok = tokens[*idx];",
"  if (!tok) return 0;",
"  if (strcmp(tok, \"num\") == 0) {",
"    if (*idx + 1 >= count) return 0;",
"    char *end = NULL;",
"    double val = strtod(tokens[*idx + 1], &end);",
"    if (!end || *end != '\\0') return 0;",
"    out->kind = PYA_PYASH_NUM;",
"    out->num = val;",
"    *idx += 2;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"text\") == 0) {",
"    if (*idx + 1 >= count) return 0;",
"    out->kind = PYA_PYASH_TEXT;",
"    out->text = pya_strdup(tokens[*idx + 1]);",
"    *idx += 2;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"bool\") == 0) {",
"    if (*idx + 1 >= count) return 0;",
"    out->kind = PYA_PYASH_BOOL;",
"    out->boolean = (strcmp(tokens[*idx + 1], \"truth\") == 0) ? 1 : 0;",
"    *idx += 2;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"hollow\") == 0) {",
"    out->kind = PYA_PYASH_HOLLOW;",
"    *idx += 1;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"unspecified\") == 0) {",
"    out->kind = PYA_PYASH_UNSPEC;",
"    *idx += 1;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"name\") == 0) {",
"    if (*idx + 1 >= count) return 0;",
"    out->kind = PYA_PYASH_NAME;",
"    out->name = pya_strdup(tokens[*idx + 1]);",
"    *idx += 2;",
"    return 1;",
"  }",
"  if (strcmp(tok, \"ve\") == 0 || strcmp(tok, \"vec\") == 0) {",
"    *idx += 1;",
"    const char *type = \"num\";",
"    if (*idx < count && strcmp(tokens[*idx], \"num\") == 0) { type = \"num\"; *idx += 1; }",
"    else if (*idx < count && strcmp(tokens[*idx], \"text\") == 0) { type = \"text\"; *idx += 1; }",
"    else if (*idx < count && strcmp(tokens[*idx], \"bool\") == 0) { type = \"bool\"; *idx += 1; }",
"    else if (*idx < count && strcmp(tokens[*idx], \"name\") == 0) { type = \"name\"; *idx += 1; }",
"    else if (*idx < count && strcmp(tokens[*idx], \"hollow\") == 0) {",
"      out->kind = PYA_PYASH_VECTOR;",
"      out->vec_type = pya_strdup(\"hollow\");",
"      out->vec_values = NULL;",
"      out->vec_len = 0;",
"      *idx += 1;",
"      return 1;",
"    }",
"    out->kind = PYA_PYASH_VECTOR;",
"    out->vec_type = pya_strdup(type);",
"    int cap = 0;",
"    int len = 0;",
"    pya_pyash_value *vals = NULL;",
"    while (*idx < count && !pya_pyash_is_keyword(tokens[*idx])) {",
"      if (len >= cap) {",
"        int next = cap == 0 ? 4 : cap * 2;",
"        pya_pyash_value *nextVals = (pya_pyash_value *)realloc(vals, sizeof(pya_pyash_value) * next);",
"        if (!nextVals) { free(vals); return 0; }",
"        vals = nextVals;",
"        cap = next;",
"      }",
"      memset(&vals[len], 0, sizeof(pya_pyash_value));",
"      if (strcmp(type, \"name\") == 0 && known) {",
"        int matchedLen = 0;",
"        char candidate[PYA_TEXT_CAP];",
"        for (int take = known->max_words; take >= 1; take--) {",
"          if (*idx + take > count) continue;",
"          candidate[0] = '\\0';",
"          for (int k = 0; k < take; k++) {",
"            if (k > 0) pya_concat_buf(candidate, \" \");",
"            pya_concat_buf(candidate, tokens[*idx + k]);",
"          }",
"          if (pya_name_list_has(known, candidate)) {",
"            matchedLen = take;",
"            break;",
"          }",
"        }",
"        if (matchedLen == 0) {",
"          matchedLen = 1;",
"          snprintf(candidate, sizeof(candidate), \"%s\", tokens[*idx]);",
"        }",
"        vals[len].kind = PYA_PYASH_NAME;",
"        vals[len].name = pya_strdup(candidate);",
"        *idx += matchedLen;",
"        len += 1;",
"        continue;",
"      }",
"      if (strcmp(type, \"num\") == 0) {",
"        char *end = NULL;",
"        double val = strtod(tokens[*idx], &end);",
"        if (!end || *end != '\\0') { free(vals); return 0; }",
"        vals[len].kind = PYA_PYASH_NUM;",
"        vals[len].num = val;",
"      } else if (strcmp(type, \"text\") == 0) {",
"        vals[len].kind = PYA_PYASH_TEXT;",
"        vals[len].text = pya_strdup(tokens[*idx]);",
"      } else if (strcmp(type, \"bool\") == 0) {",
"        vals[len].kind = PYA_PYASH_BOOL;",
"        vals[len].boolean = (strcmp(tokens[*idx], \"truth\") == 0) ? 1 : 0;",
"      } else if (strcmp(type, \"name\") == 0) {",
"        vals[len].kind = PYA_PYASH_NAME;",
"        vals[len].name = pya_strdup(tokens[*idx]);",
"      }",
"      len += 1;",
"      *idx += 1;",
"    }",
"    out->vec_values = vals;",
"    out->vec_len = len;",
"    return 1;",
"  }",
"  return 0;",
"}",
"",
"static int pya_pyash_add_entry(pya_pyash_map *map, const char *key, pya_pyash_value *value) {",
"  if (!map || !key || !value) return 0;",
"  if (map->length >= map->cap) {",
"    int next = map->cap == 0 ? 8 : map->cap * 2;"
];
