export const JSON_PYASH_PART_05 = [
"    pya_pyash_entry *nextEntries = (pya_pyash_entry *)realloc(map->entries, sizeof(pya_pyash_entry) * next);",
"    if (!nextEntries) return 0;",
"    map->entries = nextEntries;",
"    map->cap = next;",
"  }",
"  map->entries[map->length].key = pya_strdup(key);",
"  map->entries[map->length].value = *value;",
"  map->length += 1;",
"  return 1;",
"}",
"",
"static int pya_pyash_parse_maps(const char *pyash, pya_pyash_maps *defs, pya_json_error *err) {",
"  if (!pyash || !defs) return 0;",
"  pya_name_list known;",
"  pya_name_list_init(&known);",
"  const char *start = pyash;",
"  while (*start) {",
"    const char *end = strchr(start, '\\n');",
"    size_t len = end ? (size_t)(end - start) : strlen(start);",
"    if (len == 0) {",
"      if (!end) break;",
"      start = end + 1;",
"      continue;",
"    }",
"    char line[PYA_TEXT_CAP];",
"    if (len >= sizeof(line)) len = sizeof(line) - 1;",
"    memcpy(line, start, len);",
"    line[len] = '\\0';",
"    char **tokens = NULL;",
"    int count = 0;",
"    if (!pya_pyash_tokenize(line, &tokens, &count)) {",
"      pya_set_json_error(err, \"json map export failed: invalid pyash\", pyash, start);",
"      pya_name_list_free(&known);",
"      return 0;",
"    }",
"    if (count > 0) {",
"      const char *last = tokens[count - 1];",
"      if (strcmp(last, \"def\") == 0 && count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0) {",
"        int beIdx = -1;",
"        for (int i = 0; i < count; i++) {",
"          if (strcmp(tokens[i], \"be\") == 0) { beIdx = i; break; }",
"        }",
"        if (beIdx > 2) {",
"          char nameBuf[PYA_TEXT_CAP];",
"          nameBuf[0] = '\\0';",
"          for (int i = 2; i < beIdx; i++) {",
"            if (i > 2) pya_concat_buf(nameBuf, \" \");",
"            pya_concat_buf(nameBuf, tokens[i]);",
"          }",
"          pya_name_list_add(&known, nameBuf);",
"        } else if (count > 2) {",
"          pya_name_list_add(&known, tokens[2]);",
"        }",
"      }",
"    }",
"    pya_pyash_tokens_free(tokens, count);",
"    if (!end) break;",
"    start = end + 1;",
"  }",
"  pya_pyash_map *current = NULL;",
"  start = pyash;",
"  while (*start) {",
"    const char *end = strchr(start, '\\n');",
"    size_t len = end ? (size_t)(end - start) : strlen(start);",
"    if (len == 0) {",
"      if (!end) break;",
"      start = end + 1;",
"      continue;",
"    }",
"    char line[PYA_TEXT_CAP];",
"    if (len >= sizeof(line)) len = sizeof(line) - 1;",
"    memcpy(line, start, len);",
"    line[len] = '\\0';",
"    char **tokens = NULL;",
"    int count = 0;",
"    if (!pya_pyash_tokenize(line, &tokens, &count)) {",
"      pya_set_json_error(err, \"json map export failed: invalid pyash\", pyash, start);",
"      pya_name_list_free(&known);",
"      return 0;",
"    }",
"    if (count == 0) {",
"      pya_pyash_tokens_free(tokens, count);",
"      if (!end) break;",
"      start = end + 1;",
"      continue;",
"    }",
"    const char *last = tokens[count - 1];",
"    if (strcmp(last, \"def\") == 0) {",
"      if (count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0) {",
"        int beIdx = -1;",
"        for (int i = 0; i < count; i++) {",
"          if (strcmp(tokens[i], \"be\") == 0) { beIdx = i; break; }",
"        }",
"        char nameBuf[PYA_TEXT_CAP];",
"        if (beIdx > 2) {",
"          nameBuf[0] = '\\0';",
"          for (int i = 2; i < beIdx; i++) {",
"            if (i > 2) pya_concat_buf(nameBuf, \" \");",
"            pya_concat_buf(nameBuf, tokens[i]);",
"          }",
"        } else if (count > 2) {",
"          snprintf(nameBuf, sizeof(nameBuf), \"%s\", tokens[2]);",
"        } else {",
"          nameBuf[0] = '\\0';",
"        }",
"        if (nameBuf[0] != '\\0') current = pya_pyash_get_map(defs, nameBuf);",
"      }",
"      pya_pyash_tokens_free(tokens, count);",
"      if (!end) break;",
"      start = end + 1;",
"      continue;",
"    }",
"    if (strcmp(last, \"prah\") == 0) {",
"      current = NULL;",
"      pya_pyash_tokens_free(tokens, count);",
"      if (!end) break;",
"      start = end + 1;",
"      continue;",
"    }",
"    if (strcmp(last, \"ya\") == 0 && current) {",
"      if (count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0 && strcmp(tokens[3], \"ob\") == 0) {",
"        int idx = 4;",
"        pya_pyash_value value;",
"        memset(&value, 0, sizeof(value));",
"        if (!pya_pyash_parse_value(tokens, count - 1, &idx, &value, &known)) {",
"          pya_pyash_tokens_free(tokens, count);",
"          pya_set_json_error(err, \"json map contents defective: unsupported contents\", pyash, start);",
"          pya_name_list_free(&known);",
"          return 0;",
"        }",
"        if (!pya_pyash_add_entry(current, tokens[2], &value)) {",
"          pya_pyash_value_free(&value);",
"        }",
"      }",
"    }",
"    pya_pyash_tokens_free(tokens, count);",
"    if (!end) break;",
"    start = end + 1;",
"  }",
"  pya_name_list_free(&known);",
"  return 1;",
"}",
"",
"static int pya_compare_utf8(const void *a, const void *b) {",
"  const char *aa = *(const char **)a;",
"  const char *bb = *(const char **)b;",
"  if (!aa && !bb) return 0;",
"  if (!aa) return -1;",
"  if (!bb) return 1;",
"  const unsigned char *pa = (const unsigned char *)aa;",
"  const unsigned char *pb = (const unsigned char *)bb;",
"  while (*pa && *pb) {",
"    if (*pa != *pb) return *pa < *pb ? -1 : 1;",
"    pa++;",
"    pb++;",
"  }",
"  if (*pa == *pb) return 0;",
"  return *pa ? 1 : -1;",
"}",
"",
"static cJSON *pya_pyash_map_to_json(pya_pyash_maps *defs, const char *name, pya_used_names *seen, pya_json_error *err);",
"",
"static cJSON *pya_pyash_value_to_json(pya_pyash_maps *defs, const pya_pyash_value *value, pya_used_names *seen, pya_json_error *err) {",
"  if (!value) return NULL;",
"  if (value->kind == PYA_PYASH_UNSPEC) return NULL;",
"  if (value->kind == PYA_PYASH_HOLLOW) return cJSON_CreateNull();",
"  if (value->kind == PYA_PYASH_TEXT) return cJSON_CreateString(value->text ? value->text : \"\");",
"  if (value->kind == PYA_PYASH_NUM) return cJSON_CreateNumber(value->num);",
"  if (value->kind == PYA_PYASH_BOOL) return cJSON_CreateBool(value->boolean != 0);",
"  if (value->kind == PYA_PYASH_NAME) return pya_pyash_map_to_json(defs, value->name, seen, err);",
"  if (value->kind == PYA_PYASH_VECTOR) {",
"    if (!value->vec_type) return cJSON_CreateArray();",
"    if (strcmp(value->vec_type, \"hollow\") == 0) return cJSON_CreateArray();",
"    cJSON *arr = cJSON_CreateArray();",
"    for (int i = 0; i < value->vec_len; i++) {",
"      const pya_pyash_value *elem = &value->vec_values[i];",
"      cJSON *child = NULL;",
"      if (strcmp(value->vec_type, \"name\") == 0) {",
"        child = pya_pyash_map_to_json(defs, elem->name, seen, err);",
"      } else if (elem->kind == PYA_PYASH_NUM) {"
];
