export const JSON_PYASH_PART_03 = [
"static int pya_json_to_pyash(const char *jsonText, const char *rootName, char *out, pya_json_error *err) {",
"  if (!out) return 0;",
"  out[0] = '\\0';",
"  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
"  if (!jsonText) {",
"    pya_set_json_error(err, \"import: invalid json\", jsonText, jsonText);",
"    return 0;",
"  }",
"  const char *parseEnd = NULL;",
"  cJSON *root = cJSON_ParseWithOpts(jsonText, &parseEnd, 0);",
"  if (!root) {",
"    const char *errPtr = cJSON_GetErrorPtr();",
"    pya_set_json_error(err, \"import: invalid json\", jsonText, errPtr);",
"    return 0;",
"  }",
"  pya_used_names used;",
"  pya_used_init(&used);",
"  char clean[PYA_TEXT_CAP];",
"  pya_sanitize_name_part(rootName ? rootName : \"data\", clean, sizeof(clean));",
"  char *rootSafe = pya_unique_name(clean, &used);",
"  pya_emit_map(root, rootSafe ? rootSafe : \"data\", &used, out, err, jsonText);",
"  if (rootSafe) free(rootSafe);",
"  pya_used_free(&used);",
"  cJSON_Delete(root);",
"  if (err && err->message[0] != '\\0') return 0;",
"  return 1;",
"}",
"",
"typedef enum {",
"  PYA_PYASH_NUM = 0,",
"  PYA_PYASH_TEXT,",
"  PYA_PYASH_BOOL,",
"  PYA_PYASH_HOLLOW,",
"  PYA_PYASH_UNSPEC,",
"  PYA_PYASH_NAME,",
"  PYA_PYASH_VECTOR",
"} pya_pyash_kind;",
"",
"typedef struct pya_pyash_value pya_pyash_value;",
"",
"struct pya_pyash_value {",
"  pya_pyash_kind kind;",
"  double num;",
"  int boolean;",
"  char *text;",
"  char *name;",
"  char *vec_type;",
"  pya_pyash_value *vec_values;",
"  int vec_len;",
"};",
"",
"typedef struct {",
"  char *key;",
"  pya_pyash_value value;",
"} pya_pyash_entry;",
"",
"typedef struct {",
"  char *name;",
"  pya_pyash_entry *entries;",
"  int length;",
"  int cap;",
"} pya_pyash_map;",
"",
"typedef struct {",
"  pya_pyash_map *maps;",
"  int length;",
"  int cap;",
"} pya_pyash_maps;",
"",
"typedef struct {",
"  char **items;",
"  int length;",
"  int cap;",
"  int max_words;",
"} pya_name_list;",
"",
"static int pya_word_count(const char *name) {",
"  if (!name || !*name) return 0;",
"  int count = 1;",
"  for (const char *p = name; *p; p++) {",
"    if (*p == ' ') count += 1;",
"  }",
"  return count;",
"}",
"",
"static void pya_name_list_init(pya_name_list *list) {",
"  if (!list) return;",
"  list->items = NULL;",
"  list->length = 0;",
"  list->cap = 0;",
"  list->max_words = 1;",
"}",
"",
"static int pya_name_list_has(const pya_name_list *list, const char *name) {",
"  if (!list || !name) return 0;",
"  for (int i = 0; i < list->length; i++) {",
"    if (list->items[i] && strcmp(list->items[i], name) == 0) return 1;",
"  }",
"  return 0;",
"}",
"",
"static void pya_name_list_add(pya_name_list *list, const char *name) {",
"  if (!list || !name) return;",
"  if (pya_name_list_has(list, name)) return;",
"  if (list->length >= list->cap) {",
"    int next = list->cap == 0 ? 8 : list->cap * 2;",
"    char **nextItems = (char **)realloc(list->items, sizeof(char *) * next);",
"    if (!nextItems) return;",
"    list->items = nextItems;",
"    list->cap = next;",
"  }",
"  list->items[list->length++] = pya_strdup(name);",
"  int words = pya_word_count(name);",
"  if (words > list->max_words) list->max_words = words;",
"}",
"",
"static void pya_name_list_free(pya_name_list *list) {",
"  if (!list) return;",
"  for (int i = 0; i < list->length; i++) free(list->items[i]);",
"  free(list->items);",
"  list->items = NULL;",
"  list->length = 0;",
"  list->cap = 0;",
"  list->max_words = 1;",
"}",
"",
"static void pya_pyash_value_free(pya_pyash_value *value) {",
"  if (!value) return;",
"  if (value->kind == PYA_PYASH_TEXT && value->text) free(value->text);",
"  if (value->kind == PYA_PYASH_NAME && value->name) free(value->name);",
"  if (value->kind == PYA_PYASH_VECTOR) {",
"    if (value->vec_type) free(value->vec_type);",
"    for (int i = 0; i < value->vec_len; i++) {",
"      pya_pyash_value_free(&value->vec_values[i]);",
"    }",
"    free(value->vec_values);",
"  }",
"  memset(value, 0, sizeof(*value));",
"}",
"",
"static void pya_pyash_maps_free(pya_pyash_maps *defs) {",
"  if (!defs) return;",
"  for (int i = 0; i < defs->length; i++) {",
"    pya_pyash_map *map = &defs->maps[i];",
"    if (map->name) free(map->name);",
"    for (int j = 0; j < map->length; j++) {",
"      if (map->entries[j].key) free(map->entries[j].key);",
"      pya_pyash_value_free(&map->entries[j].value);",
"    }",
"    free(map->entries);",
"  }",
"  free(defs->maps);",
"  defs->maps = NULL;",
"  defs->length = 0;",
"  defs->cap = 0;",
"}",
"",
"static pya_pyash_map *pya_pyash_get_map(pya_pyash_maps *defs, const char *name) {",
"  if (!defs || !name) return NULL;",
"  for (int i = 0; i < defs->length; i++) {",
"    if (defs->maps[i].name && strcmp(defs->maps[i].name, name) == 0) return &defs->maps[i];",
"  }",
"  if (defs->length >= defs->cap) {",
"    int next = defs->cap == 0 ? 4 : defs->cap * 2;",
"    pya_pyash_map *nextMaps = (pya_pyash_map *)realloc(defs->maps, sizeof(pya_pyash_map) * next);",
"    if (!nextMaps) return NULL;",
"    defs->maps = nextMaps;",
"    defs->cap = next;",
"  }",
"  pya_pyash_map *map = &defs->maps[defs->length++];",
"  memset(map, 0, sizeof(*map));",
"  map->name = pya_strdup(name);",
"  return map;",
"}",
"",
"static int pya_pyash_tokenize(const char *line, char ***tokensOut, int *countOut) {",
"  if (!line || !tokensOut || !countOut) return 0;",
"  size_t len = strlen(line);",
"  char *storage = (char *)malloc(len + 1);",
"  char **items = (char **)malloc(sizeof(char *) * (len + 1));"
];
