export const JSON_PYASH_PART_06 = [
"        child = cJSON_CreateNumber(elem->num);",
"      } else if (elem->kind == PYA_PYASH_TEXT) {",
"        child = cJSON_CreateString(elem->text ? elem->text : \"\");",
"      } else if (elem->kind == PYA_PYASH_BOOL) {",
"        child = cJSON_CreateBool(elem->boolean != 0);",
"      }",
"      if (!child) { cJSON_Delete(arr); return NULL; }",
"      cJSON_AddItemToArray(arr, child);",
"    }",
"    return arr;",
"  }",
"  return NULL;",
"}",
"",
"static cJSON *pya_pyash_map_to_json(pya_pyash_maps *defs, const char *name, pya_used_names *seen, pya_json_error *err) {",
"  if (!defs || !name) {",
"    pya_set_json_error(err, \"json map referential defective\", name, name);",
"    return NULL;",
"  }",
"  if (pya_used_has(seen, name)) {",
"    pya_set_json_error(err, \"json map export self referential\", name, name);",
"    return NULL;",
"  }",
"  pya_pyash_map *map = NULL;",
"  for (int i = 0; i < defs->length; i++) {",
"    if (defs->maps[i].name && strcmp(defs->maps[i].name, name) == 0) {",
"      map = &defs->maps[i];",
"      break;",
"    }",
"  }",
"  if (!map) {",
"    pya_set_json_error(err, \"json map referential defective\", name, name);",
"    return NULL;",
"  }",
"  pya_used_add(seen, name);",
"  cJSON *obj = cJSON_CreateObject();",
"  if (!obj) { pya_used_remove(seen, name); return NULL; }",
"  if (map->length > 0) {",
"    char **keys = (char **)malloc(sizeof(char *) * map->length);",
"    int keyCount = 0;",
"    for (int i = 0; i < map->length; i++) {",
"      if (!map->entries[i].key) continue;",
"      keys[keyCount++] = map->entries[i].key;",
"    }",
"    qsort(keys, keyCount, sizeof(char *), pya_compare_utf8);",
"    for (int i = 0; i < keyCount; i++) {",
"      const char *key = keys[i];",
"      pya_pyash_value *value = NULL;",
"      for (int j = 0; j < map->length; j++) {",
"        if (map->entries[j].key && strcmp(map->entries[j].key, key) == 0) {",
"          value = &map->entries[j].value;",
"          break;",
"        }",
"      }",
"      if (!value) continue;",
"      cJSON *child = pya_pyash_value_to_json(defs, value, seen, err);",
"      if (!child && value->kind == PYA_PYASH_UNSPEC) continue;",
"      if (!child) { free(keys); cJSON_Delete(obj); pya_used_remove(seen, name); return NULL; }",
"      cJSON_AddItemToObject(obj, key, child);",
"    }",
"    free(keys);",
"  }",
"  pya_used_remove(seen, name);",
"  return obj;",
"}",
"",
"static int pya_pyash_to_json(const char *pyash, const char *rootName, char *out, pya_json_error *err) {",
"  if (!out) return 0;",
"  out[0] = '\\0';",
"  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
"  if (!pyash) {",
"    pya_set_json_error(err, \"json map export failed\", pyash, pyash);",
"    return 0;",
"  }",
"  pya_pyash_maps defs = {0};",
"  if (!pya_pyash_parse_maps(pyash, &defs, err)) {",
"    pya_pyash_maps_free(&defs);",
"    return 0;",
"  }",
"  const char *root = rootName ? rootName : (defs.length > 0 ? defs.maps[0].name : \"data\");",
"  pya_used_names seen;",
"  pya_used_init(&seen);",
"  cJSON *json = pya_pyash_map_to_json(&defs, root, &seen, err);",
"  pya_used_free(&seen);",
"  if (!json) {",
"    pya_pyash_maps_free(&defs);",
"    return 0;",
"  }",
"  char *printed = cJSON_PrintUnformatted(json);",
"  if (printed) {",
"    snprintf(out, PYA_TEXT_CAP, \"%s\", printed);",
"    free(printed);",
"  }",
"  cJSON_Delete(json);",
"  pya_pyash_maps_free(&defs);",
"  return 1;",
"}",
"static int pya_pyash_is_token(const char *s) {",
"  if (!s || !*s) return 0;",
"  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
"    if (!(isalnum(*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
"  }",
"  return 1;",
"}",
"static void pya_pyash_print_escaped(FILE *out, const char *s) {",
"  if (!s) return;",
"  for (const char *p = s; *p; p++) {",
"    if (*p == '\\\\' || *p == '\"') {",
"      fputc('\\\\', out);",
"      fputc(*p, out);",
"    } else if (*p == '\\n') {",
"      fputs(\"\\\\n\", out);",
"    } else {",
"      fputc(*p, out);",
"    }",
"  }",
"}",
"static void pya_pyash_print_token(FILE *out, const char *s) {",
"  if (!s) return;",
"  if (pya_pyash_is_token(s)) {",
"    fputs(s, out);",
"  } else {",
"    fputc('\"', out);",
"    pya_pyash_print_escaped(out, s);",
"    fputc('\"', out);",
"  }",
"}",
"static void pya_pyash_print_text_vector(FILE *out, char **values, size_t count) {",
"  fputs(\"ve text\", out);",
"  for (size_t i = 0; i < count; i++) {",
"    fputc(' ', out);",
"    pya_pyash_print_token(out, values[i] ? values[i] : \"\");",
"  }",
"}"
];
