export const JSON_PYASH_PART_02 = [
"  if (!f) return 0;",
"  size_t len = fread(out, 1, PYA_TEXT_CAP - 1, f);",
"  out[len] = '\\0';",
"  fclose(f);",
"  return 1;",
"}",
"",
"static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json);",
"",
"static void pya_append_vector_values(char *out, const char *type, cJSON *array) {",
"  pya_concat_buf(out, \"ve \");",
"  pya_concat_buf(out, type);",
"  int idx = 0;",
"  for (cJSON *item = array ? array->child : NULL; item; item = item->next, idx++) {",
"    pya_concat_buf(out, \" \");",
"    if (strcmp(type, \"bool\") == 0) {",
"      pya_concat_buf(out, cJSON_IsTrue(item) ? \"truth\" : \"lie\");",
"    } else if (strcmp(type, \"num\") == 0) {",
"      char buf[64];",
"      snprintf(buf, sizeof(buf), \"%g\", item->valuedouble);",
"      pya_concat_buf(out, buf);",
"    } else if (strcmp(type, \"text\") == 0) {",
"      pya_append_json_string(out, cJSON_GetStringValue(item));",
"    } else if (strcmp(type, \"name\") == 0) {",
"      pya_concat_buf(out, cJSON_GetStringValue(item));",
"    }",
"  }",
"}",
"",
"static void pya_append_np_for_value(char *line, cJSON *value, const char *parentName, const char *key, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
"  if (!value) { pya_concat_buf(line, \"hollow\"); return; }",
"  if (cJSON_IsNull(value)) { pya_concat_buf(line, \"hollow\"); return; }",
"  if (cJSON_IsString(value)) {",
"    pya_concat_buf(line, \"text \");",
"    pya_append_json_string(line, cJSON_GetStringValue(value));",
"    return;",
"  }",
"  if (cJSON_IsNumber(value)) {",
"    char buf[64];",
"    snprintf(buf, sizeof(buf), \"%g\", value->valuedouble);",
"    pya_concat_buf(line, \"num \");",
"    pya_concat_buf(line, buf);",
"    return;",
"  }",
"  if (cJSON_IsBool(value)) {",
"    pya_concat_buf(line, \"bool \");",
"    pya_concat_buf(line, cJSON_IsTrue(value) ? \"truth\" : \"lie\");",
"    return;",
"  }",
"  if (cJSON_IsArray(value)) {",
"    int hasArray = 0;",
"    int hasNull = 0;",
"    int hasObject = 0;",
"    int hasBool = 0;",
"    int hasNum = 0;",
"    int hasText = 0;",
"    int length = 0;",
"    for (cJSON *item = value->child; item; item = item->next) {",
"      length += 1;",
"      if (cJSON_IsArray(item)) hasArray = 1;",
"      else if (cJSON_IsNull(item)) hasNull = 1;",
"      else if (cJSON_IsObject(item)) hasObject = 1;",
"      else if (cJSON_IsBool(item)) hasBool = 1;",
"      else if (cJSON_IsNumber(item)) hasNum = 1;",
"      else if (cJSON_IsString(item)) hasText = 1;",
"    }",
"    if (length == 0) {",
"      pya_concat_buf(line, \"ve hollow\");",
"      return;",
"    }",
"    if (hasArray) {",
"      pya_set_json_error(err, \"json map contents defective: nested arrays are unsupported\", json, cJSON_GetErrorPtr());",
"      return;",
"    }",
"    if (hasNull) {",
"      pya_set_json_error(err, \"json map contents defective: null elements are unsupported in arrays\", json, cJSON_GetErrorPtr());",
"      return;",
"    }",
"    if (hasObject && (hasBool || hasNum || hasText)) {",
"      pya_set_json_error(err, \"json map contents defective: mixed array types are unsupported\", json, cJSON_GetErrorPtr());",
"      return;",
"    }",
"    if (hasObject) {",
"      pya_concat_buf(line, \"ve name\");",
"      int idx = 0;",
"      for (cJSON *item = value->child; item; item = item->next, idx++) {",
"        char keyPart[PYA_TEXT_CAP];",
"        pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
"        char base[PYA_TEXT_CAP];",
"        snprintf(base, sizeof(base), \"%s %s %d\", parentName, keyPart, idx + 1);",
"        char *childName = pya_unique_name(base, used);",
"        if (childName) {",
"          pya_emit_map(item, childName, used, chain, err, json);",
"          pya_concat_buf(line, \" \");",
"          pya_append_token(line, childName);",
"          free(childName);",
"        }",
"      }",
"      return;",
"    }",
"    if (hasBool && !(hasNum || hasText)) {",
"      pya_append_vector_values(line, \"bool\", value);",
"      return;",
"    }",
"    if (hasNum && !hasText) {",
"      pya_append_vector_values(line, \"num\", value);",
"      return;",
"    }",
"    pya_append_vector_values(line, \"text\", value);",
"    return;",
"  }",
"  if (cJSON_IsObject(value)) {",
"    char keyPart[PYA_TEXT_CAP];",
"    pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
"    char base[PYA_TEXT_CAP];",
"    snprintf(base, sizeof(base), \"%s %s\", parentName, keyPart);",
"    char *childName = pya_unique_name(base, used);",
"    if (childName) {",
"      pya_emit_map(value, childName, used, chain, err, json);",
"      pya_concat_buf(line, \"name \");",
"      pya_concat_buf(line, childName);",
"      free(childName);",
"    }",
"    return;",
"  }",
"}",
"",
"static int pya_json_entry_compare(const void *a, const void *b);",
"static int pya_json_entry_compare(const void *a, const void *b) {",
"  const cJSON *ea = *(const cJSON **)a;",
"  const cJSON *eb = *(const cJSON **)b;",
"  if (!ea || !ea->string) return (eb && eb->string) ? -1 : 0;",
"  if (!eb || !eb->string) return 1;",
"  return strcmp(ea->string, eb->string);",
"}",
"static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
"  if (!obj || !cJSON_IsObject(obj)) {",
"    pya_set_json_error(err, \"json map contents defective: object expected\", json, cJSON_GetErrorPtr());",
"    return;",
"  }",
"  char block[PYA_TEXT_CAP];",
"  block[0] = '\\0';",
"  pya_concat_buf(block, \"su name \");",
"  pya_concat_buf(block, name ? name : \"map\");",
"  pya_concat_buf(block, \" be json map def\\n\");",
"  int count = 0;",
"  for (cJSON *entry = obj->child; entry; entry = entry->next) {",
"    if (entry->string) count++;",
"  }",
"  if (count > 0) {",
"    cJSON **entries = (cJSON **)malloc(sizeof(cJSON *) * count);",
"    if (!entries) {",
"      pya_set_json_error(err, \"json map contents defective: allocation failed\", json, json);",
"      return;",
"    }",
"    int idx = 0;",
"    for (cJSON *entry = obj->child; entry; entry = entry->next) {",
"      if (entry->string) entries[idx++] = entry;",
"    }",
"    qsort(entries, count, sizeof(cJSON *), pya_json_entry_compare);",
"    for (int i = 0; i < count; i++) {",
"      cJSON *entry = entries[i];",
"      if (!entry || !entry->string) continue;",
"      pya_concat_buf(block, \"su name \");",
"      pya_concat_buf(block, entry->string);",
"      pya_concat_buf(block, \" ob \");",
"      pya_append_np_for_value(block, entry, name, entry->string, used, chain, err, json);",
"      if (err && err->message[0] != '\\0') {",
"        free(entries);",
"        return;",
"      }",
"      pya_concat_buf(block, \" ya\\n\");",
"    }",
"    free(entries);",
"  }",
"  pya_concat_buf(block, \"prah\\n\");",
"  if (chain[0] != '\\0') pya_concat_buf(chain, \"\\n\");",
"  pya_concat_buf(chain, block);",
"}",
""
];
