services:
  whisperx:
    container_name: whisperx
    image: ghcr.io/jim60105/whisperx:no_model
    working_dir: /workplace
    command: ["python3", "/service/server.py", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ${WHISPERX_WORKSPACE:-../../..}:/workplace
      - ../cache:/root/.cache
      - ./server.py:/service/server.py:ro
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface
      - TORCH_HOME=/root/.cache/torch
      - MPLCONFIGDIR=/root/.cache/matplotlib
    extra_hosts:
      - host.docker.internal:host-gateway
