export const CSV_RUNTIME_HELPER_PART_03 = [
"    if (dataLen > headerCount) {",
"      free(drop);",
"      pya_csv_set_error(err, \"csv row defective\", (int)r + 1, (int)dataLen + (isTemplate ? 1 : 0));",
"      return 0;",
"    }",
"    size_t colIndex = 0;",
"    for (size_t c = 0; c < headerCount; c++) {",
"      if (drop[c]) continue;",
"      const char *cell = (c + (isTemplate ? 1 : 0) < row.count) ? row.cells[c + (isTemplate ? 1 : 0)] : \"\";",
"      columns[colIndex][rowIndex] = pya_csv_strdup(cell ? cell : \"\");",
"      colIndex++;",
"    }",
"    rowIndex++;",
"  }",
"  free(drop);",
"  out->header_raw = header_raw;",
"  out->header = header;",
"  out->width = filteredCount;",
"  out->rows = dataCount;",
"  out->columns = columns;",
"  return 1;",
"}",
"static int pya_csv_read_file(const char *filename, const char *name, pya_csv_error *err) {",
"  if (!filename || !name) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
"  FILE *f = fopen(filename, \"rb\");",
"  if (!f) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
"  struct zsv_opts opts = {0};",
"  struct pya_csv_parse_ctx ctx = {0};",
"  opts.row_handler = pya_csv_row_handler;",
"  opts.ctx = &ctx;",
"  opts.stream = f;",
"  ctx.parser = zsv_new(&opts);",
"  enum zsv_status stat;",
"  while ((stat = zsv_parse_more(ctx.parser)) == zsv_status_ok) { }",
"  zsv_finish(ctx.parser);",
"  zsv_delete(ctx.parser);",
"  fclose(f);",
"  if (stat != zsv_status_no_more_input) {",
"    pya_csv_set_error(err, \"csv defective\", 0, 0);",
"    return 0;",
"  }",
"  pya_csv_map map = {0};",
"  if (!pya_csv_build_map(&ctx.rows, &map, err)) {",
"    for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
"    free(ctx.rows.rows);",
"    return 0;",
"  }",
"  for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
"  free(ctx.rows.rows);",
"  pya_csv_store(name, &map);",
"  return 1;",
"}",
"static int pya_csv_header_raw_unique(pya_csv_map *map) {",
"  if (!map || !map->header_raw) return 0;",
"  for (size_t i = 0; i < map->width; i++) {",
"    char normA[PYA_TEXT_CAP];",
"    pya_csv_lower_trim(map->header_raw[i], normA, sizeof(normA));",
"    if (!*normA) return 0;",
"    for (size_t j = i + 1; j < map->width; j++) {",
"      char normB[PYA_TEXT_CAP];",
"      pya_csv_lower_trim(map->header_raw[j], normB, sizeof(normB));",
"      if (strcmp(normA, normB) == 0) return 0;",
"    }",
"  }",
"  return 1;",
"}",
"static void pya_csv_escape(FILE *out, const char *value) {",
"  const char *str = value ? value : \"\";",
"  int needs = 0;",
"  for (const char *p = str; *p; p++) {",
"    if (*p == '\"' || *p == '\\n' || *p == '\\r' || *p == ',') { needs = 1; break; }",
"  }",
"  if (!needs) { fputs(str, out); return; }",
"  fputc('\"', out);",
"  for (const char *p = str; *p; p++) {",
"    if (*p == '\"') fputc('\"', out);",
"    fputc(*p, out);",
"  }",
"  fputc('\"', out);",
"}",
"static int pya_csv_write_file(const char *name, const char *filename) {",
"  pya_csv_map *map = pya_csv_find(name);",
"  if (!map || !filename) return 0;",
"  FILE *out = fopen(filename, \"w\");",
"  if (!out) return 0;",
"  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
"  for (size_t i = 0; i < map->width; i++) {",
"    if (i) fputc(',', out);",
"    pya_csv_escape(out, headers[i]);",
"  }",
"  fputc('\\n', out);",
"  for (size_t r = 0; r < map->rows; r++) {",
"    for (size_t c = 0; c < map->width; c++) {",
"      if (c) fputc(',', out);",
"      pya_csv_escape(out, map->columns[c][r]);",
"    }",
"    fputc('\\n', out);",
"  }",
"  fclose(out);",
"  return 1;",
"}",
"static int pya_csv_write_stdout(const char *name) {",
"  pya_csv_map *map = pya_csv_find(name);",
"  if (!map) return 0;",
"  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
"  for (size_t i = 0; i < map->width; i++) {",
"    if (i) fputc(',', stdout);",
"    pya_csv_escape(stdout, headers[i]);",
"  }",
"  fputc('\\n', stdout);",
"  for (size_t r = 0; r < map->rows; r++) {",
"    for (size_t c = 0; c < map->width; c++) {",
"      if (c) fputc(',', stdout);",
"      pya_csv_escape(stdout, map->columns[c][r]);",
"    }",
"    fputc('\\n', stdout);",
"  }",
"  return 1;",
"}",
"static int pya_pyash_is_token(const char *s) {",
"  if (!s || !*s) return 0;",
"  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
"    if (!(isalnum(*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
"  }",
"  return 1;",
"}",
"static void pya_pyash_print_escaped(FILE *out, const char *s) {",
"  if (!s) return;",
"  for (const char *p = s; *p; p++) {",
"    if (*p == '\\\\' || *p == '\"') {",
"      fputc('\\\\', out);",
"      fputc(*p, out);",
"    } else if (*p == '\\n') {",
"      fputs(\"\\\\n\", out);",
"    } else {",
"      fputc(*p, out);",
"    }",
"  }",
"}",
"static void pya_pyash_print_token(FILE *out, const char *s) {",
"  if (!s) return;",
"  if (pya_pyash_is_token(s)) {",
"    fputs(s, out);",
"  } else {",
"    fputc('\"', out);",
"    pya_pyash_print_escaped(out, s);",
"    fputc('\"', out);",
"  }",
"}",
"static void pya_pyash_print_text_vector(FILE *out, char **values, size_t count) {",
"  fputs(\"ve text\", out);",
"  for (size_t i = 0; i < count; i++) {",
"    fputc(' ', out);",
"    pya_pyash_print_token(out, values[i] ? values[i] : \"\");",
"  }",
"}",
"static int pya_csv_write_pyash(FILE *out, const char *name) {",
"  pya_csv_map *map = pya_csv_find(name);",
"  if (!map || !out) return 0;",
"  fputs(\"su name \", out);",
"  pya_pyash_print_token(out, name ? name : \"\");",
"  fputs(\" be csv map def\\n\", out);",
"  fputs(\"su name header raw ob \", out);",
"  pya_pyash_print_text_vector(out, map->header_raw ? map->header_raw : map->header, map->width);",
"  fputs(\" ya\\n\", out);",
"  fputs(\"su name header ob \", out);",
"  pya_pyash_print_text_vector(out, map->header, map->width);",
"  fputs(\" ya\\n\", out);",
"  for (size_t c = 0; c < map->width; c++) {",
"    fputs(\"su name \", out);",
"    pya_pyash_print_token(out, map->header[c] ? map->header[c] : \"\");",
"    fputs(\" ob \", out);",
"    pya_pyash_print_text_vector(out, map->columns[c], map->rows);",
"    fputs(\" ya\\n\", out);",
"  }",
"  fputs(\"prah\\n\", out);",
"  return 1;",
"}",
"static int pya_csv_write_pyash_file(const char *name, const char *filename) {",
"  FILE *out = fopen(filename, \"w\");"
];
