export const CSV_RUNTIME_HELPER_PART_01 = [
"#define PYA_CSV_RUNTIME 1",
"#ifndef PYA_TEXT_CAP",
"#define PYA_TEXT_CAP 4096",
"#endif",
"typedef struct {",
"  char message[PYA_TEXT_CAP];",
"  int line;",
"  int column;",
"} pya_csv_error;",
"typedef struct {",
"  char **cells;",
"  size_t count;",
"} pya_csv_row;",
"typedef struct {",
"  pya_csv_row *rows;",
"  size_t length;",
"  size_t cap;",
"} pya_csv_rows;",
"typedef struct {",
"  char **header_raw;",
"  char **header;",
"  size_t width;",
"  size_t rows;",
"  char ***columns;",
"} pya_csv_map;",
"typedef struct {",
"  char *name;",
"  pya_csv_map map;",
"} pya_csv_named;",
"static pya_csv_named *pya_csv_maps = NULL;",
"static size_t pya_csv_map_count = 0;",
"static size_t pya_csv_map_cap = 0;",
"static char *pya_csv_strdup(const char *s) {",
"  if (!s) return NULL;",
"  size_t len = strlen(s);",
"  char *out = (char *)malloc(len + 1);",
"  if (!out) return NULL;",
"  memcpy(out, s, len);",
"  out[len] = '\\0';",
"  return out;",
"}",
"static void pya_csv_set_error(pya_csv_error *err, const char *message, int line, int column) {",
"  if (!err) return;",
"  snprintf(err->message, sizeof(err->message), \"%s\", message ? message : \"csv defective\");",
"  err->line = line;",
"  err->column = column;",
"}",
"static int pya_csv_is_blank(const char *s) {",
"  if (!s) return 1;",
"  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
"    if (!isspace(*p)) return 0;",
"  }",
"  return 1;",
"}",
"static void pya_csv_lower_trim(const char *s, char *out, size_t cap) {",
"  if (!out || cap == 0) return;",
"  out[0] = '\\0';",
"  if (!s) return;",
"  size_t len = strlen(s);",
"  char buf[PYA_TEXT_CAP];",
"  size_t idx = 0;",
"  int lastSpace = 1;",
"  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
"    unsigned char ch = (unsigned char)s[i];",
"    if (isspace(ch)) {",
"      if (!lastSpace) { buf[idx++] = ' '; lastSpace = 1; }",
"    } else {",
"      buf[idx++] = (char)tolower(ch);",
"      lastSpace = 0;",
"    }",
"  }",
"  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
"  buf[idx] = '\\0';",
"  snprintf(out, cap, \"%s\", buf);",
"}",
"static int pya_csv_eq_lower(const char *s, const char *target) {",
"  char buf[PYA_TEXT_CAP];",
"  pya_csv_lower_trim(s, buf, sizeof(buf));",
"  return strcmp(buf, target) == 0;",
"}",
"static int pya_csv_has_alpha(const char *s) {",
"  if (!s) return 0;",
"  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
"    if (isalpha(*p)) return 1;",
"  }",
"  return 0;",
"}",
"static int pya_csv_is_numeric(const char *s) {",
"  if (!s) return 0;",
"  while (isspace((unsigned char)*s)) s++;",
"  if (!*s) return 0;",
"  char *end = NULL;",
"  strtod(s, &end);",
"  if (!end) return 0;",
"  while (*end && isspace((unsigned char)*end)) end++;",
"  return *end == '\\0';",
"}",
"static void pya_csv_rows_push(pya_csv_rows *rows, pya_csv_row row) {",
"  if (!rows) return;",
"  if (rows->length >= rows->cap) {",
"    size_t next = rows->cap == 0 ? 16 : rows->cap * 2;",
"    pya_csv_row *nextRows = (pya_csv_row *)realloc(rows->rows, sizeof(pya_csv_row) * next);",
"    if (!nextRows) return;",
"    rows->rows = nextRows;",
"    rows->cap = next;",
"  }",
"  rows->rows[rows->length++] = row;",
"}",
"struct pya_csv_parse_ctx { zsv_parser parser; pya_csv_rows rows; };",
"static void pya_csv_row_handler(void *ctx) {",
"  struct pya_csv_parse_ctx *data = ctx;",
"  size_t count = zsv_cell_count(data->parser);",
"  char **cells = count ? (char **)calloc(count, sizeof(char *)) : NULL;",
"  for (size_t i = 0; i < count; i++) {",
"    struct zsv_cell cell = zsv_get_cell(data->parser, i);",
"    char *value = (char *)malloc(cell.len + 1);",
"    if (!value) continue;",
"    memcpy(value, cell.str, cell.len);",
"    value[cell.len] = '\\0';",
"    cells[i] = value;",
"  }",
"  pya_csv_row row = { cells, count };",
"  pya_csv_rows_push(&data->rows, row);",
"}",
"static void pya_csv_free_row(pya_csv_row *row) {",
"  if (!row) return;",
"  for (size_t i = 0; i < row->count; i++) free(row->cells[i]);",
"  free(row->cells);",
"  row->cells = NULL;",
"  row->count = 0;",
"}",
"static void pya_csv_map_free(pya_csv_map *map) {",
"  if (!map) return;",
"  for (size_t i = 0; i < map->width; i++) {",
"    free(map->header_raw[i]);",
"    free(map->header[i]);",
"    for (size_t r = 0; r < map->rows; r++) free(map->columns[i][r]);",
"    free(map->columns[i]);",
"  }",
"  free(map->header_raw);",
"  free(map->header);",
"  free(map->columns);",
"  map->header_raw = NULL;",
"  map->header = NULL;",
"  map->columns = NULL;",
"  map->width = 0;",
"  map->rows = 0;",
"}",
"static pya_csv_map *pya_csv_find(const char *name) {",
"  if (!name) return NULL;",
"  for (size_t i = 0; i < pya_csv_map_count; i++) {",
"    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) return &pya_csv_maps[i].map;",
"  }",
"  return NULL;",
"}",
"static void pya_csv_store(const char *name, pya_csv_map *map) {",
"  if (!name || !map) return;",
"  for (size_t i = 0; i < pya_csv_map_count; i++) {",
"    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) {",
"      pya_csv_map_free(&pya_csv_maps[i].map);",
"      pya_csv_maps[i].map = *map;",
"      return;",
"    }",
"  }",
"  if (pya_csv_map_count >= pya_csv_map_cap) {",
"    size_t next = pya_csv_map_cap == 0 ? 8 : pya_csv_map_cap * 2;",
"    pya_csv_named *nextMaps = (pya_csv_named *)realloc(pya_csv_maps, sizeof(pya_csv_named) * next);",
"    if (!nextMaps) return;",
"    pya_csv_maps = nextMaps;",
"    pya_csv_map_cap = next;",
"  }",
"  pya_csv_maps[pya_csv_map_count].name = pya_csv_strdup(name);",
"  pya_csv_maps[pya_csv_map_count].map = *map;",
"  pya_csv_map_count += 1;",
"}",
"static int pya_csv_build_map(pya_csv_rows *rows, pya_csv_map *out, pya_csv_error *err) {",
"  if (!rows || rows->length == 0) {",
"    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
"    return 0;",
"  }"
];
