export const CSV_RUNTIME_HELPER_PART_02 = [
"  size_t nonEmpty = rows->length;",
"  for (size_t i = 0; i < rows->length; i++) {",
"    int has = 0;",
"    for (size_t c = 0; c < rows->rows[i].count; c++) {",
"      if (!pya_csv_is_blank(rows->rows[i].cells[c])) { has = 1; break; }",
"    }",
"    if (has) { nonEmpty = i; break; }",
"  }",
"  if (nonEmpty >= rows->length) {",
"    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
"    return 0;",
"  }",
"  int isTemplate = 0;",
"  if (rows->length > 0 && rows->rows[0].count > 0 && pya_csv_eq_lower(rows->rows[0].cells[0], \"data import template\")) {",
"    isTemplate = 1;",
"  }",
"  size_t headerRowIndex = rows->length;",
"  if (isTemplate) {",
"    for (size_t i = 0; i < rows->length; i++) {",
"      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"column name:\")) {",
"        headerRowIndex = i; break;",
"      }",
"    }",
"    if (headerRowIndex >= rows->length) {",
"      pya_csv_set_error(err, \"csv header defective\", 1, 1);",
"      return 0;",
"    }",
"  } else {",
"    size_t lastWidths[20] = {0};",
"    size_t lastCount = 0;",
"    for (size_t i = 0; i < rows->length; i++) {",
"      int has = 0;",
"      for (size_t c = 0; c < rows->rows[i].count; c++) {",
"        if (!pya_csv_is_blank(rows->rows[i].cells[c])) { has = 1; break; }",
"      }",
"      if (!has) continue;",
"      size_t width = rows->rows[i].count;",
"      if (lastCount < 20) {",
"        lastWidths[lastCount++] = width;",
"      } else {",
"        for (size_t j = 1; j < 20; j++) lastWidths[j - 1] = lastWidths[j];",
"        lastWidths[19] = width;",
"      }",
"    }",
"    size_t widthMode = 0;",
"    size_t bestCount = 0;",
"    for (size_t i = 0; i < lastCount; i++) {",
"      size_t width = lastWidths[i];",
"      size_t count = 0;",
"      for (size_t j = 0; j < lastCount; j++) if (lastWidths[j] == width) count++;",
"      if (count > bestCount || (count == bestCount && width > widthMode)) {",
"        widthMode = width;",
"        bestCount = count;",
"      }",
"    }",
"    for (size_t i = 0; i < rows->length; i++) {",
"      pya_csv_row row = rows->rows[i];",
"      if (row.count != widthMode || widthMode == 0) continue;",
"      int ok = 1;",
"      int hasAlpha = 0;",
"      for (size_t c = 0; c < row.count; c++) {",
"        const char *cell = row.cells[c];",
"        if (pya_csv_is_blank(cell)) { ok = 0; break; }",
"        if (pya_csv_has_alpha(cell)) hasAlpha = 1;",
"        if (pya_csv_is_numeric(cell)) { ok = 0; break; }",
"      }",
"      if (ok && hasAlpha) { headerRowIndex = i; break; }",
"    }",
"    if (headerRowIndex >= rows->length && widthMode > 0) {",
"      for (size_t i = 0; i < rows->length; i++) {",
"        if (rows->rows[i].count == widthMode) { headerRowIndex = i; break; }",
"      }",
"    }",
"  }",
"  if (headerRowIndex >= rows->length) headerRowIndex = nonEmpty;",
"  pya_csv_row headerRow = rows->rows[headerRowIndex];",
"  size_t headerCount = headerRow.count > 0 ? headerRow.count - (isTemplate ? 1 : 0) : 0;",
"  if (headerCount == 0) {",
"    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
"    return 0;",
"  }",
"  char *drop = (char *)calloc(headerCount, 1);",
"  if (isTemplate) {",
"    for (size_t i = 0; i < headerCount; i++) {",
"      const char *cell = headerRow.cells[i + 1];",
"      char norm[PYA_TEXT_CAP];",
"      pya_csv_lower_trim(cell, norm, sizeof(norm));",
"      if (pya_csv_is_blank(cell) || strcmp(norm, \"~\") == 0) drop[i] = 1;",
"    }",
"  }",
"  size_t filteredCount = 0;",
"  for (size_t i = 0; i < headerCount; i++) if (!drop[i]) filteredCount++;",
"  if (filteredCount == 0) {",
"    free(drop);",
"    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
"    return 0;",
"  }",
"  char **header_raw = (char **)calloc(filteredCount, sizeof(char *));",
"  char **header = (char **)calloc(filteredCount, sizeof(char *));",
"  size_t headerIdx = 0;",
"  for (size_t i = 0; i < headerCount; i++) {",
"    if (drop[i]) continue;",
"    const char *cell = headerRow.cells[i + (isTemplate ? 1 : 0)];",
"    header_raw[headerIdx] = pya_csv_strdup(cell ? cell : \"\");",
"    if (isTemplate) {",
"      header[headerIdx] = pya_csv_strdup(cell ? cell : \"\");",
"    } else {",
"      char norm[PYA_TEXT_CAP];",
"      pya_csv_lower_trim(cell, norm, sizeof(norm));",
"      header[headerIdx] = pya_csv_strdup(norm);",
"    }",
"    headerIdx++;",
"  }",
"  if (isTemplate) {",
"    char **bases = (char **)calloc(filteredCount, sizeof(char *));",
"    for (size_t i = 0; i < filteredCount; i++) {",
"      bases[i] = pya_csv_strdup(header[i]);",
"    }",
"    for (size_t i = 0; i < filteredCount; i++) {",
"      if (!bases[i] || !*bases[i]) continue;",
"      int count = 0;",
"      for (size_t j = 0; j < i; j++) if (bases[j] && strcmp(bases[j], bases[i]) == 0) count++;",
"      if (count > 0) {",
"        char buf[PYA_TEXT_CAP];",
"        snprintf(buf, sizeof(buf), \"%s %d\", bases[i], count + 1);",
"        free(header[i]);",
"        header[i] = pya_csv_strdup(buf);",
"      }",
"    }",
"    for (size_t i = 0; i < filteredCount; i++) free(bases[i]);",
"    free(bases);",
"  }",
"  const char *metaLabels[] = {\"column name:\",\"mandatory:\",\"type:\",\"info:\",\"doctype:\",\"column labels:\",\"start entering data below this line\"};",
"  size_t dataStart = headerRowIndex + 1;",
"  if (isTemplate) {",
"    for (size_t i = headerRowIndex + 1; i < rows->length; i++) {",
"      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"start entering data below this line\")) {",
"        dataStart = i + 1; break;",
"      }",
"    }",
"  }",
"  size_t dataCount = 0;",
"  for (size_t r = dataStart; r < rows->length; r++) {",
"    pya_csv_row row = rows->rows[r];",
"    if (isTemplate) {",
"      int isMeta = 0;",
"      if (row.count > 0) {",
"        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
"          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
"        }",
"      }",
"      if (isMeta) continue;",
"      int allBlank = 1;",
"      for (size_t c = 0; c < row.count; c++) {",
"        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
"      }",
"      if (allBlank) continue;",
"    }",
"    dataCount++;",
"  }",
"  char ***columns = (char ***)calloc(filteredCount, sizeof(char **));",
"  for (size_t i = 0; i < filteredCount; i++) columns[i] = (char **)calloc(dataCount, sizeof(char *));",
"  size_t rowIndex = 0;",
"  for (size_t r = dataStart; r < rows->length; r++) {",
"    pya_csv_row row = rows->rows[r];",
"    if (isTemplate) {",
"      int isMeta = 0;",
"      if (row.count > 0) {",
"        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
"          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
"        }",
"      }",
"      if (isMeta) continue;",
"      int allBlank = 1;",
"      for (size_t c = 0; c < row.count; c++) {",
"        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
"      }",
"      if (allBlank) continue;",
"    }",
"    size_t dataLen = row.count > 0 ? row.count - (isTemplate ? 1 : 0) : 0;"
];
