export const YAML_RUNTIME_HELPER_PART_02 = [
  "  return pya_strdup(buf);",
  "}",
  "",
  "static cJSON *pya_yaml_scalar_to_json(const char *raw, yaml_scalar_style_t style) {",
  "  if (!raw) return cJSON_CreateNull();",
  "  const int is_plain = (style == YAML_PLAIN_SCALAR_STYLE);",
  "  if (!is_plain) return cJSON_CreateString(raw);",
  "  char buf[PYA_TEXT_CAP];",
  "  snprintf(buf, sizeof(buf), \"%s\", raw);",
  "  pya_yaml_trim(buf);",
  "  if (buf[0] == '\\0' || strcmp(buf, \"~\") == 0 || strcasecmp(buf, \"null\") == 0) return cJSON_CreateNull();",
  "  if (strcasecmp(buf, \"true\") == 0) return cJSON_CreateBool(1);",
  "  if (strcasecmp(buf, \"false\") == 0) return cJSON_CreateBool(0);",
  "  if (pya_yaml_is_json_number(buf)) return cJSON_CreateNumber(strtod(buf, NULL));",
  "  return cJSON_CreateString(buf);",
  "}",
  "",
  "static int pya_yaml_stack_push(pya_yaml_stack **stack, int *depth, int *cap, cJSON *node, int is_map) {",
  "  if (*depth >= *cap) {",
  "    int next = (*cap == 0) ? 8 : (*cap * 2);",
  "    pya_yaml_stack *resized = (pya_yaml_stack *)realloc(*stack, sizeof(pya_yaml_stack) * next);",
  "    if (!resized) return 0;",
  "    *stack = resized;",
  "    *cap = next;",
  "  }",
  "  (*stack)[*depth].node = node;",
  "  (*stack)[*depth].is_map = is_map;",
  "  (*stack)[*depth].pending_key = NULL;",
  "  *depth += 1;",
  "  return 1;",
  "}",
  "",
  "static pya_yaml_stack *pya_yaml_stack_top(pya_yaml_stack *stack, int depth) {",
  "  if (!stack || depth <= 0) return NULL;",
  "  return &stack[depth - 1];",
  "}",
  "",
  "static void pya_yaml_stack_pop(pya_yaml_stack *stack, int *depth) {",
  "  if (!stack || !depth || *depth <= 0) return;",
  "  pya_yaml_stack *top = &stack[*depth - 1];",
  "  if (top->pending_key) free(top->pending_key);",
  "  *depth -= 1;",
  "}",
  "",
  "static int pya_yaml_merge_map(cJSON *target, cJSON *source) {",
  "  if (!cJSON_IsObject(source)) return 0;",
  "  for (cJSON *entry = source->child; entry; entry = entry->next) {",
  "    if (!entry->string) continue;",
  "    if (cJSON_GetObjectItemCaseSensitive(target, entry->string)) continue;",
  "    cJSON_AddItemToObject(target, entry->string, cJSON_Duplicate(entry, 1));",
  "  }",
  "  return 1;",
  "}",
  "",
  "static int pya_yaml_add_value(pya_yaml_stack *stack, int depth, cJSON **root, cJSON *value, pya_yaml_error *err) {",
  "  if (!value) return 0;",
  "  if (depth <= 0) {",
  "    if (*root) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "    *root = value;",
  "    return 1;",
  "  }",
  "  pya_yaml_stack *parent = &stack[depth - 1];",
  "  if (parent->is_map) {",
  "    if (!parent->pending_key) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return 0; }",
  "    if (strcmp(parent->pending_key, \"<<\") == 0) {",
  "      int ok = 1;",
  "      if (cJSON_IsArray(value)) {",
  "        for (cJSON *item = value->child; item; item = item->next) {",
  "          if (!pya_yaml_merge_map(parent->node, item)) ok = 0;",
  "        }",
  "      } else {",
  "        ok = pya_yaml_merge_map(parent->node, value);",
  "      }",
  "      free(parent->pending_key);",
  "      parent->pending_key = NULL;",
  "      if (!ok) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "      cJSON_Delete(value);",
  "      return 1;",
  "    }",
  "    cJSON_DeleteItemFromObjectCaseSensitive(parent->node, parent->pending_key);",
  "    cJSON_AddItemToObject(parent->node, parent->pending_key, value);",
  "    free(parent->pending_key);",
  "    parent->pending_key = NULL;",
  "    return 1;",
  "  }",
  "  cJSON_AddItemToArray(parent->node, value);",
  "  return 1;",
  "}",
  "",
  "static int pya_yaml_alias_cycle(pya_yaml_stack *stack, int depth, cJSON *target) {",
  "  for (int i = 0; i < depth; i++) {",
  "    if (stack[i].node == target) return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static cJSON *pya_yaml_parse_json(const char *text, pya_yaml_error *err) {",
  "  yaml_parser_t parser;",
  "  yaml_event_t event;",
  "  if (!yaml_parser_initialize(&parser)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return NULL; }",
  "  yaml_parser_set_input_string(&parser, (const unsigned char *)text, text ? strlen(text) : 0);",
  "  pya_yaml_anchors anchors;",
  "  pya_yaml_anchors_init(&anchors);",
  "  pya_yaml_stack *stack = NULL;",
  "  int depth = 0;",
  "  int cap = 0;",
  "  int doc_count = 0;",
  "  cJSON *root = NULL;",
  "  int done = 0;",
  "  while (!done) {",
  "    if (!yaml_parser_parse(&parser, &event)) {",
  "      pya_yaml_set_error(err, \"yaml defective\", parser.problem_mark.line + 1, parser.problem_mark.column + 1);",
  "      break;",
  "    }",
  "    switch (event.type) {",
  "      case YAML_STREAM_END_EVENT:",
  "        done = 1;",
  "        break;",
  "      case YAML_DOCUMENT_START_EVENT:",
  "        doc_count++;",
];
