export const YAML_RUNTIME_HELPER_PART_03 = [
  "        if (doc_count > 1) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      case YAML_MAPPING_START_EVENT: {",
  "        if (event.data.mapping_start.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        cJSON *obj = cJSON_CreateObject();",
  "        if (!obj) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        if (event.data.mapping_start.anchor) {",
  "          pya_yaml_anchor_set(&anchors, (const char *)event.data.mapping_start.anchor, obj);",
  "        }",
  "        if (!pya_yaml_add_value(stack, depth, &root, obj, err)) { done = 1; break; }",
  "        if (!pya_yaml_stack_push(&stack, &depth, &cap, obj, 1)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      }",
  "      case YAML_SEQUENCE_START_EVENT: {",
  "        if (event.data.sequence_start.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        cJSON *arr = cJSON_CreateArray();",
  "        if (!arr) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        if (event.data.sequence_start.anchor) {",
  "          pya_yaml_anchor_set(&anchors, (const char *)event.data.sequence_start.anchor, arr);",
  "        }",
  "        if (!pya_yaml_add_value(stack, depth, &root, arr, err)) { done = 1; break; }",
  "        if (!pya_yaml_stack_push(&stack, &depth, &cap, arr, 0)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      }",
  "      case YAML_MAPPING_END_EVENT:",
  "      case YAML_SEQUENCE_END_EVENT:",
  "        pya_yaml_stack_pop(stack, &depth);",
  "        break;",
  "      case YAML_SCALAR_EVENT: {",
  "        if (event.data.scalar.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        pya_yaml_stack *parent = pya_yaml_stack_top(stack, depth);",
  "        const char *raw = (const char *)event.data.scalar.value;",
  "        if (parent && parent->is_map && !parent->pending_key) {",
  "          char *key = pya_yaml_key_text(raw, event.data.scalar.style, err);",
  "          if (!key) { done = 1; break; }",
  "          parent->pending_key = key;",
  "        } else {",
  "          cJSON *val = pya_yaml_scalar_to_json(raw, event.data.scalar.style);",
  "          if (event.data.scalar.anchor) {",
  "            pya_yaml_anchor_set(&anchors, (const char *)event.data.scalar.anchor, val);",
  "          }",
  "          if (!pya_yaml_add_value(stack, depth, &root, val, err)) { done = 1; }",
  "        }",
  "        break;",
  "      }",
  "      case YAML_ALIAS_EVENT: {",
  "        pya_yaml_stack *parent = pya_yaml_stack_top(stack, depth);",
  "        if (parent && parent->is_map && !parent->pending_key) {",
  "          pya_yaml_set_error(err, \"yaml key defective\", 0, 0);",
  "          done = 1;",
  "          break;",
  "        }",
  "        const char *alias = (const char *)event.data.alias.anchor;",
  "        cJSON *target = pya_yaml_anchor_get(&anchors, alias);",
  "        if (!target || pya_yaml_alias_cycle(stack, depth, target)) {",
  "          pya_yaml_set_error(err, \"yaml referential defective\", 0, 0);",
  "          done = 1;",
  "          break;",
  "        }",
  "        cJSON *dup = cJSON_Duplicate(target, 1);",
  "        if (!pya_yaml_add_value(stack, depth, &root, dup, err)) { done = 1; }",
  "        break;",
  "      }",
  "      default:",
  "        break;",
  "    }",
  "    yaml_event_delete(&event);",
  "  }",
  "  if (stack) {",
  "    for (int i = 0; i < depth; i++) {",
  "      if (stack[i].pending_key) free(stack[i].pending_key);",
  "    }",
  "    free(stack);",
  "  }",
  "  pya_yaml_anchors_free(&anchors);",
  "  yaml_parser_delete(&parser);",
  "  if (err && err->message[0] != '\\0') {",
  "    if (root) cJSON_Delete(root);",
  "    return NULL;",
  "  }",
  "  if (!root || !cJSON_IsObject(root)) {",
  "    if (root) cJSON_Delete(root);",
  "    pya_yaml_set_error(err, \"yaml root defective\", 0, 0);",
  "    return NULL;",
  "  }",
  "  return root;",
  "}",
  "",
  "typedef struct { const char *key; cJSON *value; } pya_yaml_kv;",
  "",
  "static int pya_yaml_compare_utf8(const void *a, const void *b) {",
  "  const pya_yaml_kv *ka = (const pya_yaml_kv *)a;",
  "  const pya_yaml_kv *kb = (const pya_yaml_kv *)b;",
  "  if (!ka->key || !kb->key) return 0;",
  "  return strcmp(ka->key, kb->key);",
  "}",
  "",
  "static cJSON *pya_yaml_canonicalize(cJSON *node) {",
  "  if (!node) return NULL;",
  "  if (cJSON_IsArray(node)) {",
  "    cJSON *arr = cJSON_CreateArray();",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      cJSON_AddItemToArray(arr, pya_yaml_canonicalize(child));",
  "    }",
  "    return arr;",
  "  }",
  "  if (cJSON_IsObject(node)) {",
  "    int count = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    cJSON *obj = cJSON_CreateObject();",
  "    for (int i = 0; i < count; i++) {",
  "      cJSON_AddItemToObject(obj, items[i].key, pya_yaml_canonicalize(items[i].value));",
];
