export const YAML_RUNTIME_HELPER_PART_01 = [
  "/* PYA_YAML_RUNTIME */",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_yaml_error;",
  "",
  "typedef struct {",
  "  char **names;",
  "  cJSON **values;",
  "  int length;",
  "  int cap;",
  "} pya_yaml_anchors;",
  "",
  "typedef struct {",
  "  cJSON *node;",
  "  int is_map;",
  "  char *pending_key;",
  "} pya_yaml_stack;",
  "",
  "static void pya_yaml_set_error(pya_yaml_error *err, const char *msg, int line, int col) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", msg ? msg : \"yaml defective\");",
  "  err->line = line;",
  "  err->column = col;",
  "}",
  "",
  "static void pya_yaml_anchors_init(pya_yaml_anchors *anchors) {",
  "  anchors->names = NULL;",
  "  anchors->values = NULL;",
  "  anchors->length = 0;",
  "  anchors->cap = 0;",
  "}",
  "",
  "static void pya_yaml_anchors_free(pya_yaml_anchors *anchors) {",
  "  if (!anchors) return;",
  "  for (int i = 0; i < anchors->length; i++) free(anchors->names[i]);",
  "  free(anchors->names);",
  "  free(anchors->values);",
  "  anchors->names = NULL;",
  "  anchors->values = NULL;",
  "  anchors->length = 0;",
  "  anchors->cap = 0;",
  "}",
  "",
  "static void pya_yaml_anchor_set(pya_yaml_anchors *anchors, const char *name, cJSON *value) {",
  "  if (!anchors || !name || !*name || !value) return;",
  "  for (int i = 0; i < anchors->length; i++) {",
  "    if (strcmp(anchors->names[i], name) == 0) { anchors->values[i] = value; return; }",
  "  }",
  "  if (anchors->length >= anchors->cap) {",
  "    int next = anchors->cap == 0 ? 8 : anchors->cap * 2;",
  "    anchors->names = (char **)realloc(anchors->names, sizeof(char *) * next);",
  "    anchors->values = (cJSON **)realloc(anchors->values, sizeof(cJSON *) * next);",
  "    anchors->cap = next;",
  "  }",
  "  anchors->names[anchors->length] = pya_strdup(name);",
  "  anchors->values[anchors->length] = value;",
  "  anchors->length += 1;",
  "}",
  "",
  "static cJSON *pya_yaml_anchor_get(pya_yaml_anchors *anchors, const char *name) {",
  "  if (!anchors || !name) return NULL;",
  "  for (int i = 0; i < anchors->length; i++) {",
  "    if (anchors->names[i] && strcmp(anchors->names[i], name) == 0) return anchors->values[i];",
  "  }",
  "  return NULL;",
  "}",
  "",
  "static int pya_yaml_is_json_number(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  const char *p = s;",
  "  if (*p == '-') p++;",
  "  if (*p == '0') {",
  "    p++;",
  "  } else if (*p >= '1' && *p <= '9') {",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  } else {",
  "    return 0;",
  "  }",
  "  if (*p == '.') {",
  "    p++;",
  "    if (!(*p >= '0' && *p <= '9')) return 0;",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  }",
  "  if (*p == 'e' || *p == 'E') {",
  "    p++;",
  "    if (*p == '+' || *p == '-') p++;",
  "    if (!(*p >= '0' && *p <= '9')) return 0;",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  }",
  "  return *p == '\\0';",
  "}",
  "",
  "static void pya_yaml_trim(char *s) {",
  "  if (!s) return;",
  "  size_t len = strlen(s);",
  "  size_t start = 0;",
  "  while (start < len && isspace((unsigned char)s[start])) start++;",
  "  size_t end = len;",
  "  while (end > start && isspace((unsigned char)s[end - 1])) end--;",
  "  if (start > 0) memmove(s, s + start, end - start);",
  "  s[end - start] = '\\0';",
  "}",
  "",
  "static char *pya_yaml_key_text(const char *raw, yaml_scalar_style_t style, pya_yaml_error *err) {",
  "  if (!raw) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
  "  char buf[PYA_TEXT_CAP];",
  "  snprintf(buf, sizeof(buf), \"%s\", raw);",
  "  pya_yaml_trim(buf);",
  "  const int is_plain = (style == YAML_PLAIN_SCALAR_STYLE);",
  "  if (!is_plain) {",
  "    if (!buf[0]) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
  "    return pya_strdup(buf);",
  "  }",
  "  if (buf[0] == '\\0' || strcmp(buf, \"~\") == 0 || strcasecmp(buf, \"null\") == 0) return pya_strdup(\"null\");",
  "  if (strcasecmp(buf, \"true\") == 0) return pya_strdup(\"true\");",
  "  if (strcasecmp(buf, \"false\") == 0) return pya_strdup(\"false\");",
  "  if (pya_yaml_is_json_number(buf)) return pya_strdup(buf);",
  "  if (!buf[0]) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
];
