export const YAML_STRINGIFY_HELPER_PART_01 = [
  "/* PYA_YAML_STRINGIFY */",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_yaml_error;",
  "",
  "static void pya_yaml_set_error(pya_yaml_error *err, const char *msg, int line, int col) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", msg ? msg : \"yaml defective\");",
  "  err->line = line;",
  "  err->column = col;",
  "}",
  "",
  "typedef struct { const char *key; cJSON *value; } pya_yaml_kv;",
  "",
  "static int pya_yaml_compare_utf8(const void *a, const void *b) {",
  "  const pya_yaml_kv *ka = (const pya_yaml_kv *)a;",
  "  const pya_yaml_kv *kb = (const pya_yaml_kv *)b;",
  "  if (!ka->key || !kb->key) return 0;",
  "  return strcmp(ka->key, kb->key);",
  "}",
  "",
  "static cJSON *pya_yaml_canonicalize(cJSON *node) {",
  "  if (!node) return NULL;",
  "  if (cJSON_IsArray(node)) {",
  "    cJSON *arr = cJSON_CreateArray();",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      cJSON_AddItemToArray(arr, pya_yaml_canonicalize(child));",
  "    }",
  "    return arr;",
  "  }",
  "  if (cJSON_IsObject(node)) {",
  "    int count = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    cJSON *obj = cJSON_CreateObject();",
  "    for (int i = 0; i < count; i++) {",
  "      cJSON_AddItemToObject(obj, items[i].key, pya_yaml_canonicalize(items[i].value));",
  "    }",
  "    free(items);",
  "    return obj;",
  "  }",
  "  return cJSON_Duplicate(node, 1);",
  "}",
  "",
  "static void pya_yaml_emit_indent(char *out, int indent) {",
  "  for (int i = 0; i < indent; i++) pya_concat_buf(out, \" \");",
  "}",
  "",
  "static void pya_yaml_emit_quoted(char *out, const char *text) {",
  "  pya_concat_buf(out, \"\\\"\");",
  "  if (text) {",
  "    for (const char *p = text; *p; p++) {",
  "      if (*p == '\\\\' || *p == '\"') {",
  "        char esc[2] = { '\\\\', '\\0' };",
  "        pya_concat_buf(out, esc);",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      } else if (*p == '\\n') {",
  "        pya_concat_buf(out, \"\\\\n\");",
  "      } else {",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      }",
  "    }",
  "  }",
  "  pya_concat_buf(out, \"\\\"\");",
  "}",
  "",
  "static void pya_yaml_emit_value(char *out, cJSON *value, int indent) {",
  "  if (cJSON_IsNull(value)) { pya_concat_buf(out, \"null\"); return; }",
  "  if (cJSON_IsBool(value)) { pya_concat_buf(out, cJSON_IsTrue(value) ? \"true\" : \"false\"); return; }",
  "  if (cJSON_IsNumber(value)) { pya_concat_num_buf(out, value->valuedouble); return; }",
  "  if (cJSON_IsString(value)) { pya_yaml_emit_quoted(out, value->valuestring); return; }",
  "  if (cJSON_IsArray(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    for (cJSON *child = value->child; child; child = child->next) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_concat_buf(out, \"- \");",
  "      pya_yaml_emit_value(out, child, indent + 2);",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    return;",
  "  }",
  "  if (cJSON_IsObject(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    int count = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    for (int i = 0; i < count; i++) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_yaml_emit_quoted(out, items[i].key);",
  "      pya_concat_buf(out, \": \");",
  "      pya_yaml_emit_value(out, items[i].value, indent + 2);",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    free(items);",
  "    return;",
  "  }",
  "  pya_concat_buf(out, \"null\");",
  "}",
  "",
  "static int pya_json_to_yaml(const char *jsonText, char *out, pya_yaml_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  cJSON *root = cJSON_Parse(jsonText);",
  "  if (!root) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "  cJSON *canon = pya_yaml_canonicalize(root);",
  "  pya_yaml_emit_value(out, canon, 0);",
  "  cJSON_Delete(canon);",
  "  cJSON_Delete(root);",
  "  return 1;",
  "}"
];
