import fs from "node:fs/promises";
import { buildProgram } from "../../program.mjs";
import { doRemember } from "../../remember/index.mjs";

function transpileSentenceToJs(sentence) {
  const name = sentence?.subj?.name;
  const mood = sentence?.mood;
  if (!name || mood !== "ya") return null;

  const obj = sentence.obj ?? {};
  const beWords = (sentence.be || "").split(" ").filter(Boolean);
  const isPermanent = beWords[0] === "permanent";
  const baseBe = isPermanent ? beWords.slice(1).join(" ") : sentence.be;
  const decl = isPermanent ? "const" : "let";

  if (baseBe === "number" && typeof obj.num !== "undefined") {
    const value = typeof obj.num === "number" ? obj.num : Number(obj.num);
    return `${decl} ${name} = ${Number.isNaN(value) ? 0 : value};`;
  }

  if (baseBe === "text" && typeof obj.text === "string") {
    return `${decl} ${name} = ${JSON.stringify(obj.text)};`;
  }

  return null;
}

function transpileProgramToJs(sentences) {
  const lines = ["// Generated by Pyash compile"];
  for (const sentence of sentences) {
    const js = transpileSentenceToJs(sentence);
    lines.push(js ?? `// TODO: ${JSON.stringify(sentence)}`);
  }
  return lines.join("\n") + "\n";
}

async function compile_from_filename_to_filename(sentence) {
  const sourceFilename =
    sentence?.from?.filename ??
    sentence?.obj?.filename ??
    sentence?.filename;

  let sourceText = sentence?.fromtext?.text ?? sentence?.from?.text ?? sentence?.text ?? sentence?.obj?.text;

  if (!sourceText && sourceFilename) {
    sourceText = await fs.readFile(sourceFilename, "utf8");
  }
  if (typeof sourceText !== "string") {
    throw new Error("compile: source text is required (from text or from filename)");
  }

  // Allow escaped newlines in inline text blocks
  sourceText = sourceText.replaceAll("\\n", "\n");

  const program = buildProgram(sourceText);

  const jsBody = transpileProgramToJs(program.sentences);

  const targetFilename = sentence?.to?.filename;
  if (targetFilename) {
    await fs.writeFile(targetFilename, jsBody, "utf8");
  }

  const targetName = sentence?.to?.name ?? sentence?.totext?.name ?? sentence?.subj?.name;
  if (targetName) {
    doRemember({
      subj: { name: targetName },
      be: sentence?.become?.name ?? "javascript",
      obj: { text: jsBody, sentences: program.sentences },
      mood: "ya",
    });
  }

  return { obj: { text: jsBody, sentences: program.sentences }, be: sentence?.become?.name ?? "javascript" };
}

export default compile_from_filename_to_filename;

export const signatures = [
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "filename", "fromstate", "name", "num", "to", "filename"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "filename", "to", "filename"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "text", "to", "text"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "text", "to", "text"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "text", "to", "name", "num"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "text", "to", "name", "num"],
    handler: compile_from_filename_to_filename
  }
];
