import fs from "node:fs/promises";
import { buildProgram } from "../../program.mjs";
import { doRemember } from "../../remember/index.mjs";

function transpileSentence(sentence, { lang }) {
  const obj = sentence.obj ?? {};
  const beWords = (sentence.be || "").split(" ").filter(Boolean);
  const isPermanent = beWords[0] === "permanent";
  const baseBe = isPermanent ? beWords.slice(1).join(" ") : sentence.be;

  // Imperative add
  if (sentence.be === "add" && obj.num !== undefined && sentence.to?.name) {
    const safeValue = typeof obj.num === "number" ? obj.num : Number(obj.num);
    return `${sentence.to.name} = ${sentence.to.name} + ${Number.isNaN(safeValue) ? 0 : safeValue};`;
  }

  if (sentence.be === "subtract" && obj.num !== undefined && sentence.to?.name) {
    const safeValue = typeof obj.num === "number" ? obj.num : Number(obj.num);
    return `${sentence.to.name} = ${sentence.to.name} - ${Number.isNaN(safeValue) ? 0 : safeValue};`;
  }

  if (sentence.be === "multiply" && obj.num !== undefined && sentence.to?.name) {
    const safeValue = typeof obj.num === "number" ? obj.num : Number(obj.num);
    return `${sentence.to.name} = ${sentence.to.name} * ${Number.isNaN(safeValue) ? 0 : safeValue};`;
  }

  if (sentence.be === "divide" && obj.num !== undefined && sentence.to?.name) {
    const safeValue = typeof obj.num === "number" ? obj.num : Number(obj.num);
    const divisor = Number.isNaN(safeValue) ? 1 : safeValue;
    return `${sentence.to.name} = ${sentence.to.name} / ${divisor};`;
  }

  const name = sentence?.subj?.name;
  const mood = sentence?.mood;
  if (!name || mood !== "ya") return null;

  if (baseBe === "number" && typeof obj.num !== "undefined") {
    const value = typeof obj.num === "number" ? obj.num : Number(obj.num);
    const safeValue = Number.isNaN(value) ? 0 : value;
    if (lang === "c") {
      const decl = isPermanent ? "const double" : "double";
      return `${decl} ${name} = ${safeValue};`;
    }
    const decl = isPermanent ? "const" : "let";
    return `${decl} ${name} = ${safeValue};`;
  }

  if (baseBe === "text" && typeof obj.text === "string") {
    const value = JSON.stringify(obj.text);
    if (lang === "c") {
      const decl = isPermanent ? "const char *" : "char *";
      return `${decl} ${name} = ${value};`;
    }
    const decl = isPermanent ? "const" : "let";
    return `${decl} ${name} = ${value};`;
  }

  // Simple add to target name
  if (sentence.be === "add" && obj.num !== undefined && sentence.to?.name) {
    const safeValue = typeof obj.num === "number" ? obj.num : Number(obj.num);
    return `${sentence.to.name} = ${sentence.to.name} + ${Number.isNaN(safeValue) ? 0 : safeValue};`;
  }

  return null;
}

function transpileProgram(sentences, { lang }) {
  const header =
    lang === "c"
      ? "/* Generated by Pyash compile */"
      : "// Generated by Pyash compile";
  const lines = [header];
  for (const sentence of sentences) {
    const line = transpileSentence(sentence, { lang });
    const todoPrefix = lang === "c" ? "/* TODO" : "// TODO";
    const todoSuffix = lang === "c" ? " */" : "";
    lines.push(line ?? `${todoPrefix}: ${JSON.stringify(sentence)}${todoSuffix}`);
  }
  return lines.join("\n") + "\n";
}

async function compile_from_filename_to_filename(sentence) {
  const sourceFilename =
    sentence?.from?.filename ??
    sentence?.obj?.filename ??
    sentence?.filename;

  let sourceText = sentence?.fromtext?.text ?? sentence?.from?.text ?? sentence?.text ?? sentence?.obj?.text;

  if (!sourceText && sourceFilename) {
    sourceText = await fs.readFile(sourceFilename, "utf8");
  }
  if (typeof sourceText !== "string") {
    throw new Error("compile: source text is required (from text or from filename)");
  }

  // Allow escaped newlines in inline text blocks
  sourceText = sourceText.replaceAll("\\n", "\n");

  const program = buildProgram(sourceText);

  const targetLang = (sentence?.become?.name || "javascript").toLowerCase();
  const body = transpileProgram(program.sentences, { lang: targetLang });

  const targetFilename = sentence?.to?.filename;
  if (targetFilename) {
    await fs.writeFile(targetFilename, body, "utf8");
  }

  const targetName = sentence?.to?.name ?? sentence?.totext?.name ?? sentence?.subj?.name;
  if (targetName) {
    doRemember({
      subj: { name: targetName },
      be: sentence?.become?.name ?? "javascript",
      obj: { text: body, sentences: program.sentences },
      mood: "ya",
    });
  }

  return { obj: { text: body, sentences: program.sentences }, be: sentence?.become?.name ?? "javascript" };
}

export default compile_from_filename_to_filename;

export const signatures = [
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "filename", "fromstate", "name", "num", "to", "filename"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "filename", "to", "filename"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "text", "to", "text"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "text", "to", "text"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "become", "name", "num", "from", "text", "to", "name", "num"],
    handler: compile_from_filename_to_filename
  },
  {
    signatureWords: ["be", "compile", "from", "text", "to", "name", "num"],
    handler: compile_from_filename_to_filename
  }
];
