import { compositionalGrid } from "../../library/compositionalCases.mjs";
import {
  VYAH_ASPECT_MODIFIERS,
  VYAH_ASPECT_ALIASES,
  VYAH_TENSE_MODIFIERS,
  VYAH_OUTCOME_MODIFIERS,
  VYAH_ATTITUDINAL_MODIFIERS
} from "../../library/grammar/keywords.mjs";

const COMPOSITIONAL_CONTEXT_ORDER = [
  "space",
  "interior",
  "surface",
  "under",
  "time",
  "state",
  "person",
  "social",
  "discourse",
  "quantity"
];

const COMPOSITIONAL_PREPS = [];
for (const ctxKey of COMPOSITIONAL_CONTEXT_ORDER) {
  const ctx = compositionalGrid[ctxKey];
  if (!ctx) continue;
  for (const axis of ["source", "way", "destination"]) {
    const prep = ctx[axis]?.prep;
    if (prep && !COMPOSITIONAL_PREPS.includes(prep)) COMPOSITIONAL_PREPS.push(prep);
  }
}

const FORMAT_CASE_ORDER = ["su", "ob", "vyah", "fromindex", "atindex", "toindex", ...COMPOSITIONAL_PREPS];

export function vectorFormatHelper() {
  return [
    "function formatVector(values = [], type = \"num\") {",
    "  const tokens = [\"ve\", type];",
    "  for (const value of values) {",
    "    if (typeof value === \"number\") tokens.push(String(value));",
    "    else if (typeof value === \"boolean\") tokens.push(value ? \"truth\" : \"lie\");",
    "    else if (typeof value === \"string\") {",
    "      if (/^[A-Za-z0-9_.-]+$/.test(value)) tokens.push(value);",
    "      else tokens.push(JSON.stringify(value));",
    "    } else tokens.push(String(value));",
    "  }",
    "  return tokens.join(\" \");",
    "}",
    "function formatVectorSentence(name, vec) {",
    "  const v = vec || {};",
    "  return `su name ${name} ob ${formatVector(v.values || [], v.type || \"num\")} be vector ya`;",
    "}"
    ,
    "function compareUtf8(a, b) {",
    "  if (a === b) return 0;",
    "  const encoder = typeof TextEncoder !== \"undefined\" ? new TextEncoder() : null;",
    "  const bufA = encoder ? encoder.encode(String(a)) : Array.from(String(a), ch => ch.charCodeAt(0));",
    "  const bufB = encoder ? encoder.encode(String(b)) : Array.from(String(b), ch => ch.charCodeAt(0));",
    "  const len = Math.min(bufA.length, bufB.length);",
    "  for (let i = 0; i < len; i += 1) {",
    "    if (bufA[i] !== bufB[i]) return bufA[i] < bufB[i] ? -1 : 1;",
    "  }",
    "  return bufA.length < bufB.length ? -1 : 1;",
    "}",
    `const CASE_ORDER = ${JSON.stringify(FORMAT_CASE_ORDER)};`,
    `const VYAH_ASPECT = ${JSON.stringify(VYAH_ASPECT_MODIFIERS)};`,
    `const VYAH_ASPECT_ALIAS = ${JSON.stringify(VYAH_ASPECT_ALIASES)};`,
    `const VYAH_TENSE = ${JSON.stringify(VYAH_TENSE_MODIFIERS)};`,
    `const VYAH_OUTCOME = ${JSON.stringify(VYAH_OUTCOME_MODIFIERS)};`,
    `const VYAH_ATTITUDE = ${JSON.stringify(VYAH_ATTITUDINAL_MODIFIERS)};`,
    "function formatNp(np = {}) {",
    "  if (np.la) return `la ${formatSentence(np.la)} ko`;",
    "  if (np.unspecified) return \"unspecified\";",
    "  if (np.name !== undefined) return `name ${np.name}`;",
    "  if (np.hollow) return \"hollow\";",
    "  if (np.boolean !== undefined) return `bool ${np.boolean ? \"truth\" : \"lie\"}`;",
    "  if (np.num !== undefined) return `num ${np.num}`;",
    "  if (np.text !== undefined) return `text ${JSON.stringify(np.text)}`;",
    "  if (np.filename !== undefined) return `filename ${np.filename}`;",
    "  if (np.ve) return formatVector(np.ve.values || [], np.ve.type || \"num\");",
    "  return \"\";",
    "}",
    "function orderVyah(values = []) {",
    "  const aspects = [];",
    "  const tenses = [];",
    "  const outcomes = [];",
    "  const attitudes = [];",
    "  const other = [];",
    "  for (const raw of values) {",
    "    const tokenRaw = typeof raw === \"string\" ? raw : String(raw ?? \"\");",
    "    const token = VYAH_ASPECT_ALIAS[String(tokenRaw).toLowerCase()] ?? tokenRaw;",
    "    if (!token) continue;",
    "    if (VYAH_ASPECT.includes(token)) aspects.push(token);",
    "    else if (VYAH_TENSE.includes(token)) tenses.push(token);",
    "    else if (VYAH_OUTCOME.includes(token)) outcomes.push(token);",
    "    else if (VYAH_ATTITUDE.includes(token)) attitudes.push(token);",
    "    else other.push(token);",
    "  }",
    "  return [...aspects, ...tenses, ...other, ...outcomes, ...attitudes];",
    "}",
    "function formatSentence(sentence = {}) {",
    "  const parts = [];",
    "  if (sentence.exists) parts.push(\"exists\");",
    "  for (const key of CASE_ORDER) {",
    "    if (sentence[key] === undefined) continue;",
    "    if (key === \"vyah\") {",
    "      const values = sentence.vyah?.ve?.values ?? [];",
    "      const ordered = orderVyah(values);",
    "      parts.push(\"vyah\");",
    "      if (ordered.length) parts.push(ordered.join(\" \"));",
    "    } else {",
    "      parts.push(key, formatNp(sentence[key]));",
    "    }",
    "  }",
    "  if (sentence.be) parts.push(\"be\", sentence.be);",
    "  parts.push(sentence.mood || \"ya\");",
    "  return parts.join(\" \");",
    "}",
    "function formatMapSentence(name, mapFact) {",
    "  const kind = mapFact?.be === \"csv map\" ? \"csv map\" : (mapFact?.be === \"json map\" ? \"json map\" : \"map\");",
    "  const entries = mapFact?.ob?.map ?? {};",
    "  const lines = [`su name ${name} be ${kind} def`];",
    "  let orderedKeys = Object.keys(entries).sort(compareUtf8);",
    "  if (kind === \"csv map\") {",
    "    const headerRaw = entries[\"header raw\"]?.ve?.values;",
    "    const header = entries.header?.ve?.values;",
    "    orderedKeys = [];",
    "    if (headerRaw) orderedKeys.push(\"header raw\");",
    "    if (header) orderedKeys.push(\"header\");",
    "    if (Array.isArray(header)) {",
    "      for (const key of header) {",
    "        if (typeof key === \"string\") orderedKeys.push(key);",
    "      }",
    "    }",
    "    for (const key of Object.keys(entries).sort(compareUtf8)) {",
    "      if (!orderedKeys.includes(key)) orderedKeys.push(key);",
    "    }",
    "  }",
    "  for (const key of orderedKeys) {",
    "    const entry = entries[key];",
    "    if (kind === \"map\" && entry && typeof entry === \"object\" && entry.mood) {",
    "      lines.push(formatSentence(entry));",
    "    } else {",
    "      lines.push(`su name ${key} ob ${formatNp(entry || {})} ya`);",
    "    }",
    "  }",
    "  lines.push(\"prah\");",
    "  return lines.join(\"\\n\");",
    "}"
  ].join("\n");
}
