export const VECTOR_TYPE_DECL = "typedef struct { const char *type; int length; double *num_values; const char **text_values; } pya_vec;";

export const VECTOR_PRINT_HELPER = [
  "static int is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void print_vec_inline(const pya_vec *vec) {",
  "  if (!vec) { printf(\"ve num\"); return; }",
  "  const char *type = vec->type ? vec->type : \"num\";",
  "  printf(\"ve %s\", type);",
  "  if (strcmp(type, \"bool\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      printf(\" %s\", vec->num_values[i] != 0 ? \"truth\" : \"lie\");",
  "    }",
  "    return;",
  "  }",
  "  if (strcmp(type, \"text\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      const char *val = vec->text_values[i];",
  "      if (is_safe_token(val)) {",
  "        printf(\" %s\", val);",
  "      } else {",
  "        printf(\" \\\"\");",
  "        print_escaped(val);",
  "        printf(\"\\\"\");",
  "      }",
  "    }",
  "    return;",
  "  }",
  "  for (int i = 0; i < vec->length; i++) { printf(\" %g\", vec->num_values[i]); }",
  "}",
  "static void print_vec(const pya_vec *vec) {",
  "  print_vec_inline(vec);",
  "  printf(\"\\n\");",
  "}",
  "static void print_vec_sentence(const char *name, const pya_vec *vec) {",
  "  printf(\"su name %s ob \", name ? name : \"\");",
  "  print_vec_inline(vec);",
  "  printf(\" be vector ya\\n\");",
  "}"
].join("\n");

export const TEXT_HELPER = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "static void pya_concat_buf(char *dest, const char *src) {",
  "  if (!dest || !src) return;",
  "  size_t dlen = strlen(dest);",
  "  if (dlen >= PYA_TEXT_CAP - 1) return;",
  "  strncat(dest, src, PYA_TEXT_CAP - dlen - 1);",
  "}",
  "static void pya_concat_num_buf(char *dest, double value) {",
  "  char buf[64];",
  "  snprintf(buf, sizeof(buf), \"%g\", value);",
  "  pya_concat_buf(dest, buf);",
  "}"
].join("\n");

export const JSON_PYASH_HELPER = [
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_json_error;",
  "",
  "typedef struct {",
  "  char **items;",
  "  int length;",
  "  int cap;",
  "} pya_used_names;",
  "",
  "static char *pya_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static void pya_used_init(pya_used_names *used) {",
  "  if (!used) return;",
  "  used->items = NULL;",
  "  used->length = 0;",
  "  used->cap = 0;",
  "}",
  "",
  "static void pya_used_free(pya_used_names *used) {",
  "  if (!used) return;",
  "  for (int i = 0; i < used->length; i++) free(used->items[i]);",
  "  free(used->items);",
  "  used->items = NULL;",
  "  used->length = 0;",
  "  used->cap = 0;",
  "}",
  "",
  "static int pya_used_has(const pya_used_names *used, const char *name) {",
  "  if (!used || !name) return 0;",
  "  for (int i = 0; i < used->length; i++) {",
  "    if (used->items[i] && strcmp(used->items[i], name) == 0) return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static void pya_used_add(pya_used_names *used, const char *name) {",
  "  if (!used || !name) return;",
  "  if (pya_used_has(used, name)) return;",
  "  if (used->length >= used->cap) {",
  "    int next = used->cap == 0 ? 8 : used->cap * 2;",
  "    char **nextItems = (char **)realloc(used->items, sizeof(char *) * next);",
  "    if (!nextItems) return;",
  "    used->items = nextItems;",
  "    used->cap = next;",
  "  }",
  "  used->items[used->length++] = pya_strdup(name);",
  "}",
  "",
  "static void pya_sanitize_name_part(const char *raw, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  out[0] = '\\0';",
  "  if (!raw) { snprintf(out, cap, \"item\"); return; }",
  "  size_t len = strlen(raw);",
  "  char buf[PYA_TEXT_CAP];",
  "  size_t idx = 0;",
  "  int lastSpace = 1;",
  "  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
  "    char ch = raw[i];",
  "    int ok = (isalnum((unsigned char)ch) || ch == '_' || ch == '.' || ch == '-');",
  "    if (ok) {",
  "      buf[idx++] = ch;",
  "      lastSpace = 0;",
  "    } else if (!lastSpace) {",
  "      buf[idx++] = ' ';",
  "      lastSpace = 1;",
  "    }",
  "  }",
  "  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
  "  buf[idx] = '\\0';",
  "  if (idx == 0) { snprintf(out, cap, \"item\"); return; }",
  "  snprintf(out, cap, \"%s\", buf);",
  "}",
  "",
  "static char *pya_unique_name(const char *base, pya_used_names *used) {",
  "  if (!base || !used) return NULL;",
  "  if (!pya_used_has(used, base)) {",
  "    pya_used_add(used, base);",
  "    return pya_strdup(base);",
  "  }",
  "  int i = 2;",
  "  char candidate[PYA_TEXT_CAP];",
  "  while (1) {",
  "    snprintf(candidate, sizeof(candidate), \"%s %d\", base, i);",
  "    if (!pya_used_has(used, candidate)) {",
  "      pya_used_add(used, candidate);",
  "      return pya_strdup(candidate);",
  "    }",
  "    i += 1;",
  "  }",
  "}",
  "",
  "static void pya_json_error_loc(const char *json, const char *pos, int *line, int *column) {",
  "  int l = 1;",
  "  int c = 1;",
  "  if (!json || !pos || pos < json) {",
  "    if (line) *line = l;",
  "    if (column) *column = c;",
  "    return;",
  "  }",
  "  for (const char *p = json; p < pos && *p; p++) {",
  "    if (*p == '\\n') {",
  "      l += 1;",
  "      c = 1;",
  "    } else {",
  "      c += 1;",
  "    }",
  "  }",
  "  if (line) *line = l;",
  "  if (column) *column = c;",
  "}",
  "",
  "static void pya_set_json_error(pya_json_error *err, const char *message, const char *json, const char *pos) {",
  "  if (!err) return;",
  "  snprintf(err->message, PYA_TEXT_CAP, \"%s\", message ? message : \"json map defective\");",
  "  pya_json_error_loc(json, pos, &err->line, &err->column);",
  "}",
  "",
  "static void pya_append_json_string(char *out, const char *text) {",
  "  pya_concat_buf(out, \"\\\"\");",
  "  if (text) {",
  "    for (const char *p = text; *p; p++) {",
  "      char ch = *p;",
  "      if (ch == '\\\\' || ch == '\"') {",
  "        char tmp[3] = { '\\\\', ch, '\\0' };",
  "        pya_concat_buf(out, tmp);",
  "      } else if (ch == '\\n') {",
  "        pya_concat_buf(out, \"\\\\n\");",
  "      } else {",
  "        char tmp[2] = { ch, '\\0' };",
  "        pya_concat_buf(out, tmp);",
  "      }",
  "    }",
  "  }",
  "  pya_concat_buf(out, \"\\\"\");",
  "}",
  "",
  "static int pya_is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "",
  "static void pya_append_token(char *out, const char *token) {",
  "  if (pya_is_safe_token(token)) {",
  "    pya_concat_buf(out, token);",
  "  } else {",
  "    pya_append_json_string(out, token);",
  "  }",
  "}",
  "",
  "static int pya_read_file_text(const char *path, char *out) {",
  "  if (!out || !path) return 0;",
  "  FILE *f = fopen(path, \"r\");",
  "  if (!f) return 0;",
  "  size_t len = fread(out, 1, PYA_TEXT_CAP - 1, f);",
  "  out[len] = '\\0';",
  "  fclose(f);",
  "  return 1;",
  "}",
  "",
  "static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json);",
  "",
  "static void pya_append_vector_values(char *out, const char *type, cJSON *array) {",
  "  pya_concat_buf(out, \"ve \");",
  "  pya_concat_buf(out, type);",
  "  int idx = 0;",
  "  for (cJSON *item = array ? array->child : NULL; item; item = item->next, idx++) {",
  "    pya_concat_buf(out, \" \");",
  "    if (strcmp(type, \"bool\") == 0) {",
  "      pya_concat_buf(out, cJSON_IsTrue(item) ? \"truth\" : \"lie\");",
  "    } else if (strcmp(type, \"num\") == 0) {",
  "      char buf[64];",
  "      snprintf(buf, sizeof(buf), \"%g\", item->valuedouble);",
  "      pya_concat_buf(out, buf);",
  "    } else if (strcmp(type, \"text\") == 0) {",
  "      pya_append_json_string(out, cJSON_GetStringValue(item));",
  "    } else if (strcmp(type, \"name\") == 0) {",
  "      pya_concat_buf(out, cJSON_GetStringValue(item));",
  "    }",
  "  }",
  "}",
  "",
  "static void pya_append_np_for_value(char *line, cJSON *value, const char *parentName, const char *key, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
  "  if (!value) { pya_concat_buf(line, \"hollow\"); return; }",
  "  if (cJSON_IsNull(value)) { pya_concat_buf(line, \"hollow\"); return; }",
  "  if (cJSON_IsString(value)) {",
  "    pya_concat_buf(line, \"text \");",
  "    pya_append_json_string(line, cJSON_GetStringValue(value));",
  "    return;",
  "  }",
  "  if (cJSON_IsNumber(value)) {",
  "    char buf[64];",
  "    snprintf(buf, sizeof(buf), \"%g\", value->valuedouble);",
  "    pya_concat_buf(line, \"num \");",
  "    pya_concat_buf(line, buf);",
  "    return;",
  "  }",
  "  if (cJSON_IsBool(value)) {",
  "    pya_concat_buf(line, \"bool \");",
  "    pya_concat_buf(line, cJSON_IsTrue(value) ? \"truth\" : \"lie\");",
  "    return;",
  "  }",
  "  if (cJSON_IsArray(value)) {",
  "    int hasArray = 0;",
  "    int hasNull = 0;",
  "    int hasObject = 0;",
  "    int hasBool = 0;",
  "    int hasNum = 0;",
  "    int hasText = 0;",
  "    int length = 0;",
  "    for (cJSON *item = value->child; item; item = item->next) {",
  "      length += 1;",
  "      if (cJSON_IsArray(item)) hasArray = 1;",
  "      else if (cJSON_IsNull(item)) hasNull = 1;",
  "      else if (cJSON_IsObject(item)) hasObject = 1;",
  "      else if (cJSON_IsBool(item)) hasBool = 1;",
  "      else if (cJSON_IsNumber(item)) hasNum = 1;",
  "      else if (cJSON_IsString(item)) hasText = 1;",
  "    }",
  "    if (length == 0) {",
  "      pya_concat_buf(line, \"ve hollow\");",
  "      return;",
  "    }",
  "    if (hasArray) {",
  "      pya_set_json_error(err, \"json map contents defective: nested arrays are unsupported\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasNull) {",
  "      pya_set_json_error(err, \"json map contents defective: null elements are unsupported in arrays\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasObject && (hasBool || hasNum || hasText)) {",
  "      pya_set_json_error(err, \"json map contents defective: mixed array types are unsupported\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasObject) {",
  "      pya_concat_buf(line, \"ve name\");",
  "      int idx = 0;",
  "      for (cJSON *item = value->child; item; item = item->next, idx++) {",
  "        char keyPart[PYA_TEXT_CAP];",
  "        pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
  "        char base[PYA_TEXT_CAP];",
  "        snprintf(base, sizeof(base), \"%s %s %d\", parentName, keyPart, idx + 1);",
  "        char *childName = pya_unique_name(base, used);",
  "        if (childName) {",
  "          pya_emit_map(item, childName, used, chain, err, json);",
  "          pya_concat_buf(line, \" \");",
  "          pya_append_token(line, childName);",
  "          free(childName);",
  "        }",
  "      }",
  "      return;",
  "    }",
  "    if (hasBool && !(hasNum || hasText)) {",
  "      pya_append_vector_values(line, \"bool\", value);",
  "      return;",
  "    }",
  "    if (hasNum && !hasText) {",
  "      pya_append_vector_values(line, \"num\", value);",
  "      return;",
  "    }",
  "    pya_append_vector_values(line, \"text\", value);",
  "    return;",
  "  }",
  "  if (cJSON_IsObject(value)) {",
  "    char keyPart[PYA_TEXT_CAP];",
  "    pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
  "    char base[PYA_TEXT_CAP];",
  "    snprintf(base, sizeof(base), \"%s %s\", parentName, keyPart);",
  "    char *childName = pya_unique_name(base, used);",
  "    if (childName) {",
  "      pya_emit_map(value, childName, used, chain, err, json);",
  "      pya_concat_buf(line, \"name \");",
  "      pya_concat_buf(line, childName);",
  "      free(childName);",
  "    }",
  "    return;",
  "  }",
  "}",
  "",
  "static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
  "  if (!obj || !cJSON_IsObject(obj)) {",
  "    pya_set_json_error(err, \"json map contents defective: object expected\", json, cJSON_GetErrorPtr());",
  "    return;",
  "  }",
  "  char block[PYA_TEXT_CAP];",
  "  block[0] = '\\0';",
  "  pya_concat_buf(block, \"su name \");",
  "  pya_concat_buf(block, name ? name : \"map\");",
  "  pya_concat_buf(block, \" be json map def\\n\");",
  "  for (cJSON *entry = obj->child; entry; entry = entry->next) {",
  "    if (!entry->string) continue;",
  "    pya_concat_buf(block, \"su name \");",
  "    pya_concat_buf(block, entry->string);",
  "    pya_concat_buf(block, \" ob \");",
  "    pya_append_np_for_value(block, entry, name, entry->string, used, chain, err, json);",
  "    if (err && err->message[0] != '\\0') return;",
  "    pya_concat_buf(block, \" ya\\n\");",
  "  }",
  "  pya_concat_buf(block, \"prah\\n\");",
  "  if (chain[0] != '\\0') pya_concat_buf(chain, \"\\n\");",
  "  pya_concat_buf(chain, block);",
  "}",
  "",
  "static int pya_json_to_pyash(const char *jsonText, const char *rootName, char *out, pya_json_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  if (!jsonText) {",
  "    pya_set_json_error(err, \"import: invalid json\", jsonText, jsonText);",
  "    return 0;",
  "  }",
  "  const char *parseEnd = NULL;",
  "  cJSON *root = cJSON_ParseWithOpts(jsonText, &parseEnd, 0);",
  "  if (!root) {",
  "    const char *errPtr = cJSON_GetErrorPtr();",
  "    pya_set_json_error(err, \"import: invalid json\", jsonText, errPtr);",
  "    return 0;",
  "  }",
  "  pya_used_names used;",
  "  pya_used_init(&used);",
  "  char clean[PYA_TEXT_CAP];",
  "  pya_sanitize_name_part(rootName ? rootName : \"data\", clean, sizeof(clean));",
  "  char *rootSafe = pya_unique_name(clean, &used);",
  "  pya_emit_map(root, rootSafe ? rootSafe : \"data\", &used, out, err, jsonText);",
  "  if (rootSafe) free(rootSafe);",
  "  pya_used_free(&used);",
  "  cJSON_Delete(root);",
  "  if (err && err->message[0] != '\\0') return 0;",
  "  return 1;",
  "}"
].join("\n");

export const MAP_TYPE_DECL = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "#define PYA_MAP_NUM 1",
  "#define PYA_MAP_TEXT 2",
  "#define PYA_MAP_BOOL 3",
  "#define PYA_MAP_HOLLOW 4",
  "typedef struct { const char *key; int kind; double num; int boolean; char text[PYA_TEXT_CAP]; } pya_map_entry;",
  "typedef struct { int length; int cap; pya_map_entry *entries; } pya_map;"
].join("\n");

export const MAP_HELPER = [
  "static void pya_map_init(pya_map *map) {",
  "  if (!map) return;",
  "  map->length = 0;",
  "  map->cap = 0;",
  "  map->entries = NULL;",
  "}",
  "static int pya_map_find(pya_map *map, const char *key) {",
  "  if (!map || !key) return -1;",
  "  for (int i = 0; i < map->length; i++) {",
  "    if (map->entries[i].key && strcmp(map->entries[i].key, key) == 0) return i;",
  "  }",
  "  return -1;",
  "}",
  "static void pya_map_reserve(pya_map *map) {",
  "  if (!map) return;",
  "  if (map->length < map->cap) return;",
  "  int next = map->cap == 0 ? 8 : map->cap * 2;",
  "  pya_map_entry *nextEntries = (pya_map_entry *)realloc(map->entries, sizeof(pya_map_entry) * next);",
  "  if (!nextEntries) return;",
  "  map->entries = nextEntries;",
  "  map->cap = next;",
  "}",
  "static pya_map_entry *pya_map_get_or_add(pya_map *map, const char *key) {",
  "  if (!map || !key) return NULL;",
  "  int idx = pya_map_find(map, key);",
  "  if (idx >= 0) return &map->entries[idx];",
  "  pya_map_reserve(map);",
  "  if (map->length >= map->cap) return NULL;",
  "  pya_map_entry *entry = &map->entries[map->length++];",
  "  entry->key = key;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = 0;",
  "  entry->boolean = 0;",
  "  entry->text[0] = '\\0';",
  "  return entry;",
  "}",
  "static void pya_map_set_num(pya_map *map, const char *key, double value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = value;",
  "}",
  "static void pya_map_set_text(pya_map *map, const char *key, const char *value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_TEXT;",
  "  snprintf(entry->text, PYA_TEXT_CAP, \"%s\", value ? value : \"\");",
  "}",
  "static void pya_map_set_bool(pya_map *map, const char *key, int value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_BOOL;",
  "  entry->boolean = value ? 1 : 0;",
  "}",
  "static void pya_map_set_hollow(pya_map *map, const char *key) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_HOLLOW;",
  "}",
  "static void pya_map_add_num(pya_map *map, const char *key, double delta) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  if (entry->kind != PYA_MAP_NUM) {",
  "    entry->kind = PYA_MAP_NUM;",
  "    entry->num = 0;",
  "  }",
  "  entry->num += delta;",
  "}",
  "static int map_is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void map_print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void print_map_sentence(const char *name, const pya_map *map) {",
  "  printf(\"su name %s be map def\\n\", name ? name : \"\");",
  "  if (!map) {",
  "    printf(\"prah\\n\");",
  "    return;",
  "  }",
  "  for (int i = 0; i < map->length; i++) {",
  "    const pya_map_entry *entry = &map->entries[i];",
  "    if (!entry->key) continue;",
  "    if (map_is_safe_token(entry->key)) {",
  "      printf(\"su name %s ob \", entry->key);",
  "    } else {",
  "      printf(\"su name \\\"\");",
  "      map_print_escaped(entry->key);",
  "      printf(\"\\\" ob \");",
  "    }",
  "    if (entry->kind == PYA_MAP_TEXT) {",
  "      printf(\"text \\\"\");",
  "      map_print_escaped(entry->text);",
  "      printf(\"\\\"\");",
  "    } else if (entry->kind == PYA_MAP_BOOL) {",
  "      printf(\"bool %s\", entry->boolean ? \"truth\" : \"lie\");",
  "    } else if (entry->kind == PYA_MAP_HOLLOW) {",
  "      printf(\"hollow\");",
  "    } else {",
  "      printf(\"num %g\", entry->num);",
  "    }",
  "    printf(\" ya\\n\");",
  "  }",
  "  printf(\"prah\\n\");",
  "}"
].join("\n");

export const CSV_RUNTIME_HELPER = [
  "#define PYA_CSV_RUNTIME 1",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_csv_error;",
  "typedef struct {",
  "  char **cells;",
  "  size_t count;",
  "} pya_csv_row;",
  "typedef struct {",
  "  pya_csv_row *rows;",
  "  size_t length;",
  "  size_t cap;",
  "} pya_csv_rows;",
  "typedef struct {",
  "  char **header_raw;",
  "  char **header;",
  "  size_t width;",
  "  size_t rows;",
  "  char ***columns;",
  "} pya_csv_map;",
  "typedef struct {",
  "  char *name;",
  "  pya_csv_map map;",
  "} pya_csv_named;",
  "static pya_csv_named *pya_csv_maps = NULL;",
  "static size_t pya_csv_map_count = 0;",
  "static size_t pya_csv_map_cap = 0;",
  "static char *pya_csv_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "static void pya_csv_set_error(pya_csv_error *err, const char *message, int line, int column) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", message ? message : \"csv defective\");",
  "  err->line = line;",
  "  err->column = column;",
  "}",
  "static int pya_csv_is_blank(const char *s) {",
  "  if (!s) return 1;",
  "  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
  "    if (!isspace(*p)) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void pya_csv_lower_trim(const char *s, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  out[0] = '\\0';",
  "  if (!s) return;",
  "  size_t len = strlen(s);",
  "  char buf[PYA_TEXT_CAP];",
  "  size_t idx = 0;",
  "  int lastSpace = 1;",
  "  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
  "    unsigned char ch = (unsigned char)s[i];",
  "    if (isspace(ch)) {",
  "      if (!lastSpace) { buf[idx++] = ' '; lastSpace = 1; }",
  "    } else {",
  "      buf[idx++] = (char)tolower(ch);",
  "      lastSpace = 0;",
  "    }",
  "  }",
  "  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
  "  buf[idx] = '\\0';",
  "  snprintf(out, cap, \"%s\", buf);",
  "}",
  "static int pya_csv_eq_lower(const char *s, const char *target) {",
  "  char buf[PYA_TEXT_CAP];",
  "  pya_csv_lower_trim(s, buf, sizeof(buf));",
  "  return strcmp(buf, target) == 0;",
  "}",
  "static void pya_csv_rows_push(pya_csv_rows *rows, pya_csv_row row) {",
  "  if (!rows) return;",
  "  if (rows->length >= rows->cap) {",
  "    size_t next = rows->cap == 0 ? 16 : rows->cap * 2;",
  "    pya_csv_row *nextRows = (pya_csv_row *)realloc(rows->rows, sizeof(pya_csv_row) * next);",
  "    if (!nextRows) return;",
  "    rows->rows = nextRows;",
  "    rows->cap = next;",
  "  }",
  "  rows->rows[rows->length++] = row;",
  "}",
  "struct pya_csv_parse_ctx { zsv_parser parser; pya_csv_rows rows; };",
  "static void pya_csv_row_handler(void *ctx) {",
  "  struct pya_csv_parse_ctx *data = ctx;",
  "  size_t count = zsv_cell_count(data->parser);",
  "  char **cells = count ? (char **)calloc(count, sizeof(char *)) : NULL;",
  "  for (size_t i = 0; i < count; i++) {",
  "    struct zsv_cell cell = zsv_get_cell(data->parser, i);",
  "    char *value = (char *)malloc(cell.len + 1);",
  "    if (!value) continue;",
  "    memcpy(value, cell.str, cell.len);",
  "    value[cell.len] = '\\0';",
  "    cells[i] = value;",
  "  }",
  "  pya_csv_row row = { cells, count };",
  "  pya_csv_rows_push(&data->rows, row);",
  "}",
  "static void pya_csv_free_row(pya_csv_row *row) {",
  "  if (!row) return;",
  "  for (size_t i = 0; i < row->count; i++) free(row->cells[i]);",
  "  free(row->cells);",
  "  row->cells = NULL;",
  "  row->count = 0;",
  "}",
  "static void pya_csv_map_free(pya_csv_map *map) {",
  "  if (!map) return;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    free(map->header_raw[i]);",
  "    free(map->header[i]);",
  "    for (size_t r = 0; r < map->rows; r++) free(map->columns[i][r]);",
  "    free(map->columns[i]);",
  "  }",
  "  free(map->header_raw);",
  "  free(map->header);",
  "  free(map->columns);",
  "  map->header_raw = NULL;",
  "  map->header = NULL;",
  "  map->columns = NULL;",
  "  map->width = 0;",
  "  map->rows = 0;",
  "}",
  "static pya_csv_map *pya_csv_find(const char *name) {",
  "  if (!name) return NULL;",
  "  for (size_t i = 0; i < pya_csv_map_count; i++) {",
  "    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) return &pya_csv_maps[i].map;",
  "  }",
  "  return NULL;",
  "}",
  "static void pya_csv_store(const char *name, pya_csv_map *map) {",
  "  if (!name || !map) return;",
  "  for (size_t i = 0; i < pya_csv_map_count; i++) {",
  "    if (pya_csv_maps[i].name && strcmp(pya_csv_maps[i].name, name) == 0) {",
  "      pya_csv_map_free(&pya_csv_maps[i].map);",
  "      pya_csv_maps[i].map = *map;",
  "      return;",
  "    }",
  "  }",
  "  if (pya_csv_map_count >= pya_csv_map_cap) {",
  "    size_t next = pya_csv_map_cap == 0 ? 8 : pya_csv_map_cap * 2;",
  "    pya_csv_named *nextMaps = (pya_csv_named *)realloc(pya_csv_maps, sizeof(pya_csv_named) * next);",
  "    if (!nextMaps) return;",
  "    pya_csv_maps = nextMaps;",
  "    pya_csv_map_cap = next;",
  "  }",
  "  pya_csv_maps[pya_csv_map_count].name = pya_csv_strdup(name);",
  "  pya_csv_maps[pya_csv_map_count].map = *map;",
  "  pya_csv_map_count += 1;",
  "}",
  "static int pya_csv_build_map(pya_csv_rows *rows, pya_csv_map *out, pya_csv_error *err) {",
  "  if (!rows || rows->length == 0) {",
  "    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
  "    return 0;",
  "  }",
  "  size_t nonEmpty = rows->length;",
  "  for (size_t i = 0; i < rows->length; i++) {",
  "    int has = 0;",
  "    for (size_t c = 0; c < rows->rows[i].count; c++) {",
  "      if (!pya_csv_is_blank(rows->rows[i].cells[c])) { has = 1; break; }",
  "    }",
  "    if (has) { nonEmpty = i; break; }",
  "  }",
  "  if (nonEmpty >= rows->length) {",
  "    pya_csv_set_error(err, \"csv header defective\", 1, 1);",
  "    return 0;",
  "  }",
  "  size_t headerRowIndex = rows->length;",
  "  for (size_t i = 0; i < rows->length; i++) {",
  "    if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"column labels:\")) {",
  "      headerRowIndex = i; break;",
  "    }",
  "  }",
  "  int isTemplate = headerRowIndex < rows->length;",
  "  if (!isTemplate) headerRowIndex = nonEmpty;",
  "  pya_csv_row headerRow = rows->rows[headerRowIndex];",
  "  size_t headerCount = headerRow.count > 0 ? headerRow.count - (isTemplate ? 1 : 0) : 0;",
  "  if (headerCount == 0) {",
  "    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
  "    return 0;",
  "  }",
  "  size_t nameRowIndex = rows->length;",
  "  if (isTemplate) {",
  "    for (size_t i = headerRowIndex + 1; i < rows->length; i++) {",
  "      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"column name:\")) {",
  "        nameRowIndex = i; break;",
  "      }",
  "    }",
  "  }",
  "  pya_csv_row nameRow = nameRowIndex < rows->length ? rows->rows[nameRowIndex] : (pya_csv_row){0};",
  "  char *drop = (char *)calloc(headerCount, 1);",
  "  for (size_t i = 0; i < headerCount; i++) {",
  "    const char *cell = headerRow.cells[i + (isTemplate ? 1 : 0)];",
  "    if (!pya_csv_is_blank(cell)) continue;",
  "    const char *marker = (nameRow.count > i + 1) ? nameRow.cells[i + 1] : \"\";",
  "    if (pya_csv_is_blank(marker) || (marker && strcmp(marker, \"~\") == 0)) drop[i] = 1;",
  "  }",
  "  size_t filteredCount = 0;",
  "  for (size_t i = 0; i < headerCount; i++) if (!drop[i]) filteredCount++;",
  "  if (filteredCount == 0) {",
  "    free(drop);",
  "    pya_csv_set_error(err, \"csv header defective\", (int)headerRowIndex + 1, 1);",
  "    return 0;",
  "  }",
  "  char **header_raw = (char **)calloc(filteredCount, sizeof(char *));",
  "  char **header = (char **)calloc(filteredCount, sizeof(char *));",
  "  size_t headerIdx = 0;",
  "  for (size_t i = 0; i < headerCount; i++) {",
  "    if (drop[i]) continue;",
  "    const char *cell = headerRow.cells[i + (isTemplate ? 1 : 0)];",
  "    header_raw[headerIdx] = pya_csv_strdup(cell ? cell : \"\");",
  "    char norm[PYA_TEXT_CAP];",
  "    pya_csv_lower_trim(cell, norm, sizeof(norm));",
  "    header[headerIdx] = pya_csv_strdup(norm);",
  "    headerIdx++;",
  "  }",
  "  if (isTemplate) {",
  "    for (size_t i = 0; i < filteredCount; i++) {",
  "      if (!header[i] || !*header[i]) continue;",
  "      int count = 0;",
  "      for (size_t j = 0; j < i; j++) if (header[j] && strcmp(header[j], header[i]) == 0) count++;",
  "      if (count > 0) {",
  "        char buf[PYA_TEXT_CAP];",
  "        snprintf(buf, sizeof(buf), \"%s %d\", header[i], count + 1);",
  "        free(header[i]);",
  "        header[i] = pya_csv_strdup(buf);",
  "      }",
  "    }",
  "  }",
  "  const char *metaLabels[] = {\"column name:\",\"mandatory:\",\"type:\",\"info:\",\"doctype:\",\"start entering data below this line\"};",
  "  size_t dataStart = headerRowIndex + 1;",
  "  if (isTemplate) {",
  "    for (size_t i = headerRowIndex + 1; i < rows->length; i++) {",
  "      if (rows->rows[i].count > 0 && pya_csv_eq_lower(rows->rows[i].cells[0], \"start entering data below this line\")) {",
  "        dataStart = i + 1; break;",
  "      }",
  "    }",
  "  }",
  "  size_t dataCount = 0;",
  "  for (size_t r = dataStart; r < rows->length; r++) {",
  "    pya_csv_row row = rows->rows[r];",
  "    if (isTemplate) {",
  "      int isMeta = 0;",
  "      if (row.count > 0) {",
  "        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
  "          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
  "        }",
  "      }",
  "      if (isMeta) continue;",
  "      int allBlank = 1;",
  "      for (size_t c = 0; c < row.count; c++) {",
  "        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
  "      }",
  "      if (allBlank) continue;",
  "    }",
  "    dataCount++;",
  "  }",
  "  char ***columns = (char ***)calloc(filteredCount, sizeof(char **));",
  "  for (size_t i = 0; i < filteredCount; i++) columns[i] = (char **)calloc(dataCount, sizeof(char *));",
  "  size_t rowIndex = 0;",
  "  for (size_t r = dataStart; r < rows->length; r++) {",
  "    pya_csv_row row = rows->rows[r];",
  "    if (isTemplate) {",
  "      int isMeta = 0;",
  "      if (row.count > 0) {",
  "        for (size_t m = 0; m < sizeof(metaLabels)/sizeof(metaLabels[0]); m++) {",
  "          if (pya_csv_eq_lower(row.cells[0], metaLabels[m])) { isMeta = 1; break; }",
  "        }",
  "      }",
  "      if (isMeta) continue;",
  "      int allBlank = 1;",
  "      for (size_t c = 0; c < row.count; c++) {",
  "        if (!pya_csv_is_blank(row.cells[c])) { allBlank = 0; break; }",
  "      }",
  "      if (allBlank) continue;",
  "    }",
  "    size_t dataLen = row.count > 0 ? row.count - (isTemplate ? 1 : 0) : 0;",
  "    if (dataLen > headerCount) {",
  "      free(drop);",
  "      pya_csv_set_error(err, \"csv row defective\", (int)r + 1, (int)dataLen + (isTemplate ? 1 : 0));",
  "      return 0;",
  "    }",
  "    size_t colIndex = 0;",
  "    for (size_t c = 0; c < headerCount; c++) {",
  "      if (drop[c]) continue;",
  "      const char *cell = (c + (isTemplate ? 1 : 0) < row.count) ? row.cells[c + (isTemplate ? 1 : 0)] : \"\";",
  "      columns[colIndex][rowIndex] = pya_csv_strdup(cell ? cell : \"\");",
  "      colIndex++;",
  "    }",
  "    rowIndex++;",
  "  }",
  "  free(drop);",
  "  out->header_raw = header_raw;",
  "  out->header = header;",
  "  out->width = filteredCount;",
  "  out->rows = dataCount;",
  "  out->columns = columns;",
  "  return 1;",
  "}",
  "static int pya_csv_read_file(const char *filename, const char *name, pya_csv_error *err) {",
  "  if (!filename || !name) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
  "  FILE *f = fopen(filename, \"rb\");",
  "  if (!f) { pya_csv_set_error(err, \"csv lost\", 0, 0); return 0; }",
  "  struct zsv_opts opts = {0};",
  "  struct pya_csv_parse_ctx ctx = {0};",
  "  opts.row_handler = pya_csv_row_handler;",
  "  opts.ctx = &ctx;",
  "  opts.stream = f;",
  "  ctx.parser = zsv_new(&opts);",
  "  enum zsv_status stat;",
  "  while ((stat = zsv_parse_more(ctx.parser)) == zsv_status_ok) { }",
  "  zsv_finish(ctx.parser);",
  "  zsv_delete(ctx.parser);",
  "  fclose(f);",
  "  if (stat != zsv_status_no_more_input) {",
  "    pya_csv_set_error(err, \"csv defective\", 0, 0);",
  "    return 0;",
  "  }",
  "  pya_csv_map map = {0};",
  "  if (!pya_csv_build_map(&ctx.rows, &map, err)) {",
  "    for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
  "    free(ctx.rows.rows);",
  "    return 0;",
  "  }",
  "  for (size_t i = 0; i < ctx.rows.length; i++) pya_csv_free_row(&ctx.rows.rows[i]);",
  "  free(ctx.rows.rows);",
  "  pya_csv_store(name, &map);",
  "  return 1;",
  "}",
  "static int pya_csv_header_raw_unique(pya_csv_map *map) {",
  "  if (!map || !map->header_raw) return 0;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    char normA[PYA_TEXT_CAP];",
  "    pya_csv_lower_trim(map->header_raw[i], normA, sizeof(normA));",
  "    if (!*normA) return 0;",
  "    for (size_t j = i + 1; j < map->width; j++) {",
  "      char normB[PYA_TEXT_CAP];",
  "      pya_csv_lower_trim(map->header_raw[j], normB, sizeof(normB));",
  "      if (strcmp(normA, normB) == 0) return 0;",
  "    }",
  "  }",
  "  return 1;",
  "}",
  "static void pya_csv_escape(FILE *out, const char *value) {",
  "  const char *str = value ? value : \"\";",
  "  int needs = 0;",
  "  for (const char *p = str; *p; p++) {",
  "    if (*p == '\"' || *p == '\\n' || *p == '\\r' || *p == ',') { needs = 1; break; }",
  "  }",
  "  if (!needs) { fputs(str, out); return; }",
  "  fputc('\"', out);",
  "  for (const char *p = str; *p; p++) {",
  "    if (*p == '\"') fputc('\"', out);",
  "    fputc(*p, out);",
  "  }",
  "  fputc('\"', out);",
  "}",
  "static int pya_csv_write_file(const char *name, const char *filename) {",
  "  pya_csv_map *map = pya_csv_find(name);",
  "  if (!map || !filename) return 0;",
  "  FILE *out = fopen(filename, \"w\");",
  "  if (!out) return 0;",
  "  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    if (i) fputc(',', out);",
  "    pya_csv_escape(out, headers[i]);",
  "  }",
  "  fputc('\\n', out);",
  "  for (size_t r = 0; r < map->rows; r++) {",
  "    for (size_t c = 0; c < map->width; c++) {",
  "      if (c) fputc(',', out);",
  "      pya_csv_escape(out, map->columns[c][r]);",
  "    }",
  "    fputc('\\n', out);",
  "  }",
  "  fclose(out);",
  "  return 1;",
  "}",
  "static int pya_csv_write_stdout(const char *name) {",
  "  pya_csv_map *map = pya_csv_find(name);",
  "  if (!map) return 0;",
  "  char **headers = pya_csv_header_raw_unique(map) ? map->header_raw : map->header;",
  "  for (size_t i = 0; i < map->width; i++) {",
  "    if (i) fputc(',', stdout);",
  "    pya_csv_escape(stdout, headers[i]);",
  "  }",
  "  fputc('\\n', stdout);",
  "  for (size_t r = 0; r < map->rows; r++) {",
  "    for (size_t c = 0; c < map->width; c++) {",
  "      if (c) fputc(',', stdout);",
  "      pya_csv_escape(stdout, map->columns[c][r]);",
  "    }",
  "    fputc('\\n', stdout);",
  "  }",
  "  return 1;",
  "}"
].join("\n");
