export const VECTOR_TYPE_DECL = "typedef struct { const char *type; int length; double *num_values; const char **text_values; } pya_vec;";

export const VECTOR_PRINT_HELPER = [
  "static int is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void print_vec_inline(const pya_vec *vec) {",
  "  if (!vec) { printf(\"ve num\"); return; }",
  "  const char *type = vec->type ? vec->type : \"num\";",
  "  printf(\"ve %s\", type);",
  "  if (strcmp(type, \"bool\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      printf(\" %s\", vec->num_values[i] != 0 ? \"truth\" : \"lie\");",
  "    }",
  "    return;",
  "  }",
  "  if (strcmp(type, \"text\") == 0) {",
  "    for (int i = 0; i < vec->length; i++) {",
  "      const char *val = vec->text_values[i];",
  "      if (is_safe_token(val)) {",
  "        printf(\" %s\", val);",
  "      } else {",
  "        printf(\" \\\"\");",
  "        print_escaped(val);",
  "        printf(\"\\\"\");",
  "      }",
  "    }",
  "    return;",
  "  }",
  "  for (int i = 0; i < vec->length; i++) { printf(\" %g\", vec->num_values[i]); }",
  "}",
  "static void print_vec(const pya_vec *vec) {",
  "  print_vec_inline(vec);",
  "  printf(\"\\n\");",
  "}",
  "static void print_vec_sentence(const char *name, const pya_vec *vec) {",
  "  printf(\"su name %s ob \", name ? name : \"\");",
  "  print_vec_inline(vec);",
  "  printf(\" be vector ya\\n\");",
  "}"
].join("\n");

export const TEXT_HELPER = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "static void pya_concat_buf(char *dest, const char *src) {",
  "  if (!dest || !src) return;",
  "  size_t dlen = strlen(dest);",
  "  if (dlen >= PYA_TEXT_CAP - 1) return;",
  "  strncat(dest, src, PYA_TEXT_CAP - dlen - 1);",
  "}",
  "static void pya_concat_num_buf(char *dest, double value) {",
  "  char buf[64];",
  "  snprintf(buf, sizeof(buf), \"%g\", value);",
  "  pya_concat_buf(dest, buf);",
  "}"
].join("\n");

export const MAP_TYPE_DECL = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "#define PYA_MAP_NUM 1",
  "#define PYA_MAP_TEXT 2",
  "#define PYA_MAP_BOOL 3",
  "#define PYA_MAP_HOLLOW 4",
  "typedef struct { const char *key; int kind; double num; int boolean; char text[PYA_TEXT_CAP]; } pya_map_entry;",
  "typedef struct { int length; int cap; pya_map_entry *entries; } pya_map;"
].join("\n");

export const MAP_HELPER = [
  "static void pya_map_init(pya_map *map) {",
  "  if (!map) return;",
  "  map->length = 0;",
  "  map->cap = 0;",
  "  map->entries = NULL;",
  "}",
  "static int pya_map_find(pya_map *map, const char *key) {",
  "  if (!map || !key) return -1;",
  "  for (int i = 0; i < map->length; i++) {",
  "    if (map->entries[i].key && strcmp(map->entries[i].key, key) == 0) return i;",
  "  }",
  "  return -1;",
  "}",
  "static void pya_map_reserve(pya_map *map) {",
  "  if (!map) return;",
  "  if (map->length < map->cap) return;",
  "  int next = map->cap == 0 ? 8 : map->cap * 2;",
  "  pya_map_entry *nextEntries = (pya_map_entry *)realloc(map->entries, sizeof(pya_map_entry) * next);",
  "  if (!nextEntries) return;",
  "  map->entries = nextEntries;",
  "  map->cap = next;",
  "}",
  "static pya_map_entry *pya_map_get_or_add(pya_map *map, const char *key) {",
  "  if (!map || !key) return NULL;",
  "  int idx = pya_map_find(map, key);",
  "  if (idx >= 0) return &map->entries[idx];",
  "  pya_map_reserve(map);",
  "  if (map->length >= map->cap) return NULL;",
  "  pya_map_entry *entry = &map->entries[map->length++];",
  "  entry->key = key;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = 0;",
  "  entry->boolean = 0;",
  "  entry->text[0] = '\\0';",
  "  return entry;",
  "}",
  "static void pya_map_set_num(pya_map *map, const char *key, double value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = value;",
  "}",
  "static void pya_map_set_text(pya_map *map, const char *key, const char *value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_TEXT;",
  "  snprintf(entry->text, PYA_TEXT_CAP, \"%s\", value ? value : \"\");",
  "}",
  "static void pya_map_set_bool(pya_map *map, const char *key, int value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_BOOL;",
  "  entry->boolean = value ? 1 : 0;",
  "}",
  "static void pya_map_set_hollow(pya_map *map, const char *key) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_HOLLOW;",
  "}",
  "static void pya_map_add_num(pya_map *map, const char *key, double delta) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  if (entry->kind != PYA_MAP_NUM) {",
  "    entry->kind = PYA_MAP_NUM;",
  "    entry->num = 0;",
  "  }",
  "  entry->num += delta;",
  "}",
  "static int map_is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void map_print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void print_map_sentence(const char *name, const pya_map *map) {",
  "  printf(\"su name %s be map def\\n\", name ? name : \"\");",
  "  if (!map) {",
  "    printf(\"prah\\n\");",
  "    return;",
  "  }",
  "  for (int i = 0; i < map->length; i++) {",
  "    const pya_map_entry *entry = &map->entries[i];",
  "    if (!entry->key) continue;",
  "    if (map_is_safe_token(entry->key)) {",
  "      printf(\"su name %s ob \", entry->key);",
  "    } else {",
  "      printf(\"su name \\\"\");",
  "      map_print_escaped(entry->key);",
  "      printf(\"\\\" ob \");",
  "    }",
  "    if (entry->kind == PYA_MAP_TEXT) {",
  "      printf(\"text \\\"\");",
  "      map_print_escaped(entry->text);",
  "      printf(\"\\\"\");",
  "    } else if (entry->kind == PYA_MAP_BOOL) {",
  "      printf(\"bool %s\", entry->boolean ? \"truth\" : \"lie\");",
  "    } else if (entry->kind == PYA_MAP_HOLLOW) {",
  "      printf(\"hollow\");",
  "    } else {",
  "      printf(\"num %g\", entry->num);",
  "    }",
  "    printf(\" ya\\n\");",
  "  }",
  "  printf(\"prah\\n\");",
  "}"
].join("\n");
