export function vectorFormatHelper() {
  return [
    "function formatVector(values = [], type = \"num\") {",
    "  const tokens = [\"ve\", type];",
    "  for (const value of values) {",
    "    if (typeof value === \"number\") tokens.push(String(value));",
    "    else if (typeof value === \"boolean\") tokens.push(value ? \"truth\" : \"lie\");",
    "    else if (typeof value === \"string\") {",
    "      if (/^[A-Za-z0-9_.-]+$/.test(value)) tokens.push(value);",
    "      else tokens.push(JSON.stringify(value));",
    "    } else tokens.push(String(value));",
    "  }",
    "  return tokens.join(\" \");",
    "}",
    "function formatVectorSentence(name, vec) {",
    "  const v = vec || {};",
    "  return `su name ${name} ob ${formatVector(v.values || [], v.type || \"num\")} be vector ya`;",
    "}"
    ,
    "function formatNp(np = {}) {",
    "  if (np.unspecified) return \"unspecified\";",
    "  if (np.name !== undefined) return `name ${np.name}`;",
    "  if (np.hollow) return \"hollow\";",
    "  if (np.boolean !== undefined) return `bool ${np.boolean ? \"truth\" : \"lie\"}`;",
    "  if (np.num !== undefined) return `num ${np.num}`;",
    "  if (np.text !== undefined) return `text ${JSON.stringify(np.text)}`;",
    "  if (np.filename !== undefined) return `filename ${np.filename}`;",
    "  if (np.ve) return formatVector(np.ve.values || [], np.ve.type || \"num\");",
    "  return \"\";",
    "}",
    "function formatSentence(sentence = {}) {",
    "  const parts = [];",
    "  if (sentence.su) parts.push(\"su\", formatNp(sentence.su));",
    "  if (sentence.ob) parts.push(\"ob\", formatNp(sentence.ob));",
    "  if (sentence.from) parts.push(\"from\", formatNp(sentence.from));",
    "  if (sentence.by) parts.push(\"by\", formatNp(sentence.by));",
    "  if (sentence.to) parts.push(\"to\", formatNp(sentence.to));",
    "  if (sentence.fromindex) parts.push(\"fromindex\", formatNp(sentence.fromindex));",
    "  if (sentence.atindex) parts.push(\"atindex\", formatNp(sentence.atindex));",
    "  if (sentence.toindex) parts.push(\"toindex\", formatNp(sentence.toindex));",
    "  if (sentence.be) parts.push(\"be\", sentence.be);",
    "  parts.push(sentence.mood || \"ya\");",
    "  return parts.join(\" \");",
    "}",
    "function formatMapSentence(name, mapFact) {",
    "  const kind = mapFact?.be === \"csv map\" ? \"csv map\" : (mapFact?.be === \"json map\" ? \"json map\" : \"map\");",
    "  const entries = mapFact?.ob?.map ?? {};",
    "  const lines = [`su name ${name} be ${kind} def`];",
    "  for (const key of Object.keys(entries)) {",
    "    const entry = entries[key];",
    "    if (kind === \"map\" && entry && typeof entry === \"object\" && entry.mood) {",
    "      lines.push(formatSentence(entry));",
    "    } else {",
    "      lines.push(`su name ${key} ob ${formatNp(entry || {})} ya`);",
    "    }",
    "  }",
    "  lines.push(\"prah\");",
    "  return lines.join(\"\\n\");",
    "}"
  ].join("\n");
}
