export const EXCHANGE_HELPER = [
  "static int pya_exchange_enabled() {",
  "  const char *flag = getenv(\"PYA_NEWSPAPER\");",
  "  return flag && strcmp(flag, \"1\") == 0;",
  "}",
  "",
  "static int pya_tool_event_id = 0;",
  "static int pya_next_tool_event_id() {",
  "  pya_tool_event_id += 1;",
  "  return pya_tool_event_id;",
  "}",
  "",
  "static int pya_artifact_counter = 0;",
  "",
  "static void pya_escape_text(const char *text, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  size_t len = 0;",
  "  for (const char *p = text ? text : \"\"; *p && len + 2 < cap; p++) {",
  "    char ch = *p;",
  "    if (ch == '\\\\' || ch == '\"') {",
  "      out[len++] = '\\\\';",
  "      out[len++] = ch;",
  "    } else if (ch == '\\n') {",
  "      out[len++] = '\\\\';",
  "      out[len++] = 'n';",
  "    } else {",
  "      out[len++] = ch;",
  "    }",
  "  }",
  "  out[len] = '\\0';",
  "}",
  "",
  "static int pya_exchange_last_error = 0;",
  "static char pya_exchange_last_error_line[PYA_TEXT_CAP];",
  "static void pya_emit_exchange(const char *line) {",
  "  if (!pya_exchange_enabled() || !line) return;",
  "  if (strstr(line, \" be error ya\")) {",
  "    pya_exchange_last_error = 1;",
  "    snprintf(pya_exchange_last_error_line, sizeof(pya_exchange_last_error_line), \"%s\", line);",
  "  }",
  "  if (strchr(line, '\\n')) {",
  "    printf(\"PYA_NEWSPAPER:BEGIN\\n\");",
  "    printf(\"%s\\n\", line);",
  "    printf(\"PYA_NEWSPAPER:END\\n\");",
  "    return;",
  "  }",
  "  printf(\"PYA_NEWSPAPER:%s\\n\", line);",
  "}",
  "",
  "static void pya_exchange_reset_error(void) {",
  "  pya_exchange_last_error = 0;",
  "  pya_exchange_last_error_line[0] = '\\0';",
  "}",
  "",
  "static int pya_exchange_has_error(void) {",
  "  return pya_exchange_last_error;",
  "}",
  "",
  "static const char *pya_exchange_error_text(void) {",
  "  return pya_exchange_last_error_line;",
  "}",
  "",
  "typedef struct {",
  "  char locator[PYA_TEXT_CAP];",
  "  char name[64];",
  "  char hash[65];",
  "  int has_hash;",
  "} pya_artifact_entry;",
  "static pya_artifact_entry pya_artifacts[256];",
  "static int pya_artifact_count = 0;",
  "",
  "static int pya_find_artifact(const char *locator) {",
  "  for (int i = 0; i < pya_artifact_count; i++) {",
  "    if (strcmp(pya_artifacts[i].locator, locator) == 0) return i;",
  "  }",
  "  return -1;",
  "}",
  "",
  "static void pya_exchange_fail(const char *name, const char *message) {",
  "  char line[PYA_TEXT_CAP];",
  "  line[0] = '\\0';",
  "  pya_concat_buf(line, \"su name \");",
  "  pya_concat_buf(line, name);",
  "  pya_concat_buf(line, \" ob text \\\"\");",
  "  pya_concat_buf(line, message);",
  "  pya_concat_buf(line, \"\\\" from name exchange be error ya\");",
  "  pya_emit_exchange(line);",
  "  fprintf(stderr, \"%s\\n\", message);",
  "  exit(1);",
  "}",
  "",
  "static int pya_normalize_relative(const char *input, char *out, size_t cap) {",
  "  size_t len = 0;",
  "  int depth = 0;",
  "  size_t starts[256];",
  "  size_t i = 0;",
  "  if (!out || cap == 0) return 0;",
  "  out[0] = '\\0';",
  "  while (input && input[i]) {",
  "    while (input[i] == '/' ) i++;",
  "    size_t segStart = i;",
  "    while (input[i] && input[i] != '/') i++;",
  "    size_t segLen = i - segStart;",
  "    if (segLen == 0) break;",
  "    if (segLen == 1 && input[segStart] == '.') continue;",
  "    if (segLen == 2 && input[segStart] == '.' && input[segStart + 1] == '.') {",
  "      if (depth == 0) return 0;",
  "      depth -= 1;",
  "      len = starts[depth];",
  "      if (len > 0 && out[len - 1] == '/') len -= 1;",
  "      out[len] = '\\0';",
  "      continue;",
  "    }",
  "    if (len > 0) {",
  "      if (len + 1 >= cap) return 0;",
  "      out[len++] = '/';",
  "    }",
  "    if (len + segLen >= cap) return 0;",
  "    starts[depth++] = len;",
  "    memcpy(out + len, input + segStart, segLen);",
  "    len += segLen;",
  "    out[len] = '\\0';",
  "  }",
  "  return 1;",
  "}",
  "",
  "static int pya_normalize_locator(const char *locator, char *out, size_t cap) {",
  "  if (!locator) return 0;",
  "  if (strstr(locator, \"://\")) {",
  "    snprintf(out, cap, \"%s\", locator);",
  "    return 1;",
  "  }",
  "  char runRoot[PYA_TEXT_CAP];",
  "  if (!getcwd(runRoot, sizeof(runRoot))) return 0;",
  "  for (char *p = runRoot; *p; p++) { if (*p == '\\\\') *p = '/'; }",
  "  char loc[PYA_TEXT_CAP];",
  "  snprintf(loc, sizeof(loc), \"%s\", locator);",
  "  for (char *p = loc; *p; p++) { if (*p == '\\\\') *p = '/'; }",
  "  if (loc[0] == '/') {",
  "    size_t rootLen = strlen(runRoot);",
  "    if (strncmp(loc, runRoot, rootLen) != 0) return 0;",
  "    const char *rel = loc + rootLen;",
  "    if (*rel == '/') rel += 1;",
  "    return pya_normalize_relative(rel, out, cap);",
  "  }",
  "  return pya_normalize_relative(loc, out, cap);",
  "}",
  "",
  "static int pya_mkdir_recursive(const char *path) {",
  "  char tmp[PYA_TEXT_CAP];",
  "  size_t len = strlen(path);",
  "  if (len >= sizeof(tmp)) return 0;",
  "  snprintf(tmp, sizeof(tmp), \"%s\", path);",
  "  for (size_t i = 1; i < len; i++) {",
  "    if (tmp[i] == '/') {",
  "      tmp[i] = '\\0';",
  "      if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
  "      tmp[i] = '/';",
  "    }",
  "  }",
  "  if (mkdir(tmp, 0755) != 0 && errno != EEXIST) return 0;",
  "  return 1;",
  "}",
  "",
  "static void pya_artifact_ext(const char *locator, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  out[0] = '\\0';",
  "  if (!locator) return;",
  "  const char *lastSlash = strrchr(locator, '/');",
  "  const char *lastDot = strrchr(locator, '.');",
  "  if (!lastDot) return;",
  "  if (lastSlash && lastDot < lastSlash) return;",
  "  snprintf(out, cap, \"%s\", lastDot);",
  "}",
  "",
  "static void pya_content_address_path(const char *hash, const char *locator, char *out, size_t cap) {",
  "  if (!hash || strlen(hash) < 4) { if (out && cap) out[0] = '\\0'; return; }",
  "  char ext[32];",
  "  pya_artifact_ext(locator, ext, sizeof(ext));",
  "  snprintf(out, cap, \"artifacts/sha256/%c%c/%c%c/%s%s\", hash[0], hash[1], hash[2], hash[3], hash, ext);",
  "}",
  "",
  "static void pya_write_artifact_bytes(const char *rel, const unsigned char *bytes, size_t len) {",
  "  if (!rel || !bytes) return;",
  "  char runRoot[PYA_TEXT_CAP];",
  "  if (!getcwd(runRoot, sizeof(runRoot))) return;",
  "  for (char *p = runRoot; *p; p++) { if (*p == '\\\\') *p = '/'; }",
  "  char abs[PYA_TEXT_CAP];",
  "  snprintf(abs, sizeof(abs), \"%s/%s\", runRoot, rel);",
  "  char dir[PYA_TEXT_CAP];",
  "  snprintf(dir, sizeof(dir), \"%s\", abs);",
  "  char *last = strrchr(dir, '/');",
  "  if (last) {",
  "    *last = '\\0';",
  "    pya_mkdir_recursive(dir);",
  "    *last = '/';",
  "  }",
  "  FILE *f = fopen(abs, \"wb\");",
  "  if (!f) return;",
  "  fwrite(bytes, 1, len, f);",
  "  fclose(f);",
  "}",
  "",
  "static void pya_link_run_alias(const char *name, const char *target) {",
  "  const char *runId = getenv(\"PYA_RUN_ID\");",
  "  if (!runId || !name || !target) return;",
  "  char rel[PYA_TEXT_CAP];",
  "  snprintf(rel, sizeof(rel), \"artifacts/%s/%s\", runId, name);",
  "  char runRoot[PYA_TEXT_CAP];",
  "  if (!getcwd(runRoot, sizeof(runRoot))) return;",
  "  for (char *p = runRoot; *p; p++) { if (*p == '\\\\') *p = '/'; }",
  "  char abs[PYA_TEXT_CAP];",
  "  snprintf(abs, sizeof(abs), \"%s/%s\", runRoot, rel);",
  "  char dir[PYA_TEXT_CAP];",
  "  snprintf(dir, sizeof(dir), \"%s\", abs);",
  "  char *last = strrchr(dir, '/');",
  "  if (last) {",
  "    *last = '\\0';",
  "    pya_mkdir_recursive(dir);",
  "    *last = '/';",
  "  }",
  "  if (access(abs, F_OK) == 0) return;",
  "  if (link(target, abs) != 0) {",
  "    symlink(target, abs);",
  "  }",
  "}",
  "",
  "typedef struct {",
  "  uint8_t data[64];",
  "  uint32_t datalen;",
  "  unsigned long long bitlen;",
  "  uint32_t state[8];",
  "} pya_sha256_ctx;",
  "",
  "static uint32_t pya_sha256_k[64] = {",
  "  0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,",
  "  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,",
  "  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,",
  "  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,",
  "  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,",
  "  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,",
  "  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,",
  "  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2",
  "};",
  "",
  "static uint32_t pya_rotr(uint32_t a, uint32_t b) { return (a >> b) | (a << (32 - b)); }",
  "static uint32_t pya_ch(uint32_t x, uint32_t y, uint32_t z) { return (x & y) ^ (~x & z); }",
  "static uint32_t pya_maj(uint32_t x, uint32_t y, uint32_t z) { return (x & y) ^ (x & z) ^ (y & z); }",
  "static uint32_t pya_ep0(uint32_t x) { return pya_rotr(x, 2) ^ pya_rotr(x, 13) ^ pya_rotr(x, 22); }",
  "static uint32_t pya_ep1(uint32_t x) { return pya_rotr(x, 6) ^ pya_rotr(x, 11) ^ pya_rotr(x, 25); }",
  "static uint32_t pya_sig0(uint32_t x) { return pya_rotr(x, 7) ^ pya_rotr(x, 18) ^ (x >> 3); }",
  "static uint32_t pya_sig1(uint32_t x) { return pya_rotr(x, 17) ^ pya_rotr(x, 19) ^ (x >> 10); }",
  "",
  "static void pya_sha256_transform(pya_sha256_ctx *ctx, const uint8_t data[]) {",
  "  uint32_t a,b,c,d,e,f,g,h,i,j,t1,t2,m[64];",
  "  for (i = 0, j = 0; i < 16; ++i, j += 4) {",
  "    m[i] = (data[j] << 24) | (data[j + 1] << 16) | (data[j + 2] << 8) | (data[j + 3]);",
  "  }",
  "  for ( ; i < 64; ++i) {",
  "    m[i] = pya_sig1(m[i - 2]) + m[i - 7] + pya_sig0(m[i - 15]) + m[i - 16];",
  "  }",
  "  a = ctx->state[0]; b = ctx->state[1]; c = ctx->state[2]; d = ctx->state[3];",
  "  e = ctx->state[4]; f = ctx->state[5]; g = ctx->state[6]; h = ctx->state[7];",
  "  for (i = 0; i < 64; ++i) {",
  "    t1 = h + pya_ep1(e) + pya_ch(e,f,g) + pya_sha256_k[i] + m[i];",
  "    t2 = pya_ep0(a) + pya_maj(a,b,c);",
  "    h = g; g = f; f = e; e = d + t1; d = c; c = b; b = a; a = t1 + t2;",
  "  }",
  "  ctx->state[0] += a; ctx->state[1] += b; ctx->state[2] += c; ctx->state[3] += d;",
  "  ctx->state[4] += e; ctx->state[5] += f; ctx->state[6] += g; ctx->state[7] += h;",
  "}",
  "",
  "static void pya_sha256_init(pya_sha256_ctx *ctx) {",
  "  ctx->datalen = 0;",
  "  ctx->bitlen = 0;",
  "  ctx->state[0] = 0x6a09e667;",
  "  ctx->state[1] = 0xbb67ae85;",
  "  ctx->state[2] = 0x3c6ef372;",
  "  ctx->state[3] = 0xa54ff53a;",
  "  ctx->state[4] = 0x510e527f;",
  "  ctx->state[5] = 0x9b05688c;",
  "  ctx->state[6] = 0x1f83d9ab;",
  "  ctx->state[7] = 0x5be0cd19;",
  "}",
  "",
  "static void pya_sha256_update(pya_sha256_ctx *ctx, const uint8_t data[], size_t len) {",
  "  for (size_t i = 0; i < len; ++i) {",
  "    ctx->data[ctx->datalen] = data[i];",
  "    ctx->datalen++;",
  "    if (ctx->datalen == 64) {",
  "      pya_sha256_transform(ctx, ctx->data);",
  "      ctx->bitlen += 512;",
  "      ctx->datalen = 0;",
  "    }",
  "  }",
  "}",
  "",
  "static void pya_sha256_final(pya_sha256_ctx *ctx, uint8_t hash[]) {",
  "  uint32_t i = ctx->datalen;",
  "  if (ctx->datalen < 56) {",
  "    ctx->data[i++] = 0x80;",
  "    while (i < 56) ctx->data[i++] = 0x00;",
  "  } else {",
  "    ctx->data[i++] = 0x80;",
  "    while (i < 64) ctx->data[i++] = 0x00;",
  "    pya_sha256_transform(ctx, ctx->data);",
  "    memset(ctx->data, 0, 56);",
  "  }",
  "  ctx->bitlen += ctx->datalen * 8;",
  "  ctx->data[63] = ctx->bitlen;",
  "  ctx->data[62] = ctx->bitlen >> 8;",
  "  ctx->data[61] = ctx->bitlen >> 16;",
  "  ctx->data[60] = ctx->bitlen >> 24;",
  "  ctx->data[59] = ctx->bitlen >> 32;",
  "  ctx->data[58] = ctx->bitlen >> 40;",
  "  ctx->data[57] = ctx->bitlen >> 48;",
  "  ctx->data[56] = ctx->bitlen >> 56;",
  "  pya_sha256_transform(ctx, ctx->data);",
  "  for (i = 0; i < 4; ++i) {",
  "    hash[i]      = (ctx->state[0] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 4]  = (ctx->state[1] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 8]  = (ctx->state[2] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 12] = (ctx->state[3] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 16] = (ctx->state[4] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 20] = (ctx->state[5] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 24] = (ctx->state[6] >> (24 - i * 8)) & 0x000000ff;",
  "    hash[i + 28] = (ctx->state[7] >> (24 - i * 8)) & 0x000000ff;",
  "  }",
  "}",
  "",
  "static void pya_sha256_hex(const unsigned char *data, size_t len, char *out) {",
  "  uint8_t hash[32];",
  "  pya_sha256_ctx ctx;",
  "  pya_sha256_init(&ctx);",
  "  pya_sha256_update(&ctx, data, len);",
  "  pya_sha256_final(&ctx, hash);",
  "  for (int i = 0; i < 32; i++) {",
  "    sprintf(out + (i * 2), \"%02x\", hash[i]);",
  "  }",
  "  out[64] = '\\0';",
  "}",
  "",
  "static void pya_exchange_record_bytes(const char *locator, const unsigned char *bytes, size_t len, const char *op, const char *sentence_id) {",
  "  if (!pya_exchange_enabled()) return;",
  "  char norm[PYA_TEXT_CAP];",
  "  if (!pya_normalize_locator(locator, norm, sizeof(norm))) return;",
  "  char escaped[PYA_TEXT_CAP];",
  "  pya_escape_text(norm, escaped, sizeof(escaped));",
  "  char hash[65];",
  "  pya_sha256_hex(bytes, len, hash);",
  "  char ca_rel[PYA_TEXT_CAP];",
  "  pya_content_address_path(hash, norm, ca_rel, sizeof(ca_rel));",
  "  pya_write_artifact_bytes(ca_rel, bytes, len);",
  "  char runRoot[PYA_TEXT_CAP];",
  "  if (!getcwd(runRoot, sizeof(runRoot))) return;",
  "  for (char *p = runRoot; *p; p++) { if (*p == '\\\\') *p = '/'; }",
  "  char ca_abs[PYA_TEXT_CAP];",
  "  snprintf(ca_abs, sizeof(ca_abs), \"%s/%s\", runRoot, ca_rel);",
  "  int existing = pya_find_artifact(norm);",
  "  if (existing >= 0) {",
  "    if (pya_artifacts[existing].has_hash && strcmp(pya_artifacts[existing].hash, hash) != 0) {",
  "      pya_exchange_fail(\"hash inconsistency\", \"hash inconsistency\");",
  "    }",
  "    if (!pya_artifacts[existing].has_hash) {",
  "      strncpy(pya_artifacts[existing].hash, hash, sizeof(pya_artifacts[existing].hash) - 1);",
  "      pya_artifacts[existing].hash[sizeof(pya_artifacts[existing].hash) - 1] = '\\0';",
  "      pya_artifacts[existing].has_hash = 1;",
  "    }",
  "    pya_link_run_alias(pya_artifacts[existing].name, ca_abs);",
  "    if (op) {",
  "      char line2[PYA_TEXT_CAP];",
  "      line2[0] = '\\0';",
  "      pya_concat_buf(line2, \"su name \");",
  "      pya_concat_buf(line2, pya_artifacts[existing].name);",
  "      pya_concat_buf(line2, \" as name \");",
  "      pya_concat_buf(line2, op);",
  "      pya_concat_buf(line2, \" from name exchange be exchange ya\");",
  "      pya_emit_exchange(line2);",
  "    }",
  "    return;",
  "  }",
  "  char name[64];",
  "  snprintf(name, sizeof(name), \"artifact-%d\", pya_artifact_counter++);",
  "  if (pya_artifact_count < 256) {",
  "    strncpy(pya_artifacts[pya_artifact_count].locator, norm, sizeof(pya_artifacts[pya_artifact_count].locator) - 1);",
  "    pya_artifacts[pya_artifact_count].locator[sizeof(pya_artifacts[pya_artifact_count].locator) - 1] = '\\0';",
  "    strncpy(pya_artifacts[pya_artifact_count].name, name, sizeof(pya_artifacts[pya_artifact_count].name) - 1);",
  "    pya_artifacts[pya_artifact_count].name[sizeof(pya_artifacts[pya_artifact_count].name) - 1] = '\\0';",
  "    strncpy(pya_artifacts[pya_artifact_count].hash, hash, sizeof(pya_artifacts[pya_artifact_count].hash) - 1);",
  "    pya_artifacts[pya_artifact_count].hash[sizeof(pya_artifacts[pya_artifact_count].hash) - 1] = '\\0';",
  "    pya_artifacts[pya_artifact_count].has_hash = 1;",
  "    pya_artifact_count += 1;",
  "  }",
  "  char line[PYA_TEXT_CAP];",
  "  line[0] = '\\0';",
  "  pya_concat_buf(line, \"su name \");",
  "  pya_concat_buf(line, name);",
  "  if (sentence_id && sentence_id[0]) {",
  "    pya_concat_buf(line, \" ob name \");",
  "    pya_concat_buf(line, sentence_id);",
  "  } else {",
  "    pya_concat_buf(line, \" ob text \\\"\");",
  "    pya_concat_buf(line, escaped);",
  "    pya_concat_buf(line, \"\\\"\");",
  "  }",
  "  pya_concat_buf(line, \" to filename \\\"\");",
  "  pya_concat_buf(line, escaped);",
  "  pya_concat_buf(line, \"\\\" accordingto name sha256 fromtext text \\\"\");",
  "  pya_concat_buf(line, hash);",
  "  pya_concat_buf(line, \"\\\" by num \");",
  "  pya_concat_num_buf(line, (double)len);",
  "  pya_concat_buf(line, \" from name exchange be artifact ya\");",
  "  pya_emit_exchange(line);",
  "  pya_link_run_alias(name, ca_abs);",
  "  if (op) {",
  "    char line2[PYA_TEXT_CAP];",
  "    line2[0] = '\\0';",
  "    pya_concat_buf(line2, \"su name \");",
  "    pya_concat_buf(line2, name);",
  "    pya_concat_buf(line2, \" as name \");",
  "    pya_concat_buf(line2, op);",
  "    pya_concat_buf(line2, \" from name exchange be exchange ya\");",
  "    pya_emit_exchange(line2);",
  "  }",
  "}",
  "",
  "static void pya_exchange_record_file(const char *filename, const char *op, const char *sentence_id) {",
  "  if (!filename) return;",
  "  FILE *f = fopen(filename, \"rb\");",
  "  if (!f) return;",
  "  fseek(f, 0, SEEK_END);",
  "  long size = ftell(f);",
  "  if (size < 0) { fclose(f); return; }",
  "  rewind(f);",
  "  unsigned char *buf = (unsigned char *)malloc((size_t)size);",
  "  if (!buf) { fclose(f); return; }",
  "  size_t read = fread(buf, 1, (size_t)size, f);",
  "  fclose(f);",
  "  pya_exchange_record_bytes(filename, buf, read, op, sentence_id);",
  "  free(buf);",
  "}"
].join("\n");
