export const JSON_PYASH_HELPER = [
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_json_error;",
  "",
  "typedef struct {",
  "  char **items;",
  "  int length;",
  "  int cap;",
  "} pya_used_names;",
  "",
  "static char *pya_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static void pya_used_init(pya_used_names *used) {",
  "  if (!used) return;",
  "  used->items = NULL;",
  "  used->length = 0;",
  "  used->cap = 0;",
  "}",
  "",
  "static void pya_used_free(pya_used_names *used) {",
  "  if (!used) return;",
  "  for (int i = 0; i < used->length; i++) free(used->items[i]);",
  "  free(used->items);",
  "  used->items = NULL;",
  "  used->length = 0;",
  "  used->cap = 0;",
  "}",
  "",
  "static int pya_used_has(const pya_used_names *used, const char *name) {",
  "  if (!used || !name) return 0;",
  "  for (int i = 0; i < used->length; i++) {",
  "    if (used->items[i] && strcmp(used->items[i], name) == 0) return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static void pya_used_add(pya_used_names *used, const char *name) {",
  "  if (!used || !name) return;",
  "  if (pya_used_has(used, name)) return;",
  "  if (used->length >= used->cap) {",
  "    int next = used->cap == 0 ? 8 : used->cap * 2;",
  "    char **nextItems = (char **)realloc(used->items, sizeof(char *) * next);",
  "    if (!nextItems) return;",
  "    used->items = nextItems;",
  "    used->cap = next;",
  "  }",
  "  used->items[used->length++] = pya_strdup(name);",
  "}",
  "",
  "static void pya_used_remove(pya_used_names *used, const char *name) {",
  "  if (!used || !name) return;",
  "  for (int i = 0; i < used->length; i++) {",
  "    if (used->items[i] && strcmp(used->items[i], name) == 0) {",
  "      free(used->items[i]);",
  "      for (int j = i + 1; j < used->length; j++) {",
  "        used->items[j - 1] = used->items[j];",
  "      }",
  "      used->length -= 1;",
  "      return;",
  "    }",
  "  }",
  "}",
  "",
  "static void pya_sanitize_name_part(const char *raw, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  out[0] = '\\0';",
  "  if (!raw) { snprintf(out, cap, \"item\"); return; }",
  "  size_t len = strlen(raw);",
  "  char buf[PYA_TEXT_CAP];",
  "  size_t idx = 0;",
  "  int lastSpace = 1;",
  "  for (size_t i = 0; i < len && idx < sizeof(buf) - 1; i++) {",
  "    char ch = raw[i];",
  "    int ok = (isalnum((unsigned char)ch) || ch == '_' || ch == '.' || ch == '-');",
  "    if (ok) {",
  "      buf[idx++] = ch;",
  "      lastSpace = 0;",
  "    } else if (!lastSpace) {",
  "      buf[idx++] = ' ';",
  "      lastSpace = 1;",
  "    }",
  "  }",
  "  while (idx > 0 && buf[idx - 1] == ' ') idx--;",
  "  buf[idx] = '\\0';",
  "  if (idx == 0) { snprintf(out, cap, \"item\"); return; }",
  "  snprintf(out, cap, \"%s\", buf);",
  "}",
  "",
  "static char *pya_unique_name(const char *base, pya_used_names *used) {",
  "  if (!base || !used) return NULL;",
  "  if (!pya_used_has(used, base)) {",
  "    pya_used_add(used, base);",
  "    return pya_strdup(base);",
  "  }",
  "  int i = 2;",
  "  char candidate[PYA_TEXT_CAP];",
  "  while (1) {",
  "    snprintf(candidate, sizeof(candidate), \"%s %d\", base, i);",
  "    if (!pya_used_has(used, candidate)) {",
  "      pya_used_add(used, candidate);",
  "      return pya_strdup(candidate);",
  "    }",
  "    i += 1;",
  "  }",
  "}",
  "",
  "static void pya_json_error_loc(const char *json, const char *pos, int *line, int *column) {",
  "  int l = 1;",
  "  int c = 1;",
  "  if (!json || !pos || pos < json) {",
  "    if (line) *line = l;",
  "    if (column) *column = c;",
  "    return;",
  "  }",
  "  for (const char *p = json; p < pos && *p; p++) {",
  "    if (*p == '\\n') {",
  "      l += 1;",
  "      c = 1;",
  "    } else {",
  "      c += 1;",
  "    }",
  "  }",
  "  if (line) *line = l;",
  "  if (column) *column = c;",
  "}",
  "",
  "static void pya_set_json_error(pya_json_error *err, const char *message, const char *json, const char *pos) {",
  "  if (!err) return;",
  "  snprintf(err->message, PYA_TEXT_CAP, \"%s\", message ? message : \"json map defective\");",
  "  pya_json_error_loc(json, pos, &err->line, &err->column);",
  "}",
  "",
  "static void pya_append_json_string(char *out, const char *text) {",
  "  pya_concat_buf(out, \"\\\"\");",
  "  if (text) {",
  "    for (const char *p = text; *p; p++) {",
  "      char ch = *p;",
  "      if (ch == '\\\\' || ch == '\"') {",
  "        char tmp[3] = { '\\\\', ch, '\\0' };",
  "        pya_concat_buf(out, tmp);",
  "      } else if (ch == '\\n') {",
  "        pya_concat_buf(out, \"\\\\n\");",
  "      } else {",
  "        char tmp[2] = { ch, '\\0' };",
  "        pya_concat_buf(out, tmp);",
  "      }",
  "    }",
  "  }",
  "  pya_concat_buf(out, \"\\\"\");",
  "}",
  "",
  "static int pya_is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "",
  "static void pya_append_token(char *out, const char *token) {",
  "  if (pya_is_safe_token(token)) {",
  "    pya_concat_buf(out, token);",
  "  } else {",
  "    pya_append_json_string(out, token);",
  "  }",
  "}",
  "",
  "static int pya_read_file_text(const char *path, char *out) {",
  "  if (!out || !path) return 0;",
  "  FILE *f = fopen(path, \"r\");",
  "  if (!f) return 0;",
  "  size_t len = fread(out, 1, PYA_TEXT_CAP - 1, f);",
  "  out[len] = '\\0';",
  "  fclose(f);",
  "  return 1;",
  "}",
  "",
  "static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json);",
  "",
  "static void pya_append_vector_values(char *out, const char *type, cJSON *array) {",
  "  pya_concat_buf(out, \"ve \");",
  "  pya_concat_buf(out, type);",
  "  int idx = 0;",
  "  for (cJSON *item = array ? array->child : NULL; item; item = item->next, idx++) {",
  "    pya_concat_buf(out, \" \");",
  "    if (strcmp(type, \"bool\") == 0) {",
  "      pya_concat_buf(out, cJSON_IsTrue(item) ? \"truth\" : \"lie\");",
  "    } else if (strcmp(type, \"num\") == 0) {",
  "      char buf[64];",
  "      snprintf(buf, sizeof(buf), \"%g\", item->valuedouble);",
  "      pya_concat_buf(out, buf);",
  "    } else if (strcmp(type, \"text\") == 0) {",
  "      pya_append_json_string(out, cJSON_GetStringValue(item));",
  "    } else if (strcmp(type, \"name\") == 0) {",
  "      pya_concat_buf(out, cJSON_GetStringValue(item));",
  "    }",
  "  }",
  "}",
  "",
  "static void pya_append_np_for_value(char *line, cJSON *value, const char *parentName, const char *key, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
  "  if (!value) { pya_concat_buf(line, \"hollow\"); return; }",
  "  if (cJSON_IsNull(value)) { pya_concat_buf(line, \"hollow\"); return; }",
  "  if (cJSON_IsString(value)) {",
  "    pya_concat_buf(line, \"text \");",
  "    pya_append_json_string(line, cJSON_GetStringValue(value));",
  "    return;",
  "  }",
  "  if (cJSON_IsNumber(value)) {",
  "    char buf[64];",
  "    snprintf(buf, sizeof(buf), \"%g\", value->valuedouble);",
  "    pya_concat_buf(line, \"num \");",
  "    pya_concat_buf(line, buf);",
  "    return;",
  "  }",
  "  if (cJSON_IsBool(value)) {",
  "    pya_concat_buf(line, \"bool \");",
  "    pya_concat_buf(line, cJSON_IsTrue(value) ? \"truth\" : \"lie\");",
  "    return;",
  "  }",
  "  if (cJSON_IsArray(value)) {",
  "    int hasArray = 0;",
  "    int hasNull = 0;",
  "    int hasObject = 0;",
  "    int hasBool = 0;",
  "    int hasNum = 0;",
  "    int hasText = 0;",
  "    int length = 0;",
  "    for (cJSON *item = value->child; item; item = item->next) {",
  "      length += 1;",
  "      if (cJSON_IsArray(item)) hasArray = 1;",
  "      else if (cJSON_IsNull(item)) hasNull = 1;",
  "      else if (cJSON_IsObject(item)) hasObject = 1;",
  "      else if (cJSON_IsBool(item)) hasBool = 1;",
  "      else if (cJSON_IsNumber(item)) hasNum = 1;",
  "      else if (cJSON_IsString(item)) hasText = 1;",
  "    }",
  "    if (length == 0) {",
  "      pya_concat_buf(line, \"ve hollow\");",
  "      return;",
  "    }",
  "    if (hasArray) {",
  "      pya_set_json_error(err, \"json map contents defective: nested arrays are unsupported\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasNull) {",
  "      pya_set_json_error(err, \"json map contents defective: null elements are unsupported in arrays\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasObject && (hasBool || hasNum || hasText)) {",
  "      pya_set_json_error(err, \"json map contents defective: mixed array types are unsupported\", json, cJSON_GetErrorPtr());",
  "      return;",
  "    }",
  "    if (hasObject) {",
  "      pya_concat_buf(line, \"ve name\");",
  "      int idx = 0;",
  "      for (cJSON *item = value->child; item; item = item->next, idx++) {",
  "        char keyPart[PYA_TEXT_CAP];",
  "        pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
  "        char base[PYA_TEXT_CAP];",
  "        snprintf(base, sizeof(base), \"%s %s %d\", parentName, keyPart, idx + 1);",
  "        char *childName = pya_unique_name(base, used);",
  "        if (childName) {",
  "          pya_emit_map(item, childName, used, chain, err, json);",
  "          pya_concat_buf(line, \" \");",
  "          pya_append_token(line, childName);",
  "          free(childName);",
  "        }",
  "      }",
  "      return;",
  "    }",
  "    if (hasBool && !(hasNum || hasText)) {",
  "      pya_append_vector_values(line, \"bool\", value);",
  "      return;",
  "    }",
  "    if (hasNum && !hasText) {",
  "      pya_append_vector_values(line, \"num\", value);",
  "      return;",
  "    }",
  "    pya_append_vector_values(line, \"text\", value);",
  "    return;",
  "  }",
  "  if (cJSON_IsObject(value)) {",
  "    char keyPart[PYA_TEXT_CAP];",
  "    pya_sanitize_name_part(key, keyPart, sizeof(keyPart));",
  "    char base[PYA_TEXT_CAP];",
  "    snprintf(base, sizeof(base), \"%s %s\", parentName, keyPart);",
  "    char *childName = pya_unique_name(base, used);",
  "    if (childName) {",
  "      pya_emit_map(value, childName, used, chain, err, json);",
  "      pya_concat_buf(line, \"name \");",
  "      pya_concat_buf(line, childName);",
  "      free(childName);",
  "    }",
  "    return;",
  "  }",
  "}",
  "",
  "static int pya_json_entry_compare(const void *a, const void *b);",
  "static int pya_json_entry_compare(const void *a, const void *b) {",
  "  const cJSON *ea = *(const cJSON **)a;",
  "  const cJSON *eb = *(const cJSON **)b;",
  "  if (!ea || !ea->string) return (eb && eb->string) ? -1 : 0;",
  "  if (!eb || !eb->string) return 1;",
  "  return strcmp(ea->string, eb->string);",
  "}",
  "static void pya_emit_map(cJSON *obj, const char *name, pya_used_names *used, char *chain, pya_json_error *err, const char *json) {",
  "  if (!obj || !cJSON_IsObject(obj)) {",
  "    pya_set_json_error(err, \"json map contents defective: object expected\", json, cJSON_GetErrorPtr());",
  "    return;",
  "  }",
  "  char block[PYA_TEXT_CAP];",
  "  block[0] = '\\0';",
  "  pya_concat_buf(block, \"su name \");",
  "  pya_concat_buf(block, name ? name : \"map\");",
  "  pya_concat_buf(block, \" be json map def\\n\");",
  "  int count = 0;",
  "  for (cJSON *entry = obj->child; entry; entry = entry->next) {",
  "    if (entry->string) count++;",
  "  }",
  "  if (count > 0) {",
  "    cJSON **entries = (cJSON **)malloc(sizeof(cJSON *) * count);",
  "    if (!entries) {",
  "      pya_set_json_error(err, \"json map contents defective: allocation failed\", json, json);",
  "      return;",
  "    }",
  "    int idx = 0;",
  "    for (cJSON *entry = obj->child; entry; entry = entry->next) {",
  "      if (entry->string) entries[idx++] = entry;",
  "    }",
  "    qsort(entries, count, sizeof(cJSON *), pya_json_entry_compare);",
  "    for (int i = 0; i < count; i++) {",
  "      cJSON *entry = entries[i];",
  "      if (!entry || !entry->string) continue;",
  "      pya_concat_buf(block, \"su name \");",
  "      pya_concat_buf(block, entry->string);",
  "      pya_concat_buf(block, \" ob \");",
  "      pya_append_np_for_value(block, entry, name, entry->string, used, chain, err, json);",
  "      if (err && err->message[0] != '\\0') {",
  "        free(entries);",
  "        return;",
  "      }",
  "      pya_concat_buf(block, \" ya\\n\");",
  "    }",
  "    free(entries);",
  "  }",
  "  pya_concat_buf(block, \"prah\\n\");",
  "  if (chain[0] != '\\0') pya_concat_buf(chain, \"\\n\");",
  "  pya_concat_buf(chain, block);",
  "}",
  "",
  "static int pya_json_to_pyash(const char *jsonText, const char *rootName, char *out, pya_json_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  if (!jsonText) {",
  "    pya_set_json_error(err, \"import: invalid json\", jsonText, jsonText);",
  "    return 0;",
  "  }",
  "  const char *parseEnd = NULL;",
  "  cJSON *root = cJSON_ParseWithOpts(jsonText, &parseEnd, 0);",
  "  if (!root) {",
  "    const char *errPtr = cJSON_GetErrorPtr();",
  "    pya_set_json_error(err, \"import: invalid json\", jsonText, errPtr);",
  "    return 0;",
  "  }",
  "  pya_used_names used;",
  "  pya_used_init(&used);",
  "  char clean[PYA_TEXT_CAP];",
  "  pya_sanitize_name_part(rootName ? rootName : \"data\", clean, sizeof(clean));",
  "  char *rootSafe = pya_unique_name(clean, &used);",
  "  pya_emit_map(root, rootSafe ? rootSafe : \"data\", &used, out, err, jsonText);",
  "  if (rootSafe) free(rootSafe);",
  "  pya_used_free(&used);",
  "  cJSON_Delete(root);",
  "  if (err && err->message[0] != '\\0') return 0;",
  "  return 1;",
  "}",
  "",
  "typedef enum {",
  "  PYA_PYASH_NUM = 0,",
  "  PYA_PYASH_TEXT,",
  "  PYA_PYASH_BOOL,",
  "  PYA_PYASH_HOLLOW,",
  "  PYA_PYASH_UNSPEC,",
  "  PYA_PYASH_NAME,",
  "  PYA_PYASH_VECTOR",
  "} pya_pyash_kind;",
  "",
  "typedef struct pya_pyash_value pya_pyash_value;",
  "",
  "struct pya_pyash_value {",
  "  pya_pyash_kind kind;",
  "  double num;",
  "  int boolean;",
  "  char *text;",
  "  char *name;",
  "  char *vec_type;",
  "  pya_pyash_value *vec_values;",
  "  int vec_len;",
  "};",
  "",
  "typedef struct {",
  "  char *key;",
  "  pya_pyash_value value;",
  "} pya_pyash_entry;",
  "",
  "typedef struct {",
  "  char *name;",
  "  pya_pyash_entry *entries;",
  "  int length;",
  "  int cap;",
  "} pya_pyash_map;",
  "",
  "typedef struct {",
  "  pya_pyash_map *maps;",
  "  int length;",
  "  int cap;",
  "} pya_pyash_maps;",
  "",
  "typedef struct {",
  "  char **items;",
  "  int length;",
  "  int cap;",
  "  int max_words;",
  "} pya_name_list;",
  "",
  "static int pya_word_count(const char *name) {",
  "  if (!name || !*name) return 0;",
  "  int count = 1;",
  "  for (const char *p = name; *p; p++) {",
  "    if (*p == ' ') count += 1;",
  "  }",
  "  return count;",
  "}",
  "",
  "static void pya_name_list_init(pya_name_list *list) {",
  "  if (!list) return;",
  "  list->items = NULL;",
  "  list->length = 0;",
  "  list->cap = 0;",
  "  list->max_words = 1;",
  "}",
  "",
  "static int pya_name_list_has(const pya_name_list *list, const char *name) {",
  "  if (!list || !name) return 0;",
  "  for (int i = 0; i < list->length; i++) {",
  "    if (list->items[i] && strcmp(list->items[i], name) == 0) return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static void pya_name_list_add(pya_name_list *list, const char *name) {",
  "  if (!list || !name) return;",
  "  if (pya_name_list_has(list, name)) return;",
  "  if (list->length >= list->cap) {",
  "    int next = list->cap == 0 ? 8 : list->cap * 2;",
  "    char **nextItems = (char **)realloc(list->items, sizeof(char *) * next);",
  "    if (!nextItems) return;",
  "    list->items = nextItems;",
  "    list->cap = next;",
  "  }",
  "  list->items[list->length++] = pya_strdup(name);",
  "  int words = pya_word_count(name);",
  "  if (words > list->max_words) list->max_words = words;",
  "}",
  "",
  "static void pya_name_list_free(pya_name_list *list) {",
  "  if (!list) return;",
  "  for (int i = 0; i < list->length; i++) free(list->items[i]);",
  "  free(list->items);",
  "  list->items = NULL;",
  "  list->length = 0;",
  "  list->cap = 0;",
  "  list->max_words = 1;",
  "}",
  "",
  "static void pya_pyash_value_free(pya_pyash_value *value) {",
  "  if (!value) return;",
  "  if (value->kind == PYA_PYASH_TEXT && value->text) free(value->text);",
  "  if (value->kind == PYA_PYASH_NAME && value->name) free(value->name);",
  "  if (value->kind == PYA_PYASH_VECTOR) {",
  "    if (value->vec_type) free(value->vec_type);",
  "    for (int i = 0; i < value->vec_len; i++) {",
  "      pya_pyash_value_free(&value->vec_values[i]);",
  "    }",
  "    free(value->vec_values);",
  "  }",
  "  memset(value, 0, sizeof(*value));",
  "}",
  "",
  "static void pya_pyash_maps_free(pya_pyash_maps *defs) {",
  "  if (!defs) return;",
  "  for (int i = 0; i < defs->length; i++) {",
  "    pya_pyash_map *map = &defs->maps[i];",
  "    if (map->name) free(map->name);",
  "    for (int j = 0; j < map->length; j++) {",
  "      if (map->entries[j].key) free(map->entries[j].key);",
  "      pya_pyash_value_free(&map->entries[j].value);",
  "    }",
  "    free(map->entries);",
  "  }",
  "  free(defs->maps);",
  "  defs->maps = NULL;",
  "  defs->length = 0;",
  "  defs->cap = 0;",
  "}",
  "",
  "static pya_pyash_map *pya_pyash_get_map(pya_pyash_maps *defs, const char *name) {",
  "  if (!defs || !name) return NULL;",
  "  for (int i = 0; i < defs->length; i++) {",
  "    if (defs->maps[i].name && strcmp(defs->maps[i].name, name) == 0) return &defs->maps[i];",
  "  }",
  "  if (defs->length >= defs->cap) {",
  "    int next = defs->cap == 0 ? 4 : defs->cap * 2;",
  "    pya_pyash_map *nextMaps = (pya_pyash_map *)realloc(defs->maps, sizeof(pya_pyash_map) * next);",
  "    if (!nextMaps) return NULL;",
  "    defs->maps = nextMaps;",
  "    defs->cap = next;",
  "  }",
  "  pya_pyash_map *map = &defs->maps[defs->length++];",
  "  memset(map, 0, sizeof(*map));",
  "  map->name = pya_strdup(name);",
  "  return map;",
  "}",
  "",
  "static int pya_pyash_tokenize(const char *line, char ***tokensOut, int *countOut) {",
  "  if (!line || !tokensOut || !countOut) return 0;",
  "  size_t len = strlen(line);",
  "  char *storage = (char *)malloc(len + 1);",
  "  char **items = (char **)malloc(sizeof(char *) * (len + 1));",
  "  if (!storage || !items) { free(storage); free(items); return 0; }",
  "  size_t count = 0;",
  "  size_t pos = 0;",
  "  size_t write = 0;",
  "  while (pos < len) {",
  "    while (pos < len && isspace((unsigned char)line[pos])) pos++;",
  "    if (pos >= len) break;",
  "    items[count++] = &storage[write];",
  "    if (line[pos] == '\"') {",
  "      pos++;",
  "      while (pos < len && line[pos] != '\"') {",
  "        if (line[pos] == '\\\\' && pos + 1 < len) pos++;",
  "        storage[write++] = line[pos++];",
  "      }",
  "      if (pos < len && line[pos] == '\"') pos++;",
  "    } else {",
  "      while (pos < len && !isspace((unsigned char)line[pos])) {",
  "        storage[write++] = line[pos++];",
  "      }",
  "    }",
  "    storage[write++] = '\\0';",
  "  }",
  "  *tokensOut = items;",
  "  *countOut = (int)count;",
  "  return (int)write;",
  "}",
  "",
  "static void pya_pyash_tokens_free(char **tokens, int count) {",
  "  if (!tokens) return;",
  "  if (count > 0) free(tokens[0]);",
  "  free(tokens);",
  "}",
  "",
  "static int pya_pyash_is_keyword(const char *token) {",
  "  if (!token) return 0;",
  "  return strcmp(token, \"su\") == 0",
  "    || strcmp(token, \"ob\") == 0",
  "    || strcmp(token, \"to\") == 0",
  "    || strcmp(token, \"from\") == 0",
  "    || strcmp(token, \"by\") == 0",
  "    || strcmp(token, \"fromindex\") == 0",
  "    || strcmp(token, \"toindex\") == 0",
  "    || strcmp(token, \"atindex\") == 0",
  "    || strcmp(token, \"be\") == 0",
  "    || strcmp(token, \"then\") == 0",
  "    || strcmp(token, \"ya\") == 0",
  "    || strcmp(token, \"def\") == 0",
  "    || strcmp(token, \"prah\") == 0",
  "    || strcmp(token, \"do\") == 0;",
  "}",
  "",
  "static int pya_pyash_parse_value(char **tokens, int count, int *idx, pya_pyash_value *out, const pya_name_list *known) {",
  "  if (!tokens || !idx || !out || *idx >= count) return 0;",
  "  const char *tok = tokens[*idx];",
  "  if (!tok) return 0;",
  "  if (strcmp(tok, \"num\") == 0) {",
  "    if (*idx + 1 >= count) return 0;",
  "    char *end = NULL;",
  "    double val = strtod(tokens[*idx + 1], &end);",
  "    if (!end || *end != '\\0') return 0;",
  "    out->kind = PYA_PYASH_NUM;",
  "    out->num = val;",
  "    *idx += 2;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"text\") == 0) {",
  "    if (*idx + 1 >= count) return 0;",
  "    out->kind = PYA_PYASH_TEXT;",
  "    out->text = pya_strdup(tokens[*idx + 1]);",
  "    *idx += 2;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"bool\") == 0) {",
  "    if (*idx + 1 >= count) return 0;",
  "    out->kind = PYA_PYASH_BOOL;",
  "    out->boolean = (strcmp(tokens[*idx + 1], \"truth\") == 0) ? 1 : 0;",
  "    *idx += 2;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"hollow\") == 0) {",
  "    out->kind = PYA_PYASH_HOLLOW;",
  "    *idx += 1;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"unspecified\") == 0) {",
  "    out->kind = PYA_PYASH_UNSPEC;",
  "    *idx += 1;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"name\") == 0) {",
  "    if (*idx + 1 >= count) return 0;",
  "    out->kind = PYA_PYASH_NAME;",
  "    out->name = pya_strdup(tokens[*idx + 1]);",
  "    *idx += 2;",
  "    return 1;",
  "  }",
  "  if (strcmp(tok, \"ve\") == 0 || strcmp(tok, \"vec\") == 0) {",
  "    *idx += 1;",
  "    const char *type = \"num\";",
  "    if (*idx < count && strcmp(tokens[*idx], \"num\") == 0) { type = \"num\"; *idx += 1; }",
  "    else if (*idx < count && strcmp(tokens[*idx], \"text\") == 0) { type = \"text\"; *idx += 1; }",
  "    else if (*idx < count && strcmp(tokens[*idx], \"bool\") == 0) { type = \"bool\"; *idx += 1; }",
  "    else if (*idx < count && strcmp(tokens[*idx], \"name\") == 0) { type = \"name\"; *idx += 1; }",
  "    else if (*idx < count && strcmp(tokens[*idx], \"hollow\") == 0) {",
  "      out->kind = PYA_PYASH_VECTOR;",
  "      out->vec_type = pya_strdup(\"hollow\");",
  "      out->vec_values = NULL;",
  "      out->vec_len = 0;",
  "      *idx += 1;",
  "      return 1;",
  "    }",
  "    out->kind = PYA_PYASH_VECTOR;",
  "    out->vec_type = pya_strdup(type);",
  "    int cap = 0;",
  "    int len = 0;",
  "    pya_pyash_value *vals = NULL;",
  "    while (*idx < count && !pya_pyash_is_keyword(tokens[*idx])) {",
  "      if (len >= cap) {",
  "        int next = cap == 0 ? 4 : cap * 2;",
  "        pya_pyash_value *nextVals = (pya_pyash_value *)realloc(vals, sizeof(pya_pyash_value) * next);",
  "        if (!nextVals) { free(vals); return 0; }",
  "        vals = nextVals;",
  "        cap = next;",
  "      }",
  "      memset(&vals[len], 0, sizeof(pya_pyash_value));",
  "      if (strcmp(type, \"name\") == 0 && known) {",
  "        int matchedLen = 0;",
  "        char candidate[PYA_TEXT_CAP];",
  "        for (int take = known->max_words; take >= 1; take--) {",
  "          if (*idx + take > count) continue;",
  "          candidate[0] = '\\0';",
  "          for (int k = 0; k < take; k++) {",
  "            if (k > 0) pya_concat_buf(candidate, \" \");",
  "            pya_concat_buf(candidate, tokens[*idx + k]);",
  "          }",
  "          if (pya_name_list_has(known, candidate)) {",
  "            matchedLen = take;",
  "            break;",
  "          }",
  "        }",
  "        if (matchedLen == 0) {",
  "          matchedLen = 1;",
  "          snprintf(candidate, sizeof(candidate), \"%s\", tokens[*idx]);",
  "        }",
  "        vals[len].kind = PYA_PYASH_NAME;",
  "        vals[len].name = pya_strdup(candidate);",
  "        *idx += matchedLen;",
  "        len += 1;",
  "        continue;",
  "      }",
  "      if (strcmp(type, \"num\") == 0) {",
  "        char *end = NULL;",
  "        double val = strtod(tokens[*idx], &end);",
  "        if (!end || *end != '\\0') { free(vals); return 0; }",
  "        vals[len].kind = PYA_PYASH_NUM;",
  "        vals[len].num = val;",
  "      } else if (strcmp(type, \"text\") == 0) {",
  "        vals[len].kind = PYA_PYASH_TEXT;",
  "        vals[len].text = pya_strdup(tokens[*idx]);",
  "      } else if (strcmp(type, \"bool\") == 0) {",
  "        vals[len].kind = PYA_PYASH_BOOL;",
  "        vals[len].boolean = (strcmp(tokens[*idx], \"truth\") == 0) ? 1 : 0;",
  "      } else if (strcmp(type, \"name\") == 0) {",
  "        vals[len].kind = PYA_PYASH_NAME;",
  "        vals[len].name = pya_strdup(tokens[*idx]);",
  "      }",
  "      len += 1;",
  "      *idx += 1;",
  "    }",
  "    out->vec_values = vals;",
  "    out->vec_len = len;",
  "    return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static int pya_pyash_add_entry(pya_pyash_map *map, const char *key, pya_pyash_value *value) {",
  "  if (!map || !key || !value) return 0;",
  "  if (map->length >= map->cap) {",
  "    int next = map->cap == 0 ? 8 : map->cap * 2;",
  "    pya_pyash_entry *nextEntries = (pya_pyash_entry *)realloc(map->entries, sizeof(pya_pyash_entry) * next);",
  "    if (!nextEntries) return 0;",
  "    map->entries = nextEntries;",
  "    map->cap = next;",
  "  }",
  "  map->entries[map->length].key = pya_strdup(key);",
  "  map->entries[map->length].value = *value;",
  "  map->length += 1;",
  "  return 1;",
  "}",
  "",
  "static int pya_pyash_parse_maps(const char *pyash, pya_pyash_maps *defs, pya_json_error *err) {",
  "  if (!pyash || !defs) return 0;",
  "  pya_name_list known;",
  "  pya_name_list_init(&known);",
  "  const char *start = pyash;",
  "  while (*start) {",
  "    const char *end = strchr(start, '\\n');",
  "    size_t len = end ? (size_t)(end - start) : strlen(start);",
  "    if (len == 0) {",
  "      if (!end) break;",
  "      start = end + 1;",
  "      continue;",
  "    }",
  "    char line[PYA_TEXT_CAP];",
  "    if (len >= sizeof(line)) len = sizeof(line) - 1;",
  "    memcpy(line, start, len);",
  "    line[len] = '\\0';",
  "    char **tokens = NULL;",
  "    int count = 0;",
  "    if (!pya_pyash_tokenize(line, &tokens, &count)) {",
  "      pya_set_json_error(err, \"json map export failed: invalid pyash\", pyash, start);",
  "      pya_name_list_free(&known);",
  "      return 0;",
  "    }",
  "    if (count > 0) {",
  "      const char *last = tokens[count - 1];",
  "      if (strcmp(last, \"def\") == 0 && count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0) {",
  "        int beIdx = -1;",
  "        for (int i = 0; i < count; i++) {",
  "          if (strcmp(tokens[i], \"be\") == 0) { beIdx = i; break; }",
  "        }",
  "        if (beIdx > 2) {",
  "          char nameBuf[PYA_TEXT_CAP];",
  "          nameBuf[0] = '\\0';",
  "          for (int i = 2; i < beIdx; i++) {",
  "            if (i > 2) pya_concat_buf(nameBuf, \" \");",
  "            pya_concat_buf(nameBuf, tokens[i]);",
  "          }",
  "          pya_name_list_add(&known, nameBuf);",
  "        } else if (count > 2) {",
  "          pya_name_list_add(&known, tokens[2]);",
  "        }",
  "      }",
  "    }",
  "    pya_pyash_tokens_free(tokens, count);",
  "    if (!end) break;",
  "    start = end + 1;",
  "  }",
  "  pya_pyash_map *current = NULL;",
  "  start = pyash;",
  "  while (*start) {",
  "    const char *end = strchr(start, '\\n');",
  "    size_t len = end ? (size_t)(end - start) : strlen(start);",
  "    if (len == 0) {",
  "      if (!end) break;",
  "      start = end + 1;",
  "      continue;",
  "    }",
  "    char line[PYA_TEXT_CAP];",
  "    if (len >= sizeof(line)) len = sizeof(line) - 1;",
  "    memcpy(line, start, len);",
  "    line[len] = '\\0';",
  "    char **tokens = NULL;",
  "    int count = 0;",
  "    if (!pya_pyash_tokenize(line, &tokens, &count)) {",
  "      pya_set_json_error(err, \"json map export failed: invalid pyash\", pyash, start);",
  "      pya_name_list_free(&known);",
  "      return 0;",
  "    }",
  "    if (count == 0) {",
  "      pya_pyash_tokens_free(tokens, count);",
  "      if (!end) break;",
  "      start = end + 1;",
  "      continue;",
  "    }",
  "    const char *last = tokens[count - 1];",
  "    if (strcmp(last, \"def\") == 0) {",
  "      if (count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0) {",
  "        int beIdx = -1;",
  "        for (int i = 0; i < count; i++) {",
  "          if (strcmp(tokens[i], \"be\") == 0) { beIdx = i; break; }",
  "        }",
  "        char nameBuf[PYA_TEXT_CAP];",
  "        if (beIdx > 2) {",
  "          nameBuf[0] = '\\0';",
  "          for (int i = 2; i < beIdx; i++) {",
  "            if (i > 2) pya_concat_buf(nameBuf, \" \");",
  "            pya_concat_buf(nameBuf, tokens[i]);",
  "          }",
  "        } else if (count > 2) {",
  "          snprintf(nameBuf, sizeof(nameBuf), \"%s\", tokens[2]);",
  "        } else {",
  "          nameBuf[0] = '\\0';",
  "        }",
  "        if (nameBuf[0] != '\\0') current = pya_pyash_get_map(defs, nameBuf);",
  "      }",
  "      pya_pyash_tokens_free(tokens, count);",
  "      if (!end) break;",
  "      start = end + 1;",
  "      continue;",
  "    }",
  "    if (strcmp(last, \"prah\") == 0) {",
  "      current = NULL;",
  "      pya_pyash_tokens_free(tokens, count);",
  "      if (!end) break;",
  "      start = end + 1;",
  "      continue;",
  "    }",
  "    if (strcmp(last, \"ya\") == 0 && current) {",
  "      if (count >= 6 && strcmp(tokens[0], \"su\") == 0 && strcmp(tokens[1], \"name\") == 0 && strcmp(tokens[3], \"ob\") == 0) {",
  "        int idx = 4;",
  "        pya_pyash_value value;",
  "        memset(&value, 0, sizeof(value));",
  "        if (!pya_pyash_parse_value(tokens, count - 1, &idx, &value, &known)) {",
  "          pya_pyash_tokens_free(tokens, count);",
  "          pya_set_json_error(err, \"json map contents defective: unsupported contents\", pyash, start);",
  "          pya_name_list_free(&known);",
  "          return 0;",
  "        }",
  "        if (!pya_pyash_add_entry(current, tokens[2], &value)) {",
  "          pya_pyash_value_free(&value);",
  "        }",
  "      }",
  "    }",
  "    pya_pyash_tokens_free(tokens, count);",
  "    if (!end) break;",
  "    start = end + 1;",
  "  }",
  "  pya_name_list_free(&known);",
  "  return 1;",
  "}",
  "",
  "static int pya_compare_utf8(const void *a, const void *b) {",
  "  const char *aa = *(const char **)a;",
  "  const char *bb = *(const char **)b;",
  "  if (!aa && !bb) return 0;",
  "  if (!aa) return -1;",
  "  if (!bb) return 1;",
  "  const unsigned char *pa = (const unsigned char *)aa;",
  "  const unsigned char *pb = (const unsigned char *)bb;",
  "  while (*pa && *pb) {",
  "    if (*pa != *pb) return *pa < *pb ? -1 : 1;",
  "    pa++;",
  "    pb++;",
  "  }",
  "  if (*pa == *pb) return 0;",
  "  return *pa ? 1 : -1;",
  "}",
  "",
  "static cJSON *pya_pyash_map_to_json(pya_pyash_maps *defs, const char *name, pya_used_names *seen, pya_json_error *err);",
  "",
  "static cJSON *pya_pyash_value_to_json(pya_pyash_maps *defs, const pya_pyash_value *value, pya_used_names *seen, pya_json_error *err) {",
  "  if (!value) return NULL;",
  "  if (value->kind == PYA_PYASH_UNSPEC) return NULL;",
  "  if (value->kind == PYA_PYASH_HOLLOW) return cJSON_CreateNull();",
  "  if (value->kind == PYA_PYASH_TEXT) return cJSON_CreateString(value->text ? value->text : \"\");",
  "  if (value->kind == PYA_PYASH_NUM) return cJSON_CreateNumber(value->num);",
  "  if (value->kind == PYA_PYASH_BOOL) return cJSON_CreateBool(value->boolean != 0);",
  "  if (value->kind == PYA_PYASH_NAME) return pya_pyash_map_to_json(defs, value->name, seen, err);",
  "  if (value->kind == PYA_PYASH_VECTOR) {",
  "    if (!value->vec_type) return cJSON_CreateArray();",
  "    if (strcmp(value->vec_type, \"hollow\") == 0) return cJSON_CreateArray();",
  "    cJSON *arr = cJSON_CreateArray();",
  "    for (int i = 0; i < value->vec_len; i++) {",
  "      const pya_pyash_value *elem = &value->vec_values[i];",
  "      cJSON *child = NULL;",
  "      if (strcmp(value->vec_type, \"name\") == 0) {",
  "        child = pya_pyash_map_to_json(defs, elem->name, seen, err);",
  "      } else if (elem->kind == PYA_PYASH_NUM) {",
  "        child = cJSON_CreateNumber(elem->num);",
  "      } else if (elem->kind == PYA_PYASH_TEXT) {",
  "        child = cJSON_CreateString(elem->text ? elem->text : \"\");",
  "      } else if (elem->kind == PYA_PYASH_BOOL) {",
  "        child = cJSON_CreateBool(elem->boolean != 0);",
  "      }",
  "      if (!child) { cJSON_Delete(arr); return NULL; }",
  "      cJSON_AddItemToArray(arr, child);",
  "    }",
  "    return arr;",
  "  }",
  "  return NULL;",
  "}",
  "",
  "static cJSON *pya_pyash_map_to_json(pya_pyash_maps *defs, const char *name, pya_used_names *seen, pya_json_error *err) {",
  "  if (!defs || !name) {",
  "    pya_set_json_error(err, \"json map referential defective\", name, name);",
  "    return NULL;",
  "  }",
  "  if (pya_used_has(seen, name)) {",
  "    pya_set_json_error(err, \"json map export self referential\", name, name);",
  "    return NULL;",
  "  }",
  "  pya_pyash_map *map = NULL;",
  "  for (int i = 0; i < defs->length; i++) {",
  "    if (defs->maps[i].name && strcmp(defs->maps[i].name, name) == 0) {",
  "      map = &defs->maps[i];",
  "      break;",
  "    }",
  "  }",
  "  if (!map) {",
  "    pya_set_json_error(err, \"json map referential defective\", name, name);",
  "    return NULL;",
  "  }",
  "  pya_used_add(seen, name);",
  "  cJSON *obj = cJSON_CreateObject();",
  "  if (!obj) { pya_used_remove(seen, name); return NULL; }",
  "  if (map->length > 0) {",
  "    char **keys = (char **)malloc(sizeof(char *) * map->length);",
  "    int keyCount = 0;",
  "    for (int i = 0; i < map->length; i++) {",
  "      if (!map->entries[i].key) continue;",
  "      keys[keyCount++] = map->entries[i].key;",
  "    }",
  "    qsort(keys, keyCount, sizeof(char *), pya_compare_utf8);",
  "    for (int i = 0; i < keyCount; i++) {",
  "      const char *key = keys[i];",
  "      pya_pyash_value *value = NULL;",
  "      for (int j = 0; j < map->length; j++) {",
  "        if (map->entries[j].key && strcmp(map->entries[j].key, key) == 0) {",
  "          value = &map->entries[j].value;",
  "          break;",
  "        }",
  "      }",
  "      if (!value) continue;",
  "      cJSON *child = pya_pyash_value_to_json(defs, value, seen, err);",
  "      if (!child && value->kind == PYA_PYASH_UNSPEC) continue;",
  "      if (!child) { free(keys); cJSON_Delete(obj); pya_used_remove(seen, name); return NULL; }",
  "      cJSON_AddItemToObject(obj, key, child);",
  "    }",
  "    free(keys);",
  "  }",
  "  pya_used_remove(seen, name);",
  "  return obj;",
  "}",
  "",
  "static int pya_pyash_to_json(const char *pyash, const char *rootName, char *out, pya_json_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  if (!pyash) {",
  "    pya_set_json_error(err, \"json map export failed\", pyash, pyash);",
  "    return 0;",
  "  }",
  "  pya_pyash_maps defs = {0};",
  "  if (!pya_pyash_parse_maps(pyash, &defs, err)) {",
  "    pya_pyash_maps_free(&defs);",
  "    return 0;",
  "  }",
  "  const char *root = rootName ? rootName : (defs.length > 0 ? defs.maps[0].name : \"data\");",
  "  pya_used_names seen;",
  "  pya_used_init(&seen);",
  "  cJSON *json = pya_pyash_map_to_json(&defs, root, &seen, err);",
  "  pya_used_free(&seen);",
  "  if (!json) {",
  "    pya_pyash_maps_free(&defs);",
  "    return 0;",
  "  }",
  "  char *printed = cJSON_PrintUnformatted(json);",
  "  if (printed) {",
  "    snprintf(out, PYA_TEXT_CAP, \"%s\", printed);",
  "    free(printed);",
  "  }",
  "  cJSON_Delete(json);",
  "  pya_pyash_maps_free(&defs);",
  "  return 1;",
  "}",
  "static int pya_pyash_is_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const unsigned char *p = (const unsigned char *)s; *p; p++) {",
  "    if (!(isalnum(*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void pya_pyash_print_escaped(FILE *out, const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      fputc('\\\\', out);",
  "      fputc(*p, out);",
  "    } else if (*p == '\\n') {",
  "      fputs(\"\\\\n\", out);",
  "    } else {",
  "      fputc(*p, out);",
  "    }",
  "  }",
  "}",
  "static void pya_pyash_print_token(FILE *out, const char *s) {",
  "  if (!s) return;",
  "  if (pya_pyash_is_token(s)) {",
  "    fputs(s, out);",
  "  } else {",
  "    fputc('\"', out);",
  "    pya_pyash_print_escaped(out, s);",
  "    fputc('\"', out);",
  "  }",
  "}",
  "static void pya_pyash_print_text_vector(FILE *out, char **values, size_t count) {",
  "  fputs(\"ve text\", out);",
  "  for (size_t i = 0; i < count; i++) {",
  "    fputc(' ', out);",
  "    pya_pyash_print_token(out, values[i] ? values[i] : \"\");",
  "  }",
  "}",
].join("\n");
