export const MAP_TYPE_DECL = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "#define PYA_MAP_NUM 1",
  "#define PYA_MAP_TEXT 2",
  "#define PYA_MAP_BOOL 3",
  "#define PYA_MAP_HOLLOW 4",
  "#define PYA_MAP_SENTENCE 5",
  "typedef struct { const char *key; int kind; double num; int boolean; char text[PYA_TEXT_CAP]; } pya_map_entry;",
  "typedef struct { int length; int cap; pya_map_entry *entries; } pya_map;"
].join("\n");

export const MAP_HELPER = [
  "static void pya_map_init(pya_map *map) {",
  "  if (!map) return;",
  "  map->length = 0;",
  "  map->cap = 0;",
  "  map->entries = NULL;",
  "}",
  "static int pya_map_find(pya_map *map, const char *key) {",
  "  if (!map || !key) return -1;",
  "  for (int i = 0; i < map->length; i++) {",
  "    if (map->entries[i].key && strcmp(map->entries[i].key, key) == 0) return i;",
  "  }",
  "  return -1;",
  "}",
  "static void pya_map_reserve(pya_map *map) {",
  "  if (!map) return;",
  "  if (map->length < map->cap) return;",
  "  int next = map->cap == 0 ? 8 : map->cap * 2;",
  "  pya_map_entry *nextEntries = (pya_map_entry *)realloc(map->entries, sizeof(pya_map_entry) * next);",
  "  if (!nextEntries) return;",
  "  map->entries = nextEntries;",
  "  map->cap = next;",
  "}",
  "static pya_map_entry *pya_map_get_or_add(pya_map *map, const char *key) {",
  "  if (!map || !key) return NULL;",
  "  int idx = pya_map_find(map, key);",
  "  if (idx >= 0) return &map->entries[idx];",
  "  pya_map_reserve(map);",
  "  if (map->length >= map->cap) return NULL;",
  "  pya_map_entry *entry = &map->entries[map->length++];",
  "  entry->key = key;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = 0;",
  "  entry->boolean = 0;",
  "  entry->text[0] = '\\0';",
  "  return entry;",
  "}",
  "static void pya_map_set_num(pya_map *map, const char *key, double value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_NUM;",
  "  entry->num = value;",
  "}",
  "static void pya_map_set_text(pya_map *map, const char *key, const char *value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_TEXT;",
  "  snprintf(entry->text, PYA_TEXT_CAP, \"%s\", value ? value : \"\");",
  "}",
  "static void pya_map_set_bool(pya_map *map, const char *key, int value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_BOOL;",
  "  entry->boolean = value ? 1 : 0;",
  "}",
  "static void pya_map_set_hollow(pya_map *map, const char *key) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_HOLLOW;",
  "}",
  "static void pya_map_set_sentence(pya_map *map, const char *key, const char *value) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_SENTENCE;",
  "  snprintf(entry->text, PYA_TEXT_CAP, \"%s\", value ? value : \"\");",
  "}",
  "static void pya_map_add_num(pya_map *map, const char *key, double delta) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  if (entry->kind != PYA_MAP_NUM) {",
  "    entry->kind = PYA_MAP_NUM;",
  "    entry->num = 0;",
  "  }",
  "  entry->num += delta;",
  "}",
  "static int map_is_safe_token(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  for (const char *p = s; *p; p++) {",
  "    if (!(isalnum((unsigned char)*p) || *p == '_' || *p == '.' || *p == '-')) return 0;",
  "  }",
  "  return 1;",
  "}",
  "static void map_print_escaped(const char *s) {",
  "  if (!s) return;",
  "  for (const char *p = s; *p; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      putchar('\\\\');",
  "      putchar(*p);",
  "    } else if (*p == '\\n') {",
  "      printf(\"\\\\n\");",
  "    } else {",
  "      putchar(*p);",
  "    }",
  "  }",
  "}",
  "static void map_copy_escaped(char *dest, size_t cap, const char *src) {",
  "  if (!dest || cap == 0) return;",
  "  size_t pos = 0;",
  "  if (!src) { dest[0] = '\\0'; return; }",
  "  for (const char *p = src; *p && pos + 1 < cap; p++) {",
  "    if (*p == '\\\\' || *p == '\"') {",
  "      if (pos + 2 >= cap) break;",
  "      dest[pos++] = '\\\\';",
  "      dest[pos++] = *p;",
  "    } else if (*p == '\\n') {",
  "      if (pos + 2 >= cap) break;",
  "      dest[pos++] = '\\\\';",
  "      dest[pos++] = 'n';",
  "    } else {",
  "      dest[pos++] = *p;",
  "    }",
  "  }",
  "  dest[pos] = '\\0';",
  "}",
  "static void pya_map_set_sentence_num(pya_map_entry *entry, const char *key, double value) {",
  "  if (!entry) return;",
  "  entry->kind = PYA_MAP_SENTENCE;",
  "  entry->num = value;",
  "  if (map_is_safe_token(key)) {",
  "    snprintf(entry->text, PYA_TEXT_CAP, \"su name %s ob num %g ya\", key ? key : \"\", value);",
  "  } else {",
  "    char escaped[PYA_TEXT_CAP];",
  "    map_copy_escaped(escaped, sizeof(escaped), key);",
  "    snprintf(entry->text, PYA_TEXT_CAP, \"su name \\\"%s\\\" ob num %g ya\", escaped, value);",
  "  }",
  "}",
  "static void pya_map_add_sentence_num(pya_map *map, const char *key, double delta) {",
  "  pya_map_entry *entry = pya_map_get_or_add(map, key);",
  "  if (!entry) return;",
  "  double current = 0;",
  "  if (entry->kind == PYA_MAP_NUM || entry->kind == PYA_MAP_SENTENCE) current = entry->num;",
  "  pya_map_set_sentence_num(entry, key, current + delta);",
  "}",
  "static int map_entry_compare(const void *a, const void *b) {",
  "  const pya_map_entry *ea = *(const pya_map_entry **)a;",
  "  const pya_map_entry *eb = *(const pya_map_entry **)b;",
  "  if (!ea || !ea->key) return (eb && eb->key) ? -1 : 0;",
  "  if (!eb || !eb->key) return 1;",
  "  return strcmp(ea->key, eb->key);",
  "}",
  "static void print_map_sentence(const char *name, const pya_map *map) {",
  "  printf(\"su name %s be map def\\n\", name ? name : \"\");",
  "  if (!map) {",
  "    printf(\"prah\\n\");",
  "    return;",
  "  }",
  "  pya_map_entry **sorted = (pya_map_entry **)malloc(sizeof(pya_map_entry *) * map->length);",
  "  if (sorted) {",
  "    for (int i = 0; i < map->length; i++) {",
  "      sorted[i] = &map->entries[i];",
  "    }",
  "    qsort(sorted, map->length, sizeof(pya_map_entry *), map_entry_compare);",
  "  }",
  "  for (int i = 0; i < map->length; i++) {",
  "    const pya_map_entry *entry = sorted ? sorted[i] : &map->entries[i];",
    "    if (!entry->key) continue;",
    "    if (entry->kind == PYA_MAP_SENTENCE) {",
    "      printf(\"%s\\n\", entry->text);",
    "      continue;",
  "    }",
  "    if (map_is_safe_token(entry->key)) {",
  "      printf(\"su name %s ob \", entry->key);",
  "    } else {",
  "      printf(\"su name \\\"\");",
  "      map_print_escaped(entry->key);",
  "      printf(\"\\\" ob \");",
  "    }",
  "    if (entry->kind == PYA_MAP_TEXT) {",
  "      printf(\"text \\\"\");",
  "      map_print_escaped(entry->text);",
  "      printf(\"\\\"\");",
  "    } else if (entry->kind == PYA_MAP_BOOL) {",
  "      printf(\"bool %s\", entry->boolean ? \"truth\" : \"lie\");",
  "    } else if (entry->kind == PYA_MAP_HOLLOW) {",
  "      printf(\"hollow\");",
  "    } else {",
  "      printf(\"num %g\", entry->num);",
  "    }",
  "    printf(\" ya\\n\");",
  "  }",
  "  if (sorted) free(sorted);",
  "  printf(\"prah\\n\");",
  "}"
].join("\n");
