export const SPEAK_HELPER = [
  "static void pya_speak_escape(const char *text, char *out, size_t cap) {",
  "  if (!out || cap == 0) return;",
  "  size_t len = 0;",
  "  for (const char *p = text ? text : \"\"; *p && len + 2 < cap; p++) {",
  "    char ch = *p;",
  "    if (ch == '\\\\' || ch == '\"') {",
  "      out[len++] = '\\\\';",
  "      out[len++] = ch;",
  "    } else if (ch == '\\n') {",
  "      out[len++] = '\\\\';",
  "      out[len++] = 'n';",
  "    } else {",
  "      out[len++] = ch;",
  "    }",
  "  }",
  "  out[len] = '\\0';",
  "}",
  "",
  "static char *pya_speak_strdup(const char *s) {",
  "  if (!s) return NULL;",
  "  size_t len = strlen(s);",
  "  char *out = (char *)malloc(len + 1);",
  "  if (!out) return NULL;",
  "  memcpy(out, s, len);",
  "  out[len] = '\\0';",
  "  return out;",
  "}",
  "",
  "static char *pya_speak(const char *text) {",
  "  char escaped[PYA_TEXT_CAP];",
  "  pya_speak_escape(text ? text : \"\", escaped, sizeof(escaped));",
  "  char cmd[PYA_TEXT_CAP * 2];",
  "  snprintf(cmd, sizeof(cmd), \"espeak-ng -x \\\"%s\\\"\", escaped);",
  "  FILE *pipe = popen(cmd, \"r\");",
  "  if (!pipe) return pya_speak_strdup(\"\");",
  "  char out[PYA_TEXT_CAP];",
  "  out[0] = '\\0';",
  "  char buf[256];",
  "  while (fgets(buf, sizeof(buf), pipe)) {",
  "    pya_concat_buf(out, buf);",
  "  }",
  "  pclose(pipe);",
  "  return pya_speak_strdup(out);",
  "}"
].join("\n");
