export const TEXT_HELPER = [
  "#ifndef PYA_TEXT_CAP",
  "#define PYA_TEXT_CAP 4096",
  "#endif",
  "static void pya_concat_buf(char *dest, const char *src) {",
  "  if (!dest || !src) return;",
  "  size_t dlen = strlen(dest);",
  "  if (dlen >= PYA_TEXT_CAP - 1) return;",
  "  strncat(dest, src, PYA_TEXT_CAP - dlen - 1);",
  "}",
  "static void pya_concat_num_buf(char *dest, double value) {",
  "  char buf[64];",
  "  snprintf(buf, sizeof(buf), \"%g\", value);",
  "  pya_concat_buf(dest, buf);",
  "}",
  "static void pya_write_text_file(const char *filename, const char *text) {",
  "  if (!filename) return;",
  "  FILE *f = fopen(filename, \"w\");",
  "  if (!f) return;",
  "  for (const char *p = text ? text : \"\"; *p; p++) {",
  "    if (*p == '\\r') {",
  "      if (*(p + 1) == '\\n') p++;",
  "      fputc('\\n', f);",
  "    } else {",
  "      fputc(*p, f);",
  "    }",
  "  }",
  "  fclose(f);",
  "}"
].join("\n");
