export const YAML_STRINGIFY_HELPER = [
  "/* PYA_YAML_STRINGIFY */",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_yaml_error;",
  "",
  "static void pya_yaml_set_error(pya_yaml_error *err, const char *msg, int line, int col) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", msg ? msg : \"yaml defective\");",
  "  err->line = line;",
  "  err->column = col;",
  "}",
  "",
  "typedef struct { const char *key; cJSON *value; } pya_yaml_kv;",
  "",
  "static int pya_yaml_compare_utf8(const void *a, const void *b) {",
  "  const pya_yaml_kv *ka = (const pya_yaml_kv *)a;",
  "  const pya_yaml_kv *kb = (const pya_yaml_kv *)b;",
  "  if (!ka->key || !kb->key) return 0;",
  "  return strcmp(ka->key, kb->key);",
  "}",
  "",
  "static cJSON *pya_yaml_canonicalize(cJSON *node) {",
  "  if (!node) return NULL;",
  "  if (cJSON_IsArray(node)) {",
  "    cJSON *arr = cJSON_CreateArray();",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      cJSON_AddItemToArray(arr, pya_yaml_canonicalize(child));",
  "    }",
  "    return arr;",
  "  }",
  "  if (cJSON_IsObject(node)) {",
  "    int count = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    cJSON *obj = cJSON_CreateObject();",
  "    for (int i = 0; i < count; i++) {",
  "      cJSON_AddItemToObject(obj, items[i].key, pya_yaml_canonicalize(items[i].value));",
  "    }",
  "    free(items);",
  "    return obj;",
  "  }",
  "  return cJSON_Duplicate(node, 1);",
  "}",
  "",
  "static void pya_yaml_emit_indent(char *out, int indent) {",
  "  for (int i = 0; i < indent; i++) pya_concat_buf(out, \" \");",
  "}",
  "",
  "static void pya_yaml_emit_quoted(char *out, const char *text) {",
  "  pya_concat_buf(out, \"\\\"\");",
  "  if (text) {",
  "    for (const char *p = text; *p; p++) {",
  "      if (*p == '\\\\' || *p == '\"') {",
  "        char esc[2] = { '\\\\', '\\0' };",
  "        pya_concat_buf(out, esc);",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      } else if (*p == '\\n') {",
  "        pya_concat_buf(out, \"\\\\n\");",
  "      } else {",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      }",
  "    }",
  "  }",
  "  pya_concat_buf(out, \"\\\"\");",
  "}",
  "",
  "static void pya_yaml_emit_value(char *out, cJSON *value, int indent) {",
  "  if (cJSON_IsNull(value)) { pya_concat_buf(out, \"null\"); return; }",
  "  if (cJSON_IsBool(value)) { pya_concat_buf(out, cJSON_IsTrue(value) ? \"true\" : \"false\"); return; }",
  "  if (cJSON_IsNumber(value)) { pya_concat_num_buf(out, value->valuedouble); return; }",
  "  if (cJSON_IsString(value)) { pya_yaml_emit_quoted(out, value->valuestring); return; }",
  "  if (cJSON_IsArray(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    for (cJSON *child = value->child; child; child = child->next) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_concat_buf(out, \"- \");",
  "      pya_yaml_emit_value(out, child, indent + 2);",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    return;",
  "  }",
  "  if (cJSON_IsObject(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    int count = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    for (int i = 0; i < count; i++) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_yaml_emit_quoted(out, items[i].key);",
  "      pya_concat_buf(out, \": \");",
  "      pya_yaml_emit_value(out, items[i].value, indent + 2);",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    free(items);",
  "    return;",
  "  }",
  "  pya_concat_buf(out, \"null\");",
  "}",
  "",
  "static int pya_json_to_yaml(const char *jsonText, char *out, pya_yaml_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  cJSON *root = cJSON_Parse(jsonText);",
  "  if (!root) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "  cJSON *canon = pya_yaml_canonicalize(root);",
  "  pya_yaml_emit_value(out, canon, 0);",
  "  cJSON_Delete(canon);",
  "  cJSON_Delete(root);",
  "  return 1;",
  "}"
].join("\n");

export const YAML_RUNTIME_HELPER = [
  "/* PYA_YAML_RUNTIME */",
  "typedef struct {",
  "  char message[PYA_TEXT_CAP];",
  "  int line;",
  "  int column;",
  "} pya_yaml_error;",
  "",
  "typedef struct {",
  "  char **names;",
  "  cJSON **values;",
  "  int length;",
  "  int cap;",
  "} pya_yaml_anchors;",
  "",
  "typedef struct {",
  "  cJSON *node;",
  "  int is_map;",
  "  char *pending_key;",
  "} pya_yaml_stack;",
  "",
  "static void pya_yaml_set_error(pya_yaml_error *err, const char *msg, int line, int col) {",
  "  if (!err) return;",
  "  snprintf(err->message, sizeof(err->message), \"%s\", msg ? msg : \"yaml defective\");",
  "  err->line = line;",
  "  err->column = col;",
  "}",
  "",
  "static void pya_yaml_anchors_init(pya_yaml_anchors *anchors) {",
  "  anchors->names = NULL;",
  "  anchors->values = NULL;",
  "  anchors->length = 0;",
  "  anchors->cap = 0;",
  "}",
  "",
  "static void pya_yaml_anchors_free(pya_yaml_anchors *anchors) {",
  "  if (!anchors) return;",
  "  for (int i = 0; i < anchors->length; i++) free(anchors->names[i]);",
  "  free(anchors->names);",
  "  free(anchors->values);",
  "  anchors->names = NULL;",
  "  anchors->values = NULL;",
  "  anchors->length = 0;",
  "  anchors->cap = 0;",
  "}",
  "",
  "static void pya_yaml_anchor_set(pya_yaml_anchors *anchors, const char *name, cJSON *value) {",
  "  if (!anchors || !name || !*name || !value) return;",
  "  for (int i = 0; i < anchors->length; i++) {",
  "    if (strcmp(anchors->names[i], name) == 0) { anchors->values[i] = value; return; }",
  "  }",
  "  if (anchors->length >= anchors->cap) {",
  "    int next = anchors->cap == 0 ? 8 : anchors->cap * 2;",
  "    anchors->names = (char **)realloc(anchors->names, sizeof(char *) * next);",
  "    anchors->values = (cJSON **)realloc(anchors->values, sizeof(cJSON *) * next);",
  "    anchors->cap = next;",
  "  }",
  "  anchors->names[anchors->length] = pya_strdup(name);",
  "  anchors->values[anchors->length] = value;",
  "  anchors->length += 1;",
  "}",
  "",
  "static cJSON *pya_yaml_anchor_get(pya_yaml_anchors *anchors, const char *name) {",
  "  if (!anchors || !name) return NULL;",
  "  for (int i = 0; i < anchors->length; i++) {",
  "    if (anchors->names[i] && strcmp(anchors->names[i], name) == 0) return anchors->values[i];",
  "  }",
  "  return NULL;",
  "}",
  "",
  "static int pya_yaml_is_json_number(const char *s) {",
  "  if (!s || !*s) return 0;",
  "  const char *p = s;",
  "  if (*p == '-') p++;",
  "  if (*p == '0') {",
  "    p++;",
  "  } else if (*p >= '1' && *p <= '9') {",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  } else {",
  "    return 0;",
  "  }",
  "  if (*p == '.') {",
  "    p++;",
  "    if (!(*p >= '0' && *p <= '9')) return 0;",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  }",
  "  if (*p == 'e' || *p == 'E') {",
  "    p++;",
  "    if (*p == '+' || *p == '-') p++;",
  "    if (!(*p >= '0' && *p <= '9')) return 0;",
  "    while (*p >= '0' && *p <= '9') p++;",
  "  }",
  "  return *p == '\\0';",
  "}",
  "",
  "static void pya_yaml_trim(char *s) {",
  "  if (!s) return;",
  "  size_t len = strlen(s);",
  "  size_t start = 0;",
  "  while (start < len && isspace((unsigned char)s[start])) start++;",
  "  size_t end = len;",
  "  while (end > start && isspace((unsigned char)s[end - 1])) end--;",
  "  if (start > 0) memmove(s, s + start, end - start);",
  "  s[end - start] = '\\0';",
  "}",
  "",
  "static char *pya_yaml_key_text(const char *raw, yaml_scalar_style_t style, pya_yaml_error *err) {",
  "  if (!raw) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
  "  char buf[PYA_TEXT_CAP];",
  "  snprintf(buf, sizeof(buf), \"%s\", raw);",
  "  pya_yaml_trim(buf);",
  "  const int is_plain = (style == YAML_PLAIN_SCALAR_STYLE);",
  "  if (!is_plain) {",
  "    if (!buf[0]) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
  "    return pya_strdup(buf);",
  "  }",
  "  if (buf[0] == '\\0' || strcmp(buf, \"~\") == 0 || strcasecmp(buf, \"null\") == 0) return pya_strdup(\"null\");",
  "  if (strcasecmp(buf, \"true\") == 0) return pya_strdup(\"true\");",
  "  if (strcasecmp(buf, \"false\") == 0) return pya_strdup(\"false\");",
  "  if (pya_yaml_is_json_number(buf)) return pya_strdup(buf);",
  "  if (!buf[0]) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return NULL; }",
  "  return pya_strdup(buf);",
  "}",
  "",
  "static cJSON *pya_yaml_scalar_to_json(const char *raw, yaml_scalar_style_t style) {",
  "  if (!raw) return cJSON_CreateNull();",
  "  const int is_plain = (style == YAML_PLAIN_SCALAR_STYLE);",
  "  if (!is_plain) return cJSON_CreateString(raw);",
  "  char buf[PYA_TEXT_CAP];",
  "  snprintf(buf, sizeof(buf), \"%s\", raw);",
  "  pya_yaml_trim(buf);",
  "  if (buf[0] == '\\0' || strcmp(buf, \"~\") == 0 || strcasecmp(buf, \"null\") == 0) return cJSON_CreateNull();",
  "  if (strcasecmp(buf, \"true\") == 0) return cJSON_CreateBool(1);",
  "  if (strcasecmp(buf, \"false\") == 0) return cJSON_CreateBool(0);",
  "  if (pya_yaml_is_json_number(buf)) return cJSON_CreateNumber(strtod(buf, NULL));",
  "  return cJSON_CreateString(buf);",
  "}",
  "",
  "static int pya_yaml_stack_push(pya_yaml_stack **stack, int *depth, int *cap, cJSON *node, int is_map) {",
  "  if (*depth >= *cap) {",
  "    int next = (*cap == 0) ? 8 : (*cap * 2);",
  "    pya_yaml_stack *resized = (pya_yaml_stack *)realloc(*stack, sizeof(pya_yaml_stack) * next);",
  "    if (!resized) return 0;",
  "    *stack = resized;",
  "    *cap = next;",
  "  }",
  "  (*stack)[*depth].node = node;",
  "  (*stack)[*depth].is_map = is_map;",
  "  (*stack)[*depth].pending_key = NULL;",
  "  *depth += 1;",
  "  return 1;",
  "}",
  "",
  "static pya_yaml_stack *pya_yaml_stack_top(pya_yaml_stack *stack, int depth) {",
  "  if (!stack || depth <= 0) return NULL;",
  "  return &stack[depth - 1];",
  "}",
  "",
  "static void pya_yaml_stack_pop(pya_yaml_stack *stack, int *depth) {",
  "  if (!stack || !depth || *depth <= 0) return;",
  "  pya_yaml_stack *top = &stack[*depth - 1];",
  "  if (top->pending_key) free(top->pending_key);",
  "  *depth -= 1;",
  "}",
  "",
  "static int pya_yaml_merge_map(cJSON *target, cJSON *source) {",
  "  if (!cJSON_IsObject(source)) return 0;",
  "  for (cJSON *entry = source->child; entry; entry = entry->next) {",
  "    if (!entry->string) continue;",
  "    if (cJSON_GetObjectItemCaseSensitive(target, entry->string)) continue;",
  "    cJSON_AddItemToObject(target, entry->string, cJSON_Duplicate(entry, 1));",
  "  }",
  "  return 1;",
  "}",
  "",
  "static int pya_yaml_add_value(pya_yaml_stack *stack, int depth, cJSON **root, cJSON *value, pya_yaml_error *err) {",
  "  if (!value) return 0;",
  "  if (depth <= 0) {",
  "    if (*root) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "    *root = value;",
  "    return 1;",
  "  }",
  "  pya_yaml_stack *parent = &stack[depth - 1];",
  "  if (parent->is_map) {",
  "    if (!parent->pending_key) { pya_yaml_set_error(err, \"yaml key defective\", 0, 0); return 0; }",
  "    if (strcmp(parent->pending_key, \"<<\") == 0) {",
  "      int ok = 1;",
  "      if (cJSON_IsArray(value)) {",
  "        for (cJSON *item = value->child; item; item = item->next) {",
  "          if (!pya_yaml_merge_map(parent->node, item)) ok = 0;",
  "        }",
  "      } else {",
  "        ok = pya_yaml_merge_map(parent->node, value);",
  "      }",
  "      free(parent->pending_key);",
  "      parent->pending_key = NULL;",
  "      if (!ok) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "      cJSON_Delete(value);",
  "      return 1;",
  "    }",
  "    cJSON_DeleteItemFromObjectCaseSensitive(parent->node, parent->pending_key);",
  "    cJSON_AddItemToObject(parent->node, parent->pending_key, value);",
  "    free(parent->pending_key);",
  "    parent->pending_key = NULL;",
  "    return 1;",
  "  }",
  "  cJSON_AddItemToArray(parent->node, value);",
  "  return 1;",
  "}",
  "",
  "static int pya_yaml_alias_cycle(pya_yaml_stack *stack, int depth, cJSON *target) {",
  "  for (int i = 0; i < depth; i++) {",
  "    if (stack[i].node == target) return 1;",
  "  }",
  "  return 0;",
  "}",
  "",
  "static cJSON *pya_yaml_parse_json(const char *text, pya_yaml_error *err) {",
  "  yaml_parser_t parser;",
  "  yaml_event_t event;",
  "  if (!yaml_parser_initialize(&parser)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return NULL; }",
  "  yaml_parser_set_input_string(&parser, (const unsigned char *)text, text ? strlen(text) : 0);",
  "  pya_yaml_anchors anchors;",
  "  pya_yaml_anchors_init(&anchors);",
  "  pya_yaml_stack *stack = NULL;",
  "  int depth = 0;",
  "  int cap = 0;",
  "  int doc_count = 0;",
  "  cJSON *root = NULL;",
  "  int done = 0;",
  "  while (!done) {",
  "    if (!yaml_parser_parse(&parser, &event)) {",
  "      pya_yaml_set_error(err, \"yaml defective\", parser.problem_mark.line + 1, parser.problem_mark.column + 1);",
  "      break;",
  "    }",
  "    switch (event.type) {",
  "      case YAML_STREAM_END_EVENT:",
  "        done = 1;",
  "        break;",
  "      case YAML_DOCUMENT_START_EVENT:",
  "        doc_count++;",
  "        if (doc_count > 1) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      case YAML_MAPPING_START_EVENT: {",
  "        if (event.data.mapping_start.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        cJSON *obj = cJSON_CreateObject();",
  "        if (!obj) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        if (event.data.mapping_start.anchor) {",
  "          pya_yaml_anchor_set(&anchors, (const char *)event.data.mapping_start.anchor, obj);",
  "        }",
  "        if (!pya_yaml_add_value(stack, depth, &root, obj, err)) { done = 1; break; }",
  "        if (!pya_yaml_stack_push(&stack, &depth, &cap, obj, 1)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      }",
  "      case YAML_SEQUENCE_START_EVENT: {",
  "        if (event.data.sequence_start.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        cJSON *arr = cJSON_CreateArray();",
  "        if (!arr) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        if (event.data.sequence_start.anchor) {",
  "          pya_yaml_anchor_set(&anchors, (const char *)event.data.sequence_start.anchor, arr);",
  "        }",
  "        if (!pya_yaml_add_value(stack, depth, &root, arr, err)) { done = 1; break; }",
  "        if (!pya_yaml_stack_push(&stack, &depth, &cap, arr, 0)) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; }",
  "        break;",
  "      }",
  "      case YAML_MAPPING_END_EVENT:",
  "      case YAML_SEQUENCE_END_EVENT:",
  "        pya_yaml_stack_pop(stack, &depth);",
  "        break;",
  "      case YAML_SCALAR_EVENT: {",
  "        if (event.data.scalar.tag) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); done = 1; break; }",
  "        pya_yaml_stack *parent = pya_yaml_stack_top(stack, depth);",
  "        const char *raw = (const char *)event.data.scalar.value;",
  "        if (parent && parent->is_map && !parent->pending_key) {",
  "          char *key = pya_yaml_key_text(raw, event.data.scalar.style, err);",
  "          if (!key) { done = 1; break; }",
  "          parent->pending_key = key;",
  "        } else {",
  "          cJSON *val = pya_yaml_scalar_to_json(raw, event.data.scalar.style);",
  "          if (event.data.scalar.anchor) {",
  "            pya_yaml_anchor_set(&anchors, (const char *)event.data.scalar.anchor, val);",
  "          }",
  "          if (!pya_yaml_add_value(stack, depth, &root, val, err)) { done = 1; }",
  "        }",
  "        break;",
  "      }",
  "      case YAML_ALIAS_EVENT: {",
  "        pya_yaml_stack *parent = pya_yaml_stack_top(stack, depth);",
  "        if (parent && parent->is_map && !parent->pending_key) {",
  "          pya_yaml_set_error(err, \"yaml key defective\", 0, 0);",
  "          done = 1;",
  "          break;",
  "        }",
  "        const char *alias = (const char *)event.data.alias.anchor;",
  "        cJSON *target = pya_yaml_anchor_get(&anchors, alias);",
  "        if (!target || pya_yaml_alias_cycle(stack, depth, target)) {",
  "          pya_yaml_set_error(err, \"yaml referential defective\", 0, 0);",
  "          done = 1;",
  "          break;",
  "        }",
  "        cJSON *dup = cJSON_Duplicate(target, 1);",
  "        if (!pya_yaml_add_value(stack, depth, &root, dup, err)) { done = 1; }",
  "        break;",
  "      }",
  "      default:",
  "        break;",
  "    }",
  "    yaml_event_delete(&event);",
  "  }",
  "  if (stack) {",
  "    for (int i = 0; i < depth; i++) {",
  "      if (stack[i].pending_key) free(stack[i].pending_key);",
  "    }",
  "    free(stack);",
  "  }",
  "  pya_yaml_anchors_free(&anchors);",
  "  yaml_parser_delete(&parser);",
  "  if (err && err->message[0] != '\\0') {",
  "    if (root) cJSON_Delete(root);",
  "    return NULL;",
  "  }",
  "  if (!root || !cJSON_IsObject(root)) {",
  "    if (root) cJSON_Delete(root);",
  "    pya_yaml_set_error(err, \"yaml root defective\", 0, 0);",
  "    return NULL;",
  "  }",
  "  return root;",
  "}",
  "",
  "typedef struct { const char *key; cJSON *value; } pya_yaml_kv;",
  "",
  "static int pya_yaml_compare_utf8(const void *a, const void *b) {",
  "  const pya_yaml_kv *ka = (const pya_yaml_kv *)a;",
  "  const pya_yaml_kv *kb = (const pya_yaml_kv *)b;",
  "  if (!ka->key || !kb->key) return 0;",
  "  return strcmp(ka->key, kb->key);",
  "}",
  "",
  "static cJSON *pya_yaml_canonicalize(cJSON *node) {",
  "  if (!node) return NULL;",
  "  if (cJSON_IsArray(node)) {",
  "    cJSON *arr = cJSON_CreateArray();",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      cJSON_AddItemToArray(arr, pya_yaml_canonicalize(child));",
  "    }",
  "    return arr;",
  "  }",
  "  if (cJSON_IsObject(node)) {",
  "    int count = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = node->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    cJSON *obj = cJSON_CreateObject();",
  "    for (int i = 0; i < count; i++) {",
  "      cJSON_AddItemToObject(obj, items[i].key, pya_yaml_canonicalize(items[i].value));",
  "    }",
  "    free(items);",
  "    return obj;",
  "  }",
  "  return cJSON_Duplicate(node, 1);",
  "}",
  "",
  "static void pya_yaml_emit_indent(char *out, int indent) {",
  "  for (int i = 0; i < indent; i++) pya_concat_buf(out, \" \");",
  "}",
  "",
  "static void pya_yaml_emit_quoted(char *out, const char *text) {",
  "  pya_concat_buf(out, \"\\\"\");",
  "  if (text) {",
  "    for (const char *p = text; *p; p++) {",
  "      if (*p == '\\\\' || *p == '\"') {",
  "        char esc[2] = { '\\\\', '\\0' };",
  "        pya_concat_buf(out, esc);",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      } else if (*p == '\\n') {",
  "        pya_concat_buf(out, \"\\\\n\");",
  "      } else {",
  "        char ch[2] = { *p, '\\0' };",
  "        pya_concat_buf(out, ch);",
  "      }",
  "    }",
  "  }",
  "  pya_concat_buf(out, \"\\\"\");",
  "}",
  "",
  "static void pya_yaml_emit_value(char *out, cJSON *value, int indent) {",
  "  if (cJSON_IsNull(value)) { pya_concat_buf(out, \"null\"); return; }",
  "  if (cJSON_IsBool(value)) { pya_concat_buf(out, cJSON_IsTrue(value) ? \"true\" : \"false\"); return; }",
  "  if (cJSON_IsNumber(value)) { pya_concat_num_buf(out, value->valuedouble); return; }",
  "  if (cJSON_IsString(value)) { pya_yaml_emit_quoted(out, value->valuestring); return; }",
  "  if (cJSON_IsArray(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    int idx = 0;",
  "    for (cJSON *child = value->child; child; child = child->next, idx++) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_concat_buf(out, \"- \");",
  "      if (cJSON_IsObject(child) || cJSON_IsArray(child)) {",
  "        pya_yaml_emit_value(out, child, indent + 2);",
  "      } else {",
  "        pya_yaml_emit_value(out, child, indent + 2);",
  "      }",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    return;",
  "  }",
  "  if (cJSON_IsObject(value)) {",
  "    if (indent > 0) pya_concat_buf(out, \"\\n\");",
  "    int count = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) count++;",
  "    pya_yaml_kv *items = (pya_yaml_kv *)malloc(sizeof(pya_yaml_kv) * count);",
  "    int idx = 0;",
  "    for (cJSON *child = value->child; child; child = child->next) {",
  "      items[idx].key = child->string;",
  "      items[idx].value = child;",
  "      idx++;",
  "    }",
  "    qsort(items, count, sizeof(pya_yaml_kv), pya_yaml_compare_utf8);",
  "    for (int i = 0; i < count; i++) {",
  "      pya_yaml_emit_indent(out, indent);",
  "      pya_yaml_emit_quoted(out, items[i].key);",
  "      pya_concat_buf(out, \": \");",
  "      if (cJSON_IsObject(items[i].value) || cJSON_IsArray(items[i].value)) {",
  "        pya_yaml_emit_value(out, items[i].value, indent + 2);",
  "      } else {",
  "        pya_yaml_emit_value(out, items[i].value, indent + 2);",
  "      }",
  "      pya_concat_buf(out, \"\\n\");",
  "    }",
  "    free(items);",
  "    return;",
  "  }",
  "  pya_concat_buf(out, \"null\");",
  "}",
  "",
  "static int pya_json_to_yaml(const char *jsonText, char *out, pya_yaml_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  cJSON *root = cJSON_Parse(jsonText);",
  "  if (!root) { pya_yaml_set_error(err, \"yaml defective\", 0, 0); return 0; }",
  "  cJSON *canon = pya_yaml_canonicalize(root);",
  "  pya_yaml_emit_value(out, canon, 0);",
  "  cJSON_Delete(canon);",
  "  cJSON_Delete(root);",
  "  return 1;",
  "}",
  "",
  "static int pya_yaml_to_pyash(const char *yamlText, const char *rootName, char *out, pya_yaml_error *err) {",
  "  if (!out) return 0;",
  "  out[0] = '\\0';",
  "  if (err) { err->message[0] = '\\0'; err->line = 0; err->column = 0; }",
  "  cJSON *root = pya_yaml_parse_json(yamlText, err);",
  "  if (!root) return 0;",
  "  cJSON *canon = pya_yaml_canonicalize(root);",
  "  pya_json_error json_err = { \"\", 0, 0 };",
  "  pya_used_names used;",
  "  pya_used_init(&used);",
  "  char clean[PYA_TEXT_CAP];",
  "  pya_sanitize_name_part(rootName ? rootName : \"data\", clean, sizeof(clean));",
  "  char *rootSafe = pya_unique_name(clean, &used);",
  "  pya_emit_map(canon, rootSafe ? rootSafe : \"data\", &used, out, &json_err, yamlText);",
  "  if (rootSafe) free(rootSafe);",
  "  pya_used_free(&used);",
  "  cJSON_Delete(canon);",
  "  cJSON_Delete(root);",
  "  if (json_err.message[0] != '\\0') {",
  "    pya_yaml_set_error(err, \"yaml defective\", json_err.line, json_err.column);",
  "    return 0;",
  "  }",
  "  return 1;",
  "}"
].join("\\n");
