// Generated by Pyash compile
function pyaCeremonyTypeWords(value, caseName) {
  if (value == null) return [];
  if (Array.isArray(value)) return value.length ? pyaCeremonyTypeWords(value[0], caseName) : [];
  if (value.nameTypeWords?.length) return ["name", ...value.nameTypeWords];
  if (caseName === "to" && value.su?.name && value.ob) {
    if (value.ob.num !== undefined) return ["name", "num"];
    if (value.ob.text !== undefined) return ["name", "text"];
    if (value.ob.boolean !== undefined) return ["name", "bool"];
    return ["name", "num"];
  }
  if (value.num !== undefined) return ["num"];
  if (value.text !== undefined) return ["text"];
  if (value.filename !== undefined) return ["filename"];
  if (value.boolean !== undefined) return ["bool"];
  if (value.name !== undefined) return ["name", "num"];
  if (value.ob?.num !== undefined) return ["num"];
  if (value.ob?.text !== undefined) return ["text"];
  return [];
}

function pyaCeremonySignature(sentence) {
  const ignored = new Set(["mood", "be", "exists", "signatureWords", "signature", "ret", "this", "consequence", "alternative", "su", "fromindex", "toindex", "atindex"]);
  const cases = Object.entries(sentence || [])
    .filter(([key, value]) => value !== undefined && !ignored.has(key) && !((key === "by" || key === "atindex") && value?.register))
    .map(([key, value]) => [key, pyaCeremonyTypeWords(value, key)])
    .filter(([, typeWords]) => typeWords.length)
    .sort(([left], [right]) => left.localeCompare(right));
  return ["be", sentence?.be || "", ...cases.flatMap(([key, typeWords]) => [key, ...typeWords])].join(" ");
}

function pyaAssertCeremonySignature(sentence, expected) {
  if (sentence?.atindex?.register === true) return;
  const actual = pyaCeremonySignature(sentence);
  if (actual === expected) return;
  const error = new Error("Ceremony signature inconsistency: expected " + expected + ", got " + actual);
  error.name = "signature inconsistency";
  error.sentence = {
    mood: "do",
    be: "error",
    su: { name: "signature inconsistency" },
    ob: { text: error.message },
    from: { name: "compile" }
  };
  throw error;
}
let first = { su: { name: "first" }, ob: { num: 3 }, be: "number", exists: true, mood: "ya" };
globalThis["first"] = first;
let second = { su: { name: "second" }, ob: { num: 8 }, be: "number", exists: true, mood: "ya" };
globalThis["second"] = second;
function be_plus_two_ob_num_to_name_num(sentence) {
  pyaAssertCeremonySignature(sentence, "be plus two ob num to name num");
  let input = { su: { name: "input" }, ob: {}, be: "number", mood: "ya" };
input.ob.num = sentence.ob.num;
  input.ob = input.ob?.ob ?? input.ob ?? {};
input.ob.num = (input.ob.num ?? 0) + 2;
  sentence.ob = input?.ob ?? input;
return sentence;
}
globalThis["be_plus_two_ob_num_to_name_num"] = be_plus_two_ob_num_to_name_num;
const _pya_ceremony_result_0 = be_plus_two_ob_num_to_name_num({ mood: "do", ob: { num: 3 }, to: { name: first, nameTypeWords: ["num"] }, be: "plus two" });
first.ob = _pya_ceremony_result_0?.ob ?? _pya_ceremony_result_0;
globalThis["first"] = first;
const _pya_ceremony_result_1 = be_plus_two_ob_num_to_name_num({ mood: "do", ob: { num: 8 }, to: { name: second, nameTypeWords: ["num"] }, be: "plus two" });
second.ob = _pya_ceremony_result_1?.ob ?? _pya_ceremony_result_1;
globalThis["second"] = second;
console.log(first.ob?.ve?.values ?? first.ob?.text ?? first.ob?.num ?? first.ob?.date);
console.log(second.ob?.ve?.values ?? second.ob?.text ?? second.ob?.num ?? second.ob?.date);
